table Efetivos
	lineageTag: 67743122-f75d-42e4-9418-596790ab0df7

	measure 'Total de Efetivos' = CALCULATE(DISTINCTCOUNT(Efetivos[CPF]))
		formatString: #,0
		lineageTag: c02a2b63-8ef7-4a22-8325-23a8144d5578

	measure '(Sem Filtro)Não Mobilização' =
			CALCULATE([Total de Efetivos],
			ALL(Efetivos[Nome Fantasia Unidade]))
		formatString: 0
		lineageTag: 7212a8f0-5042-41f1-84ec-e6e74e39ff11

	measure (Relação) = CALCULATE([Total de Efetivos]/[(Sem Filtro)Não Mobilização])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cabfcfc6-5cec-41ea-b1a7-c3c6b853a90c

	measure '(Cadastro) Quantidade de Efetivos Cadastrados' = CALCULATE(COUNTROWS())
		formatString: #,0
		lineageTag: 2e90c3e8-80c1-4612-a1a8-ba85cbccb012

	measure '(Ativos Relação) Quantidade Efetivos Cadastrados' =
			CALCULATE([(Cadastro) Quantidade de Efetivos Cadastrados],
			'Efetivos'[Situação] = "Ativo")
		formatString: #,0
		lineageTag: e15f3d9c-b634-45fb-8e68-a34eb5a0c5f6

	column Chave
		dataType: string
		lineageTag: 29b8ee3b-7aa4-4728-8130-e4421882972b
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Número Contrato'
		dataType: string
		lineageTag: f89310f0-57bc-4099-b522-ed3fa0459729
		summarizeBy: none
		sourceColumn: Número Contrato

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia Fornecedor'
		dataType: string
		lineageTag: d7b98945-f622-4d05-81cd-6aeccdd47cf1
		summarizeBy: none
		sourceColumn: Nome Fantasia Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão Social Fornecedor - Contrato'
		dataType: string
		lineageTag: 9258d6df-0879-45e3-92af-cd5e6f55bdb6
		summarizeBy: none
		sourceColumn: Razão Social Fornecedor - Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ Fornecedor - Contrato'
		dataType: string
		lineageTag: 04f9515b-2f83-4196-984e-62c2ef70d3a5
		summarizeBy: none
		sourceColumn: CNPJ Fornecedor - Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social Fornecedor - Faturamento'
		dataType: string
		lineageTag: 46740a1c-f673-4072-81b3-631f3e5331cc
		summarizeBy: none
		sourceColumn: Razão Social Fornecedor - Faturamento

		annotation SummarizationSetBy = Automatic

	column 'CNPJ Fornecedor - Faturamento'
		dataType: string
		lineageTag: dd40f9ae-7729-4fe4-be7b-e09859456a20
		summarizeBy: none
		sourceColumn: CNPJ Fornecedor - Faturamento

		annotation SummarizationSetBy = Automatic

	column 'Origem dos dados de fornecedor'
		dataType: string
		lineageTag: 54df648d-9208-452c-9505-2b3abb07dc71
		summarizeBy: none
		sourceColumn: Origem dos dados de fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia Unidade'
		dataType: string
		lineageTag: 33a98a87-d421-4c3c-84d8-8d4602d485f6
		summarizeBy: none
		sourceColumn: Nome Fantasia Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 83b0b2bc-ae5b-41d9-b92a-2152bbfc772e
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Tipo do Contrato'
		dataType: string
		lineageTag: 8e2403dd-eeb8-4319-9b4c-3af5b3cea1d4
		summarizeBy: none
		sourceColumn: Tipo do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Data de cadastro do contrato'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8f5a6e5b-673d-4ca0-9382-85c235e00790
		summarizeBy: none
		sourceColumn: Data de cadastro do contrato

		variation Variation
			isDefault
			relationship: 27e6cb88-710f-4bf1-a570-bf65c511693f
			defaultHierarchy: LocalDateTable_d4cc921e-09e4-4df0-bd89-597745e5916d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de início da vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e01d50c4-fc13-4976-ab6e-5887a211a583
		summarizeBy: none
		sourceColumn: Data de início da vigência

		variation Variation
			isDefault
			relationship: 50a01d14-c4ff-47e6-85a2-2449bce11047
			defaultHierarchy: LocalDateTable_35f7f721-4388-4874-9836-4290b75e7c31.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de fim da vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d23bdb8-8cdc-4d87-a007-b962fdffa0a8
		summarizeBy: none
		sourceColumn: Data de fim da vigência

		variation Variation
			isDefault
			relationship: 3b9cc0d3-3d07-4e5a-ba8f-ec4ce6ed3fb3
			defaultHierarchy: LocalDateTable_0929a975-ccfb-4fb5-9200-46aaa883b237.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PIS
		dataType: string
		lineageTag: 9b447cdb-592c-4c61-8cc1-a5e09f423f22
		summarizeBy: none
		sourceColumn: PIS

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 1e884a82-bdb6-4832-89d1-9359300de483
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Data de cadastro'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1612943-f756-448b-a6f2-d144b448f73e
		summarizeBy: none
		sourceColumn: Data de cadastro

		variation Variation
			isDefault
			relationship: 3372a83d-ca4d-4a6b-bafe-6e721a314f16
			defaultHierarchy: LocalDateTable_0e67ccf8-9a4c-429a-9684-41ac2b6891a3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo de cobrança do funcionário'
		dataType: string
		lineageTag: 67c58f1a-80c9-49dd-98f8-bb52d084370a
		summarizeBy: none
		sourceColumn: Tipo de cobrança do funcionário

		annotation SummarizationSetBy = Automatic

	column Personalizar
		dataType: string
		lineageTag: 06cb592e-6440-4f0e-9755-3fda63db9dc7
		summarizeBy: none
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 53471252-c3a1-4067-9baf-2312d309b28d
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column 'Chave - Status Funcio'
		dataType: string
		lineageTag: 94f87a6e-2d34-42be-a9c9-a92ad400407b
		summarizeBy: none
		sourceColumn: Chave - Status Funcio

		annotation SummarizationSetBy = Automatic

	column Situação
		dataType: string
		lineageTag: a245b464-8927-44ed-a391-f843e0d1768a
		summarizeBy: none
		sourceColumn: Situação

		annotation SummarizationSetBy = Automatic

	column Gestor = LOOKUPVALUE(Gestores[Gestor],Gestores[Fornecedores],Efetivos[Razão Social Fornecedor - Contrato])
		lineageTag: 849b779e-4a01-48b7-a4c1-66d9cbe0fbc6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Vigência
		dataType: string
		lineageTag: 2596ab0f-ee66-4972-a1d2-9e94a8a4ed2e
		summarizeBy: none
		sourceColumn: Vigência

		annotation SummarizationSetBy = Automatic

	partition Efetivos = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="Declare @OrganizationId Uniqueidentifier = '0ef9a2b4-43f6-4be5-8e9c-aeaef626e7cf'#(lf)Declare @Date DateTime = GETDATE()#(lf)#(lf)Select #(lf)#(tab)bc.Id As 'Chave',#(lf)#(tab)c.OrderNumber As 'Número Contrato',#(lf)#(tab)p.TradeName As 'Nome Fantasia Fornecedor',#(lf)#(tab)bc.CompanyName As 'Razão Social Fornecedor - Contrato',#(lf)#(tab)(Select bc.Document) As 'CNPJ Fornecedor - Contrato',#(lf)#(tab)(#(lf)#(tab)#(tab)Case#(lf)#(tab)#(tab)#(tab)When (cb.CompanyName is not null) then cb.CompanyName#(lf)#(tab)#(tab)#(tab)When (c.FatherId is not null) then BranchCompanyFather.CompanyName#(lf)#(tab)#(tab)#(tab)When (c.FatherId is null) and (c.OrderNumber like '%Subcontratada%') then#(lf)#(tab)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)select top 1 BranchCompanyFatherSub.CompanyName from Contract as ContractSub with(nolock)#(lf)#(tab)#(tab)#(tab)#(tab)inner join BranchCompany as BranchCompanyFatherSub with(nolock)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)On BranchCompanyFatherSub.Id = ContractSub.BranchCompanyId#(lf)#(tab)#(tab)#(tab)#(tab)where#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ContractSub.OrderNumber like#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)CONCAT(#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)'%',#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)(select top 1 * from STRING_SPLIT((SELECT REPLACE(c.OrderNumber, ' ', '')), '-') where value not like 'Subcontratada'),#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)'%'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)#(tab)Order by LEN(ContractSub.OrderNumber)#(lf)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)Else bc.CompanyName#(lf)#(tab)#(tab)End#(lf)#(tab)) As 'Razão Social Fornecedor - Faturamento',#(lf)#(tab)(#(lf)#(tab)#(tab)Case#(lf)#(tab)#(tab)#(tab)When (c.ContractBillingId is not null) then cb.Document#(lf)#(tab)#(tab)#(tab)When (c.FatherId is not null) then BranchCompanyFather.Document#(lf)#(tab)#(tab)#(tab)When (c.FatherId is null) and (c.OrderNumber like '%Subcontratada%') then#(lf)#(tab)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)select top 1 BranchCompanyFatherSub.Document from Contract as ContractSub with(nolock)#(lf)#(tab)#(tab)#(tab)#(tab)inner join BranchCompany as BranchCompanyFatherSub with(nolock)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)On BranchCompanyFatherSub.Id = ContractSub.BranchCompanyId#(lf)#(tab)#(tab)#(tab)#(tab)where#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ContractSub.OrderNumber like#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)CONCAT(#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)'%',#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)(select top 1 * from STRING_SPLIT((SELECT REPLACE(c.OrderNumber, ' ', '')), '-') where value not like 'Subcontratada'),#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)'%'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)#(tab)Order by LEN(ContractSub.OrderNumber)#(lf)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)Else bc.Document#(lf)#(tab)#(tab)End#(lf)#(tab)) As 'CNPJ Fornecedor - Faturamento',#(lf)    (#(lf)        Case #(lf)            When c.ContractBillingId is null Then 'Contrato'#(lf)            Else 'Dados de faturamento'#(lf)        End#(lf)    ) As 'Origem dos dados de fornecedor',#(lf)#(tab)b.TradeName As 'Nome Fantasia Unidade',#(lf)#(tab)ca.Name As 'Categoria',#(lf)#(tab)(#(lf)#(tab)#(tab)Case#(lf)#(tab)#(tab)#(tab)When c.Type = 1 Then 'Contínuo'#(lf)#(tab)#(tab)#(tab)When c.Type = 2 Then 'Grandes Paradas'#(lf)#(tab)#(tab)#(tab)When c.Type = 4 Then 'Eventual'#(lf)#(tab)#(tab)#(tab)When c.Type = 8 Then 'Temporário'#(lf)#(tab)#(tab)#(tab)When c.Type = 16 Then 'Visitante técnico'#(lf)#(tab)#(tab)#(tab)When c.Type = 32 Then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)#(tab)#(tab)#(tab)When c.Type = 64 Then 'Prestação de serviço eventual fora da área operacional'#(lf)#(tab)#(tab)#(tab)When c.Type = 128 Then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)#(tab)#(tab)#(tab)When c.Type = 256 Then 'Compra Direta, Regulariza e Delegada'#(lf)#(tab)#(tab)#(tab)Else 'Tipo de contrato desconhecido'#(lf)#(tab)#(tab)End#(lf)#(tab)) As 'Tipo do Contrato',#(lf)#(tab)Convert(Varchar, c.CreatedAt, 103) As 'Data de cadastro do contrato',#(lf)#(tab)Convert(Varchar, c.ValidityInitial, 103) As 'Data de início da vigência',#(lf)#(tab)Convert(Varchar, c.ValidityFinal, 103) As 'Data de fim da vigência',#(lf)#(tab)(Select e.PisNumber) As 'PIS',#(lf)#(tab)(Select e.CpfNumber) As 'CPF',#(lf)#(tab)e.Name As 'Nome',#(lf)#(tab)CASE #(lf)        WHEN (E.Situation = 0 AND E.Removed = 0) THEN 'Ativo' #(lf)        WHEN (E.Situation = 1 OR E.Removed = 1) THEN 'Inativo' #(lf)        WHEN E.Situation = 2 THEN 'Folguista' #(lf)    END AS 'Situação',#(lf)#(tab)Convert(Varchar, e.CreatedAt, 103) As 'Data de cadastro',#(lf)#(tab)(#(lf)#(tab)#(tab)Case #(lf)#(tab)#(tab)#(tab)When c.Type = 1 Then#(lf)#(tab)#(tab)#(tab)#(tab)Case #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)When Month(e.CreatedAt) = Month(@Date) And Year(e.CreatedAt) = Year(@Date) Then 'Mobilização'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)When @Date > e.CreatedAt And (@Date Between c.ValidityInitial And DateAdd(Month, 1, c.ValidityFinal)) Then 'Recorrente'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)Else 'Não cobrar'#(lf)#(tab)#(tab)#(tab)#(tab)End#(lf)#(tab)#(tab)#(tab)Else#(lf)#(tab)#(tab)#(tab)#(tab)Case #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)When Month(e.CreatedAt) = Month(@Date) And Year(e.CreatedAt) = Year(@Date) Then 'Mobilização'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)When @Date > e.CreatedAt And (@Date Between c.ValidityInitial And c.ValidityFinal) Then 'Recorrente'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)Else 'Não cobrar'#(lf)#(tab)#(tab)#(tab)#(tab)End#(lf)#(tab)#(tab)End#(lf)#(tab)) As 'Tipo de cobrança do funcionário'#(lf)#(tab)#(lf)From #(lf)#(tab)Effective As e#(lf)#(tab)Inner Join [Contract] As c On c.Id = e.ContractId#(lf)#(tab)Inner Join Building As b On b.Id = c.BuildingId#(lf)#(tab)Inner Join [Provider] As p On p.Id = c.ProviderId#(lf)#(tab)Inner Join BranchCompany As bc On bc.Id = c.BranchCompanyId#(lf)#(tab)Inner Join Category As ca On ca.Id = c.CategoryId#(lf)    Left Join ContractBilling cb on c.ContractBillingId = cb.Id#(lf)#(tab)Left Join Contract as ContractFather On ContractFather.Id = c.FatherId#(lf)#(tab)Left Join BranchCompany as BranchCompanyFather On BranchCompanyFather.Id = ContractFather.BranchCompanyId#(lf)Where#(lf)#(tab)b.OrganizationId = @OrganizationId#(lf)#(tab)And c.Removed = 0#(lf)#(tab)And e.Removed = 0#(lf)#(tab)And e.CreatedAt < @Date#(lf)    And c.[Status] = 0"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Chave", type text}, {"Número Contrato", type text}, {"Nome Fantasia Fornecedor", type text}, {"Razão Social Fornecedor - Contrato", type text}, {"CNPJ Fornecedor - Contrato", type text}, {"Razão Social Fornecedor - Faturamento", type text}, {"CNPJ Fornecedor - Faturamento", type text}, {"Origem dos dados de fornecedor", type text}, {"Nome Fantasia Unidade", type text}, {"Categoria", type text}, {"Tipo do Contrato", type text}, {"Data de cadastro do contrato", type date}, {"Data de início da vigência", type date}, {"Data de fim da vigência", type date}, {"PIS", type text}, {"CPF", type text}, {"Nome", type text}, {"Data de cadastro", type date}, {"Tipo de cobrança do funcionário", type text}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas em Branco Removidas", "Personalizar", each if Text.Contains([Nome Fantasia Unidade], "Campinas") then "Com Controle de Mobilização" else if Text.Contains([Nome Fantasia Unidade], "Feira de Santana") then "Com Controle de Mobilização" else "Sem Controle de Mobilização"),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Coluna Condicional Adicionada", "CPF", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"CPF.1", "CPF.2"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Dividir Coluna por Delimitador",{{"CPF.1", "CPF"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"CPF.2"}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Colunas Removidas", "Chave - Status Funcio", each Text.Combine({[#"Nome Fantasia Fornecedor"], [Nome Fantasia Unidade], [Categoria], [CPF]}, ""), type text),
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Mesclada Inserida", "Vigência", each let 
				    inicial =  [Data de início da vigência],
				    final = [Data de fim da vigência],
				    hoje = Date.From(DateTime.LocalNow())
				in 
				    if final < hoje then "Não Vigente"
				        else if inicial > hoje then "Vigente Futuramente"
				        else "Vigente")
				in
				    #"Personalização Adicionada"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

