table 'Status de funcionários'
	lineageTag: 27b612fc-57e6-4587-9772-c93c6d5503d2

	measure '(Colaboradores) Quantidade' = CALCULATE(DISTINCTCOUNT('Status de funcionários'[CPF]))
		formatString: #,0
		lineageTag: df983886-1ce2-4893-b00f-aa206231f894

	column Nome
		dataType: string
		lineageTag: fe95c0c0-b5f3-416b-810d-628187968a2f
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Número de matrícula'
		dataType: string
		lineageTag: c37a71a5-4d9f-424b-8c35-0e5e1974d94c
		summarizeBy: none
		sourceColumn: Número de matrícula

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 26519dc3-8139-4052-b397-38cc428c4c77
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column PIS
		dataType: string
		lineageTag: 16f2a8c1-67c7-420c-998b-58a8fbb28767
		summarizeBy: none
		sourceColumn: PIS

		annotation SummarizationSetBy = Automatic

	column 'Documento Estrangeiro'
		dataType: string
		lineageTag: 02801875-cc83-4d9f-9fbc-2301be80ed07
		summarizeBy: none
		sourceColumn: Documento Estrangeiro

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 2719f3aa-834d-43e5-95a4-ceb978ab51d0
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 7debb2df-ae6d-4f60-b592-48d966759cf6
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: 77f6a220-4da0-4d9e-a44c-31bb1b0c3002
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 669df28f-c77a-4b34-a8e3-693d1cd27c83
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: f85a8346-f6af-4559-9680-cff3771bf03e
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: 000fa5c7-db6c-45f2-ac8e-a778ca8f2dfc
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: 5f243675-d7aa-43aa-b357-e3d8cec9286d
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Número de matrícula_1'
		dataType: string
		lineageTag: ff9d69bb-dd2f-43f1-a2e6-7be3ba0f12dc
		summarizeBy: none
		sourceColumn: Número de matrícula_1

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: eb5d2f0d-0fe1-4362-a6f1-e6c8b027d88b
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia do Subcontrato'
		dataType: string
		lineageTag: 37dd5d16-e790-4216-9990-869266a201cd
		summarizeBy: none
		sourceColumn: Nome Fantasia do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: 3a393fc2-ee51-4be5-b095-35d7fa6943e3
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: 3ce5c9ed-dd05-4913-b393-0c8214e16e34
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência do Contrato'
		dataType: string
		lineageTag: d35e748c-e372-4a39-9e3c-e198bb36039a
		summarizeBy: none
		sourceColumn: Vigência do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: 379dd68e-e2cd-4b18-bc03-5de86569e657
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Modalidade de Contratação'
		dataType: string
		lineageTag: 5cf9f45a-90cd-4dde-8faf-c80f648d3610
		summarizeBy: none
		sourceColumn: Modalidade de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Tipo de moradia'
		dataType: string
		lineageTag: d5fcc6a3-345d-4d56-8844-d1c7e33a6169
		summarizeBy: none
		sourceColumn: Tipo de moradia

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: ab897a1b-0a43-4edb-8078-f187aa43dc3d
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: c0723c16-f89a-4f1c-90ff-301f3f4465c0
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column Escala
		dataType: string
		lineageTag: a3ce2156-f321-4a2e-9489-06f6fb11a145
		summarizeBy: none
		sourceColumn: Escala

		annotation SummarizationSetBy = Automatic

	column 'Início da jornada'
		dataType: string
		lineageTag: 8f375fb9-814f-4908-b4a2-4bc2731ee390
		summarizeBy: none
		sourceColumn: Início da jornada

		annotation SummarizationSetBy = Automatic

	column 'Término da jornada'
		dataType: string
		lineageTag: 768a95b9-5fa9-4800-9959-03f420d0b05a
		summarizeBy: none
		sourceColumn: Término da jornada

		annotation SummarizationSetBy = Automatic

	column 'Total de Docs'
		dataType: int64
		formatString: 0
		lineageTag: 4aca83ef-2f37-4acd-b572-c16739518603
		summarizeBy: sum
		sourceColumn: Total de Docs

		annotation SummarizationSetBy = Automatic

	column 'Total de válidos'
		dataType: int64
		formatString: 0
		lineageTag: ca08ae31-f7f2-4697-9aef-ffcd7721c26a
		summarizeBy: sum
		sourceColumn: Total de válidos

		annotation SummarizationSetBy = Automatic

	column '% docs válidos'
		dataType: double
		lineageTag: b8c64e5b-c1ad-4da8-9557-a1a8d9bbc2ce
		summarizeBy: sum
		sourceColumn: % docs válidos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total em análise'
		dataType: int64
		formatString: 0
		lineageTag: 4d76bf7c-09b8-4753-b8ae-876b1b94669f
		summarizeBy: sum
		sourceColumn: Total em análise

		annotation SummarizationSetBy = Automatic

	column '% docs em análise'
		dataType: double
		lineageTag: 7c0af175-0b1b-4825-be01-3302c18a6653
		summarizeBy: sum
		sourceColumn: % docs em análise

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total pendentes'
		dataType: int64
		formatString: 0
		lineageTag: a4b736f5-24ee-4640-b6e1-051dc02870d0
		summarizeBy: sum
		sourceColumn: Total pendentes

		annotation SummarizationSetBy = Automatic

	column '% docs entregues'
		dataType: double
		lineageTag: cedd78cf-7839-41bb-8114-9b540df6c8b1
		summarizeBy: sum
		sourceColumn: % docs entregues

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mobilizado até'
		dataType: string
		lineageTag: 82e89f23-c465-4ddd-ad06-2c073412e171
		summarizeBy: none
		sourceColumn: Mobilizado até

		annotation SummarizationSetBy = Automatic

	column 'Próximo documento a vencer'
		dataType: string
		lineageTag: 272cb517-f129-4186-bc1f-39100454ea3f
		summarizeBy: none
		sourceColumn: Próximo documento a vencer

		annotation SummarizationSetBy = Automatic

	column 'Status Restrição de acesso'
		dataType: string
		lineageTag: 6e8798b7-b961-4a41-a448-357b8f938fd8
		summarizeBy: none
		sourceColumn: Status Restrição de acesso

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes (Não entregues ou Recusados)'
		dataType: string
		lineageTag: d289181d-83a4-49e3-a1e7-c915f2419a82
		summarizeBy: none
		sourceColumn: Documentos pendentes (Não entregues ou Recusados)

		annotation SummarizationSetBy = Automatic

	column 'Chave 1'
		dataType: string
		lineageTag: 210bf1a6-36ef-43bd-b3d7-09f8d35a2269
		summarizeBy: none
		sourceColumn: Chave 1

		annotation SummarizationSetBy = Automatic

	column 'Chave - Status Funcio'
		dataType: string
		lineageTag: 1a99ec8a-f55b-4794-9a00-9d3ebe75271b
		summarizeBy: none
		sourceColumn: Chave - Status Funcio

		annotation SummarizationSetBy = Automatic

	column Gestor = LOOKUPVALUE(Gestores[Gestor],Gestores[CNPJ],'Status de funcionários'[CNPJ])
		lineageTag: 9453a89e-2764-4cf0-9818-82c2afd22270
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Início e Fim das Atividades'
		dataType: string
		lineageTag: fdca0a05-743c-4d76-a398-1a51ff95d68d
		summarizeBy: none
		sourceColumn: Início e Fim das Atividades

		annotation SummarizationSetBy = Automatic

	column Column39
		dataType: string
		lineageTag: a2edca65-11de-4a01-846c-3d97a4f7d125
		summarizeBy: none
		sourceColumn: Column39

		annotation SummarizationSetBy = Automatic

	partition 'Status de funcionários' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://adminatlasinovacoescom.sharepoint.com/:x:/r/sites/DiretrioPadro/Documentos%20Compartilhados/Relat%C3%B3rios/Dados/02.%20Externo/01.%20AFM%20Gest%C3%A3o/Pirelli/2025/12%20-%20Dezembro/Funcionarios%20-%202512051429.xlsx"), null, true),
				    #"Status de funcionários_Sheet" = Fonte{[Item="Status de funcionários",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Status de funcionários_Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type any}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Linhas em Branco Removidas",7),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Nome", type text}, {"Número de matrícula", type text}, {"CPF", type text}, {"PIS", type text}, {"Documento Estrangeiro", type text}, {"Fornecedor", type text}, {"Razão Social", type text}, {"CNPJ", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Razão Social do Contrato", type text}, {"CNPJ do Contrato", type text}, {"Número de matrícula_1", type text}, {"Tipo de Fornecedor", type text}, {"Nome Fantasia do Subcontrato", type text}, {"Razão Social do Subcontrato", type text}, {"CNPJ do Subcontrato", type text}, {"Vigência do Contrato", type text}, {"Tipo de Contratação", type text}, {"Modalidade de Contratação", type text}, {"Tipo de moradia", type text}, {"Número do Pedido", type text}, {"Função", type text}, {"Escala", type text}, {"Início da jornada", type text}, {"Término da jornada", type text}, {"Total de Docs", Int64.Type}, {"Total de válidos", Int64.Type}, {"% docs válidos", type number}, {"Total em análise", Int64.Type}, {"% docs em análise", type number}, {"Total pendentes", Int64.Type}, {"% docs entregues", type number}, {"Mobilizado até", type text}, {"Próximo documento a vencer", type text}, {"Status Restrição de acesso", type text}, {"Documentos pendentes (Não entregues ou Recusados)", type text}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado1", "Chave 1", each Text.Combine({[Fornecedor], [Categoria], [Unidade]}, ""), type text),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Coluna Mesclada Inserida", "Chave - Status Funcio", each Text.Combine({[Fornecedor], [Unidade], [Categoria], [CPF]}, ""), type text)
				in
				    #"Coluna Mesclada Inserida1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

