table Contratos
	lineageTag: c7540fc2-709d-4c4e-bd1d-a3efd382f295

	column 'N° do pedido'
		dataType: string
		lineageTag: a7de5eb3-7270-41ad-8688-5da997243896
		summarizeBy: none
		sourceColumn: N° do pedido

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 0991785e-6bc9-4737-9fa8-c5d8ae374a3a
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: c1861c3e-929a-4769-a1e5-ebafc20c1d22
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: f9f9bad1-4e4a-4c0f-80bc-925d0a211fa1
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 92a67523-bbb9-4071-84db-97dcdee67846
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: dfb3612d-c99a-46a8-bf7e-c62316a802c2
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column 'Tipo do contrato'
		dataType: string
		lineageTag: f79b5303-8133-4d9f-9346-a28ec7199585
		summarizeBy: none
		sourceColumn: Tipo do contrato

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 5bb4905f-df4a-4fc5-8a4d-4f9c35efb267
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: a23158ed-2d94-4b5d-9529-6d5d568f35be
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: d9ab576c-653f-47f7-9f3f-210185d143a8
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 807843a3-8182-4f42-9fbb-549b96b9580d
			defaultHierarchy: LocalDateTable_d5ea8377-1014-4fab-8ca6-2134d7477d33.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Vigência
		dataType: string
		lineageTag: a5678f4e-fb81-4d87-b499-e9ec8be87992
		summarizeBy: none
		sourceColumn: Vigência

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: ef82f31c-cae1-433f-bcc9-945712b3849b
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 60ae5b60-8c03-46be-a06e-2748e6ebd744
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 2a10cf36-cee3-4dff-9c99-597530742bc7
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 28b701fa-94bf-436e-abe7-4e275281439b
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: 4fac44ca-461b-4de7-8c73-e99cc83f226a
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome do Gestor'
		dataType: string
		lineageTag: f31701ee-e805-49b6-aa40-fe555aa55a96
		summarizeBy: none
		sourceColumn: Nome do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Email do Gestor'
		dataType: string
		lineageTag: 4818c104-b294-489a-8fde-c97f01c6fcea
		summarizeBy: none
		sourceColumn: Email do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: ebe511dd-e1a6-4da4-867b-95752f103ab9
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Área de Atuação'
		dataType: string
		lineageTag: 8126507d-f124-4602-ac0e-441e8ebdb658
		summarizeBy: none
		sourceColumn: Área de Atuação

		annotation SummarizationSetBy = Automatic

	column 'Expectativa do Início da Prestação de Serviço'
		dataType: string
		lineageTag: 3ac3aa05-be2e-4e72-bb8f-a10d458b7261
		summarizeBy: none
		sourceColumn: Expectativa do Início da Prestação de Serviço

		annotation SummarizationSetBy = Automatic

	column 'Expectativa da Quantidade de Efetivos'
		dataType: string
		lineageTag: 565bdb05-d768-4362-8174-14d7f53b9ec0
		summarizeBy: none
		sourceColumn: Expectativa da Quantidade de Efetivos

		annotation SummarizationSetBy = Automatic

	column 'Grupo de Atuação' = ```
			
			LOOKUPVALUE(
			    'Atuação'[Grupo de Atuação],
			    'Atuação'[Área de Atuação], 'Contratos'[Área de Atuação]
			)
			
			```
		lineageTag: 7e89c6fc-d266-4320-9d10-4ef492fb26b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)    bc.CompanyName[Razão Social],#(lf)    dbo.FormatCNPJ([bc].[Document]) AS [CNPJ],#(lf)#(tab)c.OrderNumber [Número do Pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)#(tab)case#(lf)        when c.[ServiceProvision] = 0 then 'Sem controle de horário e salário'#(lf)        when c.[ServiceProvision] = 1 then 'Com controle de horário, salário e documentação do FGTS'#(lf)        when c.[ServiceProvision] = 2 then 'Com controle de horário'#(lf)        when c.[ServiceProvision] = 3 then 'Com documentação do FGTS'#(lf)    end as 'Tipo do contrato',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],  #(lf)#(tab)cm.[Name][Nome do Gestor],#(lf)#(tab)cm.[Email][Email do Gestor],#(lf)#(tab)cm.[Phone][Telefone do Gestor],#(lf)#(tab)cfi2.[Name][Área de Atuação],#(lf)#(tab)cfv2.[Value][Expectativa do Início da Prestação de Serviço],#(lf)#(tab)cfv3.[Value][Expectativa da Quantidade de Efetivos]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(tab)#(tab)left join ContractManager cm with(nolock) on cm.ContractId = c.Id#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)left join CustomFieldValue cfv2 WITH(NOLOCK) ON cfv2.EntityId = c.Id AND cfv2.CustomFieldId = '7530CE34-07FF-474C-8D39-4059D40FCDB4' -- Expectativa do Início da Prestação de Serviço#(lf)#(tab)#(tab)left join CustomFieldValue cfv3 WITH(NOLOCK) ON cfv3.EntityId = c.Id AND cfv3.CustomFieldId = '262E7D00-E7FA-44CB-A2F9-B258BF07D90A' -- Expectativa da Quantidade de Efetivos#(lf)#(tab)#(tab)outer apply #(lf)#(tab)#(tab)(#(lf)    select cfi1.[Name] from CustomFieldValue cfv1 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi1 with(nolock) on cfv1.CustomFieldItemId = cfi1.Id#(lf)    where cfv1.EntityId = c.Id#(lf)#(tab)#(tab)and cfv1.[Value] is null#(lf)#(tab)#(tab)and cfv1.Removed = 0#(lf)#(tab)#(tab)and cfi1.Removed = 0#(lf)#(tab)#(tab)AND cfv1.CustomFieldId = '50C9DCD2-53AA-4A87-AC62-5D881C55CFB4' -- Área de atuação#(lf)#(tab)) as [cfi2]#(lf)where b.OrganizationId = '78091bc0-2575-4f7e-8d04-dbb9f68815b8'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(lf)#(lf)#(tab)  --Select * from CustomField Where OrganizationId = '78091bc0-2575-4f7e-8d04-dbb9f68815b8'#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(tab)"]),
				    #"Valor Substituído" = Table.ReplaceValue(Fonte,null,"---",Replacer.ReplaceValue,{"Área de Atuação"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","AUTOMOTIVA ","AUTOMOTIVA",Replacer.ReplaceText,{"Área de Atuação"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","AUTOMOTIVA ","AUTOMOTIVA",Replacer.ReplaceText,{"Área de Atuação"})
				in
				    #"Valor Substituído2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

