table 'Relatório de Fornecedores'
	lineageTag: 941748fe-575a-4074-ae85-ff049f2ce062

	measure 'Documentos Total' = CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]))
		formatString: #,0
		lineageTag: 04d5e06f-36b4-43ce-8f4f-22bbd1954c85

	measure 'Documentos em Análise' =
			IF(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Em Análise")=0,0,CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Em Análise"))
		formatString: 0
		lineageTag: 2af97cb3-ff8f-40b7-9231-ac5b3dfb19ba

	measure '1 - %Aprovados' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Aprovado")/[Documentos Total] + 0
		lineageTag: bf552cbf-8d4e-4736-b064-ac3992b0df9d

		formatStringDefinition =
				VAR APRO =FORMAT([1 - %Aprovados],"0.0%")
				
				VAR TOTAL = [Documentos Total]
				
				RETURN """" & APRO & " (" & TOTAL & ")"

	measure '1 - Quantidade de Docs Aprovados' =
			if(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Aprovado") = 0,
			"N/A"
			, (CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Aprovado")))
		formatString: #,0
		lineageTag: 11ee845c-1ee6-49f2-8a6f-8c6ee98a4c5d

	measure '3 - %Atrasados' =
			(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado")+ CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado Recusado"))/[Documentos Total]
		lineageTag: 0053bc5e-4e3b-4f7f-ba80-0fb5015ae793

		formatStringDefinition =
				VAR vAtrasado = FORMAT([3 - %Atrasados],"0.0%")
				VAR vTotal = [Documentos Total]
				VAR vResultados = """" & vAtrasado & " (" & vTotal & ")"
				return vResultados

	measure '3 - Atrasados' = ```
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado") +  
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado Recusado")
			```
		formatString: #,0
		lineageTag: 1333a4cf-2038-48a7-9d87-23b33dac0f17

	measure '2 - %Recusados' =
			(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado Recusado") + CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Próximas Entregas Recusadas"))/[Quantidade de Enviados]
		lineageTag: bf8ea3ae-05c6-4da5-b1d2-48a02abd6a7f

		formatStringDefinition =
				VAR vRecusado = FORMAT([2 - %Recusados],"0.0%")
				VAR vEnviados = [Quantidade de Enviados]
				VAR vresultado = """" & vRecusado & " (" & vEnviados & ")"
				return vresultado

	measure '2 - Recusados' = ```
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado Recusado") + 
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Próximas Entregaas Recusadas")
			```
		formatString: #,0
		lineageTag: 6b7513c8-21ca-431b-8a71-3638f9bc270c

	measure '4 - %Quantidade de Enviados' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] <> "Atrasado")/[Documentos Total]  + 0
		lineageTag: dec939ec-684d-443d-b5cc-80e2d74c63ea

		formatStringDefinition =
				VAR PORCEN = FORMAT([4 - %Quantidade de Enviados],"0.0%")
				
				VAR TOTAL = [Documentos Total]
				
				RETURN """" & PORCEN & " (" & TOTAL & ")"

	measure 'Quantidade de Enviados' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] <> "Atrasado")
		formatString: #,0
		lineageTag: 227b0b6c-139e-4bbc-91f5-5947713a5084

	measure 'Quantidade de Enviados dividido por Documentos Total' =
			
			DIVIDE([Quantidade de Enviados], [Documentos Total])
		lineageTag: 4563817b-edea-4742-a4db-3cf8fddf0535

		formatStringDefinition =
				VAR vEnviados = FORMAT([Quantidade de Enviados dividido por Documentos Total], "0.0%")
				VAR vTotal = [Documentos Total]
				VAR vResultado = """" & vEnviados & " (" & vTotal & ")"
				RETURN vResultado

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure %Aprovados =
			(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Status] = "Aprovado")+0)/[Documentos Total]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c6bd1d2a-cea2-4029-86f1-befe81dc18f2

	measure %Recusados =
			(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado Recusado") + CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Próximas Entregas Recusadas"))/[Quantidade de Enviados]
		formatString: 0%;-0%;0%
		lineageTag: 122791aa-7e05-4c81-8408-54a5fbd781e4

	measure %Atrasados =
			(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado") + CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado Recusado"))/[Documentos Total]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a4e5238a-8926-4371-8c98-f126e2b84440

	measure 'Quantidade de Analisado' = ```
			CALCULATE(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] <> "Atrasado",
			'Relatório de Fornecedores'[Status] <> "Em Análise"))
			
			```
		formatString: #,0
		lineageTag: b7a2b6b1-ded9-43e3-ba59-23fdc6ab3439

	measure 'Não Analisados' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado")
		formatString: #,0
		lineageTag: 1f105f0e-1510-473e-9fbd-836474bb154f

	measure 'Em Análise' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Em Análise")
		formatString: #,0
		lineageTag: d5965d6d-a3e3-461d-abef-c1d1da00dfb5

	measure '%Quantidade de Enviados' = ```
			
			    (CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Status] <> "Atrasado")+0)/[Documentos Total]
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 686f7950-5935-4cb6-b511-dbc9223258eb

	measure 'Peso 3' = ```
			(IF(
			    CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 1)<1,
			    
			    (((CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 3,
			       'Relatório de Fornecedores'[Status] <> "Aprovado"))/[Qunat Peso 3]))+0,
			    
			    ((((3/4)*CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 3,
			       'Relatório de Fornecedores'[Status] <> "Aprovado")))/[Qunat Peso 3])))+0
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9a286f2f-04b6-40fb-abbb-81b31291dbd4

	measure 'Qunat Peso 1' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 1)
		formatString: 0
		lineageTag: df2541e8-9a25-4f00-9435-7608e39c3f15

	measure 'Peso 1' = ```
			(IF(
			    CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 3)<1,
			    
			    ((CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 1,
			       'Relatório de Fornecedores'[Status] <> "Aprovado"))/[Qunat Peso 1])+0,
			    
			    (((1/4)*CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 1,
			       'Relatório de Fornecedores'[Status] <> "Aprovado"))/[Qunat Peso 1])))+ 0
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bd6c8b62-db58-4b25-b8e1-4d014c447849

	measure 'Qunat Peso 3' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Peso do Documentos] = 3)
		formatString: 0
		lineageTag: 3848ae26-b978-40dd-87fe-a74deb120435

	measure 'Risco Críticos' = AVERAGEX(VALUES('Relatório de Fornecedores'[Número do Pedido]),[Peso 1] + [Peso 3])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08a200f9-cdae-45c7-9e60-790a9c9582c0

	measure 'Quantidade Fornecedores - Total' = CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[CNPJ]))
		formatString: 0
		lineageTag: a97ca23e-3625-46fe-a07a-ef2a728e4e98

	measure 'Quantidade Contratos - Total' = CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[Número do Pedido]))
		formatString: 0
		lineageTag: 6360696d-3583-4992-8d06-46131b05c66d

	measure 'NUMERO DE PEDIDOS' = DISTINCTCOUNT('Relatório de Fornecedores'[Número do Pedido])
		formatString: 0
		lineageTag: ac406a88-917f-4828-88a4-be92007d7ffa

	measure '%(Média Mensal) Aderência' = [%Quantidade de Enviados] + 0
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 08f66f33-9d66-4549-a7fd-aedc37d60f49

	measure '%(Média Mensal) Conformidade' = [%Aprovados]+0
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eeb72fcd-9935-4986-8772-65ccf8e69fa1

	measure '%(Média Mensal) Grupo Risco' = AVERAGEX(VALUES('dCalendário'[Date].[Mês]),[Risco Críticos]) + 0
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f259783d-acd9-461b-8907-b19e9512daff

	measure '!Exportação EXCEL' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Peso do Documentos] = 3)
		formatString: 0
		lineageTag: e79e9921-f6cc-4fca-845c-e85ea4d5584e

	measure '!Exportação EXCEL (Enviados)' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Peso do Documentos] = 3,
			'Relatório de Fornecedores'[Status (Reclassificado)] ="Enviado")+0
		formatString: 0
		lineageTag: fefdd3d1-44f8-4922-bff3-cd5c9991e45e

	measure '!Exportação EXCEL (Ñ Enviados)' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Peso do Documentos] = 3,
			'Relatório de Fornecedores'[Status (Reclassificado)] ="Não Enviado")+0
		formatString: 0
		lineageTag: 8af37ee6-8bdb-4fc8-8517-249376895325

	measure '(Contínuos) Contratos' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[Número do Pedido]),
			'Relatório de Fornecedores'[Tipo de Contrato] = "Contínuo")
		formatString: 0
		lineageTag: 987a86a7-b14d-43af-9d8c-06eab4e10771

	measure '(Eventual) Contratos' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[Número do Pedido]),
			'Relatório de Fornecedores'[Tipo de Contrato] = "Eventual")
		formatString: 0
		lineageTag: 86c98c09-bb58-4583-8aa2-06ba38230cbe

	measure (%Recusado) =
			(CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Atrasado Recusado") + CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] = "Próximas Entregas Recusadas"))/[Quantidade de Enviados]
		lineageTag: 758970d9-2ab8-4d74-8fa9-4e1768fcabc4

		formatStringDefinition =
				VAR ENVI = [Quantidade de Enviados]
				
				VAR POR = FORMAT([%Recusados],"0.0%")
				
				RETURN """" & POR & " (" & ENVI & ")"

	measure '(Enviados) Quantidade de Enviados' = ```
			
			    (CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			        'Relatório de Fornecedores'[Status] <> "Atrasado")+0)
			```
		formatString: 0
		lineageTag: 12beee42-ffbe-4451-8cc8-407947762145

	measure '% Fornecedores 100% Aderência' = ```
			
			VAR FornecedoresComAderencia =
			    ADDCOLUMNS(
			        VALUES ( 'Relatório de Fornecedores'[Fornecedor] ),
			        "@Aderencia", [%(Média Mensal) Aderência]
			    )
			VAR FornecedoresValidos =
			    FILTER(
			        FornecedoresComAderencia,
			        NOT ISBLANK ( [@Aderencia] )
			            && [@Aderencia] >= 0
			            && [@Aderencia] <= 1      -- se sua medida for 0 a 1
			            -- se for 0 a 100, troque por: && [@Aderencia] <= 100
			    )
			VAR Fornecedores100 =
			    FILTER(
			        FornecedoresValidos,
			        [@Aderencia] = 1              -- se for 0 a 1
			        -- se for 0 a 100, troque por: [@Aderencia] = 100
			    )
			RETURN
			DIVIDE(
			    COUNTROWS ( Fornecedores100 ),
			    COUNTROWS ( FornecedoresValidos )
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 093a4d28-604f-486e-b99a-7508f5cb915a

	measure 'Qtd Fornecedores 100% Aderencia' = ```
			
			VAR FornecedoresComAderencia =
			    ADDCOLUMNS (
			        VALUES ( 'Relatório de Fornecedores'[Fornecedor] ),
			        "@Aderencia", [%(Média Mensal) Aderência]
			        -- ou [%(Média Mensal) Aderência], se for o seu caso
			    )
			VAR Fornecedores100 =
			    FILTER (
			        FornecedoresComAderencia,
			        NOT ISBLANK ( [@Aderencia] )
			            && [@Aderencia] = 1        -- se a medida vai de 0 a 1
			            -- se for 0 a 100, use: && [@Aderencia] = 100
			    )
			RETURN
			COUNTROWS ( Fornecedores100 )
			
			```
		formatString: 0
		lineageTag: b0a7a68e-d515-45cc-b98d-b6b35c980408

	measure '% Fornecedores 100% Conformidade' = ```
			
			VAR FornecedoresComConformidade =
			    ADDCOLUMNS(
			        VALUES ( 'Relatório de Fornecedores'[Fornecedor] ),
			        "@Conformidade", [%(Média Mensal) Conformidade]
			    )
			VAR FornecedoresValidos =
			    FILTER(
			        FornecedoresComConformidade,
			        NOT ISBLANK ( [@Conformidade] )
			            && [@Conformidade] >= 0
			            && [@Conformidade] <= 1      -- se sua medida for 0 a 1
			            -- se for 0 a 100, troque por: && [@Conformidade] <= 100
			    )
			VAR Fornecedores100 =
			    FILTER(
			        FornecedoresValidos,
			        [@Conformidade] = 1              -- se for 0 a 1
			        -- se for 0 a 100, troque por: [@Conformidade] = 100
			    )
			RETURN
			DIVIDE(
			    COUNTROWS ( Fornecedores100 ),
			    COUNTROWS ( FornecedoresValidos )
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: aa6bab52-e6d5-48f4-8fc7-bc86807ab844

	measure 'Qtd Fornecedores 100% Conformidade' = ```
			
			VAR FornecedoresComConformidade =
			    ADDCOLUMNS (
			        VALUES ( 'Relatório de Fornecedores'[Fornecedor] ),
			        "@Conformidade", [%(Média Mensal) Conformidade]
			        -- ou [%(Média Mensal) Conformidade], se for o seu caso
			    )
			VAR Fornecedores100 =
			    FILTER (
			        FornecedoresComConformidade,
			        NOT ISBLANK ( [@Conformidade] )
			            && [@Conformidade] = 1        -- se a medida vai de 0 a 1
			            -- se for 0 a 100, use: && [@Conformidade] = 100
			    )
			RETURN
			COUNTROWS ( Fornecedores100 )
			
			```
		formatString: 0
		lineageTag: 42bed8f2-7982-4cbc-a144-c9a74c16a5ff

	column Documento
		dataType: string
		lineageTag: d5f82226-1c97-4b36-856d-fe9033aa5fe0
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: abd7cc4e-5251-4dd9-bca6-2fdefef44b0f
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: d1db0887-7608-4921-b0d0-55e8d967cfae
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 3643d765-de0a-41b0-baf5-0d6d577e16a1
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 9d70f986-7488-4fc4-b868-ee31c27c0126
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: b3cd0473-d63b-419b-b1dc-d03b258440e2
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 8c86c10a-baf0-4066-9d85-63ccd661bee4
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88631286-9557-4c4a-99e1-e66718300c15
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: b6118b9f-17b5-4365-b86a-94681a560edc
			defaultHierarchy: LocalDateTable_601600e6-bb4d-43b9-b6d2-852c3b8420b6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 3dfe1e27-a33e-4342-9b1e-08c28976946d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 61d21e61-d1e7-45c6-912e-66113eaf8bcb
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: fe7f7f20-4582-46a3-9b12-cd3d02ff1fa8
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column 'Status (Reclassificado)'
		dataType: string
		lineageTag: aa9f93ea-f496-4430-b672-823e7a1c17ee
		summarizeBy: none
		sourceColumn: Status (Reclassificado)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 5813ea47-6254-43c1-b215-017a8c334e3f
		summarizeBy: none
		sourceColumn: Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Chave Fornecedores'
		dataType: string
		lineageTag: 1bc51141-3225-4207-beb8-7fe0d9d28f80
		summarizeBy: none
		sourceColumn: Chave Fornecedores

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 63f5bf03-e1a4-47cd-ad96-94d47f271c71
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Data da Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: eab0069a-5b47-46f7-b4a3-47c3cfbd278e
		summarizeBy: none
		sourceColumn: Data da Análise

		variation Variation
			isDefault
			relationship: e3235d18-953f-4421-a55e-8ccd744820af
			defaultHierarchy: LocalDateTable_357696e8-dd17-4215-94fe-b3ee76ea8695.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Peso do Documentos' = LOOKUPVALUE('Peso Documentos'[Peso],'Peso Documentos'[Documento],'Relatório de Fornecedores'[Documento])
		formatString: 0
		lineageTag: aaea68fa-a9a8-4ea7-b743-2bd84f46926a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Chave Status Forne'
		dataType: string
		lineageTag: e0270797-9abb-4d60-a5df-f3980818c9ae
		summarizeBy: none
		sourceColumn: Chave Status Forne

		annotation SummarizationSetBy = Automatic

	column 'Chave de Número de Pedido'
		dataType: string
		lineageTag: 6a43df49-8322-4adf-9095-5540df1b4b09
		summarizeBy: none
		sourceColumn: Chave de Número de Pedido

		annotation SummarizationSetBy = Automatic

	column 'Início do Mês'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4dc0a292-2d87-4b75-81e0-5fd916acc229
		summarizeBy: none
		sourceColumn: Início do Mês

		variation Variation
			isDefault
			relationship: a9d9fd61-8d69-4f49-a994-a87c6d8f60ae
			defaultHierarchy: LocalDateTable_48db6bef-46cc-436d-b9b3-ecc8ff826528.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo de Documento'
		dataType: string
		lineageTag: 9939ed44-e425-4771-801d-4c59f858fec7
		summarizeBy: none
		sourceColumn: Tipo de Documento

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 5722c23c-7bb7-4a64-8aad-d3a46bca9757
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	partition 'Relatório de Fornecedores' = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = getdate();#(lf)DECLARE @organizationId uniqueidentifier = '78091bc0-2575-4f7e-8d04-dbb9f68815b8';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = getdate();#(lf)#(lf)#(lf)WITH DocumentScheduleBuildings AS (#(lf)    SELECT #(lf)        [dsb].[DocumentScheduleId],#(lf)        STRING_AGG(CAST([b].[TradeName] as nvarchar(MAX)), ', ') AS [Buildings]#(lf)    FROM#(lf)        [DocumentScheduleBuilding] AS [dsb]#(lf)        INNER JOIN [Building] AS [b] ON [dsb].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [dsb].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsb].[DocumentScheduleId]#(lf)),#(lf)DocumentScheduleCategories AS (#(lf)    SELECT#(lf)        [dsc].[DocumentScheduleId],#(lf)        STRING_AGG(CAST([c].[Name] as nvarchar(MAX)), ', ') AS [Categories]#(lf)    FROM#(lf)        [DocumentScheduleCategory] AS [dsc]#(lf)        INNER JOIN [Category] AS [c] ON [dsc].[CategoryId] = [c].[Id]#(lf)    WHERE#(lf)        [dsc].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsc].[DocumentScheduleId]#(lf))#(lf)SELECT#(lf)    DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)#(tab)CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)    [ds].Id AS [DocumentScheduleId],#(lf)    CASE#(lf)        WHEN [c].[OrderNumber] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [c].[OrderNumber]#(lf)    END AS [Número do Pedido],#(lf)#(tab)c.Id AS [Id_Contrato],#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        CASE#(lf)            WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)            WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)            WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)            WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)            WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)            WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)            WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)            WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)            WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)            ELSE 'Nenhum'#(lf)        END#(lf)    END AS [Tipo de Contrato],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    dbo.FormatCNPJ([bc].[Document]) AS [CNPJ],#(lf)    CASE#(lf)        WHEN [er].[Name] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [er].[Name]#(lf)    END AS [Funcionário],#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)    FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)    CASE#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Atrasado'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Próxima Entrega'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Atrasado Recusado'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Próxima Entrega Recusado'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL#(lf)        THEN#(lf)            'Em Análise'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 0#(lf)        THEN#(lf)            'Aprovado'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[IsValidated] IS NOT NULL AND [ds].[IsValidated] = 1#(lf)        THEN#(lf)            'Aprovado'#(lf)        ELSE#(lf)            '--'#(lf)    END AS [Status],#(lf)    ISNULL(dsBuildings.[Buildings], '---') AS [Unidade(s)],#(lf)    ISNULL(dsCategories.[Categories], '---') AS [Categoria(s)]#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    LEFT JOIN [DocumentScheduleBuildings] AS dsBuildings ON [ds].[Id] = dsBuildings.[DocumentScheduleId]#(lf)    LEFT JOIN [DocumentScheduleCategories] AS dsCategories ON [ds].[Id] = dsCategories.[DocumentScheduleId]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        (#(lf)            [ds].[UploadedAt] IS NOT NULL#(lf)            OR [c].[Removed] = 0#(lf)        )#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            (#(lf)                [ds].[ContractId] IS NOT NULL AND [ds].[ContractId] = [c].[Id]#(lf)            )#(lf)            OR (#(lf)#(tab)#(tab)#(tab)#(tab)[ds].[ContractId] IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                        AND EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                        AND NOT EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([ds].[ContractSetId] IS NOT NULL AND [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                    OR [ds].[ContractSetId] IS NULL#(lf)                )#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- unidades#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- categorias#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    (#(lf)                        [d].[DeliveryKind] <> 0#(lf)                        AND [d].[DeliveryKind] <> 1#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0#(lf)                                AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                ) -- deliveykind#(lf)                AND (#(lf)                    -- Agendamento por funcionario#(lf)                    (#(lf)                        [er].[Id] IS NOT NULL#(lf)                        AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                        AND [ds].[Kind] = 5#(lf)                        AND EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                                AND [erc].[ContractId] = [c].[Id]#(lf)                                AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                    -- / Agendamento por funcionario#(lf)                    -- Agendamento comum#(lf)                    OR (#(lf)                        [ds].[EmployeeRegisterId] IS NULL#(lf)                        AND [ds].[ContractId] IS NULL#(lf)                        AND [ds].[Kind] = 1#(lf)                    )#(lf)                    -- / Agendamento comum#(lf)                    -- Agendamento por unidade#(lf)                    OR (#(lf)                        [ds].Kind = 4#(lf)                    )#(lf)                    -- / Agendamento por unidade#(lf)                )#(lf)            )#(lf)        )#(lf)    )#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)-- ORDER BY #(lf)--     [p].[TradeName], [d].[Kind], [d].[Name], [ds].[ExpectedUploadAt], [er].[Name];"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Número do Pedido", type any}, {"Tipo de Contrato", type text}, {"Fornecedor", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Status (Reclassificado)", each if Text.Contains([Status], "Recusado") then "Enviado" else if [Status] = "Aprovado" then "Enviado" else if [Status] = "Em Análise" then "Enviado" else if [Status] = "Atrasado" then "Não Enviado" else null),
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Condicional Adicionada", "Competência", each if  [Prazo de Envio] < Date.FromText("01/11/2024") then Date.FromText("01/11/2024")
				
				else if [Tipo do documento] = "Recorrente" then if [Prazo de Envio] < Date.FromText("01/11/2024") 
				then  Date.AddMonths([Prazo de Envio],-1) 
				
				else [Prazo de Envio]
				
				else [Prazo de Envio]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Competência", type date}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado1", "Chave Fornecedores", each [Fornecedor]&[#"Categoria(s)"]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Número do Pedido", type text}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado2", "Chave", each [Fornecedor]&[CNPJ]&[#"Unidade(s)"]&[#"Categoria(s)"]&[Número do Pedido]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Personalização Adicionada2","---","",Replacer.ReplaceValue,{"Data da Análise"}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Valor Substituído",{{"Data da Análise", type date}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado3", "Chave Status Forne", each [Fornecedor]&[#"Categoria(s)"]&[#"Unidade(s)"]),
				    #"Início do Mês Inserido" = Table.AddColumn(#"Personalização Adicionada3", "Início do Mês", each Date.StartOfMonth([Competência]), type date),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Início do Mês Inserido", "Chave de Número de Pedido", each [Número do Pedido]&Date.ToText([Início do Mês])),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada4", each ([Competência] <> #date(2024, 7, 1) and [Competência] <> #date(2024, 7, 2)) and ([Status] <> "Próxima Entrega")),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Linhas Filtradas",null,"-",Replacer.ReplaceValue,{"Número do Pedido"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Valor Substituído1", each ([Status] <> "Próxima Entrega Recusado")),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Linhas Filtradas1",{{"Tipo do documento", "Tipo de Documento"}}),
				    #"Dividir Coluna por Delimitador" = Table.ExpandListColumn(Table.TransformColumns(#"Colunas Renomeadas1", {{"Unidade(s)", Splitter.SplitTextByDelimiter(", ", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Unidade(s)"),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Unidade(s)", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado4",{{"Unidade(s)", "Unidade"}})
				in
				    #"Colunas Renomeadas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

