table 'SLA Fornecedor'
	lineageTag: 22cf3dfe-7bdd-48bf-8cda-1b39a607c5d4

	measure _Dias_Envio_Fornecededor = CALCULATE(AVERAGE('SLA Fornecedor'[Tempo de Envio do Fornecedor]))/24
		lineageTag: ccc80374-b567-4086-8a97-42e3f43041c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Id_Cliente
		dataType: string
		lineageTag: 80fe6e1e-a45d-4e8e-899b-08b9d42e3335
		summarizeBy: none
		sourceColumn: Id_Cliente

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 4d17be6a-e418-4c50-b69e-09a4d025c861
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Id_Fornecedor
		dataType: string
		lineageTag: 6e580df3-a643-4f8b-b77b-5d1df0cddb77
		summarizeBy: none
		sourceColumn: Id_Fornecedor

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 8463bc0b-a3d1-4619-b8d0-08d12d52590c
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Funcionario
		dataType: string
		lineageTag: bee91813-ddf8-4902-b714-33f447b64b5d
		summarizeBy: none
		sourceColumn: Funcionario

		annotation SummarizationSetBy = Automatic

	column Id_Documento
		dataType: string
		lineageTag: cc1ae1f8-ce7c-4b93-965e-d921faf67738
		summarizeBy: none
		sourceColumn: Id_Documento

		annotation SummarizationSetBy = Automatic

	column Nome_Documento
		dataType: string
		lineageTag: 8e8044aa-dabc-4f2e-979f-c88e0e2f5ace
		summarizeBy: none
		sourceColumn: Nome_Documento

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: a5a0bad7-6dd2-4908-9fe0-32a97dc74ae5
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Id_Pedido
		dataType: string
		lineageTag: 1e71a359-0061-4b55-b778-ca6b398681fb
		summarizeBy: none
		sourceColumn: Id_Pedido

		annotation SummarizationSetBy = Automatic

	column Numero_Pedido
		dataType: string
		lineageTag: a929ee2f-33c3-4b91-b75b-7293988c359d
		summarizeBy: none
		sourceColumn: Numero_Pedido

		annotation SummarizationSetBy = Automatic

	column Data_Cadastro_Pedido
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1e3d265e-41de-4d44-8ec9-c43bdab07a11
		summarizeBy: none
		sourceColumn: Data_Cadastro_Pedido

		variation Variation
			isDefault
			relationship: dde68102-9b6b-4c24-829a-bfbc592d9005
			defaultHierarchy: LocalDateTable_6f3cfe76-699c-499e-8d92-7c936bf0b0d8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Hora_Cadastro_Pedido
		dataType: dateTime
		formatString: Long Time
		lineageTag: 282101b3-c601-4ddb-b0ce-efc3df088c0d
		summarizeBy: none
		sourceColumn: Hora_Cadastro_Pedido

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Prazo_Envio
		dataType: dateTime
		formatString: Short Date
		lineageTag: c310edfc-e0be-4f9a-82c1-fd872be60fa5
		summarizeBy: none
		sourceColumn: Prazo_Envio

		variation Variation
			isDefault
			relationship: 052ce243-c056-4046-9a79-9d3b380f9a0e
			defaultHierarchy: LocalDateTable_a8ae62f7-a589-4b80-8999-27e13900c003.'Hierarquia de datas'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Data_Envio
		dataType: double
		lineageTag: 51fab770-9b17-44d3-a4b2-38ee981a6a58
		summarizeBy: sum
		sourceColumn: Data_Envio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hora_Envio
		dataType: double
		lineageTag: 0e138c56-eefd-4bec-bf05-cd16806fc868
		summarizeBy: sum
		sourceColumn: Hora_Envio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data_Analise
		dataType: double
		lineageTag: 9d910664-8e2e-4ac2-9a90-c312ccd117c4
		summarizeBy: sum
		sourceColumn: Data_Analise

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hora_Analise
		dataType: double
		lineageTag: fdfc37b8-e6fe-4140-b53f-7a6c7366f2ca
		summarizeBy: sum
		sourceColumn: Hora_Analise

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Foi_Aprovado
		dataType: string
		lineageTag: d14eb568-1dae-4df4-b02a-7214a525c412
		summarizeBy: none
		sourceColumn: Foi_Aprovado

		annotation SummarizationSetBy = Automatic

	column Id_Analista
		dataType: string
		lineageTag: 649f9484-ac4b-4333-85fd-b2352f2c6bfd
		summarizeBy: none
		sourceColumn: Id_Analista

		annotation SummarizationSetBy = Automatic

	column Analisado_Por
		dataType: string
		lineageTag: 0e18dd52-c562-4531-a3ef-5eea7cc7a1e1
		summarizeBy: none
		sourceColumn: Analisado_Por

		annotation SummarizationSetBy = Automatic

	column Status_Documentacao
		dataType: string
		lineageTag: 8ac575e5-386b-423a-b0a8-b3800d2afa8c
		summarizeBy: none
		sourceColumn: Status_Documentacao

		annotation SummarizationSetBy = Automatic

	column Perfil
		dataType: string
		lineageTag: a6ab2328-ac2d-471f-b8cb-c32e53eda243
		summarizeBy: none
		sourceColumn: Perfil

		annotation SummarizationSetBy = Automatic

	column Observacao_Cliente
		dataType: string
		lineageTag: 46ef6ab8-9543-4c95-9c45-78d84b60244b
		summarizeBy: none
		sourceColumn: Observacao_Cliente

		annotation SummarizationSetBy = Automatic

	column Observacao_Fornecedor
		dataType: string
		lineageTag: 40ed3c5a-7801-402d-ad5f-4fcf01e2843d
		summarizeBy: none
		sourceColumn: Observacao_Fornecedor

		annotation SummarizationSetBy = Automatic

	column FDS_Análise
		dataType: string
		lineageTag: 97d389d8-b916-476a-9b07-2d5a1c7bfc03
		summarizeBy: none
		sourceColumn: FDS_Análise

		annotation SummarizationSetBy = Automatic

	column FDS_Envio
		dataType: string
		lineageTag: 11c2088b-6394-4b9c-a515-4ffd8936d848
		summarizeBy: none
		sourceColumn: FDS_Envio

		annotation SummarizationSetBy = Automatic

	column Hora_Corrigida_Análise
		dataType: dateTime
		formatString: Long Time
		lineageTag: d2463530-7238-43aa-b435-c37738a804f2
		summarizeBy: none
		sourceColumn: Hora_Corrigida_Análise

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Hora_Corrigida_Envio
		dataType: dateTime
		formatString: Long Time
		lineageTag: e85fed9c-fff6-465c-943b-1b7d73f6cb97
		summarizeBy: none
		sourceColumn: Hora_Corrigida_Envio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Data_Corrigida_Análise
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9afe865-398b-4ae5-93d7-57a8ae2e4e16
		summarizeBy: none
		sourceColumn: Data_Corrigida_Análise

		variation Variation
			isDefault
			relationship: f8ad47fc-2869-4bc6-a060-16db642625fc
			defaultHierarchy: LocalDateTable_b8047c4c-0a07-43d7-858c-8f8c54905459.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data_Corrigida _Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6f55747-80b9-48b8-a121-d8c694284a01
		summarizeBy: none
		sourceColumn: Data_Corrigida _Envio

		variation Variation
			isDefault
			relationship: b78a2916-a639-454d-b9c8-9dc112510dd9
			defaultHierarchy: LocalDateTable_a1f40830-59d1-4b94-9235-21f96a4386a2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SLA
		dataType: double
		lineageTag: 92a418b8-b0ca-49d7-95be-d871c158ad1a
		summarizeBy: sum
		sourceColumn: SLA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Final de semana'
		dataType: string
		lineageTag: fd76e1c0-f1f7-4953-8bfe-aadfbb39ba8f
		summarizeBy: none
		sourceColumn: Final de semana

		annotation SummarizationSetBy = Automatic

	column Data_Hora_Envio
		dataType: dateTime
		formatString: General Date
		lineageTag: f9d1c0fb-9206-4b25-a789-67643f1768d3
		summarizeBy: none
		sourceColumn: Data_Hora_Envio

		variation Variation
			isDefault
			relationship: c179c5c4-89e3-4a5b-b5aa-4b2009e4884e
			defaultHierarchy: LocalDateTable_0d480b8a-8bad-4e01-9c38-689cdaf894f7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Data_Hora_Análise
		dataType: dateTime
		formatString: General Date
		lineageTag: 95956d55-9b96-4a45-8935-d8a9ea0820e2
		summarizeBy: none
		sourceColumn: Data_Hora_Análise

		variation Variation
			isDefault
			relationship: 0fe54aa3-c6f4-426d-b9ec-864b60ec4756
			defaultHierarchy: LocalDateTable_b4ff59d0-e485-4e39-956d-8a334c6ca933.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Classificação_Envio
		dataType: string
		lineageTag: cb3edd90-bbe4-489c-9d82-73f6b0cc4286
		summarizeBy: none
		sourceColumn: Classificação_Envio

		annotation SummarizationSetBy = Automatic

	column Classificação_Analise
		dataType: string
		lineageTag: da4313c8-9c1a-4c1b-b9cb-0c538ce2aca2
		summarizeBy: none
		sourceColumn: Classificação_Analise

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: b7b7e6e0-cd31-4ebe-80ee-7594ec50df1a
		summarizeBy: sum
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	column 'Índice.1'
		dataType: int64
		formatString: 0
		lineageTag: 4d26c243-6d1f-4dfa-b4b9-af60b2af5291
		summarizeBy: sum
		sourceColumn: Índice.1

		annotation SummarizationSetBy = Automatic

	column 'Índice Adicionado1.Id_Documento'
		dataType: string
		lineageTag: 61b3d942-db9d-45b2-aa4d-754d5f302f4c
		summarizeBy: none
		sourceColumn: Índice Adicionado1.Id_Documento

		annotation SummarizationSetBy = Automatic

	column 'Índice Adicionado1.Data_Hora_Análise'
		dataType: dateTime
		formatString: General Date
		lineageTag: ec6c8862-a245-4802-b5f5-e19d3e66eb86
		summarizeBy: none
		sourceColumn: Índice Adicionado1.Data_Hora_Análise

		variation Variation
			isDefault
			relationship: 521a0789-3056-48da-9b1d-37c9224486e5
			defaultHierarchy: LocalDateTable_f1665a8a-0409-42a6-b7a5-b26b5731b016.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Tempo de Envio do Fornecedor'
		dataType: double
		lineageTag: f74b56e4-81fb-4167-ab2e-2151fd53d4c5
		summarizeBy: sum
		sourceColumn: Tempo de Envio do Fornecedor

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'SLA Fornecedor' = m
		mode: import
		source = ```
				let
				Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-gestao", [Query="Select * from DocumentValidationSla where Cliente = 'ATVOS' and Tipo in ('Mobilização','Treinamento') and Funcionario is not null"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Data_Envio", type date}, {"Data_Analise", type date}, {"Hora_Envio", type time}, {"Hora_Analise", type time}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "FDS_Análise", each if Date.DayOfWeek([Data_Analise]) = 0 or Date.DayOfWeek([Data_Analise]) = 6 then "FDS"
				 
				else  "DDS"),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "FDS_Envio", each if Date.DayOfWeek([Data_Envio]) = 0 or Date.DayOfWeek([Data_Envio]) = 6 then "FDS"
				 
				else  "DDS"),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Personalização Adicionada1", "Hora_Corrigida_Análise", each let
				    HoraLimiteInferior = #time(9, 0, 0),
				    HoraLimiteSuperior = #time(18, 0, 0),
				    Hora = [Hora_Analise],
				    FDSE = [FDS_Envio],
				    FDSA = [FDS_Análise],
				
				    // Ajuste de hora entre 09:00 e 18:00
				    HoraCorrigida =
				        if Hora < HoraLimiteInferior then HoraLimiteInferior
				        else if Hora > HoraLimiteSuperior then HoraLimiteSuperior
				        else Hora,
				
				    Resultado =
				       if FDSA = "FDS" and FDSE <> "FDS" then
				            HoraLimiteSuperior
				        else if FDSA = "FDS" and FDSE = "FDS" then null
				        else
				            HoraCorrigida
				in
				    Resultado),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Personalização Adicionada2", "Hora_Corrigida_Envio", each let
				    HoraLimiteInferior = #time(9, 0, 0),
				    HoraLimiteSuperior = #time(18, 0, 0),
				    Hora = [Hora_Envio],
				    FDSE = [FDS_Envio],
				    FDSA = [FDS_Análise],
				    
				    // Ajuste de hora entre 09:00 e 18:00
				    HoraCorrigida =
				        if Hora < HoraLimiteInferior then HoraLimiteInferior
				        else if Hora > HoraLimiteSuperior then HoraLimiteSuperior
				        else Hora,
				
				    Resultado =
				       if FDSA <> "FDS" and FDSE = "FDS" then
				            HoraLimiteInferior
				           else if FDSA = "FDS" and FDSE = "FDS" then null
				        else
				            HoraCorrigida
				in
				    Resultado),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada3",{{"Hora_Corrigida_Análise", type time}, {"Hora_Corrigida_Envio", type time}}),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Tipo Alterado1", "Data_Corrigida_Análise", each let
				    FDSE = [FDS_Envio],
				    FDSA = [FDS_Análise],
				    DataBase = Date.From([Data_Analise]),
				
				    // Cálculo da próxima segunda-feira
				    DiaSemanaSeg = Date.DayOfWeek(DataBase, Day.Monday),
				    ProximaSegunda = Date.AddDays(DataBase, 7 - DiaSemanaSeg),
				
				    // Cálculo da próxima sexta-feira
				   DiaSemana = Date.DayOfWeek(DataBase, Day.Monday),  // segunda = 0 ... domingo = 6
				    DiasParaSubtrair = if DiaSemana >= 4 then DiaSemana - 4 else DiaSemana + 3,
				    SextaAnterior = Date.AddDays(DataBase, -DiasParaSubtrair),
				
				    Resultado =
				        if FDSE <> "FDS" and FDSA = "FDS" then
				            SextaAnterior
				        else if FDSE = "FDS" and FDSA = "FDS" then null
				        else
				            DataBase
				in
				    Resultado),
				    #"Personalização Adicionada5" = Table.AddColumn(#"Personalização Adicionada4", "Data_Corrigida _Envio", each let
				    FDSE = [FDS_Envio],
				    FDSA = [FDS_Análise],
				    DataBase = Date.From([Data_Envio]),
				
				    // Cálculo da próxima segunda-feira
				    DiaSemanaSeg = Date.DayOfWeek(DataBase, Day.Monday),
				    ProximaSegunda = Date.AddDays(DataBase, 7 - DiaSemanaSeg),
				
				    // Cálculo da próxima sexta-feira
				    DiaSemanaSex = Date.DayOfWeek(DataBase, Day.Monday),
				    DiasAteSexta = if DiaSemanaSex <= 4 then 4 - DiaSemanaSex else 11 - DiaSemanaSex,
				    SextaMaisProxima = Date.AddDays(DataBase, DiasAteSexta),
				
				    Resultado =
				        if FDSE = "FDS" and FDSA <> "FDS" then
				            ProximaSegunda
				        else if FDSE = "FDS" and FDSA = "FDS" then null
				        else
				            DataBase
				in
				    Resultado),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada5",{{"Data_Corrigida_Análise", type date}, {"Data_Corrigida _Envio", type date}}),
				    #"Personalização Adicionada6" = Table.AddColumn(#"Tipo Alterado2", "SLA", each let
				    // Colunas de fim de semana
				    FDS_Envio = [FDS_Envio],
				    FDS_Analise = [FDS_Análise],
				
				    // Verificação inicial de fim de semana
				    HorasSLA = if FDS_Envio = "FDS" or FDS_Analise = "FDS" then
				        0
				    else
				        let
				            // Quebra em data e hora
				            DataEnvio = [Data_Corrigida _Envio],
				            HoraEnvio = Duration.TotalHours([Hora_Corrigida_Envio] - #time(0, 0, 0)),
				            DataAnalise = [Data_Corrigida_Análise],
				            HoraAnalise = Duration.TotalHours([Hora_Corrigida_Análise] - #time(0, 0, 0)),
				
				            // Constantes do expediente
				            HoraInicio = #time(9, 0, 0),
				            HoraFim = #time(18, 0, 0),
				            Jornada = 9, // 9 horas por dia útil
				
				            DataHoraAnaliseDia = (HoraAnalise - 9),
				            DataHoraEnvioDia = (18 - HoraEnvio),
				
				            // Conta os dias entre as datas
				            DiasTotais = List.Dates(DataEnvio, Duration.Days(DataAnalise - DataEnvio)+1, #duration(1, 0, 0, 0)),
				            DiasFinaisSemana = List.Count(List.Select(DiasTotais, each Date.DayOfWeek(_, Day.Sunday) = 0 or Date.DayOfWeek(_, Day.Saturday) = 0)),
				
				            // Caso 1: Mesmo dia
				            HorasMesmoDia = if DataEnvio = DataAnalise then
				                (HoraAnalise - HoraEnvio)
				            else
				                null,
				
				            // Cálculo do SLA com desconto de fins de semana
				            DiasUteisEntre = Duration.Days(DataAnalise - DataEnvio) - DiasFinaisSemana - 1,
				            ResultadoFinal = if DataEnvio = DataAnalise then
				                HorasMesmoDia
				            else
				                DiasUteisEntre * Jornada +(DataHoraAnaliseDia + DataHoraEnvioDia)
				        in
				            ResultadoFinal
				in
				    HorasSLA),
				    #"Personalização Adicionada7" = Table.AddColumn(#"Personalização Adicionada6", "Final de semana", each let 
				
				// Quebra em data e hora
				            DataEnvio = [Data_Corrigida _Envio],
				            HoraEnvio = Duration.TotalHours([Hora_Corrigida_Envio] - #time(0, 0, 0)),
				            DataAnalise = [Data_Corrigida_Análise],
				            HoraAnalise = Duration.TotalHours([Hora_Corrigida_Análise] - #time(0, 0, 0)),
				
				
				
				// Conta os dias entre as datas
				            DiasTotais = List.Dates(DataEnvio, Duration.Days(DataAnalise - DataEnvio)+1, #duration(1, 0, 0, 0)),
				            DiasFinaisSemana = List.Count(List.Select(DiasTotais, each Date.DayOfWeek(_, Day.Sunday) = 0 or Date.DayOfWeek(_, Day.Saturday) = 0))
				
				in
				if DataAnalise = null and DataEnvio = null then null
				
				else DiasFinaisSemana*9),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada7", each [Data_Envio] >= #date(2025, 2, 1)),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"SLA", type number}}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Tipo Alterado3",{{"Id_Pedido", Text.Upper, type text}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Texto em Maiúscula", "Data_Hora_Envio", each Text.Combine({Text.From([Data_Envio], "pt-BR"), Text.From([Hora_Envio], "pt-BR")}, " "), type text),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Coluna Mesclada Inserida", "Data_Hora_Análise", each Text.Combine({Text.From([Data_Analise], "pt-BR"), Text.From([Hora_Analise], "pt-BR")}, " "), type text),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida1",{{"Data_Hora_Envio", type datetime}, {"Data_Hora_Análise", type datetime}}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Tipo Alterado5",{{"Prazo_Envio", type number}, {"Data_Envio", type number}, {"Hora_Envio", type number}, {"Hora_Analise", type number}, {"Data_Analise", type number}}),
				    #"Coluna Mesclada Inserida2" = Table.AddColumn(#"Tipo Alterado4", "Classificação_Envio", each Text.Combine({[Id_Documento], Text.From([Data_Envio], "pt-BR"), Text.From([Hora_Envio], "pt-BR")}, ""), type text),
				    #"Coluna Mesclada Inserida3" = Table.AddColumn(#"Coluna Mesclada Inserida2", "Classificação_Analise", each Text.Combine({[Id_Documento], Text.From([Data_Analise], "pt-BR"), Text.From([Hora_Analise], "pt-BR")}, ""), type text),
				    #"Linhas Classificadas" = Table.Buffer(Table.Sort(#"Coluna Mesclada Inserida3",{{"Classificação_Analise", Order.Ascending}})),
				    #"Linhas Classificadas1" = Table.Buffer(Table.Sort(#"Linhas Classificadas",{{"Classificação_Envio", Order.Ascending}})),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Linhas Classificadas1", "Índice", 0, 1, Int64.Type),
				    #"Índice Adicionado1" = Table.AddIndexColumn(#"Índice Adicionado", "Índice.1", 1, 1, Int64.Type),
				    #"Duplicatas Removidas" = Table.Distinct(#"Índice Adicionado1", {"Classificação_Envio"}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Duplicatas Removidas", {"Índice"}, #"Duplicatas Removidas", {"Índice.1"}, "Índice Adicionado1", JoinKind.LeftOuter),
				    #"Índice Adicionado1 Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Índice Adicionado1", {"Id_Documento", "Data_Hora_Análise"}, {"Índice Adicionado1.Id_Documento", "Índice Adicionado1.Data_Hora_Análise"}),
				    #"Personalização Adicionada8" = Table.AddColumn(#"Índice Adicionado1 Expandido", "Tempo de Envio do Fornecedor", each if [Id_Documento] = [Índice Adicionado1.Id_Documento] then
				Duration.TotalHours ([Data_Hora_Envio]-[Índice Adicionado1.Data_Hora_Análise])
				
				else null)
				in
				    #"Personalização Adicionada8"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

