table Contratos
	lineageTag: 1fd70a1f-e20f-49bf-89f4-880cb325b5f9

	column CNPJ
		dataType: string
		lineageTag: 7a3d5058-81e8-48a8-8501-51c7d57bda87
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: d161d663-6e3c-496c-9e02-61057a061737
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3f757940-f19d-45be-86f1-73a9b7a69ba5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 631462a0-35f8-46f0-a32c-dbcf4dcc654f
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 981e8b82-c32f-40ce-8008-2c6ea563dd4a
			defaultHierarchy: LocalDateTable_0b2a5d4c-cb90-4c9f-a030-6dd6d808f000.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Vigência
		dataType: string
		lineageTag: 2d18865a-b644-4a3d-8387-59ba5f6203dc
		summarizeBy: none
		sourceColumn: Vigência

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: f34ee242-8a86-4fba-8937-ec2c97b22d15
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 9362236c-15de-4969-a4ca-9fe3a14d0195
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 6ab54d3a-1196-498f-ab6b-d4e79ba55f7c
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'N° do pedido'
		dataType: string
		lineageTag: 722a1008-a834-4b2b-8262-0e7e4aeb3246
		summarizeBy: none
		sourceColumn: N° do pedido

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: c013ac1b-711e-4db9-86ff-9ca5699a4cf8
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 1f51fa21-2c33-413a-8204-21893486aa3d
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 45b67d62-28e3-4791-ac67-146dd4eb4a71
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 919c7cfa-ccd6-408b-96ce-58c75f0fbf78
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 6995e896-5022-4b66-ba76-e1c0c91e9b8b
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: string
		lineageTag: 8c44b616-4489-470d-b2f6-25c6bfd12556
		summarizeBy: none
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

	column 'Nome do Gestor'
		dataType: string
		lineageTag: 779cdfc0-c590-4d4f-965b-9e44ef3b1fe4
		summarizeBy: none
		sourceColumn: Nome do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Email do Gestor'
		dataType: string
		lineageTag: 8e8a948c-f59c-4c1e-8bff-109a50a9840c
		summarizeBy: none
		sourceColumn: Email do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: 7ba80480-28fc-452e-9891-58f890a23078
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoãoLima\Diretório Padrão\Atlas Inovações - Documentos\Produtos\AFM\SETUP\Gestão\16. Relatório Interno e Externo - Power BI\02. Externo\01. AFM Gestão\Algar\2025\03 - Março\Contratos - Algar.xlsx"), null, true),
				    Contratos_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Contratos_Sheet,{{"Column1", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type any}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Column19"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Cadastro no sistema", type date}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado1","NULL","GESTOR NÃO IDENTIFICADO",Replacer.ReplaceText,{"Nome do Gestor"})
				in
				    #"Valor Substituído"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

