table 'Entrega de documentos'
	lineageTag: 18726dd2-0358-401c-b783-f8d17fe34ef9

	column 'Tipo de documento'
		dataType: string
		lineageTag: 84789241-903d-4479-b777-04edd248b424
		summarizeBy: none
		sourceColumn: Tipo de documento

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 94e7a67f-ab71-4841-a774-85966a16ff09
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 8c7dc3a7-9fc5-4599-bad6-074780d7e28f
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: dde9dfc5-8d84-4169-b5ad-2bc5d2c9efb1
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: b3b28e4f-5898-4f98-b3ae-2458f7d06bca
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 519453b2-17bf-4644-aa1d-e483d02d6a3e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Coluna Concatenada' = ```
			
			'Entrega de documentos'[Fornecedor] & " - " & 'Entrega de documentos'[Categoria(s)] & " - " & 'Entrega de documentos'[Unidade(s)]
			
			```
		lineageTag: e7ad6d80-e72c-4614-9c49-47fa8034d71e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato' = "Mão de obra alocada"
		lineageTag: 5d27ab02-3b14-42af-b61f-11ee80755aa9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Mês de Envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4e98b37f-e1ff-420c-9a03-7f129cb36ba5
		summarizeBy: none
		sourceColumn: Mês de Envio

		variation Variation
			isDefault
			relationship: b80381de-e502-48e3-a2ee-9bcd5e240922
			defaultHierarchy: LocalDateTable_0d08bab6-2f82-44e1-b534-2a1890ed7e29.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Mês de Competência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6bf49d3a-becf-461a-9ff3-ad27523397d8
		summarizeBy: none
		sourceColumn: Mês de Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Fornecedor-Categoria-Unidade
		dataType: string
		lineageTag: cce3f02c-6c11-450d-9550-ca132f7a0254
		summarizeBy: none
		sourceColumn: Fornecedor-Categoria-Unidade

		annotation SummarizationSetBy = Automatic

	column 'Início Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a00303b6-5fd9-467a-975c-87966a1f72b1
		summarizeBy: none
		sourceColumn: Início Vigência

		variation Variation
			isDefault
			relationship: 7504d227-adc5-43ef-8c2b-159eaa190ba9
			defaultHierarchy: LocalDateTable_153caa65-b5a4-4303-8ed1-a2a5f82670a8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 610aee16-86bc-476f-9b85-a2568ae938bb
		summarizeBy: none
		sourceColumn: Fim Vigência

		variation Variation
			isDefault
			relationship: 795031cd-f8a4-4702-bddc-976a64039daf
			defaultHierarchy: LocalDateTable_376411a9-b894-4ea0-9ef1-ac3a76aafae9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status Contrato'
		dataType: string
		lineageTag: af5fad43-2414-4074-82b9-e273307ae7d3
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column 'Contagem Documentos Entregues' = ```
			SWITCH(TRUE(), 
			'Entrega de documentos'[Status] = "Ok", 1, 
			'Entrega de documentos'[Status] = "*", 1, 
			0
			)
			```
		formatString: 0
		lineageTag: ee21a71e-55b5-468f-940a-9a200066b724
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: string
		lineageTag: 560dca2f-7e96-44b1-953b-8c44367ec2e7
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		annotation SummarizationSetBy = Automatic

	partition 'Entrega de documentos' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoanaMalheiros\Diretório Padrão\Atlas Inovações - Documentos\Consultoria\1.1. AFM CLIENTES\Shopping Cerrado\4. Relatório AFM Gestão\12. Dezembro\Relatorio - Entrega de documentos - 2501311109.xlsx"), null, true),
				    #"Entrega de documentos_Sheet" = Fonte{[Item="Entrega de documentos",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Entrega de documentos_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Column1", Int64.Type}, {"Relatório - Entrega de documentos", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",11),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Colunas Não Dinâmicas1" = Table.UnpivotOtherColumns(#"Cabeçalhos Promovidos1", {"Column1", "Documento", "Fornecedor", "CNPJ", "Regional", "Unidade(s)", "Categoria(s)", "Número do pedido", "SLA", "Frequência", "Restrição"}, "Mês de Envio", "Status"),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Não Dinâmicas1",{{"Mês de Envio", type date}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado2", "Mês de Competência", each Date.AddMonths([Mês de Envio], -1)),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Mês de Competência", type date}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado3", "Fornecedor-Categoria-Unidade", each Text.Combine({[Fornecedor], [#"Categoria(s)"], [#"Unidade(s)"]}, " - "), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"Fornecedor-Categoria-Unidade"}, Contratos, {"Fornecedor-Categoria-Unidade"}, "Contratos", JoinKind.LeftOuter),
				    #"Contratos Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Contratos", {"Cadastro no sistema", "Início Vigência", "Fim Vigência", "Status Contrato"}, {"Cadastro no sistema", "Início Vigência", "Fim Vigência", "Status Contrato"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Contratos Expandido", each ([Status Contrato] = "Vigente") and ([Status] <> "---")),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Linhas Filtradas",{{"Documento", "Tipo de documento"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"Column1", "CNPJ", "Número do pedido", "SLA", "Frequência", "Restrição"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

