table Contratos
	lineageTag: 894c1caf-b78e-4c29-8874-390bf6c80598

	measure _Eventuais_Quantidade =
			CALCULATE(DISTINCTCOUNT(Contratos[Nº do pedido]),
			Contratos[Tipo da contratação] = "Eventual") -- Número de Pedidos Distintos
		formatString: 0
		lineageTag: 3bc60ed5-db18-4a34-8f63-9608ec47220e

	measure _Contínuos_Quantidade = ```
			
			    CALCULATE(DISTINCTCOUNT(Contratos[Nº do pedido]),
			        Contratos[Tipo da contratação] = "Contínuo") -- Número de Pedidos
			```
		formatString: 0
		lineageTag: ec9261f3-6cce-47b2-89e2-d86e3a78c068

	column CNPJ
		dataType: string
		lineageTag: a412dad7-c013-402c-a5c9-766a4744c841
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 85b44698-8ea8-4f4e-bc8e-3ca94cab16b8
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 4891be18-3c19-4d4b-a62f-d1218a6aef9b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: a6b822ab-ea8e-4dcc-852a-8ad6635cc89f
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 44092313-0169-4e0f-94c4-16f90581a9de
			defaultHierarchy: LocalDateTable_23a10012-4f40-4357-a242-021e3b78da4c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 6cbfe1b5-2996-40c1-964e-84ca3d9c8710
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 9ee8fb2c-5612-4132-82ce-b97e0ac2b2bf
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 3388f16a-eddc-453f-920f-580edad45b3c
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicial'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f62c8884-7227-4107-a894-2d24ff3a5e62
		summarizeBy: none
		sourceColumn: Vigência Inicial

		variation Variation
			isDefault
			relationship: c0cba777-d0df-4b93-a31c-ade4af083a30
			defaultHierarchy: LocalDateTable_f8d1dc3f-b8dd-4543-ad71-2cbb5147a312.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Final'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4c4ddc92-6683-4e32-8bac-94c1ca7c09e5
		summarizeBy: none
		sourceColumn: Vigência Final

		variation Variation
			isDefault
			relationship: 7d2c9721-c2d7-41e6-bd46-13a5e94b24cb
			defaultHierarchy: LocalDateTable_ffce0ef7-6b29-4782-a697-6d2b3f2c2120.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Status'
		dataType: string
		lineageTag: fc71ee2d-6456-43ca-b1ee-6efefcab239a
		summarizeBy: none
		sourceColumn: Vigência Status

		annotation SummarizationSetBy = Automatic

	column 'Nº do pedido'
		dataType: string
		lineageTag: d56aa553-114b-4a86-935f-1abcfaeebd89
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 2a3bc104-785d-4b5e-8984-403bca3a4c86
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: d0d91a44-a322-4676-9ee9-946786a6fb6c
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column SLA
		dataType: string
		lineageTag: 73fe7fe5-fb81-46f4-bca2-7e09fbe2d74f
		summarizeBy: none
		sourceColumn: SLA

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 96ec2b4e-f806-4380-af2b-b4738dfa950e
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: 4fdb063e-81a7-4565-af78-2b9e6d022573
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome do Gestor'
		dataType: string
		lineageTag: 85b3aee0-ea7b-4f39-b182-f65df5a1d0da
		summarizeBy: none
		sourceColumn: Nome do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Email do Gestor'
		dataType: string
		lineageTag: 79422ea4-cc6c-4246-9172-5b668343eead
		summarizeBy: none
		sourceColumn: Email do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: 15115f91-93ac-42f0-9dab-896351129197
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    bc.CompanyName[Razão Social],#(lf)    dbo.FormatCNPJ([bc].[Document]) AS [CNPJ],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],  #(lf)#(tab)cm.[Name][Nome do Gestor],#(lf)#(tab)cm.[Email][Email do Gestor],#(lf)#(tab)cm.[Phone][Telefone do Gestor]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(lf)#(tab)#(tab)left join ContractManager cm with(nolock) on cm.ContractId = c.Id#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)where b.OrganizationId = '5e8158ee-be53-42a6-a438-29d67db30280'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(lf)#(lf)#(lf)#(tab) #(lf)#(tab)  #(lf)#(tab)"]),
				    #"Colunas Renomeadas1" = Table.RenameColumns(Fonte,{{"N° do pedido", "Nº do pedido"}, {"Razão Social", "Razão social"}, {"Sla", "SLA"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Nº do pedido", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"SLA", type text}, {"Status", type text}, {"Cadastro no sistema", type datetime}, {"Vigência", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Tipo Alterado1", "Vigência", Splitter.SplitTextByDelimiter("a", QuoteStyle.Csv), {"Vigência.1", "Vigência.2"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência.1", type date}, {"Vigência.2", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado2",{{"Vigência.1", "Vigência Inicial"}, {"Vigência.2", "Vigência Final"}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "Vigência Status", each if [Vigência Inicial] > #date(2025, 2, 10) then "Vigência Futura" else if [Vigência Final] < #date(2025, 2, 10) then "Vigência Finalizada" else "Vigente")
				in
				    #"Coluna Condicional Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

