table 'Análise de Documentos'
	lineageTag: ad32f156-9712-401c-92aa-5570b7e147e7

	measure 'Documentos Total' = CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]))
		formatString: #,0
		lineageTag: d06a6f90-afc4-4a99-a5e6-bd3d58cf3cba

	measure _Enviados_Documentos_ =
			
			VAR ENV = CALCULATE([Documentos Total],
			'Análise de Documentos'[Enviado] = "Enviado")
			
			VAR TOTAL = [Documentos Total]
			
			RETURN IF(ENV = BLANK() && TOTAL>0,0,ENV)
		formatString: #,0
		lineageTag: 3b3baa20-2642-4005-bc15-41bbb8815420

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '1- %Aprovados' =
			CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			'Análise de Documentos'[Status] = "Aprovado")/[_Enviados_Documentos_]
		lineageTag: 83e57d87-1db9-4039-b008-15d81f403b2b

		formatStringDefinition =
				VAR Aprovados = FORMAT([1- %Aprovados],"0,0%")
				
				VAR Enviado = [_Enviados_Documentos_]
				
				RETURN """" & Aprovados & " (" & Enviado & ")"

	measure _Aprovados_Quantidade =
			
			VAR APROV = CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			'Análise de Documentos'[Status] = "Aprovado")
			
			VAR TOTAL = [Documentos Total]
			
			
			RETURN IF(APROV = BLANK() && TOTAL>0,0,APROV)
		formatString: #,0
		lineageTag: 92ed618d-1a56-46e6-8196-a4b2d890c0c3

	measure '1 - Quantidade de Reprovados' =
			CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			'Análise de Documentos'[Enviado] = "Recusado")
		formatString: #,0
		lineageTag: 4c360445-8dcf-430a-aa37-aa35760e97f5

	measure '1 - %Reprovados' =
			CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			'Análise de Documentos'[Enviado] = "Recusado")/[_Enviados_Documentos_]
		lineageTag: 6ed87812-3f35-4904-8abf-0c809707bdbc

		formatStringDefinition =
				VAR Reprovados =FORMAT([1 - %Reprovados],"0.0%")
				
				VAR Enviados = [_Enviados_Documentos_]
				
				RETURN """" & Reprovados & " (" & Enviados & ")"

	measure '1 - %Risco Coletivo' = ```
			IF(
			    CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			        'Análise de Documentos'[Risco] = "Risco Individual")<1,
			    
			    (CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			    'Análise de Documentos'[Risco] = "Risco Coletivo",
			    'Análise de Documentos'[Enviado] = "Enviado")/[1 - Quantidade de Docs de Risco Coletivo])+ 0,
			    
			    (0.8*(CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			       'Análise de Documentos'[Risco] = "Risco Coletivo",
			       'Análise de Documentos'[Enviado] = "Enviado")/([1 - Quantidade de Docs de Risco Coletivo])))+ 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bffa3826-03b6-4404-a53f-45ac0e504e85

	measure '1 - %Risco Individual' = ```
			IF(
			    CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			        'Análise de Documentos'[Risco] = "Risco Coletivo")<1,
			    
			    (CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			    'Análise de Documentos'[Risco] = "Risco Individual",
			    'Análise de Documentos'[Enviado] = "Enviado")/[1 - Quantidade de Docs Risco Individual])+ 0,
			    
			    (0.2*(CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			       'Análise de Documentos'[Risco] = "Risco Individual",
			       'Análise de Documentos'[Enviado] = "Enviado")/([1 - Quantidade de Docs Risco Individual])))+ 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c2a8e994-42b3-42d9-8d85-590c049180a7

	measure '1- %Documentos Críticos' = [1 - %Risco Individual]+ [1 - %Risco Coletivo]  + 0
		lineageTag: 7d4814d8-0799-4480-9e19-beb3b2e6caf6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1 - Quantidade de Docs de Risco Coletivo' =
			CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			       'Análise de Documentos'[Risco] = "Risco Coletivo")
		formatString: 0
		lineageTag: d8e325f6-a427-4b66-b2bc-557236a31dd4

	measure '1 - Quantidade de Docs Risco Individual' =
			CALCULATE(DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId]),
			       'Análise de Documentos'[Risco] = "Risco Individual")
		formatString: 0
		lineageTag: a345cdc6-d276-4b73-8f6d-c0d2770077ff

	measure '1 - %Documentos Críticos' = ```
			[1 - %Risco Coletivo] + [1 - %Risco Individual] 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4b07968e-cd4c-44eb-ac47-ef36bc9df722

	measure '(Quantidade) Documentos' = DISTINCTCOUNT('Análise de Documentos'[DocumentScheduleId])
		formatString: #,0
		lineageTag: deff8e92-c39f-4d32-bf61-c70992987f76

	measure '(Média) Contrato' = AVERAGEX(VALUES('Análise de Documentos'[Chave]),[(Quantidade) Documentos])
		lineageTag: f883fcd0-a909-4ecd-baa1-b37c82421856

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Conformidade = CALCULATE([_Aprovados_Quantidade]/[(Quantidade) Documentos]) + 0
		lineageTag: 1150e8fc-1e01-488f-a2fb-cf74696b2f84

		formatStringDefinition =
				VAR CONF = FORMAT([%Conformidade],"0.0%")
				
				VAR AGEN = FORMAT([(Quantidade) Documentos],"#,###")
				
				RETURN """" & CONF & " (" & AGEN & ")"

	measure (%Conformidade) = DIVIDE([_Aprovados_Quantidade],[(Quantidade) Documentos], 0)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: a93e8b6b-4f9b-4e2f-9b4d-506f16303982

	measure %Aderência = DIVIDE([_Enviados_Documentos_],[(Quantidade) Documentos],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5c7bee61-20e3-4bba-a60a-6a105142eebe

	measure %(Aderência) = [_Enviados_Documentos_]/[(Quantidade) Documentos] + 0
		lineageTag: 0b4a7c58-984c-4c0c-8768-84d4553a283d

		formatStringDefinition =
				VAR ADE = FORMAT([%(Aderência)],"0.0%")
				
				VAR DOC = FORMAT([(Quantidade) Documentos],"#,###")
				
				RETURN """" & ADE & " (" & DOC & ")"

	measure %Aderência_Concessões =
			
			CALCULATE(
			    DIVIDE([_Enviados_Documentos_], [(Quantidade) Documentos]),
			    'Análise de Documentos'[Número do Pedido] = "Concessão"
			)+0
		lineageTag: c2a95139-2963-426b-aa7f-2241bc631e1f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure (%Conformidade_Concessões) =
			
			CALCULATE(
			    DIVIDE([_Aprovados_Quantidade], [(Quantidade) Documentos]),
			    'Análise de Documentos'[Número do Pedido] = "Concessão"
			)
		lineageTag: ff7ae3d0-6d24-431a-99ee-904b6b5df1e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Documento
		dataType: string
		lineageTag: f55b1fa8-3869-44fb-bf5b-b12119ff2cfc
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: b6a9f434-09c7-46a7-a5e8-8f51b9158380
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: ed98c581-22df-45bb-9851-4af413a8e705
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: f365a7cd-ab07-48c7-83fd-1e742ccacbcd
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 5dbd030f-0826-4209-98df-073ecc2f91f7
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: be7462fb-956e-43d1-87b6-74ee1de99467
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: ec6957e4-4444-4ed2-bc2b-40f682a66f1d
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: dda5ef75-6c15-49c0-92a4-f0951a79e2bd
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: 659bca46-03d6-4a22-aa13-1628bb3963ae
			defaultHierarchy: LocalDateTable_2c432539-8235-4be2-9f57-9de3a1c5dcdb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data da Análise'
		dataType: string
		lineageTag: a2cde4dd-e153-4386-8ae1-9ef6dd43c8a1
		summarizeBy: none
		sourceColumn: Data da Análise

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 471c2935-1dce-45af-9bc0-2d1a1a8a1b5c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: c10d84dc-e98c-4e0d-bc51-73b3af0afc9f
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: 03d1385c-1788-4afc-9593-a8b4c53abd44
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column Enviado
		dataType: string
		lineageTag: 401f277e-9682-427d-81dc-a581fe189f92
		summarizeBy: none
		sourceColumn: Enviado

		annotation SummarizationSetBy = Automatic

	column Risco = LOOKUPVALUE(Pesos[Risco],Pesos[Documento],'Análise de Documentos'[Documento])
		lineageTag: 6687e2b5-7aaf-406f-aa61-f4a3b9666b60
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 0473f942-e612-4b63-bf5f-105f7266f4e3
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Status de Contrato' = LOOKUPVALUE(Contratos[Status de Contrato],Contratos[Nº do pedido],'Análise de Documentos'[Número do Pedido])
		lineageTag: 3e47d425-f562-45ee-a87f-c569dbc8a38c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: Long Date
		lineageTag: 119fa9ce-d128-40cd-bddb-969bbd15b5fc
		summarizeBy: none
		sourceColumn: Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo do documento'
		dataType: string
		lineageTag: 1ceb2a80-c0c7-429c-ad7d-280add9bbf10
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: a793c67e-8888-4b85-81ef-73b58851ebdd
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	partition 'Análise de Documentos' = m
		mode: import
		source =
				let
				Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = GETDATE();#(lf)DECLARE @organizationId uniqueidentifier = '464e9a8a-8388-4b5e-9109-a2d18edd631a';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = GETDATE();#(lf)#(lf)#(lf)WITH DocumentScheduleBuildings AS (#(lf)    SELECT #(lf)        [dsb].[DocumentScheduleId],#(lf)        STRING_AGG(CAST([b].[TradeName] as nvarchar(MAX)), ', ') AS [Buildings]#(lf)    FROM#(lf)        [DocumentScheduleBuilding] AS [dsb]#(lf)        INNER JOIN [Building] AS [b] ON [dsb].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [dsb].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsb].[DocumentScheduleId]#(lf)),#(lf)DocumentScheduleCategories AS (#(lf)    SELECT#(lf)        [dsc].[DocumentScheduleId],#(lf)        STRING_AGG(CAST([c].[Name] as nvarchar(MAX)), ', ') AS [Categories]#(lf)    FROM#(lf)        [DocumentScheduleCategory] AS [dsc]#(lf)        INNER JOIN [Category] AS [c] ON [dsc].[CategoryId] = [c].[Id]#(lf)    WHERE#(lf)        [dsc].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsc].[DocumentScheduleId]#(lf))#(lf)SELECT#(lf)    DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)#(tab)CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)    [ds].Id AS [DocumentScheduleId],#(lf)    CASE#(lf)        WHEN [c].[OrderNumber] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [c].[OrderNumber]#(lf)    END AS [Número do Pedido],#(lf)#(tab)c.Id AS [Id_Contrato],#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        CASE#(lf)            WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)            WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)            WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)            WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)            WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)            WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)            WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)            WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)            WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)            ELSE 'Nenhum'#(lf)        END#(lf)    END AS [Tipo de Contrato],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    dbo.FormatCNPJ([bc].[Document]) AS [CNPJ],#(lf)    CASE#(lf)        WHEN [er].[Name] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [er].[Name]#(lf)    END AS [Funcionário],#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)    FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)    CASE#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Atrasado'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Próxima Entrega'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Atrasado Recusado'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Próxima Entrega Recusado'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL#(lf)        THEN#(lf)            'Em Análise'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 0#(lf)        THEN#(lf)            'Aprovado'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[IsValidated] IS NOT NULL AND [ds].[IsValidated] = 1#(lf)        THEN#(lf)            'Aprovado'#(lf)        ELSE#(lf)            '--'#(lf)    END AS [Status],#(lf)    ISNULL(dsBuildings.[Buildings], '---') AS [Unidade(s)],#(lf)    ISNULL(dsCategories.[Categories], '---') AS [Categoria(s)]#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    LEFT JOIN [DocumentScheduleBuildings] AS dsBuildings ON [ds].[Id] = dsBuildings.[DocumentScheduleId]#(lf)    LEFT JOIN [DocumentScheduleCategories] AS dsCategories ON [ds].[Id] = dsCategories.[DocumentScheduleId]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        (#(lf)            [ds].[UploadedAt] IS NOT NULL#(lf)            OR [c].[Removed] = 0#(lf)        )#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            (#(lf)                [ds].[ContractId] IS NOT NULL AND [ds].[ContractId] = [c].[Id]#(lf)            )#(lf)            OR (#(lf)#(tab)#(tab)#(tab)#(tab)[ds].[ContractId] IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                        AND EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                        AND NOT EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([ds].[ContractSetId] IS NOT NULL AND [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                    OR [ds].[ContractSetId] IS NULL#(lf)                )#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- unidades#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- categorias#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    (#(lf)                        [d].[DeliveryKind] <> 0#(lf)                        AND [d].[DeliveryKind] <> 1#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0#(lf)                                AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                ) -- deliveykind#(lf)                AND (#(lf)                    -- Agendamento por funcionario#(lf)                    (#(lf)                        [er].[Id] IS NOT NULL#(lf)                        AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                        AND [ds].[Kind] = 5#(lf)                        AND EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                                AND [erc].[ContractId] = [c].[Id]#(lf)                                AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                    -- / Agendamento por funcionario#(lf)                    -- Agendamento comum#(lf)                    OR (#(lf)                        [ds].[EmployeeRegisterId] IS NULL#(lf)                        AND [ds].[ContractId] IS NULL#(lf)                        AND [ds].[Kind] = 1#(lf)                    )#(lf)                    -- / Agendamento comum#(lf)                    -- Agendamento por unidade#(lf)                    OR (#(lf)                        [ds].Kind = 4#(lf)                    )#(lf)                    -- / Agendamento por unidade#(lf)                )#(lf)            )#(lf)        )#(lf)    )#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)-- ORDER BY #(lf)--     [p].[TradeName], [d].[Kind], [d].[Name], [ds].[ExpectedUploadAt], [er].[Name];"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Número do Pedido", type any}, {"Tipo de Contrato", type text}, {"Fornecedor", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Data da Análise", type any}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas em Branco Removidas", "Enviado", each if [Status] = "Aprovado" then "Enviado" else if [Status] = "Em Análise" then "Enviado" else if [Status] = "Atrasado" then "Atrasado" else if Text.Contains([Status], "Recusado") then "Recusado" else if [Status] = "Próxima Entrega" then "Não Considerar" else "Não Classificado"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Coluna Condicional Adicionada", each ([Status] <> "Próxima Entrega")),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Número do Pedido", type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado1", "Chave", each [Fornecedor] & [Número do Pedido]),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "Competência", each Date.AddMonths ([Prazo de Envio],-1)),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Competência", type date}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado2", each ([Status] <> "Próxima Entrega Recusado"))
				in
				    #"Linhas Filtradas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

