table Contratos
	lineageTag: c772d7f9-f9e2-453c-b3e0-fbe6285363c7

	measure '(Contratos) Quantidade' = CALCULATE(COUNTROWS())
		formatString: 0
		lineageTag: 18ab4bf3-10b4-4fd8-a4cd-dc0f63c48e9d

	column 'Nº do pedido'
		dataType: string
		lineageTag: 4b056a50-ec1f-4165-bd70-5a103f14cc60
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 214b727e-43c0-4ba8-89b9-b435e3ec6adc
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: a5ee82b6-2f9d-4c54-9516-5d58cc1eb3f6
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: bb044cf4-eb32-4846-b0fb-6fd5f3cc5277
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column SLA
		dataType: string
		lineageTag: 702e92fc-74dc-4fc9-b51e-90b51528b131
		summarizeBy: none
		sourceColumn: SLA

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6c0e38f3-8c3b-4994-99ee-d58a36f85b29
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6958c254-9eb8-4b44-9ff3-51c774e71394
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: a831fe63-2964-4ca5-a55e-b64bfca5b294
			defaultHierarchy: LocalDateTable_72c55838-61b6-4f42-b9c3-34c82825952c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicial'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7d15ccf6-e02f-44ac-9060-2385eefb8e4b
		summarizeBy: none
		sourceColumn: Vigência Inicial

		variation Variation
			isDefault
			relationship: b6e22d98-ef01-4e2d-ae43-569b6b307312
			defaultHierarchy: LocalDateTable_5dbc9fbd-2e06-4508-a3bc-a083fa2bb747.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Final'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d30016af-2c2c-4b0d-94ab-efde492d187e
		summarizeBy: none
		sourceColumn: Vigência Final

		variation Variation
			isDefault
			relationship: 326d5cae-2826-47a8-891d-46983ebbdd61
			defaultHierarchy: LocalDateTable_fd8be1be-937f-4227-bb68-a191c240a502.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: ea94ff15-3d8d-43f4-8488-5aa39bf45f93
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 2433fb09-9127-4f76-af7c-b6573b9f1066
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 1bf1fcfa-760b-48db-8b01-7c92229c173d
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Hoje
		dataType: dateTime
		formatString: Long Date
		lineageTag: 66a38d1f-993f-4a70-a01c-6841e5311170
		summarizeBy: none
		sourceColumn: Hoje

		variation Variation
			isDefault
			relationship: 598e4865-ae1a-4fa0-93ba-c19e1083e188
			defaultHierarchy: LocalDateTable_082f5a83-5f60-4475-9789-a74a5e858a8c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status de Contrato'
		dataType: string
		lineageTag: c45660fc-8327-4b97-b9af-899c47731c7b
		summarizeBy: none
		sourceColumn: Status de Contrato

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 91859a9c-6a66-4d79-9d5c-41a5d5ceeebf
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 4a152cc3-23ba-4395-9813-6a252d8f1013
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: 9e335cbe-0a31-44e5-84a5-297faff97a38
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome do Gestor'
		dataType: string
		lineageTag: de18aa5d-3afb-4e04-8907-e06a7efe736d
		summarizeBy: none
		sourceColumn: Nome do Gestor

		annotation SummarizationSetBy = Automatic

	column 'E-mail do Gestor'
		dataType: string
		lineageTag: 4cbdba3e-c006-437c-b874-11825982ecd2
		summarizeBy: none
		sourceColumn: E-mail do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: 28ff025e-dac5-4520-9518-4d10abea5663
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[Nº do pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    bc.CompanyName[Razão social],#(lf)    dbo.FormatCNPJ([bc].[Document]) AS [CNPJ],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'SLA',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],  #(lf)#(tab)cfv1.[Value][Nome do Gestor],#(lf)#(tab)cfv2.[Value][E-mail do Gestor],#(lf)#(tab)cfv3.[Value][Telefone do Gestor]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)LEFT JOIN CustomFieldValue cfv1 WITH(NOLOCK) ON cfv1.EntityId = c.Id AND cfv1.CustomFieldId = 'C4B327E3-E393-4A56-8BE4-06A3800FECA3'#(lf)#(tab)#(tab)LEFT JOIN CustomFieldValue cfv2 WITH(NOLOCK) ON cfv2.EntityId = c.Id AND cfv2.CustomFieldId = 'E73F3D0E-65F3-4025-ACB7-65AC77313D8F'#(lf)#(tab)#(tab)LEFT JOIN CustomFieldValue cfv3 WITH(NOLOCK) ON cfv3.EntityId = c.Id AND cfv3.CustomFieldId = 'AAED95E9-E631-4E6D-9509-FB7B108AF7E1'#(lf)where b.OrganizationId = '464e9a8a-8388-4b5e-9109-a2d18edd631a'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(tab)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Nº do pedido", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"SLA", type text}, {"Status", type text}, {"Cadastro no sistema", type datetime}, {"Vigência", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Tipo Alterado", "Vigência", Splitter.SplitTextByDelimiter("a", QuoteStyle.Csv), {"Vigência.1", "Vigência.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência.1", type date}, {"Vigência.2", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Vigência.1", "Vigência Inicial"}, {"Vigência.2", "Vigência Final"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "Hoje", each DateTimeZone.FixedLocalNow()),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Hoje", type date}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado2", "Status de Contrato", each if [Vigência Inicial] > [Hoje] then "Vigencia Futura"
				else if [Vigência Final] < [Hoje] then "Contrato Finalizado"
				else "Contrato Atual")
				in
				    #"Personalização Adicionada1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

