table 'Tabela Chave'
	lineageTag: c3687591-991e-4a24-9a51-d4925b327ef5

	measure 'Quantidade de Mídias (Disponibilidade e Ocupação)' = CALCULATE(DISTINCTCOUNT('Tabela Chave'[Locação]))
		formatString: 0
		lineageTag: 2c7e5362-dc04-41c3-8f1b-d96359b869ed

	column 'Nome fantasia do cliente' = LOOKUPVALUE('Dia a Dia'[Unidade],'Dia a Dia'[Chave],'Tabela Chave'[Chave])
		lineageTag: e19a0191-4c67-4dc9-9642-82332ece7ad7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Cliente = LOOKUPVALUE('Dia a Dia'[Nome fantasia do cliente],'Dia a Dia'[Chave],'Tabela Chave'[Chave])
		lineageTag: a35d5016-f80d-4d25-aa21-b48d68f03e9c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Cliente' = LOOKUPVALUE('Dia a Dia'[Cliente do Contrato],'Dia a Dia'[Chave],'Tabela Chave'[Chave])
		lineageTag: 1840603c-d5f8-486c-84d3-bac5da54b1ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato' = LOOKUPVALUE('Dia a Dia'[Segmento],'Dia a Dia'[Chave],'Tabela Chave'[Chave])
		lineageTag: 9554be9f-73d2-4d51-bd70-a0eb079954d8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Locação = LOOKUPVALUE('Dia a Dia'[Espaços para Locação],'Dia a Dia'[Chave],'Tabela Chave'[Chave])
		lineageTag: cd160ab5-9371-4ba4-b3eb-1f4ccb91bbd4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Chave
		lineageTag: b126d1a1-89e3-46ed-b807-f303249a3605
		summarizeBy: none
		isNameInferred
		sourceColumn: Dia a Dia[Chave]

		annotation SummarizationSetBy = Automatic

	column 'Mídia & Mall' = LOOKUPVALUE(Unidades[Tipo de Mídia],Unidades[Espaços para Locação],'Tabela Chave'[Locação])
		lineageTag: 329b64ee-c09d-43f2-9664-c486ea75f2c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Tabela Chave' = calculated
		mode: import
		source = DISTINCT('Dia a Dia'[Chave])

	annotation PBI_Id = bec3fe329e2d4f579570df9cc7a06fba

