table Contratos
	lineageTag: 087190bb-78e2-480f-b2b5-a7545f8dad88

	measure 'Categorias Agrupadas' = ```
			
			IF(
			    ISINSCOPE(Contratos[Fornecedor]),
			    CONCATENATEX(
			        VALUES(Contratos[Categoria]),
			        Contratos[Categoria],
			        ", ",
			        Contratos[Categoria],
			        ASC
			    ),
			    BLANK()
			)
			
			```
		lineageTag: e1e29267-fc04-4033-8693-82b99cb231da

	column CNPJ
		dataType: string
		lineageTag: 7df61d5d-9edd-4487-bc47-ed9045090a3f
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: c128ef9c-0b4e-49a0-be5a-f5527458e2b3
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: cdef3124-fa67-4fbe-905b-fb758d06f1bc
			defaultHierarchy: LocalDateTable_df4626a3-04d0-46f7-b73b-9a92e85158ce.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Início Vigência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5d3cdf95-8231-46b0-aa97-5cc7aaa7fd0d
		summarizeBy: none
		sourceColumn: Início Vigência

		variation Variation
			isDefault
			relationship: a020eb9c-ae35-4a1a-a48c-577d3dc6ba0e
			defaultHierarchy: LocalDateTable_6f7c3d1a-c4b0-4a62-a5d8-f7a83be4883c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim Vigência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 37a05a3c-fe47-430a-99de-6e33f45fb145
		summarizeBy: none
		sourceColumn: Fim Vigência

		variation Variation
			isDefault
			relationship: c88a2474-018d-4ce5-85d8-df60151de58a
			defaultHierarchy: LocalDateTable_73cbebba-0c00-4a1b-8549-afb0fc619c4f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: 2c5af1c5-99bf-4015-8aec-52dc18378359
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: e7b59119-be1a-42c7-91ee-ed8d145015a1
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 0b5d41c1-2820-495f-a36d-05320b16a151
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Status Contrato'
		dataType: string
		lineageTag: d829377f-3b17-4dbb-ac78-73902c885c92
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 00631489-61d4-43a5-9532-72f22a588b85
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: dbadb5e6-c3f4-46f5-b0b8-abbf868d3a25
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: e00c4094-5bee-43b7-8bcd-5f14d3d702e6
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'CNPJ Matriz'
		dataType: string
		lineageTag: 67d8320c-e438-4677-98db-7fe4de1da9a4
		summarizeBy: none
		sourceColumn: CNPJ Matriz

		annotation SummarizationSetBy = Automatic

	column 'CND.Emissão'
		dataType: dateTime
		formatString: Short Date
		lineageTag: dbb2d35b-0266-4571-91a6-0b828a9c547a
		summarizeBy: none
		sourceColumn: CND.Emissão

		variation Variation
			isDefault
			relationship: c56bdb34-28a6-4090-9d74-48c6386a0977
			defaultHierarchy: LocalDateTable_381c943f-3ada-4470-b99a-1649922a1960.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CND.Validade'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2a8a98b7-46b3-449a-ab54-4583aadef18a
		summarizeBy: none
		sourceColumn: CND.Validade

		variation Variation
			isDefault
			relationship: 488fba08-1dad-43a3-abe8-1be337f4fc43
			defaultHierarchy: LocalDateTable_d3af13ed-b234-4746-ac73-3be4176951ed.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CND.Status Certidão'
		dataType: string
		lineageTag: 9ab22b74-630f-4ccb-92f7-d87baa4e800e
		summarizeBy: none
		sourceColumn: CND.Status Certidão

		annotation SummarizationSetBy = Automatic

	column 'CND.Status Validade'
		dataType: string
		lineageTag: 96e305d6-0de4-44d0-b2c3-bb6f5a0ff0f5
		summarizeBy: none
		sourceColumn: CND.Status Validade

		annotation SummarizationSetBy = Automatic

	column 'N° do pedido'
		dataType: string
		lineageTag: 518fb9f1-84ea-438e-83e4-8700c209d0f5
		summarizeBy: none
		sourceColumn: N° do pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 8e223bb5-1f22-47be-8947-f2fb32011f3b
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 43bae36c-977a-4164-abd1-5979e7ac1b30
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: e1f0cc9e-6293-4534-a0d3-3f42b6bd2021
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column CNPJ-Categoria-Unidade
		dataType: string
		lineageTag: 1c8380d8-39be-4541-ae99-578e002c2e1a
		summarizeBy: none
		sourceColumn: CNPJ-Categoria-Unidade

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    bc.CompanyName[Razão Social],#(lf)   dbo.FNCNPJMask(bc.Document) as [CNPJ],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor]#(lf)from [Contract] c with(nolock)#(lf)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)#(lf)where b.OrganizationId = '11739F3B-431A-4554-B354-68E1BC62C1F1'#(lf)#(lf)"]),
				    
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(Fonte, "Vigência", Splitter.SplitTextByDelimiter(" a ", QuoteStyle.Csv), {"Início Vigência", "Fim Vigência"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Início Vigência", type date}, {"Fim Vigência", type date}}),
				        
				    // Calcula o primeiro dia do mês de hoje menos 2 meses
				    ReferenciaData = Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -2)),
				
				    // Coluna condicional automática baseada na referência calculada
				    #"Coluna Condicional Adicionada" = Table.AddColumn(
				        #"Tipo Alterado2",
				    "Status Contrato",
				    each if [Início Vigência] <= ReferenciaData and [Fim Vigência] >= ReferenciaData 
				         then "Vigente"
				         else "Não Vigente"
				),
				    #"Linhas Filtradas" = Table.SelectRows(#"Coluna Condicional Adicionada", each ([Status Contrato] = "Vigente")),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Linhas Filtradas", "CNPJ-Categoria-Unidade", each Text.Combine({[CNPJ], [Categoria], [Unidade]}, " - "), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"CNPJ"}, ListaCNPJs, {"CNPJ"}, "ListaCNPJs", JoinKind.LeftOuter),
				    #"ListaCNPJs Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "ListaCNPJs", {"CNPJ Matriz"}, {"CNPJ Matriz"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"ListaCNPJs Expandido", {"CNPJ-Categoria-Unidade"}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Duplicatas Removidas", {"CNPJ Matriz"}, CND, {"CNPJ"}, "CND", JoinKind.LeftOuter),
				    #"CND Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "CND", {"Emissão", "Validade", "Status Certidão", "Status Validade"}, {"CND.Emissão", "CND.Validade", "CND.Status Certidão", "CND.Status Validade"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"CND Expandido",null,"Certidão não emitida",Replacer.ReplaceValue,{"CND.Status Certidão"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",null,"Certidão não emitida",Replacer.ReplaceValue,{"CND.Status Validade"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Valor Substituído1", each Text.Contains([Unidade], "Edifício ") or Text.Contains([Unidade], "TORRE ") or Text.Contains([Unidade], "EDIFÍCIO") or Text.Contains([Unidade], "Torre "))
				in
				    #"Linhas Filtradas1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

