table Medidas
	lineageTag: 7b78c0f7-4eb5-4656-971c-e8b800e1a8da

	measure 'Total de documentos' =
			
			CALCULATE(
			    COUNTROWS(
			        'Entrega de documentos')
			        )
		formatString: 0
		lineageTag: 46d8088e-4db1-478e-9891-f4eb2bdef242

	measure 'Documentos entregues' = ```
			
			    SUM('Entrega de documentos'[Contagem Entregue])
			```
		formatString: 0
		lineageTag: 39cefd31-b1c0-4f52-a2fd-7b43d2bb9b5a

	measure 'Nº Fornecedores' = DISTINCTCOUNT('Entrega de documentos'[Fornecedor])
		formatString: 0
		lineageTag: 479f5d8f-2f16-4ab4-92a6-aa1919fe05ee

	measure 'Nº de Categorias' = DISTINCTCOUNT('Entrega de documentos'[Categoria(s)])
		formatString: 0
		lineageTag: ec414c30-fe82-4142-9702-5b0f25f1317f

	measure 'Formatação condicional Documentos Entregues' = ```
			
			SWITCH(
			    TRUE(),
			   [Percentual de Entrega] = 0, "#FFC7CE",
			    [Percentual de Entrega] < 0.3, "#FFC7CE",
			    [Percentual de Entrega] < 0.7, "#FFEB9C",
			    "#C6EFCE"
			)
			
			```
		lineageTag: dbea37d2-c4e8-48a4-8813-b7813357dcf4

	measure 'Risco Fornecedor' =
			
			CALCULATE(SWITCH (
			    TRUE (),
			    [Percentual de Entrega] < 0.3, "Alto",
			    AND ( [Percentual de Entrega] >= 0.3, [Percentual de Entrega] < 0.7 ), "Médio",
			   [Percentual de Entrega] >= 0.7, "Baixo"
			), REMOVEFILTERS('Entrega de documentos'[Competência])
			)
		lineageTag: 516339b4-88e5-464e-84bf-8530d0a18ec6

	measure 'Percentual de Entrega' = ```
			DIVIDE(
			    [Documentos entregues], 
			    [Total de documentos],"0"
			)
			```
		formatString: 0%;-0%;0%
		lineageTag: c32e6cb0-8808-4af3-8821-0e578a130c94

	measure 'Formatação condicional letras Documentos Entregues' = ```
			
			SWITCH(
			    TRUE(),
			   [Percentual de Entrega] = 0, "#9C0006",
			    [Percentual de Entrega] < 0.3, "#9C0006",
			    [Percentual de Entrega] < 0.7, "#9C5700",
			    "#006100"
			)
			
			```
		lineageTag: f94c8fc9-8cc1-49f1-8e5c-3e1322fdc094

	measure 'Número de contratos' =
			
			DISTINCTCOUNT(Contratos[CNPJ-Categoria-Unidade])
		formatString: 0
		lineageTag: fa05f60a-0aa0-4720-97e3-ee04d30eb6bb

	measure 'Mês Competência' = UPPER(FORMAT(MAX('d_Calendario'[Competência]), "MMMM YYYY"))
		lineageTag: 462dee2b-13d4-4050-88f1-3d8b46d1b522

	measure 'Mês incial' =
			
			UPPER(FORMAT(MIN('Entrega de documentos'[Competência]), "MMMM YYYY"))
		lineageTag: 3d05aef0-7bd4-4212-aee0-fd8b0cf54db2

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

