table 'Dia a Dia - Contratos'
	lineageTag: 2b5cc98b-427a-4d66-838d-681775dd33c4

	column 'Nº do pedido'
		dataType: string
		lineageTag: 0668ef0c-c909-4477-b52f-b118aeadaea5
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column 'Id do Contrato'
		dataType: string
		lineageTag: f8036af9-41ee-4313-98e1-7f548f6e66e6
		summarizeBy: none
		sourceColumn: Id do Contrato

		annotation SummarizationSetBy = Automatic

	column Dias
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2ce1ef71-cbd9-4c90-a282-5182103a7848
		summarizeBy: none
		sourceColumn: Dias

		variation Variation
			isDefault
			relationship: d494e0c2-1b7c-4857-b58c-63d3e1c33ca1
			defaultHierarchy: LocalDateTable_9af2a121-74ec-49d6-bab9-f3108ffe50b9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Dia a Dia - Contratos' = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[Nº do pedido],#(lf)#(tab)c.Id[Id do Contrato],#(lf)    bc.CompanyName[Razão social],#(lf)    [bc].[Document] AS [CNPJ],#(lf)#(tab)#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN c.FatherId IS NULL THEN 'Contratado'#(lf)#(tab)#(tab)ELSE 'Subcontratado'#(lf)#(tab) END 'Tipo de Fornecedor',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],#(lf)#(tab)cm.[Name][Nome do Gestor],#(lf)#(tab)cm.[Email][Email do Gestor],#(lf)#(tab)cm.[Phone][Telefone do Gestor],#(lf)#(tab)cfi3.[Name][Frequência],#(lf)#(tab)cfi5.[Name][VP de Execução do contrato],#(lf)#(tab)cfi7.[Name][VP Requisitante do contrato],#(lf)#(tab)cfv10.[Value][Nome do gestor técnico],#(lf)#(tab)cfv11.[Value][E-mail do gestor técnico],#(lf)#(tab)cfv8.[Value][Nome do fiscal técnico],#(lf)#(tab)cfv9.[Value][E-mail do fiscal técnico],#(tab)#(lf)#(tab)cfv12.[Value][Nome do gestor administrativo],#(lf)#(tab)cfv13.[Value][E-mail do gestor administrativo],#(lf)#(tab)cfv14.[Value][Nome do SST responsável],#(lf)#(tab)cfv15.[Value][E-mail do SST responsável],#(lf)#(tab)cfv16.[Value][Centro de Custo]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(tab)#(tab)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)left join ContractManager cm with(nolock) on cm.ContractId = c.Id and cm.Removed = 0#(lf)#(tab)#(tab)left join CustomFieldValue cfv8 WITH(NOLOCK) ON cfv8.EntityId = c.Id AND cfv8.CustomFieldId = '46797071-E688-4C4D-9D1E-A43BA98C9648' -- Nome do fiscal técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv9 WITH(NOLOCK) ON cfv9.EntityId = c.Id AND cfv9.CustomFieldId = '2DA18E51-F8A5-4BDC-8553-87A17EB27A7C' -- E-mail do fiscal técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv10 WITH(NOLOCK) ON cfv10.EntityId = c.Id AND cfv10.CustomFieldId = '9C244155-B8D4-4F0B-9413-7ECBCAFCD254' -- Nome do gestor técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv11 WITH(NOLOCK) ON cfv11.EntityId = c.Id AND cfv11.CustomFieldId = '7BF74685-4491-455C-9A27-F582AEE0ECA9' -- E-mail do gestor técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv12 WITH(NOLOCK) ON cfv12.EntityId = c.Id AND cfv12.CustomFieldId = '9F3F9320-74D8-4A80-A465-21C47B1D3AB1' -- Nome do gestor administrativo#(lf)#(tab)#(tab)left join CustomFieldValue cfv13 WITH(NOLOCK) ON cfv13.EntityId = c.Id AND cfv13.CustomFieldId = '8909197F-A741-48C4-82A9-02090DAD2FAD' -- E-mail do gestor administrativo#(lf)#(tab)#(tab)left join CustomFieldValue cfv14 WITH(NOLOCK) ON cfv14.EntityId = c.Id AND cfv14.CustomFieldId = '853608BB-71D6-407D-8BF1-413B396A4992' -- Nome do SST responsável#(lf)#(tab)#(tab)left join CustomFieldValue cfv15 WITH(NOLOCK) ON cfv15.EntityId = c.Id AND cfv15.CustomFieldId = '73E86956-CFF0-4D88-940B-F0F09E78E677' -- E-mail do SST responsável#(lf)#(tab)#(tab)left join CustomFieldValue cfv16 WITH(NOLOCK) ON cfv16.EntityId = c.Id AND cfv16.CustomFieldId = 'A684A08F-8759-4429-80C0-23BBB16AF57A' -- Centro de Custo#(lf)#(tab)#(tab)outer apply #(lf)#(tab)#(tab)(#(lf)    select cfi2.[Name] from CustomFieldValue cfv2 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi2 with(nolock) on cfv2.CustomFieldItemId = cfi2.Id#(lf)    where cfv2.EntityId = c.Id#(lf)#(tab)#(tab)and cfv2.[Value] is null#(lf)#(tab)#(tab)and cfv2.Removed = 0#(lf)#(tab)#(tab)and cfi2.Removed = 0#(lf)#(tab)#(tab)AND cfv2.CustomFieldId = '1C30677D-3F2F-4396-93DE-1DA0FD90E592' -- Frequência#(lf)#(tab)) as [cfi3]#(lf)#(tab)outer apply #(lf)#(tab)(#(lf)    select cfi4.[Name] from CustomFieldValue cfv4 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi4 with(nolock) on cfv4.CustomFieldItemId = cfi4.Id#(lf)    where cfv4.EntityId = c.Id#(lf)#(tab)#(tab)and cfv4.[Value] is null#(lf)#(tab)#(tab)and cfv4.Removed = 0#(lf)#(tab)#(tab)and cfi4.Removed = 0#(lf)#(tab)#(tab)AND cfv4.CustomFieldId = '586D0602-B8D0-480F-8565-5A1040393B54' -- VP de Execução do contrato#(lf)#(tab)) as [cfi5]#(lf)#(tab)outer apply #(lf)#(tab)(#(lf)    select cfi6.[Name] from CustomFieldValue cfv6 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi6 with(nolock) on cfv6.CustomFieldItemId = cfi6.Id#(lf)    where cfv6.EntityId = c.Id#(lf)#(tab)#(tab)and cfv6.[Value] is null#(lf)#(tab)#(tab)and cfv6.Removed = 0#(lf)#(tab)#(tab)and cfi6.Removed = 0#(lf)#(tab)#(tab)AND cfv6.CustomFieldId = 'A53C1F6C-9334-4AF9-8B78-03CC327FB6D7' -- VP Requisitante do contrato#(lf)#(tab)) as [cfi7]#(lf)where b.OrganizationId = 'e9654655-6595-4748-991d-6b50831c6ca5'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(lf)#(tab) -- Select * from CustomField Where OrganizationId = 'e9654655-6595-4748-991d-6b50831c6ca5'#(lf)#(lf)#(lf)#(lf)#(lf)#(tab)"]),
				    #"Colunas Removidas1" = Table.RemoveColumns(Fonte,{"Tipo de Fornecedor"}),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Colunas Removidas1", "Tipo de Fornecedor", each if Text.Contains([Nº do pedido], "S") then "Subcontratado" else "Contratado"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada2",{{"Nº do pedido", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"Status", type text}, {"Vigência", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Tipo Alterado", "Vigência", Splitter.SplitTextByDelimiter("a", QuoteStyle.Csv), {"Vigência.1", "Vigência.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência.1", type date}, {"Vigência.2", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Vigência.1", "Vigência Inicial"}, {"Vigência.2", "Vigência Final"}}),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Colunas Renomeadas", "Status Vigência", each if [Vigência Inicial] > DateTime.Date(DateTime.LocalNow()) then "Vigência Futura" else if [Vigência Final] < DateTime.Date(DateTime.LocalNow()) then "Vigência Finalizada" else "Vigente"),
				    #"Valor Substituído" = Table.ReplaceValue(#"Coluna Condicional Adicionada1","Aguardando dados de contatos do fornecedor","Aguardando Ação do Gestor",Replacer.ReplaceText,{"Status"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","Aguardando fornecedor preencher o contrato","Aguardando Ação do Fornecedor",Replacer.ReplaceText,{"Status"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",null,"SEM GESTOR",Replacer.ReplaceValue,{"Nome do Gestor"}),
				    #"Texto Limpo" = Table.TransformColumns(#"Valor Substituído2",{{"Nome do Gestor", Text.Clean, type text}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Texto Limpo", "Chave_Contratos", each Text.Combine({[Nº do pedido], [Razão social], [Unidade], [Categoria]}, ""), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"Id do Contrato"}, Gestor, {"Id do Contrato"}, "Gestor", JoinKind.LeftOuter),
				    #"Gestor Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Gestor", {"Nome do Gestor"}, {"Nome do Gestor.1"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Gestor Expandido",{{"Nome do Gestor.1", "Gestor"}}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Colunas Renomeadas1",null,"SEM TIPO DE CONTRATAÇÃO",Replacer.ReplaceValue,{"Tipo da contratação"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Valor Substituído3", each true),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Linhas Filtradas", "Índice", 0, 1, Int64.Type),
				    #"Personalização Adicionada" = Table.AddColumn(#"Índice Adicionado", "VP", each if [VP de Execução do contrato] = null then 
				    if [#"Compilado.Vice-Presidência"] = null then 
				        "Sem VP"
				    else [#"Compilado.Vice-Presidência"]
				else [VP de Execução do contrato]),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "Gestor_2", each if [Gestor] = "SEM GESTOR" or [Gestor]=null then
				   if [Gestores_Enviados.Gestor Técnico] = null then
				       if [Nome do gestor técnico] = null or [Nome do gestor técnico] = null then
				           if [Nome do gestor administrativo] = null or [Nome do gestor administrativo] = "" then
				              "Sem Gestor"
				              else [Nome do gestor administrativo]
				         else [Nome do gestor técnico]
				    else [Gestores_Enviados.Gestor Técnico]
				else [Gestor]),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Personalização Adicionada1", "Email_Gestor", each if  [Email do Gestor] =null then
				   if [Gestores_Enviados.Email] = null then
				       if [#"E-mail do gestor técnico"] = null or [#"E-mail do gestor técnico"] = "" then
				           if [#"E-mail do gestor administrativo"] = null or [#"E-mail do gestor administrativo"] = "" then
				              null
				              else [#"E-mail do gestor administrativo"]
				         else [#"E-mail do gestor técnico"]
				    else [Gestores_Enviados.Email]
				else [Email do Gestor]),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Personalização Adicionada2",{"Gestor"}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Colunas Removidas",{{"Email_Gestor", Text.Upper, type text}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Texto em Maiúscula",{{"Gestor_2", type text}}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Tipo Alterado2",{{"Gestor_2", "Gestor"}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas2", "Status Gestor Email", each if [Email_Gestor] = null then "Sem Gestor" else if Text.Contains([Email_Gestor], "eletrobras") then "Gestor Eletrobras" else if Text.Contains([Email_Gestor], "ELETROBRAS") then "Gestor Eletrobras" else "Não Gestor Eletrobras"),
				    #"Coluna Condicional Adicionada3" = Table.AddColumn(#"Coluna Condicional Adicionada", "Personalizar", each if [Gestor] = "SEM GESTOR" then "Sem Gestor" else if [Gestor] = "Sem Gestor" then "Sem Gestor" else if [Gestor] = "" then "Sem Gestor" else "Com Gestor"),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Coluna Condicional Adicionada3", "Personalizar.1", each if [Status Gestor Email] = "Gestor Eletrobras" then [Status Gestor Email]
				
				else if [Status Gestor Email] = "Não Gestor Eletrobras" then [Status Gestor Email]
				
				else if [Status Gestor Email] = "Sem Gestor" then 
				     if [Personalizar] = "Com Gestor" then "Gestor Sem Email" else "Sem Gestor" else "Sem Gestor"),
				    #"Duplicatas Removidas" = Table.Distinct(#"Personalização Adicionada3", {"Índice"}),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Duplicatas Removidas",{{"Personalizar.1", "Status Gestor"}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Renomeadas3", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Linhas em Branco Removidas","","Sem Gestor",Replacer.ReplaceValue,{"Gestor"}),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Valor Substituído4", "Dias de Contrato", each [Vigência Final]-[Vigência Inicial]),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada4",{{"Dias de Contrato", type number}}),
				    #"Personalização Adicionada5" = Table.AddColumn(#"Tipo Alterado3", "Personalizar.1", each {1..[Dias de Contrato]}),
				    #"Personalizar.1 Expandido" = Table.ExpandListColumn(#"Personalização Adicionada5", "Personalizar.1"),
				    #"Valor Substituído5" = Table.ReplaceValue(#"Personalizar.1 Expandido",null,1,Replacer.ReplaceValue,{"Personalizar.1"}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Valor Substituído5",{{"Personalizar.1", type number}}),
				    #"Personalização Adicionada6" = Table.AddColumn(#"Tipo Alterado4", "Dias", each Date.AddDays([Vigência Inicial],[Personalizar.1]-1)),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Personalização Adicionada6",{{"Dias", type date}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado5", each [Dias] < #date(2026, 12, 31)),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Linhas Filtradas1",{"Razão social", "CNPJ", "Tipo da contratação", "Sla", "Status", "Cadastro no sistema", "Vigência Inicial", "Vigência Final", "Unidade", "Regional", "Categoria", "Fornecedor", "Valor do contrato", "Nome do Gestor", "Email do Gestor", "Telefone do Gestor", "Frequência", "VP de Execução do contrato", "VP Requisitante do contrato", "Nome do gestor técnico", "E-mail do gestor técnico", "Nome do fiscal técnico", "E-mail do fiscal técnico", "Nome do gestor administrativo", "E-mail do gestor administrativo", "Nome do SST responsável", "E-mail do SST responsável", "Centro de Custo", "Tipo de Fornecedor", "Status Vigência", "Chave_Contratos", "Índice", "VP", "Gestor", "Email_Gestor", "Status Gestor Email", "Personalizar", "Status Gestor", "Dias de Contrato", "Personalizar.1"})
				in
				    #"Colunas Removidas2"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

