table 'Documentos em Análise'
	lineageTag: 941748fe-575a-4074-ae85-ff049f2ce062

	measure '(Total) Documentos' = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]))
		formatString: #,0
		lineageTag: 04d5e06f-36b4-43ce-8f4f-22bbd1954c85

	measure '(Enviados) Quantidade' =
			
			VAR ENVI = CALCULATE([(Total) Documentos],
			'Documentos em Análise'[Status] <> "Atrasado")
			
			RETURN IF(
			        ENVI = BLANK(),
			        0,
			        ENVI)
		formatString: #,0
		lineageTag: 227b0b6c-139e-4bbc-91f5-5947713a5084

	measure (%)Conformidade = ```
			
			
			VAR APROVADO = CALCULATE([(Total) Documentos],
			        'Documentos em Análise'[Status] = "Aprovado")
			
			VAR TOTAL = [(Total) Documentos]
			
			RETURN IF(
			            APROVADO =0 && TOTAL>0, 
			            0,
			            APROVADO/TOTAL)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c6bd1d2a-cea2-4029-86f1-befe81dc18f2

	measure (%)Aderência = ```
			
			
			VAR ATRASADO = CALCULATE([(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Atrasado")
			
			VAR TOTAL = [(Total) Documentos]
			
			RETURN IF(
			            ATRASADO =0 && TOTAL>0, 
			            0,
			            ATRASADO/TOTAL)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 686f7950-5935-4cb6-b511-dbc9223258eb

	measure '(%)Peso 3' = ```
			
			
			VAR PESO3 = 3
			
			VAR PESO1 = 1
			
			VAR TOTAL3 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO3)
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR APROV3 = CALCULATE([(Total) Documentos],'Documentos em Análise'[Status] <> "Aprovado" ,'Documentos em Análise'[Peso do Documentos]  = PESO3)
			
			
			RETURN IF(
			    PESO1 <1,
			            IF(APROV3 = 0 && TOTAL3 >1, 
			            0,
			            APROV3/TOTAL3
			            ),
			        IF(APROV3 = 0 && TOTAL3 >1, 
			            0,
			        (3/4)*APROV3/TOTAL3
			            ))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9a286f2f-04b6-40fb-abbb-81b31291dbd4

	measure '(%)Peso 1' = ```
			
			
			VAR PESO3 = 3
			
			VAR PESO1 = 1
			
			VAR TOTAL3 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO3)
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR APROV1 = CALCULATE([(Total) Documentos],'Documentos em Análise'[Status] <> "Aprovado" ,'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			
			RETURN IF(
			    PESO3 <1,
			            IF(APROV1 = 0 && TOTAL1 >1, 
			            0,
			            APROV1/TOTAL1
			            ),
			        IF(APROV1 = 0 && TOTAL1 >1, 
			            0,
			        (1/4)*APROV1/TOTAL1
			            ))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bd6c8b62-db58-4b25-b8e1-4d014c447849

	measure '(%)Grau de Risco' = [(%)Peso 1] + [(%)Peso 3]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08a200f9-cdae-45c7-9e60-790a9c9582c0

	measure '(%Menos 1)_Aderência  Mês Atrás' =
			
			
			VAR Corte = EOMONTH(TODAY(), -1)
			VAR Numerador =
			    CALCULATE(
			        [(Total) Documentos],
			        'Documentos em Análise'[Data de Envio] <= Corte,
			        'Documentos em Análise'[Status] <> "Atrasado"
			    )
			VAR Denominador =
			    CALCULATE(
			        [(Total) Documentos],
			        REMOVEFILTERS('Documentos em Análise'[Data de Envio])
			    )
			RETURN
			    DIVIDE(Numerador, Denominador, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5114e392-248b-4253-97c8-5e62a44d31ce

	measure '(%Menos 2)_Aderência  Mês Atrás' =
			
			
			VAR Corte = EOMONTH(TODAY(), -2)
			VAR Numerador =
			    CALCULATE(
			        [(Total) Documentos],
			        'Documentos em Análise'[Data de Envio] <= Corte,
			        'Documentos em Análise'[Status] <> "Atrasado"
			    )
			VAR Denominador =
			    CALCULATE(
			        [(Total) Documentos],
			        REMOVEFILTERS('Documentos em Análise'[Data de Envio])
			    )
			RETURN
			    DIVIDE(Numerador, Denominador, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ee0c6541-febf-433f-8c87-5a225fec143c

	measure '(%Menos 1)_Conformidade  Mês Atrás' =
			
			
			VAR Corte = EOMONTH(TODAY(), -1)
			VAR Numerador =
			    CALCULATE(
			        [(Total) Documentos],
			        'Documentos em Análise'[Data de Envio] <= Corte,
			        'Documentos em Análise'[Status] = "Aprovado"
			    )
			VAR Denominador =
			    CALCULATE(
			        [(Total) Documentos],
			        REMOVEFILTERS('Documentos em Análise'[Data de Envio])
			    )
			RETURN
			    DIVIDE(Numerador, Denominador, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6f1afdda-79d2-4b88-a35d-f021b3dca887

	measure '(%Menos 2)_Conformidade  Mês Atrás' =
			
			
			VAR Corte = EOMONTH(TODAY(), -2)
			VAR Numerador =
			    CALCULATE(
			        [(Total) Documentos],
			        'Documentos em Análise'[Data de Envio] <= Corte,
			        'Documentos em Análise'[Status] = "Aprovado"
			    )
			VAR Denominador =
			    CALCULATE(
			        [(Total) Documentos],
			        REMOVEFILTERS('Documentos em Análise'[Data de Envio])
			    )
			RETURN
			    DIVIDE(Numerador, Denominador, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1368d0ca-6e7f-4798-baeb-115a6e696322

	measure Medida
		lineageTag: 092f9eb4-d05a-4520-977f-b10f1591c8d5

	measure '(menos1)(%)Peso 1' = ```
			
			
			
			VAR PESO3 = 3
			
			VAR PESO1 = 1
			
			VAR TOTAL3 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO3)
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR Corte = EOMONTH(TODAY(), -1)
			
			VAR APROV1 = CALCULATE(
			    [(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Aprovado" ,
			        'Documentos em Análise'[Peso do Documentos]  = PESO1,
			        'Documentos em Análise'[Data de Envio] <= Corte)
			
			
			RETURN IF(
			    PESO3 <1,
			            IF(APROV1 = 0 && TOTAL1 >1, 
			            0,
			            APROV1/TOTAL1
			            ),
			        IF(APROV1 = 0 && TOTAL1 >1, 
			            0,
			        (1/4)*APROV1/TOTAL1
			            ))
			```
		lineageTag: a5d9c6c7-24b3-4f89-bc70-ab6bcaf482b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '(menos2)(%)Peso 1' = ```
			
			
			VAR PESO3 = 3
			
			VAR PESO1 = 1
			
			VAR TOTAL3 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO3)
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR Corte = EOMONTH(TODAY(), -2)
			
			VAR APROV1 = CALCULATE(
			    [(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Aprovado" ,
			        'Documentos em Análise'[Peso do Documentos]  = PESO1,
			        'Documentos em Análise'[Data de Envio] <= Corte)
			
			
			RETURN IF(
			    PESO3 <1,
			            IF(APROV1 = 0 && TOTAL1 >1, 
			            0,
			            APROV1/TOTAL1
			            ),
			        IF(APROV1 = 0 && TOTAL1 >1, 
			            0,
			        (1/4)*APROV1/TOTAL1
			            ))
			```
		lineageTag: c893ab75-1d46-4991-8e3d-97680a127c41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '(menos1)(%)Peso 3' = ```
			
			
			VAR PESO3 = 3
			
			VAR PESO1 = 1
			
			VAR TOTAL3 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO3)
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR Corte = EOMONTH(TODAY(), -1)
			
			VAR APROV3 = CALCULATE(
			    [(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Aprovado" ,
			        'Documentos em Análise'[Peso do Documentos]  = PESO3,
			        'Documentos em Análise'[Data de Envio] <= Corte)
			
			
			RETURN IF(
			    PESO1 <1,
			            IF(APROV3 = 0 && TOTAL3 >1, 
			            0,
			            APROV3/TOTAL3
			            ),
			        IF(APROV3 = 0 && TOTAL3 >1, 
			            0,
			        (3/4)*APROV3/TOTAL3
			            ))
			```
		lineageTag: ae4d3840-23d3-490d-b60c-1bb06477ac72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '(menos2)(%)Peso 3' = ```
			
			
			VAR PESO3 = 3
			
			VAR PESO1 = 1
			
			VAR TOTAL3 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO3)
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR Corte = EOMONTH(TODAY(), -2)
			
			VAR APROV3 = CALCULATE(
			    [(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Aprovado" ,
			        'Documentos em Análise'[Peso do Documentos]  = PESO3,
			        'Documentos em Análise'[Data de Envio] <= Corte)
			
			
			RETURN IF(
			    PESO1 <1,
			            IF(APROV3 = 0 && TOTAL3 >1, 
			            0,
			            APROV3/TOTAL3
			            ),
			        IF(APROV3 = 0 && TOTAL3 >1, 
			            0,
			        (3/4)*APROV3/TOTAL3
			            ))
			```
		lineageTag: b79cedfe-a0b2-4e39-bc31-9d33d619e8a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '(%Menos 1)Grau de Risco' = [(menos1)(%)Peso 1] + [(menos1)(%)Peso 3]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 13f94d6a-a476-4f69-b510-0b86cdf95bd1

	measure '(%Menos 2)Grau de Risco' = [(menos2)(%)Peso 1] + [(menos2)(%)Peso 3]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cced2267-dc5c-4854-ad70-2a0244b79bc5

	measure !T1 =
			
			
			VAR PESO1 = 1
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR Corte = EOMONTH(TODAY(), -1)
			
			VAR APROV1 = CALCULATE(
			    [(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Aprovado" ,
			        'Documentos em Análise'[Peso do Documentos]  = PESO1,
			        'Documentos em Análise'[Data de Envio] <= Corte)
			RETURN APROV1
		formatString: 0
		lineageTag: f609d9a6-91a4-4dcc-9c4e-c203fa33bbd2

	measure !T1_ATUAL =
			
			
			VAR PESO1 = 1
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR Corte = EOMONTH(TODAY(), -1)
			
			VAR APROV1 = CALCULATE(
			    [(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Aprovado" ,
			        'Documentos em Análise'[Peso do Documentos]  = PESO1)
			RETURN APROV1
		formatString: 0
		lineageTag: 6cea4241-2811-40aa-9357-801639e7a85a

	measure !T1-2 =
			
			
			VAR PESO1 = 1
			
			VAR TOTAL1 = CALCULATE([(Total) Documentos], 'Documentos em Análise'[Peso do Documentos]  = PESO1)
			
			VAR Corte = EOMONTH(TODAY(), -2)
			
			VAR APROV1 = CALCULATE(
			    [(Total) Documentos],
			        'Documentos em Análise'[Status] <> "Aprovado" ,
			        'Documentos em Análise'[Peso do Documentos]  = PESO1,
			        'Documentos em Análise'[Data de Envio] <= Corte)
			RETURN APROV1
		formatString: 0
		lineageTag: 4871278a-1d01-4a5c-9574-f5f8625999a1

	column Documento
		dataType: string
		lineageTag: d5f82226-1c97-4b36-856d-fe9033aa5fe0
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: abd7cc4e-5251-4dd9-bca6-2fdefef44b0f
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: d1db0887-7608-4921-b0d0-55e8d967cfae
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 3643d765-de0a-41b0-baf5-0d6d577e16a1
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 9d70f986-7488-4fc4-b868-ee31c27c0126
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: b3cd0473-d63b-419b-b1dc-d03b258440e2
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 8c86c10a-baf0-4066-9d85-63ccd661bee4
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88631286-9557-4c4a-99e1-e66718300c15
		summarizeBy: none
		sourceColumn: Prazo de Envio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 3dfe1e27-a33e-4342-9b1e-08c28976946d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: 61d21e61-d1e7-45c6-912e-66113eaf8bcb
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: fe7f7f20-4582-46a3-9b12-cd3d02ff1fa8
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column 'Status (Reclassificado)'
		dataType: string
		lineageTag: aa9f93ea-f496-4430-b672-823e7a1c17ee
		summarizeBy: none
		sourceColumn: Status (Reclassificado)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 5813ea47-6254-43c1-b215-017a8c334e3f
		summarizeBy: none
		sourceColumn: Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Chave Fornecedores'
		dataType: string
		lineageTag: 1bc51141-3225-4207-beb8-7fe0d9d28f80
		summarizeBy: none
		sourceColumn: Chave Fornecedores

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 63f5bf03-e1a4-47cd-ad96-94d47f271c71
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Data da Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: eab0069a-5b47-46f7-b4a3-47c3cfbd278e
		summarizeBy: none
		sourceColumn: Data da Análise

		variation Variation
			isDefault
			relationship: 06fe6741-1c69-4805-b060-0f6ae5877fe7
			defaultHierarchy: LocalDateTable_a800a1f3-bb34-4433-8cef-69f6eefe1b6d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Peso do Documentos' = LOOKUPVALUE('Classificação Docs'[Peso],'Classificação Docs'[Documento],'Documentos em Análise'[Documento])
		formatString: 0
		lineageTag: aaea68fa-a9a8-4ea7-b743-2bd84f46926a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 80a4f18f-ae6d-48b1-b30e-7f4c4e76baad
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 3ab0cb64-decc-4ceb-9fb9-e94371cc4812
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: 45ac8224-cb58-4efd-8f14-cd0b1765bcd0
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column Unidade = LOOKUPVALUE(Contratos[Unidade],Contratos[Id_Contrato],'Documentos em Análise'[Id_Contrato])
		lineageTag: 738edada-768b-4616-ab79-40e309fd7cc5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Data de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc26c76c-077a-4a2f-b235-11c0c5905ed7
		summarizeBy: none
		sourceColumn: Data de Envio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Documentos em Análise' = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = GETDATE();#(lf)DECLARE @organizationId uniqueidentifier = '0ba2c073-2a0d-4625-9985-8c32e95d7c27';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = GETDATE();#(lf)#(lf)WITH DocumentScheduleBuildings AS (#(lf)    SELECT#(lf)        [dsb].[DocumentScheduleId],#(lf)        STRING_AGG([b].[TradeName], ', ') AS [Buildings]#(lf)    FROM#(lf)        [DocumentScheduleBuilding] AS [dsb]#(lf)        INNER JOIN [Building] AS [b] ON [dsb].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [dsb].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsb].[DocumentScheduleId]#(lf)),#(lf)DocumentScheduleCategories AS (#(lf)    SELECT#(lf)        [dsc].[DocumentScheduleId],#(lf)        STRING_AGG([c].[Name], ', ') AS [Categories]#(lf)    FROM#(lf)        [DocumentScheduleCategory] AS [dsc]#(lf)        INNER JOIN [Category] AS [c] ON [dsc].[CategoryId] = [c].[Id]#(lf)    WHERE#(lf)        [dsc].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsc].[DocumentScheduleId]#(lf))#(lf)SELECT#(lf)    DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)    [ds].Id AS [DocumentScheduleId],#(lf)    CASE#(lf)        WHEN [c].[OrderNumber] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [c].[OrderNumber]#(lf)    END AS [Número do Pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        CASE#(lf)            WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)            WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)            WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)            WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)            WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)            WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)            WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)            WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)            WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)            ELSE 'Nenhum'#(lf)        END#(lf)    END AS [Tipo de Contrato],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)#(tab)[bc].[CompanyName] AS [Razão Social],#(lf)    [bc].[Document] AS [CNPJ],#(lf)    CASE#(lf)        WHEN [er].[Name] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [er].[Name]#(lf)    END AS [Funcionário],#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)    FORMAT([ds].[UploadedAt], 'dd/MM/yyyy') AS [Data de Envio],#(lf)    FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)    CASE#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Atrasado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Próxima Entrega'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Atrasado Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Próxima Entrega Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL#(lf)        THEN#(lf)            'Em Análise'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 0#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[IsValidated] IS NOT NULL AND [ds].[IsValidated] = 1#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)ELSE#(lf)            '--'#(lf)    END AS [Status],#(lf)    ISNULL(dsBuildings.[Buildings], '---') AS [Unidade(s)],#(lf)    ISNULL(dsCategories.[Categories], '---') AS [Categoria(s)],#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN [ds].[ExpectedUploadAt] < '2024-03-01' THEN '03/2024'#(lf)#(tab)#(tab)#(tab)ELSE #(lf)#(tab)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)Case#(lf)#(tab)#(tab)#(tab)#(tab)WHEN d.Frequency = 2 and d.DeliveryKind = 0 THEN FORMAT(DATEADD(MONTH, -1, [ds].[ExpectedUploadAt]), 'MM/yyyy')#(lf)#(tab)#(tab)#(tab)#(tab)ELSE FORMAT([ds].[ExpectedUploadAt], 'MM/yyyy') END) #(lf)    END AS [Competência]#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    LEFT JOIN [DocumentScheduleBuildings] AS dsBuildings ON [ds].[Id] = dsBuildings.[DocumentScheduleId]#(lf)    LEFT JOIN [DocumentScheduleCategories] AS dsCategories ON [ds].[Id] = dsCategories.[DocumentScheduleId]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        [c].[Removed] = 0#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            (#(lf)                ([ds].[ContractId] IS NOT NULL AND [ds].[ContractId] = [c].[Id])#(lf)                OR [ds].[ContractId] IS NULL#(lf)            )#(lf)            OR (#(lf)                (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                        AND EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                        AND NOT EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([ds].[ContractSetId] IS NOT NULL AND [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                    OR [ds].[ContractSetId] IS NULL#(lf)                )#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) #(lf)                    )#(lf)                ) -- unidades#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- categorias#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    (#(lf)                        [d].[DeliveryKind] <> 0#(lf)                        AND [d].[DeliveryKind] <> 1#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0#(lf)                                AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                ) -- deliveykind#(lf)                AND (#(lf)                    -- Agendamento por funcionario#(lf)                    (#(lf)                        [er].[Id] IS NOT NULL#(lf)                        AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                        AND [ds].[Kind] = 5#(lf)                        AND EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                                AND [erc].[ContractId] = [c].[Id]#(lf)                                AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                    -- / Agendamento por funcionario#(lf)                    -- Agendamento comum#(lf)                    OR (#(lf)                        [ds].[EmployeeRegisterId] IS NULL#(lf)                        AND [ds].[ContractId] IS NULL#(lf)                        AND [ds].[Kind] = 1#(lf)                    )#(lf)                    -- / Agendamento comum#(lf)                    -- Agendamento por unidade#(lf)                    OR (#(lf)                        [ds].Kind = 4#(lf)                    )#(lf)                    -- / Agendamento por unidade#(lf)                )#(lf)            )#(lf)        )#(lf)    )#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)#(tab)AND c.removed = 0#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Número do Pedido", type text}, {"Tipo de Contrato", type text}, {"Fornecedor", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}, {"Competência", type date}, {"Data da Análise", type date}, {"Data de Envio", type date}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Status (Reclassificado)", each if Text.Contains([Status], "Recusado") then "Enviado" else if [Status] = "Aprovado" then "Enviado" else if [Status] = "Em Análise" then "Enviado" else if [Status] = "Atrasado" then "Não Enviado" else null),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "Chave Fornecedores", each [Fornecedor]&[#"Categoria(s)"]),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Personalização Adicionada1", "Chave", each [Fornecedor]&[CNPJ]&[#"Unidade(s)"]&[#"Categoria(s)"]&[Número do Pedido]),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Personalização Adicionada2","Atrasado Recusado","Recusado",Replacer.ReplaceText,{"Status"})
				in
				    #"Valor Substituído1"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

