table 'SETUP de Documentos'
	lineageTag: 15ebe278-6df9-47b6-8095-d48ae29c4fbd

	column Check
		dataType: string
		lineageTag: b6be25e1-18fc-4c4c-8308-aa8b744efa0a
		summarizeBy: none
		sourceColumn: Check

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Entrega'
		dataType: string
		lineageTag: 3dc5f8b2-3b9f-4e3a-bcc3-ea241c48021a
		summarizeBy: none
		sourceColumn: Tipo de Entrega

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Cobrança'
		dataType: string
		lineageTag: fbe900a6-cfeb-4963-b2ae-39a46fa04bcc
		summarizeBy: none
		sourceColumn: Tipo de Cobrança

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: string
		lineageTag: 8cf8d826-767d-4a12-998f-daede83cd383
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column 'Documento (Proposta  Comercial)'
		dataType: string
		lineageTag: 14ab632b-2f46-4394-be9a-a0782e418ff7
		summarizeBy: none
		sourceColumn: Documento (Proposta  Comercial)

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: f27b9021-e62b-4fe5-83e2-51dddae955d2
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column 'Crachá (Favorito)'
		dataType: string
		lineageTag: 1a8792ba-fa23-4f72-840b-65f388fdd8d7
		summarizeBy: none
		sourceColumn: Crachá (Favorito)

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 450fd883-a146-4379-9eea-8833a3575966
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: ae1f0fa0-61df-485b-9efb-1fb867c01f62
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Holding
		dataType: string
		lineageTag: d1b363bb-feeb-46e9-949d-8082fd7a56e7
		summarizeBy: none
		sourceColumn: Holding

		annotation SummarizationSetBy = Automatic

	column 'EDF NF'
		dataType: string
		lineageTag: c58066e3-3cd1-4fe6-a60e-2c1445755da0
		summarizeBy: none
		sourceColumn: EDF NF

		annotation SummarizationSetBy = Automatic

	column 'EDF MAZ'
		dataType: string
		lineageTag: bcc08315-c3b1-4c15-b58d-af25016e4db8
		summarizeBy: none
		sourceColumn: EDF MAZ

		annotation SummarizationSetBy = Automatic

	column 'EDF SINOP'
		dataType: string
		lineageTag: 74f73ac7-8b0f-4a2e-8660-a1890b66aa00
		summarizeBy: none
		sourceColumn: EDF SINOP

		annotation SummarizationSetBy = Automatic

	column 'EDF OITI'
		dataType: string
		lineageTag: efdc9c29-c10f-457c-a525-f44f6ff54173
		summarizeBy: none
		sourceColumn: EDF OITI

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: 714df38d-214a-4fa4-9ace-f6417ebbed08
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column Atividades
		dataType: string
		lineageTag: 026922c9-ed2d-428f-b8dc-c7054f23f452
		summarizeBy: none
		sourceColumn: Atividades

		annotation SummarizationSetBy = Automatic

	column 'Tipo de fornecedor'
		dataType: string
		lineageTag: 66f53e63-8f87-45db-8854-c61cba61993f
		summarizeBy: none
		sourceColumn: Tipo de fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Tipo de contratação'
		dataType: string
		lineageTag: 366e932c-1445-4cef-a49c-b4a24e72096c
		summarizeBy: none
		sourceColumn: Tipo de contratação

		annotation SummarizationSetBy = Automatic

	column 'Modalidade de contratação'
		dataType: string
		lineageTag: 41d50b1e-ae01-4e38-8fea-7652b201ff6e
		summarizeBy: none
		sourceColumn: Modalidade de contratação

		annotation SummarizationSetBy = Automatic

	column 'Tipo de moradia'
		dataType: string
		lineageTag: d265a2d4-5595-488f-ab0a-5bf0e6f70f13
		summarizeBy: none
		sourceColumn: Tipo de moradia

		annotation SummarizationSetBy = Automatic

	column 'Formato de arquivo'
		dataType: string
		lineageTag: 664dfcb5-2e20-49a6-9143-865128dad3c4
		summarizeBy: none
		sourceColumn: Formato de arquivo

		annotation SummarizationSetBy = Automatic

	column Frequência
		dataType: string
		lineageTag: 1ca01214-9899-461d-9bf4-3a42c37f1d2b
		summarizeBy: none
		sourceColumn: Frequência

		annotation SummarizationSetBy = Automatic

	column Ocorrência
		dataType: string
		lineageTag: 659d9918-e88e-4604-9449-f79d6a673637
		summarizeBy: none
		sourceColumn: Ocorrência

		annotation SummarizationSetBy = Automatic

	column 'Prazo de envio*'
		dataType: string
		lineageTag: d515fbcd-0aed-4251-bc56-5a3c289405c5
		summarizeBy: none
		sourceColumn: Prazo de envio*

		annotation SummarizationSetBy = Automatic

	column 'Período de solicitação'
		dataType: string
		lineageTag: 0c23c081-f25f-44f8-b6dd-3a574f89eeb4
		summarizeBy: none
		sourceColumn: Período de solicitação

		annotation SummarizationSetBy = Automatic

	column 'Forma de entrega'
		dataType: string
		lineageTag: 6ee02a00-c374-4a79-b435-57c2579f8fe2
		summarizeBy: none
		sourceColumn: Forma de entrega

		annotation SummarizationSetBy = Automatic

	column Validar
		dataType: string
		lineageTag: de2fc160-8c19-4c27-bdd9-d7669a7d1851
		summarizeBy: none
		sourceColumn: Validar

		annotation SummarizationSetBy = Automatic

	column Restrições*
		dataType: string
		lineageTag: 77520e33-570d-4127-bf46-052562302c95
		summarizeBy: none
		sourceColumn: Restrições*

		annotation SummarizationSetBy = Automatic

	column Observação
		dataType: string
		lineageTag: 23fb133f-2c2a-41f7-9105-f5fd3e938272
		summarizeBy: none
		sourceColumn: Observação

		annotation SummarizationSetBy = Automatic

	partition 'SETUP de Documentos' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoãoLima\Diretório Padrão\Atlas Inovações - Documentos\Produtos\AFM\Gestão\16. Relatório Interno e Externo - Power BI\02. Externo\01. AFM Gestão\Argo\Setup\SETUP de Documentos.xlsx"), null, true),
				    #"SETUP de Documentos_Sheet" = Fonte{[Item="SETUP de Documentos",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"SETUP de Documentos_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Unidade", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type any}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}}),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos1",{{"Check", type text}, {"Tipo de Entrega", type text}, {"Tipo de Cobrança", type text}, {"Time", type text}, {"Documento (Proposta  Comercial)", type text}, {"Documento", type text}, {"Crachá (Favorito)", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Holding", type text}, {"EDF NF", type text}, {"EDF MAZ", type text}, {"EDF SINOP", type text}, {"EDF OITI", type text}, {"Função", type text}, {"Atividades", type text}, {"Tipo de fornecedor", type text}, {"Tipo de contratação", type text}, {"Modalidade de contratação", type text}, {"Tipo de moradia", type text}, {"Formato de arquivo", type text}, {"Frequência", type text}, {"Ocorrência", type text}, {"Prazo de envio*", type any}, {"Período de solicitação", type text}, {"Forma de entrega", type text}, {"Validar", type text}, {"Restrições*", type text}, {"Observação", type text}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

