table 'Classificação Docs'
	lineageTag: 2b8b65d5-b772-4b40-85b9-939d3ab73014

	column Documento
		dataType: string
		lineageTag: e7224fe6-1a88-4353-9c2c-8cbb036d5fc4
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Recorrência
		dataType: string
		lineageTag: 3c82d1d1-b574-4d7f-9be4-4f0fbe166610
		summarizeBy: none
		sourceColumn: Recorrência

		annotation SummarizationSetBy = Automatic

	column Referência
		dataType: string
		lineageTag: 8c9b49b6-ac85-462b-bec6-8b63f1da4c26
		summarizeBy: none
		sourceColumn: Referência

		annotation SummarizationSetBy = Automatic

	column Restrição
		dataType: string
		lineageTag: 5b797e7b-844b-42be-a10e-0a13312615d1
		summarizeBy: none
		sourceColumn: Restrição

		annotation SummarizationSetBy = Automatic

	column Peso
		dataType: int64
		formatString: 0
		lineageTag: 7aa0e3e5-9391-4318-9a45-39254b1590ff
		summarizeBy: none
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

	partition 'Classificação Docs' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://adminatlasinovacoescom.sharepoint.com/sites/DiretrioPadro/Documentos%20Compartilhados/Relat%C3%B3rios/Dados/02.%20Externo/03.%20Consultoria/Argo/Setup/documentos%20-%20peso%20e%20restri%C3%A7%C3%A3o.xlsx")),
				    Planilha1_sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Documento", type text}, {"Recorrência", type text}, {"Referência", type text}, {"Restrição", type text}, {"Peso", Int64.Type}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

