table Contratos
	lineageTag: 0b60eaf6-b893-4880-84cd-00002096574b

	measure 'Quantidade de Contratos' = CALCULATE(DISTINCTCOUNT(Contratos[Id_Contrato]))
		formatString: 0
		lineageTag: 11085f7b-9c23-43b7-a8ec-6875885190e0

	measure (FILTRO) = [Relação - Quantidade de Colaboradores]+'Status de Efetivos'[(Ativos Relação) Quantidade Efetivos Cadastrados]+ [(Relação) Ativos-Contratos]
		lineageTag: 1da2ce93-e43a-481a-8b6b-703264a2f905

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CNPJ
		dataType: string
		lineageTag: e401cdf6-97e9-4f75-b688-322ad7281207
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 731ea080-0cb3-4d8f-acfe-7c3758f80b84
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6ae5a074-edb6-41f3-bfc2-95d7b6a9fe4f
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: 04566036-08ae-4846-977a-c3569a6efa2b
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 6f46be1e-3434-4805-b1dc-18e45ecaa4ce
			defaultHierarchy: LocalDateTable_af1dde64-e6d6-4d9f-88e0-99b4fdb521ae.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 40f6596b-7cb2-459a-ab04-a14143f4e24d
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: bee1dbe8-571b-49cd-b8e5-401bf1fe81d3
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 7e81ef56-2af1-4f42-b724-5062e3cd231d
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Contrato
		dataType: string
		lineageTag: e3d86378-d1ea-49bd-8e0d-de0d822e825c
		summarizeBy: none
		sourceColumn: Contrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicial'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 862e79b3-b9fa-47b6-9fcd-4b1d6e55c63c
		summarizeBy: none
		sourceColumn: Vigência Inicial

		variation Variation
			isDefault
			relationship: 92983895-a294-42a2-bc85-2c512fc864ab
			defaultHierarchy: LocalDateTable_e14e83ab-68b0-4100-81ff-a5d91497f96c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Final'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b1a1310e-60b7-4a10-9856-d2659df488ec
		summarizeBy: none
		sourceColumn: Vigência Final

		variation Variation
			isDefault
			relationship: faa1a1b5-9fc9-4a63-8cb6-e036acb275a9
			defaultHierarchy: LocalDateTable_d4e51b63-850e-40a0-9d39-b1669fac8d35.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status Contrato'
		dataType: string
		lineageTag: d4c89de8-e450-4400-92e9-82328aa7ed0c
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 0eb50d1b-a002-4c02-ba4d-f95b9c7abde1
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Nº do pedido'
		dataType: string
		lineageTag: 55e4448e-8f4a-40d3-b51a-93afcedfcb82
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: a4ce3919-1795-4405-bab9-3d6d05f81f41
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 71c65820-e6b8-487c-b7cd-634a421345df
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 5b13ff8b-af9e-4baa-8a23-d3332956fb8e
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column SLA
		dataType: string
		lineageTag: ec2d0a9c-77dd-4f98-9193-e1b14b558167
		summarizeBy: none
		sourceColumn: SLA

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 189ddf64-18e8-422f-8373-cc39c9354371
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: eff78405-c24c-44db-85df-4dadcda9edd0
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome do gestor do contrato'
		dataType: string
		lineageTag: 2919c7b2-8adf-45f4-bbeb-91fa8d66160e
		summarizeBy: none
		sourceColumn: Nome do gestor do contrato

		annotation SummarizationSetBy = Automatic

	column 'E-mail do gestor do contrato'
		dataType: string
		lineageTag: 56665242-9363-4772-95c4-730a4777a368
		summarizeBy: none
		sourceColumn: E-mail do gestor do contrato

		annotation SummarizationSetBy = Automatic

	column 'Nome do Gestor'
		dataType: string
		lineageTag: 762218af-5f97-439a-b4c8-8ea2a7b23c94
		summarizeBy: none
		sourceColumn: Nome do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Email do Gestor'
		dataType: string
		lineageTag: 3e7a6f22-aa9b-4580-8c6c-02e968af158d
		summarizeBy: none
		sourceColumn: Email do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: d6c6fcd0-6c90-49c1-80ad-7b0cf795a448
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)    bc.CompanyName[Razão Social],#(lf)    dbo.FormatCNPJ([bc].[Document]) AS [CNPJ],#(lf)#(tab)c.OrderNumber [Número do Pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],#(lf)#(tab)cfv1.Value AS 'Nome do gestor do contrato',#(lf)#(tab)cfv2.Value AS 'E-mail do gestor do contrato',#(lf)#(tab)cm.[Name][Nome do Gestor],#(lf)#(tab)cm.[Email][Email do Gestor],#(lf)#(tab)cm.[Phone][Telefone do Gestor]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(tab)#(tab)left join ContractManager cm with(nolock) on cm.ContractId = c.Id#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)LEFT JOIN CustomFieldValue cfv1 WITH(NOLOCK) ON cfv1.EntityId = c.Id AND cfv1.CustomFieldId = '5C1FBD29-0347-4771-99F7-3A7809168809'#(lf)#(tab)#(tab)LEFT JOIN CustomFieldValue cfv2 WITH(NOLOCK) ON cfv2.EntityId = c.Id AND cfv2.CustomFieldId = '38FCAE3A-AA36-41E8-BA82-F542E09F27F5'#(lf)#(lf)where b.OrganizationId = 'ff063ad2-100d-4f34-895b-5af6697eec11'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(lf)#(tab)"]),
				        #"Linhas em Branco Removidas" = Table.SelectRows(Fonte, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Linhas em Branco Removidas",{{"N° do pedido", "Nº do pedido"}, {"Razão Social", "Razão social"}, {"Sla", "SLA"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Nº do pedido", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"SLA", type text}, {"Status", type text}, {"Cadastro no sistema", type datetime}, {"Vigência", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado1", "Contrato", each Text.Combine({[Fornecedor], [Unidade], [Categoria], [Razão social]}, ""), type text),
				    #"Linhas Filtradas" = Table.SelectRows(#"Coluna Mesclada Inserida", each ([Fornecedor] <> "Fornecedor Orgânico Argo")),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Linhas Filtradas", "Vigência", Splitter.SplitTextByDelimiter("a", QuoteStyle.Csv), {"Vigência.1", "Vigência.2"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência.1", type date}, {"Vigência.2", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado2",{{"Vigência.1", "Vigência Inicial"}, {"Vigência.2", "Vigência Final"}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "Status Contrato", each if [Vigência Inicial] > #date(2024, 12, 18) then "Vigência Futura" else if [Vigência Final] < #date(2024, 12, 18) then "Vigência Finalizada" else "Vigente"),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Coluna Condicional Adicionada", each ([Nº do pedido] <> "---")),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Linhas Filtradas1", "Chave", each Text.Combine({[Fornecedor], [Categoria], [Unidade]}, ""), type text),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Coluna Mesclada Inserida1", each ([Unidade] <> "Aparecida Shopping" and [Unidade] <> "DF Plaza" and [Unidade] <> "Shopping Crystal "))
				in
				    #"Linhas Filtradas2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

