table 'Documentos em Análise'
	lineageTag: 941748fe-575a-4074-ae85-ff049f2ce062

	measure '(Total) Documentos' = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]))
		formatString: #,0
		lineageTag: 04d5e06f-36b4-43ce-8f4f-22bbd1954c85

	measure 'Documentos em Análise' =
			IF(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Em Análise")=0,0,CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Em Análise"))
		formatString: 0
		lineageTag: 2af97cb3-ff8f-40b7-9231-ac5b3dfb19ba

	measure '(Aprovados) Documentos' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Aprovado")/[(Total) Documentos] + 0
		lineageTag: bf552cbf-8d4e-4736-b064-ac3992b0df9d

		formatStringDefinition =
				VAR APRO =FORMAT([(Aprovados) Documentos],"0.0%")
				
				VAR TOTAL = [(Total) Documentos]
				
				RETURN """" & APRO & " (" & TOTAL & ")"

	measure '1 - Quantidade de Docs Aprovados' =
			if(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Aprovado") = 0,
			"N/A"
			, (CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Aprovado")))
		formatString: #,0
		lineageTag: 11ee845c-1ee6-49f2-8a6f-8c6ee98a4c5d

	measure '3 - %Atrasados' =
			(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado")+ CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado"))/[(Total) Documentos]
		lineageTag: 0053bc5e-4e3b-4f7f-ba80-0fb5015ae793

		formatStringDefinition =
				VAR vAtrasado = FORMAT([3 - %Atrasados],"0.0%")
				VAR vTotal = [(Total) Documentos]
				VAR vResultados = """" & vAtrasado & " (" & vTotal & ")"
				return vResultados

	measure '3 - Atrasados' = ```
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado") +  
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado")
			```
		formatString: #,0
		lineageTag: 1333a4cf-2038-48a7-9d87-23b33dac0f17

	measure '2 - Recusados' = ```
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado") + 
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Próximas Entregaas Recusadas")
			```
		formatString: 0
		lineageTag: 6b7513c8-21ca-431b-8a71-3638f9bc270c

	measure '4 - %Quantidade de Enviados' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] <> "Atrasado")/[(Total) Documentos]  + 0
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: dec939ec-684d-443d-b5cc-80e2d74c63ea

	measure '(Enviados) Quantidade' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] <> "Atrasado")+0
		formatString: #,0
		lineageTag: 227b0b6c-139e-4bbc-91f5-5947713a5084

	measure 'Quantidade de Enviados dividido por Documentos Total' =
			
			DIVIDE([(Enviados) Quantidade], [(Total) Documentos])
		lineageTag: 4563817b-edea-4742-a4db-3cf8fddf0535

		formatStringDefinition =
				VAR vEnviados = FORMAT([Quantidade de Enviados dividido por Documentos Total], "0.0%")
				VAR vTotal = [(Total) Documentos]
				VAR vResultado = """" & vEnviados & " (" & vTotal & ")"
				RETURN vResultado

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure '(Conformidade) Aprovados' =
			AVERAGEX(
			    VALUES('Documentos em Análise'[Número do Pedido]),
			    (CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Status] = "Aprovado")+0)/[(Total) Documentos])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c6bd1d2a-cea2-4029-86f1-befe81dc18f2

	measure %Recusados =
			(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado") + CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Próximas Entregas Recusadas"))/[(Enviados) Quantidade]
		formatString: 0%;-0%;0%
		lineageTag: 122791aa-7e05-4c81-8408-54a5fbd781e4

	measure %Atrasados =
			(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado") + CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado"))/[(Total) Documentos]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a4e5238a-8926-4371-8c98-f126e2b84440

	measure 'Quantidade de Analisado' = ```
			CALCULATE(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] <> "Atrasado",
			'Documentos em Análise'[Status] <> "Em Análise"))
			
			```
		formatString: #,0
		lineageTag: b7a2b6b1-ded9-43e3-ba59-23fdc6ab3439

	measure '(Aderência) Envio Documento' = ```
			
			    (CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Status] <> "Atrasado")+0)/[(Total) Documentos]
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 686f7950-5935-4cb6-b511-dbc9223258eb

	measure 'Peso 3' = ```
			(IF(
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 1)<1,
			    
			    ((CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 3,
			       'Documentos em Análise'[Status] <> "Aprovado")/[(Total) Peso 3]))+0,
			    
			    (((3/4)*CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 3,
			       'Documentos em Análise'[Status] <> "Aprovado"))/[(Total) Peso 3])))+0
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9a286f2f-04b6-40fb-abbb-81b31291dbd4

	measure '(Total) Peso 1' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 1)+0
		formatString: 0
		lineageTag: df2541e8-9a25-4f00-9435-7608e39c3f15

	measure 'Peso 1' = ```
			(IF(
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 3)<1,
			    
			    (CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 1,
			       'Documentos em Análise'[Status] <> "Aprovado")/[(Total) Peso 1])+0,
			    
			    ((1/4)*CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 1,
			       'Documentos em Análise'[Status] <> "Aprovado")/[(Total) Peso 1])))+0
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bd6c8b62-db58-4b25-b8e1-4d014c447849

	measure '(Total) Peso 3' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 3)+0
		formatString: 0
		lineageTag: 3848ae26-b978-40dd-87fe-a74deb120435

	measure '(Risco) Críticos' = ([Peso 1] + [Peso 3]+0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08a200f9-cdae-45c7-9e60-790a9c9582c0

	measure 'Quantidade Contratos - Total' = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[Número do Pedido]))
		formatString: 0
		lineageTag: 6360696d-3583-4992-8d06-46131b05c66d

	measure (_Qtd_Pendentes) = ```
			CALCULATE(
			    COUNTROWS('Documentos em Análise'), 
			    ('Documentos em Análise'[(Pendente _NPendente)] = "Pendente"))
			```
		formatString: 0
		lineageTag: 81e22ccf-35eb-48d0-8700-1a4df0d23e2c

	measure (_Qtd_N_Pendentes) = ```
			CALCULATE(
			    COUNTROWS('Documentos em Análise'), 
			    ('Documentos em Análise'[(Pendente _NPendente)] = "Não pendente"))
			```
		formatString: 0
		lineageTag: 756f81ce-b9b0-4c17-b8b2-75df859af397

	column Documento
		dataType: string
		lineageTag: d5f82226-1c97-4b36-856d-fe9033aa5fe0
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: abd7cc4e-5251-4dd9-bca6-2fdefef44b0f
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: d1db0887-7608-4921-b0d0-55e8d967cfae
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 3643d765-de0a-41b0-baf5-0d6d577e16a1
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 9d70f986-7488-4fc4-b868-ee31c27c0126
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: b3cd0473-d63b-419b-b1dc-d03b258440e2
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 8c86c10a-baf0-4066-9d85-63ccd661bee4
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88631286-9557-4c4a-99e1-e66718300c15
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: b6118b9f-17b5-4365-b86a-94681a560edc
			defaultHierarchy: LocalDateTable_601600e6-bb4d-43b9-b6d2-852c3b8420b6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 3dfe1e27-a33e-4342-9b1e-08c28976946d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: 61d21e61-d1e7-45c6-912e-66113eaf8bcb
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: fe7f7f20-4582-46a3-9b12-cd3d02ff1fa8
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column 'Status (Reclassificado)'
		dataType: string
		lineageTag: aa9f93ea-f496-4430-b672-823e7a1c17ee
		summarizeBy: none
		sourceColumn: Status (Reclassificado)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 5813ea47-6254-43c1-b215-017a8c334e3f
		summarizeBy: none
		sourceColumn: Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Chave Fornecedores'
		dataType: string
		lineageTag: 1bc51141-3225-4207-beb8-7fe0d9d28f80
		summarizeBy: none
		sourceColumn: Chave Fornecedores

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 63f5bf03-e1a4-47cd-ad96-94d47f271c71
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Data da Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: eab0069a-5b47-46f7-b4a3-47c3cfbd278e
		summarizeBy: none
		sourceColumn: Data da Análise

		variation Variation
			isDefault
			relationship: 748537b3-f2c3-4887-82a7-0b63886ead7c
			defaultHierarchy: LocalDateTable_8b551f5c-0001-487f-915c-94a65b85aa05.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Peso do Documentos' = LOOKUPVALUE('Classificação Docs'[Peso],'Classificação Docs'[Documento],'Documentos em Análise'[Documento])
		formatString: 0
		lineageTag: aaea68fa-a9a8-4ea7-b743-2bd84f46926a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Chave Status Forne'
		dataType: string
		lineageTag: e0270797-9abb-4d60-a5df-f3980818c9ae
		summarizeBy: none
		sourceColumn: Chave Status Forne

		annotation SummarizationSetBy = Automatic

	column 'Início do Mês'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4dc0a292-2d87-4b75-81e0-5fd916acc229
		summarizeBy: none
		sourceColumn: Início do Mês

		variation Variation
			isDefault
			relationship: a9d9fd61-8d69-4f49-a994-a87c6d8f60ae
			defaultHierarchy: LocalDateTable_48db6bef-46cc-436d-b9b3-ecc8ff826528.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo do documento'
		dataType: string
		lineageTag: bd802db9-dadf-43bb-b331-053f4014d200
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Doc'
		dataType: string
		lineageTag: 65c4c2ed-89ba-40af-a3fa-5fea0be6bed7
		summarizeBy: none
		sourceColumn: Tipo de Doc

		annotation SummarizationSetBy = Automatic

	column Recorrência
		dataType: string
		lineageTag: 800d3130-8c7b-485e-9356-978f235f303f
		summarizeBy: none
		sourceColumn: Recorrência

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 2d398353-473a-4eca-9ca1-f47d6a82c0d8
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Data de Envio'
		dataType: string
		lineageTag: 7d2418a0-6c00-470a-a123-4dd74d7bbffe
		summarizeBy: none
		sourceColumn: Data de Envio

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 991a457a-51f3-4ef2-befd-d505172d47cc
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Documentos empresas e funcionarios '
		dataType: string
		lineageTag: 3774fa18-68ef-42dd-8064-d27d8464a4ec
		summarizeBy: none
		sourceColumn: "Documentos empresas e funcionarios "

		annotation SummarizationSetBy = Automatic

	column (FGTS_INSS_Pagamento_Ponto) = ```
			
			SWITCH(
			    'Documentos em Análise'[Documento],
			    
			    // FGTS
			    "FGTS - Comprovante de pagamento", "FGTS",
			    "FGTS - Guia de recolhimento (boleto)", "FGTS",
			    "FGTS - RE - Relação de Empregados/Trabalhadores", "FGTS",
			    
			    // INSS
			    "Comprovante de Recolhimento", "INSS",
			    "DARF – Documento de Arrecadação de Receitas Federais", "INSS",
			    "Relatório da Declaração Completa – DCTFWeb", "INSS",
			    "Recibo de Entrega da Declaração de Débitos e Créditos Tributários Federais Previdenciários – DCTFWeb", "INSS",
			
			    // Pagamento
			    "Folha de Pagamento", "Folha de Pagamento",
			
			     // Ponto
			    "Cartão de Ponto", "Folha de Ponto",
			
			    // Outros
			    "-"
			)
			
			```
		lineageTag: 6a8bf4c4-4520-4948-adcb-d73818b9d8d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '(Pendente _NPendente)' = ```
			
			    SWITCH(
			    'Documentos em Análise'[Status],
			    
			    // Pendente
			    "Atrasado", "Pendente",
			    "Atrasado Recusado", "Pendente",
			
			    //Não Pendente
			    "Aprovado", "Não pendente",
			    "Em Análise", "Não pendente",
			
			    //Outros
			    "-")
			
			```
		lineageTag: 5096af3b-1807-4684-be86-9c38c8c3a62d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vigência de Contrato'
		dataType: string
		lineageTag: e65fb216-51cd-4eab-9b58-e7f093aee462
		summarizeBy: none
		sourceColumn: Vigência de Contrato

		annotation SummarizationSetBy = Automatic

	column 'Data da Competência' = ```
			'Documentos em Análise'[Competência]
			
			```
		formatString: yyyy-mm
		lineageTag: 64acb68b-9d76-4463-89ef-90c34e481a6a
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 3a6eac75-ff78-43dc-baa8-e23a09e3b2a1
			defaultHierarchy: LocalDateTable_87ef1b30-6214-4082-84dc-21e7bf27be4f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column OrdemData = RANKX(ALL('Documentos em Análise'), 'Documentos em Análise'[Data da Análise],,DESC,DENSE)
		formatString: 0
		lineageTag: ed3154a4-c38a-4a79-8f59-ef59955ef97f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Documentos em Análise' = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="#(lf)DECLARE @currentDate datetime2 = CAST(GETDATE() AS DATETIME);#(lf)DECLARE @organizationId uniqueidentifier = 'ff063ad2-100d-4f34-895b-5af6697eec11';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = CAST(GETDATE() AS DATETIME);#(lf)#(lf)#(lf)WITH ContractBuildings AS (#(lf)    SELECT#(lf)        [c].[Id] AS ContractId,#(lf)        STRING_AGG([b].[TradeName], ', ') AS Buildings#(lf)    FROM#(lf)        [Contract] AS [c]#(lf)        INNER JOIN [Building] AS [b] ON [c].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [c].[Removed] = 0#(lf)        AND [b].[Removed] = 0#(lf)    GROUP BY#(lf)        [c].[Id]#(lf)),#(lf)ContractCategories AS (#(lf)    SELECT#(lf)        [c].[Id] AS ContractId,#(lf)        STRING_AGG([cat].[Name], ', ') AS Categories#(lf)    FROM#(lf)        [Contract] AS [c]#(lf)        INNER JOIN [Category] AS [cat] ON [c].[CategoryId] = [cat].[Id]#(lf)    WHERE#(lf)        [c].[Removed] = 0#(lf)    GROUP BY#(lf)        [c].[Id]#(lf))#(lf)#(lf)SELECT DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)#(lf)    CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)        WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)#(lf)    [ds].[Id] AS [DocumentScheduleId],#(lf)    [c].[Id] AS [Id_Contrato],#(lf)#(lf)    CASE WHEN [c].[OrderNumber] IS NULL THEN '---' ELSE [c].[OrderNumber] END AS [Número do Pedido],#(lf)#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN '---'#(lf)        ELSE#(lf)            CASE#(lf)                WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)                WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)                WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)                WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)                WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)                WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)                WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)                WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)                WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)                ELSE 'Nenhum'#(lf)            END#(lf)    END AS [Tipo de Contrato],#(lf)#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN c.ValidityInitial > GETDATE() THEN 'Vigência Futura'#(lf)#(tab)#(tab)WHEN c.ValidityFinal < GETDATE() THEN 'Vigência Finalizada'#(lf)#(tab)#(tab)ELSE 'Vigente'#(lf)#(tab)END AS 'Vigência de Contrato',#(lf)#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    [bc].[CompanyName] AS [Razão Social],#(lf)    dbo.FormatCNPJ(bc.Document) as [CNPJ],#(lf)#(lf)    ISNULL([er].[Name], '---') AS [Funcionário],#(lf)#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(tab)FORMAT([ds].[UploadedAt], 'dd/MM/yyyy HH:mm:ss') AS [Data de Envio],#(lf)    Case#(lf)        WHEN d.Frequency = 2 and d.DeliveryKind = 0 THEN FORMAT(DATEADD(MONTH, -1, [ds].[ExpectedUploadAt]), 'MM/yyyy')#(lf)        ELSE FORMAT([ds].[ExpectedUploadAt], 'MM/yyyy')#(lf)    END AS [Competência],#(lf)#(lf)    FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)#(lf)     CASE#(lf)        WHEN [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL) OR ([ds].[UploadedAt] >@currentDate) THEN 'Atrasado'#(lf)        WHEN [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL) THEN 'Próxima Entrega'#(lf)        WHEN [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] = 0) THEN 'Atrasado Recusado'#(lf)        WHEN [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] = 0) THEN 'Próxima Entrega Recusado'#(lf)        WHEN [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL THEN 'Em Análise'#(lf)        WHEN [ds].[UploadedAt] IS NOT NULL AND ([ds].[RequiresValidation] = 0 OR [ds].[IsValidated] = 1) THEN 'Aprovado'#(lf)        ELSE '--'#(lf)    END AS [Status],#(lf)#(lf)#(lf)    ISNULL(cb.Buildings, '---') AS [Unidade(s)],#(lf)    ISNULL(cc.Categories, '---') AS [Categoria(s)]#(lf)#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        (#(lf)            [ds].[UploadedAt] IS NOT NULL#(lf)            OR [c].[Removed] = 0#(lf)        )#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            ([ds].[ContractId] = [c].[Id])#(lf)            OR (#(lf)                (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                        AND EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                        AND NOT EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND ([ds].[ContractSetId] IS NULL OR [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) #(lf)                    )#(lf)                ) -- unidades#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- categorias#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    (#(lf)                        [d].[DeliveryKind] <> 0#(lf)                        AND [d].[DeliveryKind] <> 1#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0#(lf)                                AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                ) -- deliveykind#(lf)                AND ( -- Agendamento por funcionario#(lf)                    [ds].[Kind] <> 5#(lf)                    OR (#(lf)                        [er].[Id] IS NOT NULL#(lf)                        AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                        AND EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                                AND [erc].[ContractId] = [c].[Id]#(lf)                                AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- / Agendamento por funcionario#(lf)                AND ( -- Agendamento comum#(lf)                    [ds].[Kind] <> 1#(lf)                    OR (#(lf)                        [ds].[EmployeeRegisterId] IS NULL#(lf)                        AND [ds].[ContractId] IS NULL#(lf)                    )#(lf)                ) -- / Agendamento comum#(lf)            )#(lf)        )#(lf)    )#(lf)#(lf)LEFT JOIN ContractBuildings AS cb ON cb.ContractId = c.Id#(lf)LEFT JOIN ContractCategories AS cc ON cc.ContractId = c.Id#(lf)#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)#(tab)and c.removed = 0"]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(Fonte, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Número do Pedido", type any}, {"Tipo de Contrato", type text}, {"Fornecedor", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Status (Reclassificado)", each if Text.Contains([Status], "Recusado") then "Enviado" else if [Status] = "Aprovado" then "Enviado" else if [Status] = "Em Análise" then "Enviado" else if [Status] = "Atrasado" then "Não Enviado" else null),
				    #"Consultas Mescladas2" = Table.NestedJoin(#"Coluna Condicional Adicionada", {"Documento"}, #"Classificação Docs", {"Documento"}, "Classificação Docs", JoinKind.LeftOuter),
				    #"Classificação Docs Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas2", "Classificação Docs", {"Recorrência"}, {"Classificação Docs.Recorrência"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Classificação Docs Expandido",{{"Classificação Docs.Recorrência", "Recorrência"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas2",{{"Competência", type date}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado1", "Chave Fornecedores", each [Fornecedor]&[#"Categoria(s)"]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Número do Pedido", type text}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado2", "Chave", each [Fornecedor]&[CNPJ]&[#"Unidade(s)"]&[#"Categoria(s)"]&[Número do Pedido]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Personalização Adicionada2","---","",Replacer.ReplaceValue,{"Data da Análise"}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Valor Substituído",{{"Data da Análise", type date}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado3", "Chave Status Forne", each [Fornecedor]&[#"Categoria(s)"]&[#"Unidade(s)"]),
				    #"Início do Mês Inserido" = Table.AddColumn(#"Personalização Adicionada3", "Início do Mês", each Date.StartOfMonth([Competência]), type date),
				    #"Linhas Filtradas" = Table.SelectRows(#"Início do Mês Inserido", each ([Fornecedor] <> "Fornecedor Orgânico Argo")),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Linhas Filtradas", "Personalizar", each if [Funcionário] = "---" then "Documento de Empresa" else "Documento de Funcionário"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Condicional Adicionada1",{{"Personalizar", "Tipo de Doc"}}),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Colunas Renomeadas1", "Documentos empresas e funcionarios ", each if [Funcionário] = "---" then "Documento de Empresa" else "Documento de Funcionário")
				in
				    #"Coluna Condicional Adicionada2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

