table Contratos
	lineageTag: 087190bb-78e2-480f-b2b5-a7545f8dad88

	column CNPJ
		dataType: string
		lineageTag: 7df61d5d-9edd-4487-bc47-ed9045090a3f
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: c128ef9c-0b4e-49a0-be5a-f5527458e2b3
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 6ed815f1-3d7b-4851-b5c3-35b1b2021b76
			defaultHierarchy: LocalDateTable_7fe43cde-c2ea-4a23-a548-cd4127c3f2c2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Início Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5d3cdf95-8231-46b0-aa97-5cc7aaa7fd0d
		summarizeBy: none
		sourceColumn: Início Vigência

		variation Variation
			isDefault
			relationship: a020eb9c-ae35-4a1a-a48c-577d3dc6ba0e
			defaultHierarchy: LocalDateTable_6f7c3d1a-c4b0-4a62-a5d8-f7a83be4883c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 37a05a3c-fe47-430a-99de-6e33f45fb145
		summarizeBy: none
		sourceColumn: Fim Vigência

		variation Variation
			isDefault
			relationship: c88a2474-018d-4ce5-85d8-df60151de58a
			defaultHierarchy: LocalDateTable_73cbebba-0c00-4a1b-8549-afb0fc619c4f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: 2c5af1c5-99bf-4015-8aec-52dc18378359
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: e7b59119-be1a-42c7-91ee-ed8d145015a1
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 0b5d41c1-2820-495f-a36d-05320b16a151
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Status Contrato'
		dataType: string
		lineageTag: d829377f-3b17-4dbb-ac78-73902c885c92
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor-Categoria-Unidade
		dataType: string
		lineageTag: 294920e8-1ad0-4be7-a9b1-2fa77d454b1d
		summarizeBy: none
		sourceColumn: Fornecedor-Categoria-Unidade

		annotation SummarizationSetBy = Automatic

	column 'CNPJ Matriz'
		dataType: string
		lineageTag: 4f09d07a-f436-465b-af61-4d45aee3bc53
		summarizeBy: none
		sourceColumn: CNPJ Matriz

		annotation SummarizationSetBy = Automatic

	column 'CND.Emissão'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6205b0b1-7efe-45d6-a773-1ee84b13052d
		summarizeBy: none
		sourceColumn: CND.Emissão

		variation Variation
			isDefault
			relationship: 62a900d4-52e1-4082-9cd8-e51a61884581
			defaultHierarchy: LocalDateTable_4d7a5c95-ddfb-4885-9381-88ff6bfafb03.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CND.Validade'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 41b0ee9f-00cb-4c28-ac6c-4d229a2a0938
		summarizeBy: none
		sourceColumn: CND.Validade

		variation Variation
			isDefault
			relationship: d10ebb38-22a5-4538-853d-5d6f946d97fb
			defaultHierarchy: LocalDateTable_48a985a2-38e6-4428-90d9-6678ef78a820.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CND.Status Certidão'
		dataType: string
		lineageTag: b3017265-700d-485c-a36a-9a871bbd1b63
		summarizeBy: none
		sourceColumn: CND.Status Certidão

		annotation SummarizationSetBy = Automatic

	column 'CND.Status Validade'
		dataType: string
		lineageTag: 47f0f291-7b3b-4bc0-a243-69463f4aabe3
		summarizeBy: none
		sourceColumn: CND.Status Validade

		annotation SummarizationSetBy = Automatic

	column 'N° do pedido'
		dataType: string
		lineageTag: d55b27c6-436c-48b7-81bb-af8845a71e67
		summarizeBy: none
		sourceColumn: N° do pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: b824ead2-d297-4fd6-aa64-01ed5d9c4433
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: edb6e7e0-f49b-4c9e-a979-7b03b354573e
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 91b63dd8-ecdd-430b-93d0-ecbc0219a9ca
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 917fe27f-3fa7-4ccc-bd11-23d07120a663
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 116d5b20-0fad-4856-92b5-f4fc79002918
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 93612b5f-c6fb-4418-bfff-5303690c1a44
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    bc.CompanyName[Razão Social],#(lf)   dbo.FNCNPJMask(bc.Document) as [CNPJ],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor]#(lf)from [Contract] c with(nolock)#(lf)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)#(lf)where b.OrganizationId = 'B6D6CD6F-8777-491F-A831-FBD16FEF1887'#(lf)"]),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(Fonte, "Vigência", Splitter.SplitTextByDelimiter(" a ", QuoteStyle.Csv), {"Início Vigência", "Fim Vigência"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Início Vigência", type date}, {"Fim Vigência", type date}}),
				    
				    
				    // Calcula o primeiro dia do mês de hoje menos 2 meses
				    ReferenciaData = Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -2)),
				
				    // Coluna condicional automática baseada na referência calculada
				    #"Coluna Condicional Adicionada" = Table.AddColumn(
				        #"Tipo Alterado2",
				    "Status Contrato",
				    each if [Início Vigência] <= ReferenciaData and [Fim Vigência] >= ReferenciaData 
				         then "Vigente"
				         else "Não Vigente"
				),
				
				
				
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Coluna Condicional Adicionada", "Fornecedor-Categoria-Unidade", each Text.Combine({[Fornecedor], [Categoria], [Unidade]}, " - "), type text),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Coluna Mesclada Inserida", each ([Status Contrato] = "Vigente")),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas1", each ([Status Contrato] = "Vigente") and ([Fornecedor] <> "TESTE FORNECEDOR 1" and [Fornecedor] <> "TESTE FORNECEDOR 2")),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Linhas Filtradas", {"CNPJ"}, ListaCNPJs, {"CNPJ"}, "ListaCNPJs", JoinKind.LeftOuter),
				    #"ListaCNPJs Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "ListaCNPJs", {"CNPJ Matriz"}, {"CNPJ Matriz"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"ListaCNPJs Expandido", {"Fornecedor-Categoria-Unidade"}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Duplicatas Removidas", {"CNPJ Matriz"}, CND, {"CNPJ"}, "CND", JoinKind.LeftOuter),
				    #"CND Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "CND", {"Emissão", "Validade", "Status Certidão", "Status Validade"}, {"CND.Emissão", "CND.Validade", "CND.Status Certidão", "CND.Status Validade"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"CND Expandido",null,"Certidão não emitida",Replacer.ReplaceValue,{"CND.Status Certidão"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",null,"Certidão não emitida",Replacer.ReplaceValue,{"CND.Status Validade"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído1",{{"CND.Emissão", type date}, {"CND.Validade", type date}, {"CND.Status Certidão", type text}, {"CND.Status Validade", type text}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

