table 'Entrega de documentos'
	lineageTag: 6d22200c-8079-4426-b5bb-466e15d0e316

	column Documento
		dataType: string
		lineageTag: f0472d0f-e8fa-438c-a94a-9b0ca1df1cdb
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: 859bd0ba-3b5b-4b92-9ac6-040cf4657a55
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: d00a71d0-96ed-465b-82ca-a762561873d4
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 8e2d6e62-7bf0-4372-b477-ce1063eed6be
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Id.Contrato'
		dataType: string
		lineageTag: 1cd4ec01-146b-425f-a4ee-609bccc01aa2
		summarizeBy: none
		sourceColumn: Id.Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 3ccd3207-3f16-4ed5-8915-ee690f217985
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 364e6bae-9a79-4395-922b-3b8b4731eefe
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: 652cd5d1-02c1-4acf-832e-d22cb3dee525
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 6ea9067f-c97d-44ef-b173-a55cd5ab9805
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 260606ee-4e21-47f1-a687-f5233bcb1f56
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: 44e2198a-0b79-422e-a9c2-020e9d55f346
			defaultHierarchy: LocalDateTable_0d74e4dc-089d-4b1f-adf4-b6ed99e12426.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1b18bb6-8048-4888-8251-e8d157f5f475
		summarizeBy: none
		sourceColumn: Data de Envio

		variation Variation
			isDefault
			relationship: fae29e24-555c-459a-9621-53e2ac4ab72d
			defaultHierarchy: LocalDateTable_74adf570-f93c-4262-86a0-4cf52998279f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data da Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d2dc3faa-d1dd-4107-a2b6-3db32a9be388
		summarizeBy: none
		sourceColumn: Data da Análise

		variation Variation
			isDefault
			relationship: 3f3d16c5-2041-4bc9-a550-362ab0a1ec8f
			defaultHierarchy: LocalDateTable_4756c2d6-018c-4cbb-a3c2-1eff96cd5463.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: f5b19371-aca5-4b3c-987c-d3aa6380bd56
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: 4f8f8672-93ab-4f64-9fd4-a848db787db3
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: f925bfe1-34bf-4aeb-b6fd-b55b9cb33258
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: mmmm" de "yyyy
		lineageTag: 826db075-8d50-4296-9528-d11c18f4ede3
		summarizeBy: none
		sourceColumn: Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Fornecedor-Categoria-Unidade
		dataType: string
		lineageTag: 9143b0c9-9660-4df4-91c5-f98de90129e8
		summarizeBy: none
		sourceColumn: Fornecedor-Categoria-Unidade

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 07b4e46f-0e81-48d0-acfa-d0048f86c6e1
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 7311eea0-b0dd-4d2f-9169-03e7f1480266
			defaultHierarchy: LocalDateTable_e30bd396-51bd-474e-9da6-7091b01ca27d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Início Vigência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f1767c54-f529-44eb-b10c-6b863f9c1f2b
		summarizeBy: none
		sourceColumn: Início Vigência

		variation Variation
			isDefault
			relationship: cd29b1d5-b660-4b8e-8887-5d0a9d8f3dcf
			defaultHierarchy: LocalDateTable_50c0b729-fbad-4fbd-88bc-2707c5daf622.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim Vigência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1a23da43-456b-4c1b-9c71-a254a76148a2
		summarizeBy: none
		sourceColumn: Fim Vigência

		variation Variation
			isDefault
			relationship: 2f37be44-57a0-40f5-a555-cdebc4530f47
			defaultHierarchy: LocalDateTable_2811033a-1ca2-437f-8c1b-39a2861755b3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status Contrato'
		dataType: string
		lineageTag: bc54eb09-2e5a-45f2-8d18-5a754176db7e
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column 'Classificação Documentos' =
			
			IF('Entrega de documentos'[Documento] = "FGTS - Comprovante de pagamento", "Comprovante de Pagamento",
			    IF('Entrega de documentos'[Documento] = "FGTS - RE - Relação de Empregados/Trabalhadores", "RT - Relatório de Trabalhador",
			        IF('Entrega de documentos'[Documento] = "FGTS - Guia de Recolhimento (boleto)", "GFD - Boleto","Outros"
			        )))
		lineageTag: 8c47701b-9b86-482e-a8b0-82466b554f05
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Contagem Entregue' = ```
			
			IF(
			    'Entrega de documentos'[Status] <> "Atrasado" &&
			    'Entrega de documentos'[Status] <> "Atrasado Recusado",
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: 5ea4c34d-389b-40ee-a006-162618482832
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Entrega de documentos' = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = GETDATE();#(lf)DECLARE @organizationId uniqueidentifier = 'B6D6CD6F-8777-491F-A831-FBD16FEF1887';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = GETDATE();#(lf)#(lf)WITH DocumentScheduleBuildings AS (#(lf)    SELECT#(lf)        [dsb].[DocumentScheduleId],#(lf)        STRING_AGG([b].[TradeName], ', ') AS [Buildings]#(lf)    FROM#(lf)#(lf)        [DocumentScheduleBuilding] AS [dsb]#(lf)        INNER JOIN [Building] AS [b] ON [dsb].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [dsb].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsb].[DocumentScheduleId]#(lf)),#(lf)DocumentScheduleCategories AS (#(lf)    SELECT#(lf)        [dsc].[DocumentScheduleId],#(lf)        STRING_AGG([c].[Name], ', ') AS [Categories]#(lf)    FROM#(lf)        [DocumentScheduleCategory] AS [dsc]#(lf)        INNER JOIN [Category] AS [c] ON [dsc].[CategoryId] = [c].[Id]#(lf)    WHERE#(lf)        [dsc].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsc].[DocumentScheduleId]#(lf))#(lf)SELECT#(lf)    DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)#(tab)CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)    [ds].Id AS [DocumentScheduleId],#(lf)    CASE#(lf)        WHEN [c].[OrderNumber] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [c].[OrderNumber]#(lf)    END AS [Número do Pedido],#(lf)#(tab)c.Id [Id.Contrato],#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        CASE#(lf)            WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)            WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)            WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)            WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)            WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)            WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)            WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)            WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)            WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)            ELSE 'Nenhum'#(lf)        END#(lf)    END AS [Tipo de Contrato],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    [bc].[Document] AS [CNPJ],#(lf)    CASE#(lf)        WHEN [er].[Name] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [er].[Name]#(lf)    END AS [Funcionário],#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(tab)FORMAT([ds].[UploadedAt], 'dd/MM/yyyy') AS [Data de Envio],#(lf)#(tab)FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)    CASE#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Atrasado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Próxima Entrega'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Atrasado Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Próxima Entrega Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL#(lf)        THEN#(lf)            'Em Análise'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 0#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[IsValidated] IS NOT NULL AND [ds].[IsValidated] = 1#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)ELSE#(lf)            '--'#(lf)    END AS [Status],#(lf)    b.tradename AS [Unidade(s)],#(lf)    cat.Name AS [Categoria(s)]#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    INNER JOIN [DocumentScheduleContractBI] as dscBI on [dscBI].DocumentScheduleId = [ds].Id#(lf)    INNER JOIN [Contract] as c on c.id = dscBI.ContractId#(lf)    INNER JOIN Building as b on b.id = c.BuildingId#(lf)    INNER JOIN Category as cat on cat.id = c.CategoryId#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)-- ORDER BY #(lf)--     [p].[TradeName], [d].[Kind], [d].[Name], [ds].[ExpectedUploadAt], [er].[Name];"]),
				
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Prazo de Envio", type date}, {"Data de Envio", type date}, {"Data da Análise", type date}}),
				
				    // Cria coluna Competência = Prazo de Envio - 1 mês
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Competência", each Date.StartOfMonth(Date.AddMonths([Prazo de Envio], -1))),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Competência", type date}}),
				
				    // ======== FILTRO DE COMPETÊNCIA (12 meses) ========
				    UltimaData = Date.EndOfMonth(List.Max(#"Tipo Alterado1"[Competência])),
				    DataInicial = Date.StartOfMonth(Date.AddMonths(UltimaData, -12)),
				
				    #"Competencia Filtrada" =
				        Table.SelectRows(
				            #"Tipo Alterado1",
				            each [Competência] >= DataInicial and [Competência] <= UltimaData
				        ),
				    // ==================================================
				
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Competencia Filtrada", "Fornecedor-Categoria-Unidade", each Text.Combine({[Fornecedor], [#"Categoria(s)"], [#"Unidade(s)"]}, " - "), type text),
				
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"Fornecedor-Categoria-Unidade"}, Contratos, {"Fornecedor-Categoria-Unidade"}, "Contratos", JoinKind.LeftOuter),
				    #"Contratos Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Contratos", {"Cadastro no sistema", "Início Vigência", "Fim Vigência", "Status Contrato"}, {"Cadastro no sistema", "Início Vigência", "Fim Vigência", "Status Contrato"}),
				
				    #"Linhas Filtradas" = Table.SelectRows(#"Contratos Expandido", each ([Status Contrato] = "Vigente"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

