table 'Relatório de Contratos'
	lineageTag: d5d98fd3-2526-4c4f-bfc3-f4730b018f1e

	measure _Unidades_ = DISTINCTCOUNT('Relatório de Contratos'[Unidade])
		formatString: 0
		lineageTag: 2c24e76f-dd63-41ab-acb7-ca17baca30c3

	measure _Contratos_ = DISTINCTCOUNT('Relatório de Contratos'[Id do Contrato])
		formatString: #,0
		lineageTag: 56c675e0-46fc-4053-b2d9-7262be04bcac

	measure _Fornecedores_ = DISTINCTCOUNT('Relatório de Contratos'[CNPJ])
		formatString: 0
		lineageTag: 53cdb454-8647-45d0-9050-24fa1b479f71

	measure _Quantidade_Contratos = CALCULATE(COUNTROWS())
		formatString: 0
		lineageTag: d34ca110-05a0-4ff1-a079-f9a88f6fe04f

	column 'Nº do pedido'
		dataType: string
		lineageTag: 043d7409-bc4e-400a-ad1b-5a9908ca48ed
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column 'Id do Contrato'
		dataType: string
		lineageTag: f8f4144e-f546-44bd-9aa3-2913783b137c
		summarizeBy: none
		sourceColumn: Id do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 11a8f40a-eab1-4a89-995c-9bfcec38abd5
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: 0b9eb200-3d92-48ae-ac4e-8bf3a27d694d
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: e00ed8de-29c7-49f8-bb0a-9b68966f4ca0
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 7f38dac2-fe63-4482-8041-d07b53a6abce
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: a6425969-d680-430b-80ea-ff4aed7513ce
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6465ca51-5681-4cc5-8b41-457c042d26ed
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 96a4b494-6b3f-42ec-aa9e-fbcf16dc085e
			defaultHierarchy: LocalDateTable_2a979920-7442-413f-b2ef-109de928a00f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Vigência
		dataType: string
		lineageTag: c5f74993-e8a6-4d6b-9b00-ad10bf0f7f3e
		summarizeBy: none
		sourceColumn: Vigência

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: e8676b09-ddf8-4d02-8b85-133f0ba76cc8
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 0b5a2883-7d08-43c1-a80e-7d3b4942373d
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: a50f2518-47a0-4edb-a896-610048ada59e
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 106a1447-b16e-42ac-a0b1-cc4ba413decb
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: de38409c-e6b4-4d97-bf57-1b0847fa114e
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column (%Aderência) = [(%Aderência)]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0f674d74-6d30-40b5-ac05-1b03e7944833
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column (%Conformidade) = [(%Conformidade)]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f6b20edd-6d67-4a7e-9d30-3bd1007f1d9e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Faixa de Adesão' =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([(%Aderência)]), "0%",
			    [(%Aderência)] < 0.25, "0%-25%",
			    [(%Aderência)] < 0.5, "25%-50%",
			    [(%Aderência)] < 0.75, "50%-75%",
			    [(%Aderência)] < 1, "75%-100%",
			    [(%Aderência)] = 1, "100%",
			    "Outro"
			)
		lineageTag: f6d2eca0-1ba7-4d4e-ac39-940078439bbc
		summarizeBy: none
		sortByColumn: OrdemFaixaAdesao

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Faixa de Conformidade' =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([(%Conformidade)]), "0%",
			    [(%Conformidade)] < 0.25, "0%-25%",
			    [(%Conformidade)] < 0.5, "25%-50%",
			    [(%Conformidade)] < 0.75, "50%-75%",
			    [(%Conformidade)] < 1, "75%-100%",
			    [(%Conformidade)] = 1, "100%",
			    "Outro"
			)
		lineageTag: 3d088ea9-9dc9-4ffd-ad3e-a1eab57bf21d
		summarizeBy: none
		sortByColumn: OrdemFaixaConformidade

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column OrdemFaixaAdesao =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([(%Aderência)]), 1,
			    [(%Aderência)] < 0.25, 2,
			    [(%Aderência)] < 0.5, 3,
			    [(%Aderência)] < 0.75, 4,
			    [(%Aderência)] < 1, 5,
			    [(%Aderência)] = 1, 6,
			    0
			)
		formatString: 0
		lineageTag: 2d3d86f5-3d16-4a4d-a99b-c576ab0a9a7b
		summarizeBy: sum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column OrdemFaixaConformidade =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([(%Conformidade)]), 1,
			    [(%Conformidade)] < 0.25, 2,
			    [(%Conformidade)] < 0.5, 3,
			    [(%Conformidade)] < 0.75, 4,
			    [(%Conformidade)] < 1, 5,
			    [(%Conformidade)] = 1, 6,
			    0
			)
		formatString: 0
		lineageTag: 75e07c1d-0cb0-4793-98a0-794693e5654b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Peso1 = [Peso 1]
		formatString: 0
		lineageTag: 01ca135c-0d0f-4d6b-843f-a0c0a0739c95
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Peso3 = [Peso 3]
		formatString: 0
		lineageTag: a54932b9-077e-475c-ac3d-6c15365e01ef
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column (%Grau_de_Risco) = ((1/4)*[Peso1])+(3/4)*[Peso3]
		lineageTag: 879d5d25-92c5-4060-a2b2-7abebcf6bad2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrdemFaixaGrauRisco =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([(%Grau_de_Risco)]), 1,
			    [(%Grau_de_Risco)] < 0.25, 2,
			    [(%Grau_de_Risco)] < 0.5, 3,
			    [(%Grau_de_Risco)] < 0.75, 4,
			    [(%Grau_de_Risco)] < 1, 5,
			    [(%Grau_de_Risco)] = 1, 6,
			    0
			)
		formatString: 0
		lineageTag: 5938c76c-8d9a-4960-b031-512db1cd7557
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Faixa de Grau de Risco' =
			
			SWITCH(
			    TRUE(),
			    ISBLANK([(%Grau_de_Risco)]), "0%",
			    [(%Grau_de_Risco)] < 0.25, "0%-25%",
			    [(%Grau_de_Risco)] < 0.5, "25%-50%",
			    [(%Grau_de_Risco)] < 0.75, "50%-75%",
			    [(%Grau_de_Risco)] < 1, "75%-100%",
			    [(%Grau_de_Risco)] = 1, "100%",
			    "Outro"
			)
		lineageTag: 7fec746e-8d67-47f5-8dd2-ee0ec132edcd
		summarizeBy: none
		sortByColumn: OrdemFaixaGrauRisco

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Relatório de Contratos' = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[Nº do pedido],#(lf)#(tab)c.Id[Id do Contrato],#(lf)    bc.CompanyName[Razão social],#(lf)    [bc].[Document] AS [CNPJ],#(lf)#(tab)#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    c.[CreatedAt][Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato]#(lf)#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(tab)#(tab)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)left join ContractManager cm with(nolock) on cm.ContractId = c.Id and cm.Removed = 0 #(lf)#(tab)#(tab)left join ContractContact cc with(nolock) on cc.ContractId = c.Id and cm.Removed = 0#(lf)where b.OrganizationId = '49443CB2-548F-4529-AA0B-019F6FC55E27'#(lf)and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(lf)#(tab) -- Select * from CustomField Where OrganizationId = 'e9654655-6595-4748-991d-6b50831c6ca5'#(lf)#(lf)#(lf)#(lf)#(lf)#(tab)"])
				in
				    Fonte

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

