table Contratos
	lineageTag: 1fd70a1f-e20f-49bf-89f4-880cb325b5f9

	column 'Nº do pedido'
		dataType: string
		lineageTag: 8089207d-b24b-47a8-bb2d-8a836a485da3
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 673afd35-82bf-495d-a281-5df01abea4a6
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: 7a3d5058-81e8-48a8-8501-51c7d57bda87
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: d161d663-6e3c-496c-9e02-61057a061737
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column SLA
		dataType: string
		lineageTag: 2802e0df-fe61-45b5-8d0a-1d2d5d326516
		summarizeBy: none
		sourceColumn: SLA

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3f757940-f19d-45be-86f1-73a9b7a69ba5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: 631462a0-35f8-46f0-a32c-dbcf4dcc654f
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 981e8b82-c32f-40ce-8008-2c6ea563dd4a
			defaultHierarchy: LocalDateTable_0b2a5d4c-cb90-4c9f-a030-6dd6d808f000.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Vigência
		dataType: string
		lineageTag: 2d18865a-b644-4a3d-8387-59ba5f6203dc
		summarizeBy: none
		sourceColumn: Vigência

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: f34ee242-8a86-4fba-8937-ec2c97b22d15
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 9362236c-15de-4969-a4ca-9fe3a14d0195
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 6ab54d3a-1196-498f-ab6b-d4e79ba55f7c
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Possui dados de faturamento?'
		dataType: string
		lineageTag: 9a29d934-57a9-42e5-8d51-e5d43f524b7c
		summarizeBy: none
		sourceColumn: Possui dados de faturamento?

		annotation SummarizationSetBy = Automatic

	column 'Possui dados de faturamento?_1'
		dataType: string
		lineageTag: ec42894e-a3a0-4ec1-9faf-40f405686e25
		summarizeBy: none
		sourceColumn: Possui dados de faturamento?_1

		annotation SummarizationSetBy = Automatic

	column 'Atividades do Contrato'
		dataType: string
		lineageTag: e42fc44a-2a82-42a8-88f8-fc066de2af02
		summarizeBy: none
		sourceColumn: Atividades do Contrato

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoãoLima\Diretório Padrão\Atlas Inovações - Documentos\Produtos\AFM\SETUP\Gestão\16. Relatório Interno e Externo - Power BI\02. Externo\01. AFM Gestão\Algar\2025\02 - Fevereiro\Relatorio - Contratos - 2502101618.xlsx"), null, true),
				    Contratos_Sheet = Fonte{[Item="Contratos",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Contratos_Sheet,{{"Column1", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type any}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Column1", "Column16"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Linhas em Branco Removidas",1),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Nº do pedido", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"SLA", type text}, {"Status", type text}, {"Cadastro no sistema", type datetime}, {"Vigência", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}, {"Possui dados de faturamento?", type text}, {"Possui dados de faturamento?_1", type text}, {"Atividades do Contrato", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

