table Contratos
	lineageTag: 0b60eaf6-b893-4880-84cd-00002096574b

	measure '(Contratos) Quantidade' = CALCULATE(COUNTROWS())
		formatString: 0
		lineageTag: b4e6f195-c1e5-4fbe-9c0d-88d2725f8b87

	measure '(Fornecedor) Quantidade' = CALCULATE(DISTINCTCOUNT(Contratos[Razão Social]))
		formatString: 0
		lineageTag: f8ef5869-0926-49b0-9df2-2ecaa89fc51f

	column CNPJ
		dataType: string
		lineageTag: e401cdf6-97e9-4f75-b688-322ad7281207
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 731ea080-0cb3-4d8f-acfe-7c3758f80b84
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6ae5a074-edb6-41f3-bfc2-95d7b6a9fe4f
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: 04566036-08ae-4846-977a-c3569a6efa2b
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 6ca186ff-5fa1-413d-903a-d34a7ff112b3
			defaultHierarchy: LocalDateTable_91c0d0ba-daf7-49e1-ba16-073ad6fcb8dc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: bee1dbe8-571b-49cd-b8e5-401bf1fe81d3
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 7e81ef56-2af1-4f42-b724-5062e3cd231d
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'N° do pedido'
		dataType: string
		lineageTag: 3ac34605-df3e-433a-a4d0-809c209c44fd
		summarizeBy: none
		sourceColumn: N° do pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: f8ad6db8-c302-4a09-932e-f2c080f16311
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: a1b41dd0-33a3-4890-9db2-b193363a4a7c
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 8cf34781-92c8-4538-b519-18056aa6710b
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 01ecdc81-166f-4e49-9fef-84c0b88a3d3b
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: 75b50266-b9fc-4196-b141-96b2edfc0c38
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status2
		dataType: int64
		formatString: 0
		lineageTag: b97ecedb-f0c4-42eb-8443-66817571e1a3
		summarizeBy: sum
		sourceColumn: Status2

		annotation SummarizationSetBy = Automatic

	column 'Vigência de Contrato'
		dataType: string
		lineageTag: e21c809a-ec7f-43a3-b5a1-6c2681bf9a69
		summarizeBy: none
		sourceColumn: Vigência de Contrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicial'
		dataType: string
		lineageTag: 12f50cf3-a63b-48c3-997b-e273bf9330e5
		summarizeBy: none
		sourceColumn: Vigência Inicial

		annotation SummarizationSetBy = Automatic

	column 'Vigência Final'
		dataType: string
		lineageTag: cf03c994-b8f2-4d02-99e4-a43fd6f0f8cf
		summarizeBy: none
		sourceColumn: Vigência Final

		annotation SummarizationSetBy = Automatic

	column Distribuidora
		dataType: string
		lineageTag: 15224376-20c1-43a6-9443-c128940132ac
		summarizeBy: none
		sourceColumn: Distribuidora

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 8c710104-0310-441d-b741-fe74caabc36f
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column Agendamentos =
			
			VAR TOTAL = [(Total) Documentos]
			
			RETURN IF (TOTAL = BLANK(),0,TOTAL)
		formatString: 0
		lineageTag: 34f47ace-f42d-4748-9e56-85cf39e12994
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Ativos Efetivos' = ```
			
			VAR Efetivos = 'Status de Efetivos'[_Ativos_Efetivos] 
			RETURN IF(Efetivos=BLANK(),0,Efetivos)
			```
		formatString: 0
		lineageTag: d0151ef2-95ac-4d0c-acea-614a883fec41
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Status3
		dataType: string
		lineageTag: 5fb17e79-674a-4d8f-8788-20ec541c45e2
		summarizeBy: none
		sourceColumn: Status3

		annotation SummarizationSetBy = Automatic

	column 'Status Não Prestação' = ```
			
			VAR ST = Contratos[Status2]
			RETURN IF(ST=2, "Não Prestação", "Prestação")
			
			```
		lineageTag: 350b35c8-65cc-4f27-8488-359813485fde
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN c.ValidityInitial > GETDATE() THEN 'Vigência Futura'#(lf)#(tab)#(tab)WHEN c.ValidityFinal < GETDATE() THEN 'Vigência Finalizada'#(lf)#(tab)#(tab)ELSE 'Vigente'#(lf)#(tab)END AS 'Vigência de Contrato',#(lf)    bc.CompanyName[Razão Social],#(lf)   dbo.FNCNPJMask(bc.Document) as [CNPJ],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    FORMAT(c.ValidityInitial, 'dd/MM/yyyy')[Vigência Inicial],#(lf)    FORMAT(c.ValidityFinal, 'dd/MM/yyyy')[Vigência Final], #(lf)    b.TradeName[Distribuidora],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    nprov.[Status],#(lf)    c.[Value][Valor do contrato],#(lf)#(tab)cfi3.[Name][Status]#(lf)from [Contract] c with(nolock)#(lf)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)LEFT join CustomFieldValue cfv with(nolock) on cfv.EntityId = c.Id#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)         LEFT JOIN [NonProvisionOfServiceDeclaration] as nprov WITH (NOLOCK) #(lf)        ON nprov.ContractId = c.Id AND nprov.Status = 2#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)outer apply #(lf)#(tab)(#(lf)    select cfi2.[Name] from CustomFieldValue cfv2 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi2 with(nolock) on cfv2.CustomFieldItemId = cfi2.Id#(lf)       #(lf)    where cfv2.EntityId = c.Id#(lf)#(tab)#(tab)and cfv2.[Value] is null#(lf)#(tab)#(tab)and cfv2.Removed = 0#(lf)#(tab)#(tab)and cfi2.Removed = 0#(lf)#(tab)) as [cfi3]#(lf)#(lf)where b.OrganizationId = '41cacafc-2823-4a1a-a0db-381a24eb9014'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(tab)"]),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(Fonte, "Chave", each Text.Combine({[Fornecedor], [Categoria], [Distribuidora]}, ""), type text),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Mesclada Inserida",{{"Status2", "Status2"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

