table Lista_Total_Efetivos
	lineageTag: 234d82b0-e728-4c02-b738-5feb640ac507

	column Id_Contrato
		dataType: string
		lineageTag: f46b2d93-6a03-44bd-a3de-39464f17a911
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência de Contrato'
		dataType: string
		lineageTag: 98b4cb43-10cc-44c7-926c-db0336f7614c
		summarizeBy: none
		sourceColumn: Vigência de Contrato

		annotation SummarizationSetBy = Automatic

	column Contrato
		dataType: string
		lineageTag: b4ceca9a-6fda-4792-9d12-4ea993f61842
		summarizeBy: none
		sourceColumn: Contrato

		annotation SummarizationSetBy = Automatic

	column PIS
		dataType: string
		lineageTag: a3979f25-3120-4e6c-923f-06b48486ffd2
		summarizeBy: none
		sourceColumn: PIS

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: c4c6a96c-ef91-4ed7-a87d-9a16d5c2a43b
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 4c777c2b-6a75-4744-9cac-253a17108f99
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: a61a3e51-63f5-4bc1-9d4f-48c9f4b2b762
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 7c930965-8e4c-4042-8a02-371c10b7576a
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Documento Estrangeiro'
		dataType: string
		lineageTag: fb4f8955-736f-4afc-a46c-87e351f0f55e
		summarizeBy: none
		sourceColumn: Documento Estrangeiro

		annotation SummarizationSetBy = Automatic

	column 'Tipo de contratação'
		dataType: string
		lineageTag: f951e2d7-c7cd-4ba6-abff-2038ba36d639
		summarizeBy: none
		sourceColumn: Tipo de contratação

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: a0f5a7c7-954c-4621-af1b-b7d20f15f0c5
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column 'Data de Cadastro'
		dataType: dateTime
		formatString: Long Date
		lineageTag: deda2d60-25fb-433a-9bf4-789bd127b549
		summarizeBy: none
		sourceColumn: Data de Cadastro

		variation Variation
			isDefault
			relationship: b930cacb-a0e8-4223-87fb-48523dd1e41c
			defaultHierarchy: LocalDateTable_ce5b44d0-25be-4ef4-99d0-748da1b6e25d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Chave Motivo'
		dataType: string
		lineageTag: 1a9cdb3f-54ee-485a-b066-6953f84d4b39
		summarizeBy: none
		sourceColumn: Chave Motivo

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: e28bb2a6-8406-4b0c-a995-589dadefb29d
		summarizeBy: sum
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	column 'Chave Status'
		dataType: string
		lineageTag: 2e1eb705-7e06-47b4-99c9-c7ba2a8cdb1f
		summarizeBy: none
		sourceColumn: Chave Status

		annotation SummarizationSetBy = Automatic

	column Mesclado
		dataType: string
		lineageTag: 4a676ac5-734d-4cc1-a4f4-a72d35ac9f41
		summarizeBy: none
		sourceColumn: Mesclado

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 02d46a81-46b7-4185-8728-671d36986407
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 7f34624e-a25b-47b6-bef5-1cab88e4957c
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column Origem
		dataType: string
		lineageTag: 0dbd6969-96f3-4c2d-8a9c-3f01c8bb705d
		summarizeBy: none
		sourceColumn: Origem

		annotation SummarizationSetBy = Automatic

	column 'CPF - Copiar'
		dataType: string
		lineageTag: 52631d74-9627-40b9-ba20-b400d3441332
		summarizeBy: none
		sourceColumn: CPF - Copiar

		annotation SummarizationSetBy = Automatic

	column 'Data de Admissão do Colaborador'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0866998d-60ae-462f-9cbc-1732e8675cc4
		summarizeBy: none
		sourceColumn: Data de Admissão do Colaborador

		variation Variation
			isDefault
			relationship: 8a55759c-1280-4340-b212-1115feb61d09
			defaultHierarchy: LocalDateTable_430cee34-0a0f-4ea0-ba3d-a037ce1b9611.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Situação
		dataType: string
		lineageTag: 74fbd2cf-62e2-462d-a499-724d0863a5a2
		summarizeBy: none
		sourceColumn: Situação

		annotation SummarizationSetBy = Automatic

	column 'Chave única'
		dataType: string
		lineageTag: e82bed69-5abc-452b-9fec-cb1a7eec086f
		summarizeBy: none
		sourceColumn: Chave única

		annotation SummarizationSetBy = Automatic

	partition Lista_Total_Efetivos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select#(lf)#(tab)o.TradeName as 'Cliente',#(lf)#(tab)b.TradeName as 'Unidade',#(lf)#(tab)p.TradeName as 'Fornecedor',#(lf)#(tab)c.OrderNumber as 'Contrato',#(lf)#(tab)c.Id AS 'Id_Contrato',#(lf)#(tab)cat.Name as 'Categoria',#(lf)#(tab)r.Name as 'Regional',#(lf)#(tab)e.Name as 'Funcionário',#(lf)#(tab)dbo.FNCPFMask(e.CpfNumber) as 'CPF',#(lf)#(tab)dbo.FNPISMask(e.PisNumber) as 'PIS',#(lf)#(tab)FORMAT(g.Competency, 'MM/yyyy') as 'Competência',#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN ee.Status = 0#(lf)#(tab)#(tab)THEN 'Irregular'#(lf)#(lf)#(tab)#(tab)WHEN ee.Status = 1#(lf)#(tab)#(tab)THEN 'Regular'#(lf)#(tab)END as 'Status',#(lf)#(tab)ee.StatusObservation as 'Observação',#(lf)#(tab)ee.Remuneration as 'Valor sefip',#(lf)#(tab)ee.SalaryExpected as 'Valor do contrato',#(lf)#(tab)ee.EffectiveSalary as 'Valor cadastrado',#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 0#(lf)#(tab)#(tab)THEN '0x0'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 1#(lf)#(tab)#(tab)THEN '2x1'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 2#(lf)#(tab)#(tab)THEN '4x2'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 3#(lf)#(tab)#(tab)THEN '5x1'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 4#(lf)#(tab)#(tab)THEN '5x2'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 5#(lf)#(tab)#(tab)THEN '6x1'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 6#(lf)#(tab)#(tab)THEN '6x2'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 7#(lf)#(tab)#(tab)THEN '12x36'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 8#(lf)#(tab)#(tab)THEN '12x48'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 9#(lf)#(tab)#(tab)THEN '12x36 (36hrs)'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 10#(lf)#(tab)#(tab)THEN '4x4'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 11#(lf)#(tab)#(tab)THEN '14x14'#(lf)#(tab)END as 'Escala',#(lf)#(tab)FORMAT(ee.EffectiveStartTime, 'HH:mm') as 'Início da jornada',#(lf)#(tab)FORMAT(ee.EffectiveEndTime, 'HH:mm') as 'Término da jornada',#(lf)#(tab)FORMAT(ee.EffectiveInterval, 'HH:mm') as 'Intrajornada descansada',#(lf)#(tab)FORMAT(ee.EffectiveOvertimeInterval, 'HH:mm') as 'Intrajornada remunerada',#(lf)#(tab)ee.EffectiveTotalMonthlyOvertimeInterval as 'Valor intrajornada remunerada',#(lf)#(tab)ee.EffectiveTotalAdditionalValueNightTime as 'Adicional noturno',#(lf)#(tab)ee.EffectiveTotalAdditionalValueNightTimeReduced as 'Hora noturna reduzida',#(lf)#(tab)FORMAT(ee.EffectiveOverTime, 'HH:mm') as 'Hora extra',#(lf)#(tab)ee.EffectiveTotalMonthlyOvertimeHour as 'Valor hora extra',#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN ee.EffectiveHolidayWorkingKind = 0#(lf)#(tab)#(tab)THEN 'Sim, Trabalha nos feriados'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveHolidayWorkingKind = 1#(lf)#(tab)#(tab)THEN 'Não trabalha nos feriados'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveHolidayWorkingKind = 3#(lf)#(tab)#(tab)THEN 'Folga compensada'#(lf)#(tab)END as 'Trabalha aos feriados',#(lf)#(tab)ee.EffectiveUnhealthiness as 'Insalubridade',#(lf)#(tab)ee.EffectiveTotalUnhealthiness as 'Total insalubridade',#(lf)#(tab)ee.EffectiveDangerousness as 'Periculosidade',#(lf)#(tab)ee.EffectiveTotalDangerousness as 'Total periculosidade',#(lf)#(tab)ee.EffectiveBonus as 'Gratificação/Acúm. funções',#(lf)#(tab)ee.EffectiveTotalBonus as 'Valor gratificação/Acúm. funções',#(lf)#(tab)ee.EffectiveTotalLeadership as 'Gratificação liderança',#(lf)#(tab)ee.EffectiveTotalOthersAdditional as 'Outros adicionais',#(lf)#(tab)u.Name as 'Responsável',#(lf)#(tab)u.Email as 'Email'#(lf)from #(lf)#(tab)EmployeeEntry ee#(lf)#(lf)#(tab)left join Employee e#(lf)#(tab)on e.Id = ee.EmployeeId#(lf)#(lf)#(tab)inner join [User] u #(lf)#(tab)on u.Id = ee.ResponsibleId#(lf)#(lf)#(tab)left join [Function] f#(lf)#(tab)on f.Id = ee.FunctionId#(lf)#(lf)#(tab)inner join Gfip g#(lf)#(tab)on g.Id = ee.GfipId#(lf)#(lf)#(tab)inner join ContractSet cs#(lf)#(tab)on cs.Id = g.ContractSetId#(lf)#(lf)#(tab)inner join Building b#(lf)#(tab)on b.Id = cs.BuildingId#(lf)#(lf)#(tab)inner join Region r#(lf)#(tab)on r.Id = b.RegionId #(lf)#(lf)#(tab)inner join Provider p #(lf)#(tab)on p.Id = cs.ProviderId#(lf)#(lf)#(tab)inner join Organization o#(lf)#(tab)on o.Id = b.OrganizationId#(lf)#(lf)#(tab)inner join CategoryContractSet catSet#(lf)#(tab)on g.ContractSetId = catSet.ContractSetId#(lf)#(lf)#(tab)inner join Category cat#(lf)#(tab)on catSet.CategoryId = cat.Id#(lf)#(lf)#(tab)inner join Contract c#(lf)#(tab)on c.ContractSetId = cs.Id#(lf)where#(lf)o.Id = '41CACAFC-2823-4A1A-A0DB-381A24EB9014' and#(lf)g.Competency >= '2022-02-01 00:00:00.0000000'#(lf)and g.Id NOT IN#(lf)(#(lf)'F950FDB2-E041-4A73-8950-A7E80C3D0E69',#(lf)'679BE57D-5145-4DF1-956D-D08E4CA9E54E',#(lf)'CCCBD6D1-EDCC-4373-9ADF-00C0FE5EAA9C',#(lf)'22E7A015-3F18-4E85-8446-6E1BE76AE6CA'#(lf))#(lf)#(lf)order by #(lf)#(tab)o.TradeName,#(lf)#(tab)b.TradeName,#(lf)#(tab)p.TradeName,#(lf)#(tab)e.Name,#(lf)#(tab)g.Competency#(lf)#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Cliente", type text}, {"Unidade", type text}, {"Fornecedor", type text}, {"Categoria", type text}, {"Funcionário", type text}, {"PIS", type any}, {"Competência", type date}, {"Status", type text}, {"Observação", type text}, {"Valor sefip", Int64.Type}, {"Valor do contrato", Int64.Type}, {"Valor cadastrado", Int64.Type}, {"Escala", type text}, {"Início da jornada", type text}, {"Término da jornada", type text}, {"Intrajornada descansada", type text}, {"Intrajornada remunerada", type text}, {"Valor intrajornada remunerada", Int64.Type}, {"Adicional noturno", Int64.Type}, {"Hora noturna reduzida", Int64.Type}, {"Hora extra", type text}, {"Valor hora extra", Int64.Type}, {"Trabalha aos feriados", type text}, {"Insalubridade", Int64.Type}, {"Total insalubridade", Int64.Type}, {"Periculosidade", Int64.Type}, {"Total periculosidade", Int64.Type}, {"Gratificação/Acúm. funções", Int64.Type}, {"Valor gratificação/Acúm. funções", Int64.Type}, {"Gratificação liderança", Int64.Type}, {"Outros adicionais", Int64.Type}, {"Responsável", type text}, {"Email", type text}, {"CPF", type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Chave", each [Fornecedor]&[Categoria]&[Unidade]),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Personalização Adicionada", "Chave Movimentações", each Text.Combine({[Fornecedor], [Unidade], [Funcionário]}, ""), type text),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Coluna Mesclada Inserida", "Origem", each "FGTS Digital"),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Personalização Adicionada1",{"Cliente", "Unidade", "Fornecedor", "Categoria", "Regional", "Competência", "Status", "Observação", "Valor sefip", "Valor do contrato", "Valor cadastrado", "Escala", "Início da jornada", "Término da jornada", "Intrajornada descansada", "Intrajornada remunerada", "Valor intrajornada remunerada", "Adicional noturno", "Hora noturna reduzida", "Hora extra", "Valor hora extra", "Trabalha aos feriados", "Insalubridade", "Total insalubridade", "Periculosidade", "Total periculosidade", "Gratificação/Acúm. funções", "Valor gratificação/Acúm. funções", "Gratificação liderança", "Outros adicionais", "Responsável", "Email", "Chave", "Chave Movimentações"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"Funcionário", "Nome"}}),
				    #"Consulta Acrescentada1" = Table.Combine({#"Colunas Renomeadas", #"Status de Efetivos"}),
				    #"Linhas Classificadas" = Table.Sort(#"Consulta Acrescentada1",{{"CPF", Order.Ascending}}),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Linhas Classificadas", "Mesclado", each Text.Combine({[Nome], [CPF]}, ""), type text),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Coluna Mesclada Inserida1", "CPF", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"CPF.1", "CPF.2"}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Dividir Coluna por Delimitador",{"CPF.2"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"CPF.1", "CPF"}}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Colunas Renomeadas1", "CPF", "CPF - Copiar")
				in
				    #"Coluna Duplicada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

