table Pesos
	lineageTag: 2b8b65d5-b772-4b40-85b9-939d3ab73014

	column Documento
		dataType: string
		lineageTag: e7224fe6-1a88-4353-9c2c-8cbb036d5fc4
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Recorrência
		dataType: string
		lineageTag: 3c82d1d1-b574-4d7f-9be4-4f0fbe166610
		summarizeBy: none
		sourceColumn: Recorrência

		annotation SummarizationSetBy = Automatic

	column Referência
		dataType: string
		lineageTag: 8c9b49b6-ac85-462b-bec6-8b63f1da4c26
		summarizeBy: none
		sourceColumn: Referência

		annotation SummarizationSetBy = Automatic

	column Restrição
		dataType: string
		lineageTag: 5b797e7b-844b-42be-a10e-0a13312615d1
		summarizeBy: none
		sourceColumn: Restrição

		annotation SummarizationSetBy = Automatic

	column Peso
		dataType: int64
		formatString: 0
		lineageTag: 7aa0e3e5-9391-4318-9a45-39254b1590ff
		summarizeBy: none
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

	partition Pesos = m
		mode: import
		source =
				let
				     Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vVdNbtpAFL7KiBVRE6GqJwADaRZNLHDTSlEWD8+DjDSeiWYM6rJ36AmqLqpEyirqJlvfpCfpm7EBG0gg4EaKiGc8872/7/346qrRjrXhmgVaYipm+pie1AxV9jv7tdgFpqesOHimuJgJPgXJOLLIwAjkjW4cN0Jt2Ayk4MCRlueaJdm9dYdQzYQ7McSEGbSpEYT+By1tvW9cH5MOwwsGPBHWCq1AtkKkI49cxO5Wz91m2ZPKl6/F7eICl/Y/obL5g8MAlZIkbWgd6BIGWU7wtzCBBFWqHeCHHHAmrGbv2ABjMfKHxtmdEWBpL9bJrdEzh1m5fbjUDohvwBSwIAqHDFsUjN6J1bHwmNv9vpuUAExavA11LXoHaFLBi/fd7G4k6O2cMsKmwE5YcN6NapY0wMlUgvEOYcTY/mk0dAQmUfNlDRIJrI8cTR20CkrU6YCKs5903QdiftYthiD9C3evraZe3muyIagSlDisKQw1cXQNfEIBNpqIOpwT9UAJ3fagz/5+/8G6Op4unNI2BmPgsLhJZqFIKSPz6Ah7uGRPIKLqf0vwQsDpVIA7YUqRYc2Rq8H6qDYpg577Qbl0WY/swglwbVtFctKzwRc99yzL+iK+gTIF9kMhB0A1A3IQ1qZCnj2kIoa9gHMfF0WhKyZEFUmq2ljY7JEqOWue9rvljSMq7SuRD3eJ/LMahMgF937nvjW5IFB1iqn8Qr5rpThIgARVFIzsif41K8HuoMKxiEVeSsi4judX1coX2bZF8AV33UNmjxNq2G8nfNmSeyp1dGYcqPnH1AmW8hdNCFlgsjteNCQxmqaFSvOqwUKDNOagWijrS08Q9b/gaE8FJaSOUnpNM2c8+QHqlFGkCxl9QYObye7JEtgvpYfUUI333yU11bcLaYQmKWq6T0fvKQou5KV/PnuyZhQMoiM3gNWbqZcgqcFIX4gLg/e0ffFXAh7gGEXtqOQUZW+1SffO+xXUMm0rAwl9Cgxero27I4Vnw1dBuRq9qZIfVzDCs68Mq61utb+t4oZ+UvSjBomvjvrzurJM0JXbm8i5fmrlY2f9QF+bZCoXM+BnJca0g6RLaHSqaTYoq7P1/jqLWyXq7QPaU9SsJtpPnX1Isgcptqvh5lr/8FEbms6ape9IN5sXn58bCLjJnBLLdzLg+h8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Documento = _t, Recorrência = _t, Referência = _t, Restrição = _t, Peso = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Documento", type text}, {"Recorrência", type text}, {"Referência", type text}, {"Restrição", type text}, {"Peso", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

