table CND
	lineageTag: 2973e16d-7005-421b-b50c-82b7bf77e29c

	column Unidade
		dataType: string
		lineageTag: 64a151a2-32e3-4e79-b040-4dc584758d2a
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 99934d7c-3ddb-482d-b7d5-931b9a37044c
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: bbcf7a8b-fb45-4c4c-aa0a-bc4e5ef00364
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Fornecedor-Categoria-Unidade
		dataType: string
		lineageTag: 80b509bf-6844-46bd-badd-1057fade1370
		summarizeBy: none
		sourceColumn: Fornecedor-Categoria-Unidade

		annotation SummarizationSetBy = Automatic

	column 'Início Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72fcbc32-e01f-4669-af52-ae4cc0d8c7c9
		summarizeBy: none
		sourceColumn: Início Vigência

		variation Variation
			isDefault
			relationship: 061ece13-df77-44fd-8b33-b90caaec1153
			defaultHierarchy: LocalDateTable_ae7493fc-35a3-4fef-8743-c8ebf5d69cf1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0a79c3fb-b890-49da-bfe2-bced00ef48e2
		summarizeBy: none
		sourceColumn: Fim Vigência

		variation Variation
			isDefault
			relationship: 6e9992ec-13ed-4b3b-8873-fb4f957a5b42
			defaultHierarchy: LocalDateTable_1c44d9ca-3964-48f1-b8f8-67d8f911d3fb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Vigência
		dataType: string
		lineageTag: ba95193a-acae-450c-867a-4b5c191020ee
		summarizeBy: none
		sourceColumn: Vigência

		annotation SummarizationSetBy = Automatic

	column 'Envio CND Federal '
		dataType: string
		lineageTag: d76e19fd-2289-4f16-9b28-bbb35c448333
		summarizeBy: none
		sourceColumn: "Envio CND Federal "

		annotation SummarizationSetBy = Automatic

	column 'CND Federal'
		dataType: string
		lineageTag: c45ca211-d081-4079-87a8-bd0b6c724973
		summarizeBy: none
		sourceColumn: CND Federal

		annotation SummarizationSetBy = Automatic

	column 'Prazo de entrega CND Federal'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e10b43cf-92f0-4349-bdd9-2ead409dbef6
		summarizeBy: none
		sourceColumn: Prazo de entrega CND Federal

		variation Variation
			isDefault
			relationship: a64af93e-5ed3-4493-85da-59d1bee8508e
			defaultHierarchy: LocalDateTable_14a8615b-e6a7-4ea3-9da9-3bdb411500b1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data entrega CND Federal'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8ec67ccb-35bd-4511-b1eb-ddfc90f9a43f
		summarizeBy: none
		sourceColumn: Data entrega CND Federal

		variation Variation
			isDefault
			relationship: c79d8002-7c88-4b73-babd-dad3c01fb0d9
			defaultHierarchy: LocalDateTable_a7bf8b5a-3c68-4169-91ee-4d0ed14634ce.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status CND Federal'
		dataType: string
		lineageTag: aad49a21-b5d6-47ac-8e61-471a79efb6a2
		summarizeBy: none
		sourceColumn: Status CND Federal

		annotation SummarizationSetBy = Automatic

	column 'Envio CND Estadual'
		dataType: string
		lineageTag: da815207-4ee3-4f74-ad01-c1a5a12ac5fd
		summarizeBy: none
		sourceColumn: Envio CND Estadual

		annotation SummarizationSetBy = Automatic

	column 'CND Estadual'
		dataType: string
		lineageTag: e3656e76-5b4b-43d9-98e5-fe0499b3bca8
		summarizeBy: none
		sourceColumn: CND Estadual

		annotation SummarizationSetBy = Automatic

	column 'Prazo de entrega CND Municipal'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9108df4b-ef34-4cf6-a90f-3153039343da
		summarizeBy: none
		sourceColumn: Prazo de entrega CND Municipal

		variation Variation
			isDefault
			relationship: 83513bc4-98cc-41ed-99e5-1566e9b7f76a
			defaultHierarchy: LocalDateTable_4e51caa5-333f-4ba8-b9c4-43caa3626a8f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data entrega CND Estadual'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 23490e31-0797-4cb9-85b0-939e7e334801
		summarizeBy: none
		sourceColumn: Data entrega CND Estadual

		variation Variation
			isDefault
			relationship: 0075858a-f98e-47fb-ae43-87d238a08a07
			defaultHierarchy: LocalDateTable_5f7b62b7-4f91-4def-a42d-cba733bbab91.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status CND Estadual'
		dataType: string
		lineageTag: 9e5a67aa-485d-4ed2-a16c-6ab552bc0b5c
		summarizeBy: none
		sourceColumn: Status CND Estadual

		annotation SummarizationSetBy = Automatic

	column 'Envio CND Municipal'
		dataType: string
		lineageTag: 01be25b5-1d83-4a51-87d6-17ba5b8a46f2
		summarizeBy: none
		sourceColumn: Envio CND Municipal

		annotation SummarizationSetBy = Automatic

	column 'CND Municipal'
		dataType: string
		lineageTag: 4636db76-5840-4238-a67f-ee9326e1239a
		summarizeBy: none
		sourceColumn: CND Municipal

		annotation SummarizationSetBy = Automatic

	column 'Prazo de entrega CND Estadual'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 30130116-b6c6-4071-a6dc-1c9ff133d13a
		summarizeBy: none
		sourceColumn: Prazo de entrega CND Estadual

		variation Variation
			isDefault
			relationship: 8c45debb-83fe-476f-b416-5c278100f41f
			defaultHierarchy: LocalDateTable_bcf55ad5-3df6-46f9-bec3-d3d924b7ab04.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data entrega CND Municipal'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2ef0b654-c560-49f9-af05-9a3abde1ff0b
		summarizeBy: none
		sourceColumn: Data entrega CND Municipal

		variation Variation
			isDefault
			relationship: 669d3e73-0b65-40ce-b494-cb5b30ebb744
			defaultHierarchy: LocalDateTable_3dc56463-8ea9-4df4-b308-507da01aa18d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status CND Municipal'
		dataType: string
		lineageTag: f471bdca-c61a-436e-9324-d593b8c0d9a5
		summarizeBy: none
		sourceColumn: Status CND Municipal

		annotation SummarizationSetBy = Automatic

	partition CND = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoanaMalheiros\Diretório Padrão\Atlas Inovações - Documentos\Consultoria\1.1. AFM CLIENTES\Shopping Vitoria\STATUS SHOPPING VITÓRIA\2024\4. Abril\Entrega CND.xlsx"), null, true),
				    CND_Sheet = Fonte{[Item="CND",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(CND_Sheet, [PromoteAllScalars=true]),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Cabeçalhos Promovidos",{"Razão social", "CNPJ"}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Colunas Removidas", "Fornecedor-Categoria-Unidade", each Text.Combine({[Fornecedor], [Categoria], [Unidade]}, " - "), type text),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Coluna Mesclada Inserida", "Vigência", Splitter.SplitTextByDelimiter(" a ", QuoteStyle.Csv), {"Início Vigência", "Fim Vigência"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Início Vigência", type date}, {"Fim Vigência", type date}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado1", "Vigência", each if [Fim Vigência] >= #date(2024, 7, 1) then "Vigente" else "Não vigente"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Coluna Condicional Adicionada", each ([Vigência] = "Vigente")),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Prazo de entrega CND Estadual", type date}, {"Data entrega CND Municipal", type date}, {"Prazo de entrega CND Municipal", type date}, {"Data entrega CND Estadual", type date}, {"Data entrega CND Federal", type date}, {"Prazo de entrega CND Federal", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

