table Contratos
	lineageTag: bdecbffc-38e8-4d06-949c-cddd30512e72

	measure _Quantidade_Contrato = DISTINCTCOUNT('Contratos'[Id_Contrato])
		formatString: 0
		lineageTag: 28eafeae-e407-4599-a520-272b8d34223d

	column CNPJ
		dataType: string
		lineageTag: 65994f1c-1309-4271-9c4c-93185ed16c4c
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: bc407221-7dbd-40f7-961c-3551f27b2744
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 53081f9d-d1e2-4406-8587-034ad3136bf7
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: c50d06ce-ccc3-49da-a07d-927cdfd16292
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 0f764b8d-400c-4472-bd12-c836342c13ed
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 2bf91b04-e4c0-4766-9a9c-e22c0f4421f2
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: a488dcbd-4308-4b57-a95d-3d5cdc460abd
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 1e13713a-8d4f-49c1-811f-d44206777d88
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 78f95930-e4f0-4123-bb66-23885395a6f5
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Grupo de Risco - Mobilização'
		dataType: string
		lineageTag: 34ad009d-0725-4561-ae49-3ec7372c117b
		summarizeBy: none
		sourceColumn: Grupo de Risco - Mobilização

		annotation SummarizationSetBy = Automatic

	column 'Data Original do Contrato'
		dataType: string
		lineageTag: 986d0f92-9e75-4973-8816-5f90c1d03f64
		summarizeBy: none
		sourceColumn: Data Original do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Objeto de Contrato'
		dataType: string
		lineageTag: a86428d9-7b1b-4228-a583-79ed91186b0c
		summarizeBy: none
		sourceColumn: Objeto de Contrato

		annotation SummarizationSetBy = Automatic

	column CNO
		dataType: string
		lineageTag: 1249d048-f0b2-40be-b1bc-294bbad2ad53
		summarizeBy: none
		sourceColumn: CNO

		annotation SummarizationSetBy = Automatic

	column 'Data de Mobilização'
		dataType: string
		lineageTag: 9067af0e-2f29-48d3-8f03-45bf1481d36c
		summarizeBy: none
		sourceColumn: Data de Mobilização

		annotation SummarizationSetBy = Automatic

	column 'Grau de Risco - Trabalhista'
		dataType: string
		lineageTag: 579caa1c-e2b5-4dfb-93b6-0306e81afcbc
		summarizeBy: none
		sourceColumn: Grau de Risco - Trabalhista

		annotation SummarizationSetBy = Automatic

	column 'Nome do Gestor do Contrato'
		dataType: string
		lineageTag: dc2c18aa-8e4d-4100-8078-82d606e4bc56
		summarizeBy: none
		sourceColumn: Nome do Gestor do Contrato

		annotation SummarizationSetBy = Automatic

	column 'E-mail do Gestor do Contrato'
		dataType: string
		lineageTag: 72827401-d425-4351-adbb-e159adbcfa7f
		summarizeBy: none
		sourceColumn: E-mail do Gestor do Contrato

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 27199b05-6ecf-42b0-b419-7555a33dc9d8
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column 'Data da Solicitação'
		dataType: string
		lineageTag: 6e1a81b9-ed16-4619-b5bf-07fcb39d43a2
		summarizeBy: none
		sourceColumn: Data da Solicitação

		annotation SummarizationSetBy = Automatic

	column 'Tipo da Contratação'
		dataType: string
		lineageTag: f7679bbe-b295-448a-ae65-37ef498c4fa2
		summarizeBy: none
		sourceColumn: Tipo da Contratação

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: f90f12ef-028a-4491-a00e-2ba26e0bebb0
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Valor do Contrato'
		dataType: double
		lineageTag: 04765781-0f3d-445a-bca9-dfff037dd9c4
		summarizeBy: sum
		sourceColumn: Valor do Contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vigência Inicial'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 12a673a7-2c81-4ec0-80a8-dafd2cb1c261
		summarizeBy: none
		sourceColumn: Vigência Inicial

		variation Variation
			isDefault
			relationship: c5b0866b-e916-473a-a7c7-963e1cdd00aa
			defaultHierarchy: LocalDateTable_71857990-85b6-4f44-9784-6ca81f3b8ffa.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Final'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7c0f470a-3a65-4939-b83d-7c6a8e62bc41
		summarizeBy: none
		sourceColumn: Vigência Final

		variation Variation
			isDefault
			relationship: 6d7bc4ed-84f2-44de-b5a7-e187feba66ee
			defaultHierarchy: LocalDateTable_75fbb428-b4ef-4180-a662-589ef2188a6e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'N° do Pedido'
		dataType: string
		lineageTag: 5fbb1cb2-b246-425e-812a-58980ba382aa
		summarizeBy: none
		sourceColumn: N° do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4f6f21de-c9f0-494b-a2f6-ec14ebb39783
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: a16bac22-17a3-4fbf-b848-222b7a0fc0d2
			defaultHierarchy: LocalDateTable_3a8c36a6-8736-439c-9a92-8245ea2b6101.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status Contrato'
		dataType: string
		lineageTag: 609c1c56-2f5b-4730-b780-455420a6ab1d
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column Chave-Cadas
		dataType: string
		lineageTag: 2f4e3afd-bf30-4684-b20f-7d53ffccc3c7
		summarizeBy: none
		sourceColumn: Chave-Cadas

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = EOMONTH(GETDATE(), -1);#(lf)#(lf)SELECT DISTINCT #(lf)    c.OrderNumber AS [N° do Pedido],#(lf)#(tab)c.Id AS [Id_Contrato],#(lf)    bc.CompanyName AS [Razão Social],#(lf)  SUBSTRING(bc.Document, 1, 2) + '.' + SUBSTRING(bc.Document, 3, 3) + '.' + SUBSTRING(bc.Document, 6, 3) + '/' + SUBSTRING(bc.Document, 9, 4) + '-' + SUBSTRING(bc.Document, 13, 2) AS [CNPJ],#(lf)    CASE#(lf)        WHEN c.[Type] = 1 THEN 'Contínuo'#(lf)        WHEN c.[Type] = 2 THEN 'Grandes Paradas'#(lf)        WHEN c.[Type] = 4 THEN 'Eventual'#(lf)        WHEN c.[Type] = 8 THEN 'Temporário'#(lf)        WHEN c.[Type] = 16 THEN 'Visitante técnico'#(lf)        WHEN c.[Type] = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        WHEN c.[Type] = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)        WHEN c.[Type] = 128 THEN 'Prestação de serviço de auditoria, sem acesso às áreas restritas'#(lf)        WHEN c.[Type] = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)    END AS [Tipo da Contratação],#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)WHEN c.FatherId IS NULL THEN 'Contratado'#(lf)#(tab)#(tab)ELSE 'Subcontratado'#(lf)#(tab) END as 'Tipo de Fornecedor',#(lf)    CASE#(lf)        WHEN c.Sla = 0 THEN 'Padrão'#(lf)        WHEN c.Sla = 1 THEN 'Emergencial'#(lf)    END AS [Sla],#(lf)    CASE#(lf)        WHEN c.[Status] = 0 THEN 'Regular'#(lf)        WHEN c.[Status] = 1 THEN 'Aguardando dados de contatos do fornecedor'#(lf)        WHEN c.[Status] = 2 THEN 'Aguardando fornecedor preencher o contrato'#(lf)        WHEN c.[Status] = 3 THEN 'Arquivado'#(lf)    END AS [Status],#(lf)    FORMAT(TRY_CAST(c.CreatedAt AS DATE), 'dd/MM/yyyy') AS [Cadastro no sistema],#(lf)    FORMAT(c.ValidityInitial, 'dd/MM/yyyy') AS [Vigência Inicial],#(lf)    FORMAT(c.ValidityFinal, 'dd/MM/yyyy') AS [Vigência Final],#(lf)#(lf)    CASE #(lf)        WHEN c.ValidityInitial > GETDATE() THEN 'Contrato Futuro'#(lf)        WHEN c.ValidityFinal < GETDATE() THEN 'Contrato Inativo'#(lf)        ELSE 'Contrato Ativo'#(lf)     END AS [Status Contrato],#(lf)    CONCAT(c.OrderNumber,b.TradeName) as [Chave-Cadas],#(lf)    b.TradeName AS [Unidade],#(lf)    r.Name AS [Regional],#(lf)    ca.[Name] AS [Categoria],#(lf)    p.TradeName AS [Fornecedor],#(lf)    c.[Value] AS [Valor do Contrato], #(lf)    [Grupo de Risco].[Name] AS [Grupo de Risco - Mobilização],#(lf)    FORMAT(TRY_CAST(cfv2.[Value] AS DATE), 'dd/MM/yyyy') AS [Data Original do Contrato], #(lf)    cfv3.[Value] AS [Objeto de Contrato],#(lf)    cfv4.[Value] AS [CNO],#(lf)    cfv5.[Value] AS [Data de Mobilização],#(lf)    [Grau de Risco].[Name] AS [Grau de Risco - Trabalhista],#(lf)    ISNULL(cfv6.[Value],'Sem Gestor') AS [Nome do Gestor do Contrato],#(lf)    cfv7.[Value] AS [E-mail do Gestor do Contrato],#(lf)    cfv8.[Value] AS [Solicitante],#(lf)    cfv9.[Value] AS [Data da Solicitação]#(lf)FROM #(lf)    [Contract] c WITH(NOLOCK)#(lf)INNER JOIN #(lf)    Building b WITH(NOLOCK) ON b.Id = c.BuildingId#(lf)INNER JOIN #(lf)    Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)INNER JOIN #(lf)    CustomFieldValue cfv WITH(NOLOCK) ON cfv.EntityId = c.Id#(lf)INNER JOIN #(lf)    BranchCompany bc WITH(NOLOCK) ON bc.Id = c.BranchCompanyId#(lf)INNER JOIN #(lf)    [Category] ca WITH(NOLOCK) ON ca.Id = c.CategoryId#(lf)INNER JOIN #(lf)    [Provider] p WITH(NOLOCK) ON c.ProviderId = p.Id#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv2 WITH(NOLOCK) ON cfv2.EntityId = c.Id AND cfv2.CustomFieldId = '35F4D9D3-A055-4BBA-AC14-168B26BC2A07' -- Data original do início do contrato#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv3 WITH(NOLOCK) ON cfv3.EntityId = c.Id AND cfv3.CustomFieldId = 'B334C1D9-2CA3-4954-A7A4-7056362CC480' -- Objeto de Contrato#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv4 WITH(NOLOCK) ON cfv4.EntityId = c.Id AND cfv4.CustomFieldId = '4D0CB535-C054-4D66-96D5-A4C9A697DDF6' -- CNO#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv5 WITH(NOLOCK) ON cfv5.EntityId = c.Id AND cfv5.CustomFieldId = 'FE71101C-EA3A-4F21-A392-999EE3810D92' -- Data de Mobilização#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv6 WITH(NOLOCK) ON cfv6.EntityId = c.Id AND cfv6.CustomFieldId = 'BEA30E2D-D72D-466B-9DCF-E3963CDD894E' -- Nome do gestor do contrato#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv7 WITH(NOLOCK) ON cfv7.EntityId = c.Id AND cfv7.CustomFieldId = 'D76E189B-AF15-4881-B8EF-13AF376BDF5B' -- E-mail do gestor do contrato#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv8 WITH(NOLOCK) ON cfv8.EntityId = c.Id AND cfv8.CustomFieldId = '810B170B-D585-4EDA-BBD7-299F1E844750' -- Nome do solicitante#(lf)LEFT JOIN #(lf)    CustomFieldValue cfv9 WITH(NOLOCK) ON cfv9.EntityId = c.Id AND cfv9.CustomFieldId = '9D457DE9-8142-4098-95E6-312C255C85DE' -- Data da solicitação#(lf)OUTER APPLY #(lf)    (#(lf)        SELECT cfi2.[Name]#(lf)        FROM CustomFieldValue cfv10 WITH(NOLOCK)#(lf)        INNER JOIN CustomFieldItem cfi2 WITH(NOLOCK) ON cfv10.CustomFieldItemId = cfi2.Id#(lf)        WHERE cfv10.EntityId = c.Id#(lf)            AND cfv10.Removed = 0#(lf)            AND cfi2.Removed = 0#(lf)            AND cfv10.CustomFieldId = 'fd7e2177-9dc6-4ca0-9b79-a7c88fa6abcb' -- Grupo de Risco - Mobilização#(lf)    ) AS [Grupo de Risco]#(lf)OUTER APPLY #(lf)    (#(lf)        SELECT cfi3.[Name]#(lf)        FROM CustomFieldValue cfv11 WITH(NOLOCK)#(lf)        INNER JOIN CustomFieldItem cfi3 WITH(NOLOCK) ON cfv11.CustomFieldItemId = cfi3.Id#(lf)        WHERE cfv11.EntityId = c.Id#(lf)            AND cfv11.Removed = 0#(lf)            AND cfi3.Removed = 0#(lf)            AND cfv11.CustomFieldId = '2740532e-e70c-434c-99e1-e9930cd607d5' -- Grau de Risco - Trabalhista#(lf)    ) AS [Grau de Risco]#(lf)WHERE #(lf)    b.OrganizationId = '24d80b2f-c0de-4e58-9273-06a8de082474'#(lf)    and c.ValidityInitial <= @currentDate#(lf)    and c.CreatedAt <= @CurrentDate#(lf)    and c.removed =0 #(lf)ORDER BY #(lf)    c.OrderNumber;#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"N° do Pedido", type text}, {"Razão Social", type text}, {"CNPJ", type text}, {"Tipo da Contratação", type text}, {"Status", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}, {"Vigência Final", type date}, {"Vigência Inicial", type date}, {"Cadastro no sistema", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

