table DocumentValidationSla
	lineageTag: 32b8f7da-64a1-46a7-9def-d834e2650321

	measure _Análises_Quantidade = CALCULATE(COUNTROWS())
		formatString: #,0
		lineageTag: 4b4eed5b-4d98-4e24-83bb-b4cd5b7c96d2

	measure '_Enviados_Quantidade de Enviados' = CALCULATE(DISTINCTCOUNT(DocumentValidationSla[DocumentScheduleId]))
		formatString: #,0
		lineageTag: dca8f7dd-cbb6-47a1-ae0e-9388367b884a

	measure _Reprovações_Quantidade =
			
			VAR Recusados = CALCULATE(COUNTROWS(),
			DocumentValidationSla[Status_Documentacao] = "Reprovado")
			
			VAR Total = [_Análises_Quantidade]
			
			RETURN IF(Recusados = BLANK() && Total >0, 0, Recusados)
		formatString: #,0
		lineageTag: 884638fb-d53d-475a-b15f-f1dc26df4422

	measure _%Reprovação_ =
			
			VAR Reprovacoes = [_Reprovações_Quantidade]
			VAR Total = [_Análises_Quantidade]
			RETURN IF(Reprovacoes = BLANK() && Total>0,0, Reprovacoes/Total)
		lineageTag: e16396e1-7eb4-4cb3-86fc-77eb5dfaeb72

		formatStringDefinition =
				VAR REPROV = FORMAT([_%Reprovação_],"0.0%")
				
				VAR ANAL = FORMAT([_Análises_Quantidade],"#,###")
				
				RETURN """" & REPROV & " (" & ANAL & ")"

	measure '_Validação_Quantidade de Validação' = CALCULATE(COUNTROWS())
		lineageTag: e59a1c60-d2c9-4b5d-8d32-bf1176af467b

		formatStringDefinition =
				VAR VALI = FORMAT(DocumentValidationSla[_Validação_Quantidade de Validação],"#,###")
				
				VAR ENVI = FORMAT([_Enviados_Quantidade de Enviados],"#,###")
				
				RETURN """" & VALI & " (" & ENVI & ")"

	measure _Taxa_Reprovação = ```
			
			VAR Reprovacoes = [_Reprovações_Quantidade]
			VAR Total = [_Enviados_Quantidade de Enviados]
			RETURN IF(Reprovacoes = BLANK() && Total>0,0, Reprovacoes/Total)
			
			```
		lineageTag: 2210e6ab-486e-49fc-be8f-4be494d27f30

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fornecedor
		dataType: string
		lineageTag: cfb7e9c8-9f1f-4790-80a0-b7cf1f210c10
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Data_Envio
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2185d4a4-7efc-40e8-bf72-ffbc663cbb61
		summarizeBy: none
		sourceColumn: Data_Envio

		variation Variation
			isDefault
			relationship: 0476d6fa-f188-4c7e-a004-cd5a9100e86c
			defaultHierarchy: LocalDateTable_3c4f4dfa-c2fc-41f2-9f02-5618f4626e04.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Status_Documentacao
		dataType: string
		lineageTag: 1787ed21-afa8-436e-b6f9-b8b529787d68
		summarizeBy: none
		sourceColumn: Status_Documentacao

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: c3a9fac9-dcab-4434-ae50-cf601f0cba5c
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: 02e02e56-3025-4037-a2bd-2f627fdce38a
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Nome Cliente'
		dataType: string
		lineageTag: efe70fad-2564-4906-81fa-d286cdfb0b45
		summarizeBy: none
		sourceColumn: Nome Cliente

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: 1dbc4900-a6ea-48ef-844a-2ebdfecb826d
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 9a9c4482-28b0-45a1-acba-44453ad28e16
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Analisado por'
		dataType: string
		lineageTag: e20d7844-575d-4999-b2e8-5d76e71a08a3
		summarizeBy: none
		sourceColumn: Analisado por

		annotation SummarizationSetBy = Automatic

	column Id_Validador
		dataType: string
		lineageTag: a89a852b-2e66-48ac-be11-110f4cf216ea
		summarizeBy: none
		sourceColumn: Id_Validador

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: string
		lineageTag: ced077ae-eb0e-4cc2-8f7e-44a8bf7768dc
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 84294575-4432-4f79-9730-93315c8f1fa2
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: 7c4956cf-5005-4de0-970b-7fd1d4d7297b
			defaultHierarchy: LocalDateTable_1f323e31-a72f-4b1c-9e0f-3d16e9819ad9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Data_Análise
		dataType: dateTime
		formatString: General Date
		lineageTag: 44691b20-3a45-49c1-be73-976388ba64f3
		summarizeBy: none
		sourceColumn: Data_Análise

		variation Variation
			isDefault
			relationship: 544a9d4f-25ec-4c90-ba1e-43c42e1ad7c8
			defaultHierarchy: LocalDateTable_a407d8c9-e438-4a20-8c02-e64cb5efd362.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Id_Reanálise
		dataType: string
		lineageTag: 168c3fd5-f606-4049-a9ba-6d1f99c39403
		summarizeBy: none
		sourceColumn: Id_Reanálise

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: 4476d782-7671-4c5a-89c3-6dcedd1c8e40
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	partition DocumentValidationSla = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = EOMONTH(GETDATE(),-1);#(lf)DECLARE @organizationId uniqueidentifier = '24d80b2f-c0de-4e58-9273-06a8de082474';#(lf)DECLARE @initialDate datetime2 = '2024-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = EOMONTH(GETDATE(),-1);#(lf)#(lf)#(lf)SELECT DISTINCT#(lf)       [ds].[Name] AS [Documento],#(lf)#(tab)   [ds].Id AS [DocumentScheduleId],#(lf)#(tab)   o.TradeName as 'Nome Cliente',#(lf)#(tab)   CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)    --[c].[Id] as [Id_Contrato],#(lf)    --[c].[OrderNumber] as [Número de Pedido],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    [b].[TradeName] AS [Unidade],#(lf)#(lf)#(tab) CASE#(lf)#(tab)#(tab)WHEN (ds.ValidatedBy =  '00000000-0000-0000-0000-000000000000' and dsv.Responsibleid is null) THEN 'Validado Automaticamente'#(lf)        WHEN dsv.Responsibleid =  '00000000-0000-0000-0000-000000000000' THEN 'Validado Automaticamente'#(lf)#(tab)#(tab)WHEN ds.RequiresValidation = 0 THEN 'Não é Necessário Validação'#(lf)        WHEN (ds.ValidatedBy IS NULL and dsv.Responsibleid is null) THEN 'Pendente de Validação'#(lf)        ELSE ISNULL(u.Name, '---')#(lf)    END AS 'Analisado por',#(lf)#(lf)#(tab)ISNULL(ISNULL (dsv.Responsibleid, ds.ValidatedBy), '00000000-0000-0000-0000-000000000000')  as 'Id_Validador',#(lf)#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN (ds.ValidatedBy = '00000000-0000-0000-0000-000000000000' and dsv.Responsibleid is null) THEN 'Sistema'#(lf)        WHEN dsv.Responsibleid =  '00000000-0000-0000-0000-000000000000' THEN 'Sistema'#(lf)#(tab)#(tab)WHEN u.Email like '%Atlas%'  THEN 'Atlas'#(lf)        WHEN ds.ValidatedBy IS NULL THEN 'Pendente de Validação'#(lf)        ELSE 'Cliente'#(lf)    END AS 'Time',#(lf)#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)    ISNULL(ISNULL(FORMAT(df.CreatedAt, 'dd/MM/yyyy HH:mm:ss'), FORMAT(df.UpdatedAt,  'dd/MM/yyyy HH:mm:ss')),FORMAT([ds].[UploadedAt], 'dd/MM/yyyy HH:mm:ss')) AS Data_Envio,#(lf)#(tab)ISNULL(FORMAT(dsv.Createdat, 'dd/MM/yyyy HH:mm:ss'), FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy HH:mm:ss')) AS Data_Análise,#(lf)#(tab)#(lf)#(lf)#(tab)CASE#(lf)            WHEN #(lf)                ISNULL(dsv.IsValid, Ds.IsValidated) = 1#(lf)            THEN#(lf)                'Aprovado'#(lf)            WHEN#(lf)                ISNULL(dsv.IsValid, ds.IsValidated) = 0#(lf)            THEN #(lf)                'Reprovado'#(lf)            WHEN#(lf)                ds.IsValidated IS NULL#(lf)            THEN #(lf)                'Aguardando Validação'#(lf)            ELSE#(lf)                'Pendente'#(lf)        END AS Status_Documentacao,#(lf)#(lf)#(lf)        ISNULL(dsv.id,ds.id) as 'Id_Reanálise',#(lf)#(lf)dsv.message#(lf)#(lf)#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)#(tab)INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    INNER JOIN [DocumentScheduleBuilding] as [dsb] WITH (NOLOCK) ON [dsb].[DocumentScheduleId] = [ds].[Id] and dsb.Removed = 0#(lf)    INNER JOIN [Building] AS [b] WITH (NOLOCK) ON  [b].[Id] = [dsb].[BuildingId] and b.Removed = 0#(lf)#(tab)--INNER JOIN [Category] AS [cat] WITH (NOLOCK) ON  [cat].[Id] = [c].[CategoryId]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    LEFT JOIN DocumentScheduleValidationLog AS dsv WITH(NOLOCK) ON dsv.DocumentScheduleId = ds.Id#(lf)#(tab)LEFT JOIN [User] AS u WITH(NOLOCK) ON u.Id = COALESCE(dsv.Responsibleid, ds.ValidatedBy)#(lf)#(tab)LEFT JOIN DocumentFile AS df WITH(NOLOCK) ON df.Id = dsv.DocumentFileId#(lf)    #(lf)#(lf)WHERE#(lf)      --COALESCE(dsv.CreatedAt, ds.ValidatedAt) >= @initialDate#(lf)  COALESCE(dsv.CreatedAt, ds.ValidatedAt) <  @finalDate#(lf)  AND ds.OrganizationId = @organizationId#(lf)  --AND (DS.Removed = 0 OR (DS.Removed = 1 AND IsValidated = 0))#(lf)        AND DS.UploadedAt IS NOT NULL#(lf)        AND DS.RequiresValidation = 1#(lf)        AND DS.CertificationId IS NULL#(lf)       -- AND DS.OrganizationId in (#(lf)        --    SELECT #(lf)         --       Id #(lf)          --  FROM #(lf)           --     Organization #(lf)            --WHERE ([Resource] & 4) = 4 #(lf)              --  AND [Resource] != 0#(lf)                --AND [Status] = 1#(lf)               -- AND Removed = 0#(lf)               -- AND GestaoScope != 0#(lf)      --  )#(lf)order by  #(lf)[ds].Id ,#(lf)ISNULL(ISNULL(FORMAT(df.CreatedAt, 'dd/MM/yyyy HH:mm:ss'), FORMAT(df.UpdatedAt,  'dd/MM/yyyy HH:mm:ss')),FORMAT([ds].[UploadedAt], 'dd/MM/yyyy HH:mm:ss')) ,#(lf)ISNULL(FORMAT(dsv.Createdat, 'dd/MM/yyyy HH:mm:ss'), FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy HH:mm:ss'))"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Prazo de Envio", type date}, {"Data_Envio", type datetime}, {"Data_Análise", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

