table 'Status do Fornecedores'
	lineageTag: 6f05e263-bb70-4969-84d3-7ffde8466f2a

	measure _Fornecedores_Quantidade_ = CALCULATE(COUNTROWS())
		formatString: 0
		lineageTag: 0bf7353f-ed22-4f3b-a3c1-cf45b2256c67

	column Fornecedor
		dataType: string
		lineageTag: 5dd34db0-fb29-463e-9b17-12779528562a
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 9f652e86-f3ac-465e-8c18-801bf4bd6570
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: e842513f-0f4d-486f-bb7e-ca5a15a64d0f
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 410b65d1-7933-4481-a644-0a0db0109ea1
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 333f8c72-8790-48ef-b0ca-e11039845f08
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: 634d6921-9bde-4152-bbc0-dc6559f448cf
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: e7b3f18d-6f84-4d45-8665-3a909f3c7789
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: 71fa4d5d-b4e7-48f2-b277-60970dae2888
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: 48c3fe02-4325-4793-95a6-b663c0f3dd0a
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: d329b84a-9b6d-4d19-831f-d9aaf93719fe
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: e295e3bc-65e5-401f-bed1-606c2ae106b2
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 49a29c92-42cd-4591-89ba-673e0b610894
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Total Docs'
		dataType: int64
		formatString: 0
		lineageTag: df8bff08-f30b-472d-ba72-afe2d8b2911f
		summarizeBy: sum
		sourceColumn: Total Docs

		annotation SummarizationSetBy = Automatic

	column 'Documentos entregues'
		dataType: int64
		formatString: 0
		lineageTag: 52f87da4-20d7-4e6f-b8f8-a4c365414bd4
		summarizeBy: sum
		sourceColumn: Documentos entregues

		annotation SummarizationSetBy = Automatic

	column 'Taxa de entrega'
		dataType: double
		lineageTag: 8650093a-5e14-4502-af3d-d98d0d8d2d5c
		summarizeBy: sum
		sourceColumn: Taxa de entrega

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Restrições
		dataType: string
		lineageTag: 62d20db8-bfb4-4f95-9823-20cf99f065ab
		summarizeBy: none
		sourceColumn: Restrições

		annotation SummarizationSetBy = Automatic

	column 'Docs pendentes com restrição de pgto'
		dataType: string
		lineageTag: 39fb96fc-f3fc-4454-855c-054d571a5802
		summarizeBy: none
		sourceColumn: Docs pendentes com restrição de pgto

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes'
		dataType: string
		lineageTag: e8f8215c-d42f-4173-9e0a-cc92c13bf800
		summarizeBy: none
		sourceColumn: Documentos pendentes

		annotation SummarizationSetBy = Automatic

	column 'N de Docs Pendentes'
		dataType: string
		lineageTag: 686d7942-bec7-46e5-9413-4e03863d54a3
		summarizeBy: none
		sourceColumn: N de Docs Pendentes

		annotation SummarizationSetBy = Automatic

	column 'Taxa de Pendência'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8504b944-ea55-4045-b3ca-74433987ce21
		summarizeBy: sum
		sourceColumn: Taxa de Pendência

		annotation SummarizationSetBy = Automatic

	column 'Status do Fornecedor'
		dataType: string
		lineageTag: a7f0046b-d5f7-4c9b-a022-d8ac4a92a4cf
		summarizeBy: none
		sourceColumn: Status do Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Chave Gestores'
		dataType: string
		lineageTag: 66d62c6a-99ba-4895-9da0-36941e5a7be8
		summarizeBy: none
		sourceColumn: Chave Gestores

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 491b78ea-6ab5-443d-8043-a152271c4f4d
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Atividades do contrato'
		dataType: string
		lineageTag: 329bcc0f-30aa-4461-bd00-0122d1613906
		summarizeBy: none
		sourceColumn: Atividades do contrato

		annotation SummarizationSetBy = Automatic

	column 'Qtde pessoas contratadas'
		dataType: string
		lineageTag: 4a5cccca-5fcd-4b8d-b325-1ca26c3c94be
		summarizeBy: none
		sourceColumn: Qtde pessoas contratadas

		annotation SummarizationSetBy = Automatic

	column 'Qtde funcionários mobilizados'
		dataType: string
		lineageTag: 21d0f9ef-6ea0-4f3c-a209-568399e71af2
		summarizeBy: none
		sourceColumn: Qtde funcionários mobilizados

		annotation SummarizationSetBy = Automatic

	column (_Status_Contrato) = ```
			
			IF('Status do Fornecedores'[Vigência do Contrato Inicio] > TODAY(), 
			    "Contrato Futuro", 
			    IF('Status do Fornecedores'[Vigência do Contrato Fim] < TODAY(), 
			        "Contrato Inativo", 
			        "Contrato Ativo"
			    )
			)
			
			```
		lineageTag: 20b36d70-5087-44e7-ad27-3fbe2f4fb5c9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Documentos em análise'
		dataType: string
		lineageTag: f72b5eef-d905-4917-9d2a-8cbafe44cbbb
		summarizeBy: none
		sourceColumn: Documentos em análise

		annotation SummarizationSetBy = Automatic

	column (_Grau_Risco_M) =
			IF(
			    'Status do Fornecedores'[Contratos  (Contratos).Grau de Risco - Trabalhista] = "Não Monitorado", "Não Monitorado", 'Status do Fornecedores'[Status do Fornecedor])
		lineageTag: 1c7bf0c3-c430-4b75-b7c2-1eaf58ad7b16
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: ed1fb31c-80f9-4a74-9947-ecb3af23569c
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column 'Contratos  (Contratos).Grau de Risco - Trabalhista'
		dataType: string
		lineageTag: dc7d7de3-25c7-4c05-abf0-1a3082fcd9fd
		summarizeBy: none
		sourceColumn: Contratos  (Contratos).Grau de Risco - Trabalhista

		annotation SummarizationSetBy = Automatic

	column Personalizar
		dataType: string
		lineageTag: 29ad04fb-3052-4b62-9fe7-07097cec6475
		summarizeBy: none
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

	column 'Status GS' = ```
			
			
			VAR PEND = 'Status do Fornecedores'[Taxa de Pendência]
			
			VAR RIS = 'Status do Fornecedores'[(_Grau_Risco_M)]
			
			VAR DOC_PEND = 'Status do Fornecedores'[Documentos pendentes]
			
			VAR DOC_ANA = 'Status do Fornecedores'[Documentos em análise]
			
			VAR DOCS = 'Status do Fornecedores'[Total Docs]
			
			RETURN IF(RIS = "Não Monitorado", "Habilitado",
			            IF(DOCS = 0, "Habilitado",
			            IF(PEND = 0, "Habilitado", 
			            IF(DOC_PEND = DOC_ANA,"Habilitado com Docs em Análise",
			            IF(PEND=1,"Não Entregue","Não Habilitado")
			
			    ))))
			```
		lineageTag: fb0eb00b-ed9e-46d1-90bb-4079672d4523
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Status Atlas' =
			
			VAR RIS      = 'Status do Fornecedores'[(_Grau_Risco_M)]
			VAR rawPend  = 'Status do Fornecedores'[Taxa de Pendência]
			VAR DOCS = 'Status do Fornecedores'[Total Docs]
			VAR PEND     = IF(NOT ISBLANK(rawPend), IF(rawPend > 1, rawPend / 100, rawPend))
			VAR faixa =
			    SWITCH(
			        TRUE(),
			        ISBLANK(PEND), BLANK(),
			        PEND <= 0.2,     " 80–100%"
			    )
			VAR DOC_PEND = 'Status do Fornecedores'[Documentos pendentes]
			VAR DOC_ANA = 'Status do Fornecedores'[Documentos em análise]
			RETURN
			SWITCH(
			    TRUE(),
			    RIS = "Não Monitorado", "Habilitado",
			    DOCS = 0, "Habilitado",
			    PEND = 0,               "Habilitado",
			    IF(DOC_PEND = DOC_ANA,"Não Habilitado - Possui documentos em análise",
			        IF(PEND=1,"Não Habilitado - Não entregou nenhum documento",  IF(PEND <= 0.2,"Habilitado com Ressalvas - Conforme" & faixa,"Não Habilitado")
			)))
		lineageTag: 85419b73-ac7a-41bf-8079-34e6442a9fd0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quantidade de efetivos'
		dataType: int64
		formatString: 0
		lineageTag: 9d0a3a12-af01-4a28-b026-8da0db7e75de
		summarizeBy: sum
		sourceColumn: Quantidade de efetivos

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: 284ec177-78f0-4786-9088-47d65a721d48
		summarizeBy: sum
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	column 'Contratos  (Contratos).Nome do Gestor do Contrato'
		dataType: string
		lineageTag: d076f64f-4f1e-470a-931e-75d69fd32a18
		summarizeBy: none
		sourceColumn: Contratos  (Contratos).Nome do Gestor do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência do Contrato Inicio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a61b298-b634-4cfe-899b-62830a53459c
		summarizeBy: none
		sourceColumn: Vigência do Contrato Inicio

		variation Variation
			isDefault
			relationship: 3af10deb-6f3d-45c5-9842-937c09f4b125
			defaultHierarchy: LocalDateTable_b8e4fb75-77a8-4e73-8427-67149fa7f929.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência do Contrato Fim'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e31e5232-0d53-4d64-8e21-de9c205ef6a8
		summarizeBy: none
		sourceColumn: Vigência do Contrato Fim

		variation Variation
			isDefault
			relationship: 624077cc-e86c-4467-9423-62e12a866531
			defaultHierarchy: LocalDateTable_0b711295-3989-4f2c-88a5-0c18bdb4de56.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Column1
		dataType: string
		lineageTag: 2cbdd093-4c7d-4dae-9f5e-45697eb70c5c
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column28
		dataType: string
		lineageTag: b6f2ff3d-c2e0-49d7-a0c6-320fba88f4bd
		summarizeBy: none
		sourceColumn: Column28

		annotation SummarizationSetBy = Automatic

	partition 'Status do Fornecedores' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://adminatlasinovacoescom.sharepoint.com/:x:/r/sites/DiretrioPadro/Documentos%20Compartilhados/Relat%C3%B3rios/Dados/02.%20Externo/01.%20AFM%20Gest%C3%A3o/GSInima/08%20-%20Power%20BI/2026/1%20-%20Janeiro/(Rec)Fornecedores%20-%20260106113239.xlsx")),
				    #"Status de fornecedores_sheet" = Fonte{[Item="Status de fornecedores",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Status de fornecedores_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"Qtde funcionários cadastrados", "Quantidade de efetivos"}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Renomeadas3", each not List.IsEmpty(FilterNullAndWhitespace(Record.FieldValues(_)))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"Nome", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Razão Social do Contrato", type text}, {"CNPJ do Contrato", type text}, {"Tipo de Fornecedor", type text}, {"Nome Fantasia do Subcontrato", type text}, {"Razão Social do Subcontrato", type text}, {"CNPJ do Subcontrato", type text}, {"Tipo de Contratação", type text}, {"Número do Pedido", type text}, {"Quantidade de efetivos", Int64.Type}, {"Total Docs", Int64.Type}, {"Documentos entregues", Int64.Type}, {"Taxa de entrega", type number}, {"Restrições", type text}, {"Docs pendentes com restrição de pgto", type text}, {"Documentos pendentes", type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "N de Docs Pendentes", each [Total Docs] - [Documentos entregues]),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Personalização Adicionada",{"Nome", "Razão social", "CNPJ", "Categoria", "Unidade", "Razão Social do Contrato", "CNPJ do Contrato", "Tipo de Fornecedor", "Nome Fantasia do Subcontrato", "Razão Social do Subcontrato", "CNPJ do Subcontrato",  "Tipo de Contratação", "Número do Pedido", "Quantidade de efetivos", "Total Docs", "Documentos entregues", "N de Docs Pendentes", "Taxa de entrega", "Restrições", "Docs pendentes com restrição de pgto", "Documentos pendentes"}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Colunas Reordenadas", "Taxa de Pendência", each if [N de Docs Pendentes]= 0 then 0
				else [N de Docs Pendentes]/[Total Docs]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Taxa de Pendência", Percentage.Type}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado1", "Status do Fornecedor", each if [Taxa de Pendência] = 1 then "Não Entregue" else if [Taxa de Pendência] >= 0.8 then "Não Habilitado" else if [Taxa de Pendência] >= 0 then "Habilitado" else "Sem Classificação"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada2",{{"Nome", "Fornecedor"}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Colunas Renomeadas", "Chave Gestores", each [Fornecedor]&[Categoria]),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Personalização Adicionada3",{{"Razão social", Text.Upper, type text}}),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Texto em Maiúscula", "Chave", each [Fornecedor]&[CNPJ]&[Unidade]&[Categoria]&[Número do Pedido]),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Personalização Adicionada4", "Vigência do Contrato", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Vigência do Contrato.1", "Vigência do Contrato.2"}),
				    #"Colunas Renomeadas4" = Table.RenameColumns(#"Dividir Coluna por Delimitador",{{"Vigência do Contrato.1", "Início da vigência"}, {"Vigência do Contrato.2", "Fim da vigência"}}),
				    #"Texto em Maiúscula1" = Table.TransformColumns(#"Colunas Renomeadas4",{{"Fornecedor", Text.Upper, type text}}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Texto em Maiúscula1",{{"Início da vigência", "Vigência do Contrato Inicio"}, {"Fim da vigência", "Vigência do Contrato Fim"}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Vigência do Contrato Inicio", type date}, {"Vigência do Contrato Fim", type date}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado2", each true),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"Nome Fantasia do Subcontrato"}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Colunas Removidas", "Índice", 0, 1, Int64.Type),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Índice Adicionado", {"Número do Pedido"}, Contratos, {"N° do Pedido"}, "Contratos  (Contratos)", JoinKind.LeftOuter),
				    #"Contratos  (Contratos) Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Contratos  (Contratos)", {"Grau de Risco - Trabalhista", "Nome do Gestor do Contrato"}, {"Contratos  (Contratos).Grau de Risco - Trabalhista", "Contratos  (Contratos).Nome do Gestor do Contrato"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Contratos  (Contratos) Expandido", "Personalizar", each if [#"Contratos  (Contratos).Grau de Risco - Trabalhista"] = "Não Monitorado" then "Não Monitorado" else if [Taxa de Pendência] = 1 then "Não Entregue" else if [Taxa de Pendência] >= 0.8 then "Não Habilitado" else if [Taxa de Pendência] >= 0 then "Habilitado" else null),
				    #"Duplicatas Removidas" = Table.Distinct(#"Coluna Condicional Adicionada", {"Índice"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Duplicatas Removidas",null,"Não classificado",Replacer.ReplaceValue,{"Contratos  (Contratos).Grau de Risco - Trabalhista"})
				in
				    #"Valor Substituído"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

