table 'Risco Críticos'
	lineageTag: 28da7496-b732-4124-8cd5-af852521c735

	column Documento
		dataType: string
		lineageTag: 5bbed6a2-acac-4939-aff4-d94047cf3f94
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: 4c8f45fa-250b-4071-ad17-8773aac3422a
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: 1bdfab2a-f03e-4888-ab52-013b03fcde63
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Id do Contrato'
		dataType: string
		lineageTag: db44cb82-78cb-4c40-bab2-3a3046af2038
		summarizeBy: none
		sourceColumn: Id do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 99143e2e-ca15-4d5d-b059-bb9ef512ba10
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 95881e4d-f739-4b58-a4b5-139fc3123846
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 61d0fc7f-6ce4-4bc0-8ff1-be9f66d60417
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 2d648f16-feef-4b28-9c9c-baaeb27ab172
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: d331f751-8b03-4824-89e5-5e813269dcb0
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 183b3671-5004-4619-bc10-11854c6b0d8d
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6db42522-3fa5-42c1-b866-f97cf9c8e5f3
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: 096aebfe-2f47-4bb6-8c58-8802bbc41455
			defaultHierarchy: LocalDateTable_a558b15d-c929-4a13-bcee-ec54634d356b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b2e001d4-78db-429b-8a4c-137456c9c715
		summarizeBy: none
		sourceColumn: Data de Envio

		variation Variation
			isDefault
			relationship: 6827076d-59b2-4efa-aca3-c0e38ab573bc
			defaultHierarchy: LocalDateTable_7948ef15-511e-47c8-b186-dce46c7e3626.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data da Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3b2547b-2e80-41a5-b00a-9396721d05a9
		summarizeBy: none
		sourceColumn: Data da Análise

		variation Variation
			isDefault
			relationship: 55fb5194-0d06-4c31-bec7-5196c69a4ac6
			defaultHierarchy: LocalDateTable_18cd0e03-052d-4494-92cd-99c638b5e97a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 06ba8435-4eb9-49b8-a0ae-4ac95bd5fb1b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Distribuidora
		dataType: string
		lineageTag: 6923b47c-c791-43b2-847a-f1ffd776c2c5
		summarizeBy: none
		sourceColumn: Distribuidora

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: fa2f546f-aab0-4bfd-b066-1825f9a5b3d8
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column 'Status (Reclassificado)'
		dataType: string
		lineageTag: c964a076-e147-4d26-8e64-f0dddaea6648
		summarizeBy: none
		sourceColumn: Status (Reclassificado)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0752243e-8986-4428-a446-b25955509e9d
		summarizeBy: none
		sourceColumn: Competência

		variation Variation
			isDefault
			relationship: f04f05f9-430b-428f-bdbd-e9070647baaa
			defaultHierarchy: LocalDateTable_b61cefd5-38b9-44f0-94a6-115fdf0056c2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Chave de Duplicada'
		dataType: string
		lineageTag: 2b566337-c722-4eb1-99f6-be36cad99fdd
		summarizeBy: none
		sourceColumn: Chave de Duplicada

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: b7b09667-3869-4189-850b-02940d7730fb
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Status de Indicador'
		dataType: string
		lineageTag: a8f20e1e-6b22-4032-875c-212a3336800d
		summarizeBy: none
		sourceColumn: Status de Indicador

		annotation SummarizationSetBy = Automatic

	column 'Status de Janela'
		dataType: string
		lineageTag: c1caa5f2-bc8f-45a1-adcb-59cdb75117ae
		summarizeBy: none
		sourceColumn: Status de Janela

		annotation SummarizationSetBy = Automatic

	column 'Documento Empresa ou Funcionário'
		dataType: string
		lineageTag: 0912ac76-b989-4756-a812-8b0c1b871c72
		summarizeBy: none
		sourceColumn: Documento Empresa ou Funcionário

		annotation SummarizationSetBy = Automatic

	column Chave_Risco
		dataType: string
		lineageTag: 3e1e0528-122b-408c-9213-23b706870c60
		summarizeBy: none
		sourceColumn: Chave_Risco

		annotation SummarizationSetBy = Automatic

	column 'Mês/Ano - Compete'
		dataType: string
		lineageTag: d42ca2a4-dea9-4d67-9e83-a2373f67f35b
		summarizeBy: none
		sourceColumn: Mês/Ano - Compete

		annotation SummarizationSetBy = Automatic

	column Chave_Duplicada_Envio
		dataType: string
		lineageTag: dac3fb25-6d04-4bbe-8793-6e5394f5b90f
		summarizeBy: none
		sourceColumn: Chave_Duplicada_Envio

		annotation SummarizationSetBy = Automatic

	column 'Vigência de Contrato'
		dataType: string
		lineageTag: 14dc9cbd-4c38-4293-b768-006709fc0e98
		summarizeBy: none
		sourceColumn: Vigência de Contrato

		annotation SummarizationSetBy = Automatic

	partition 'Risco Críticos' = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = getdate();#(lf)DECLARE @organizationId uniqueidentifier = '464e9a8a-8388-4b5e-9109-a2d18edd631a';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = getdate();#(lf)#(lf)WITH ContractBuildings AS (#(lf)    SELECT#(lf)        [c].[Id] AS ContractId,#(lf)        STRING_AGG([b].[TradeName], ', ') AS Buildings#(lf)    FROM#(lf)        [Contract] AS [c]#(lf)        INNER JOIN [Building] AS [b] ON [c].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [c].[Removed] = 0#(lf)        AND [b].[Removed] = 0#(lf)    GROUP BY#(lf)        [c].[Id]#(lf)),#(lf)ContractCategories AS (#(lf)    SELECT#(lf)        [c].[Id] AS ContractId,#(lf)        STRING_AGG([cat].[Name], ', ') AS Categories#(lf)    FROM#(lf)        [Contract] AS [c]#(lf)        INNER JOIN [Category] AS [cat] ON [c].[CategoryId] = [cat].[Id]#(lf)    WHERE#(lf)        [c].[Removed] = 0#(lf)    GROUP BY#(lf)        [c].[Id]#(lf))#(lf)#(lf)SELECT DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)#(lf)    CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)        WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)#(lf)    [ds].[Id] AS [DocumentScheduleId],#(lf)    [c].[Id] AS [Id_Contrato],#(lf)#(lf)    CASE WHEN [c].[OrderNumber] IS NULL THEN '---' ELSE [c].[OrderNumber] END AS [Número do Pedido],#(lf)#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN '---'#(lf)        ELSE#(lf)            CASE#(lf)                WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)                WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)                WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)                WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)                WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)                WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)                WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)                WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)                WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)                ELSE 'Nenhum'#(lf)            END#(lf)    END AS [Tipo de Contrato],#(lf)#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN c.ValidityInitial > GETDATE() THEN 'Vigência Futura'#(lf)#(tab)#(tab)WHEN c.ValidityFinal < GETDATE() THEN 'Vigência Finalizada'#(lf)#(tab)#(tab)ELSE 'Vigente'#(lf)#(tab)END AS 'Vigência de Contrato',#(lf)#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    [bc].[CompanyName] AS [Razão Social],#(lf)    dbo.FormatCNPJ(bc.Document) as [CNPJ],#(lf)#(lf)    ISNULL([er].[Name], '---') AS [Funcionário],#(lf)#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(tab)FORMAT([ds].[UploadedAt], 'dd/MM/yyyy HH:mm:ss') AS [Data de Envio],#(lf)#(lf)    FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)#(lf)    CASE#(lf)        WHEN [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL) THEN 'Atrasado'#(lf)        WHEN [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL) THEN 'Próxima Entrega'#(lf)        WHEN [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] = 0) THEN 'Atrasado Recusado'#(lf)        WHEN [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] = 0) THEN 'Próxima Entrega Recusado'#(lf)        WHEN [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL THEN 'Em Análise'#(lf)        WHEN [ds].[UploadedAt] IS NOT NULL AND ([ds].[RequiresValidation] = 0 OR [ds].[IsValidated] = 1) THEN 'Aprovado'#(lf)        ELSE '--'#(lf)    END AS [Status],#(lf)#(lf)#(lf)    ISNULL(cb.Buildings, '---') AS [Unidade(s)],#(lf)    ISNULL(cc.Categories, '---') AS [Categoria(s)]#(lf)#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        [c].[Removed] = 0#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            (#(lf)                ([ds].[ContractId] IS NOT NULL AND [ds].[ContractId] = [c].[Id])#(lf)                OR [ds].[ContractId] IS NULL#(lf)            )#(lf)            OR (#(lf)                (#(lf)                    ([d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                     OR ([d].[OrderNumberInclusiveOrExclusive] = 1 AND EXISTS (#(lf)                            SELECT 1 FROM STRING_SPLIT([d].[OrderNumber], ';') WHERE value = [c].[OrderNumber]#(lf)                        ))#(lf)                     OR ([d].[OrderNumberInclusiveOrExclusive] = 0 AND NOT EXISTS (#(lf)                            SELECT 1 FROM STRING_SPLIT([d].[OrderNumber], ';') WHERE value = [c].[OrderNumber]#(lf)                        ))#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([ds].[ContractSetId] IS NOT NULL AND [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                    OR [ds].[ContractSetId] IS NULL#(lf)                )#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    OR NOT EXISTS (#(lf)                        SELECT 1 FROM [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                        WHERE [dsb].[DocumentScheduleId] = [ds].[Id] AND [dsb].[Removed] = 0#(lf)                    )#(lf)                    OR EXISTS (#(lf)                        SELECT 1 FROM [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                        WHERE [dsb].[DocumentScheduleId] = [ds].[Id] AND [dsb].[BuildingId] = [c].[BuildingId] AND [dsb].[Removed] = 0#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    OR NOT EXISTS (#(lf)                        SELECT 1 FROM [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                        WHERE [dsc].[DocumentScheduleId] = [ds].[Id] AND [dsc].[Removed] = 0#(lf)                    )#(lf)                    OR EXISTS (#(lf)                        SELECT 1 FROM [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                        WHERE [dsc].[DocumentScheduleId] = [ds].[Id] AND [dsc].[CategoryId] = [c].[CategoryId] AND [dsc].[Removed] = 0#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE())#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE())#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    ([d].[DeliveryKind] <> 0 AND [d].[DeliveryKind] <> 1)#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0 AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0 AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0 AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([er].[Id] IS NOT NULL AND [c].[BranchCompanyId] = [bc].[Id] AND [ds].[Kind] = 5#(lf)                        AND EXISTS (#(lf)                            SELECT 1 FROM [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                            AND [erc].[ContractId] = [c].[Id]#(lf)                            AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                    OR ([ds].[EmployeeRegisterId] IS NULL AND [ds].[ContractId] IS NULL AND [ds].[Kind] = 1)#(lf)                    OR ([ds].Kind = 4)#(lf)                )#(lf)            )#(lf)        )#(lf)    )#(lf)#(lf)LEFT JOIN ContractBuildings AS cb ON cb.ContractId = c.Id#(lf)LEFT JOIN ContractCategories AS cc ON cc.ContractId = c.Id#(lf)#(lf)WHERE#(lf)    [ds].[Removed] = 0#(lf)    AND [d].[Removed] = 0#(lf)    AND [d].[Archived] = 0#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)   AND [ds].[Name] iN (#(lf)        'FGTS - Comprovante de pagamento',#(lf)        'Comprovante de Recolhimento',#(lf)        'DARF – Documento de Arrecadação de Receitas Federais',#(lf)        'Comprovante Bancário de Pagamento de Salários',#(lf)        'FGTS - Guia de recolhimento (boleto)',#(lf)        'FGTS - RE - Relação de Empregados/Trabalhadores',#(lf)        'Relatório da Declaração Completa – DCTFWeb',#(lf)        'Folha de Pagamento Mensal Analítica',#(lf)        'Recibo de Entrega da Declaração de Débitos e Créditos Tributários Federais Previdenciários – DCTFWeb'#(lf)    )#(lf)"]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(Fonte, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Número do Pedido", type any}, {"Tipo de Contrato", type text}, {"Razão Social", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Status (Reclassificado)", each if Text.Contains([Status], "Recusado") then "Enviado" else if [Status] = "Aprovado" then "Enviado" else if [Status] = "Em Análise" then "Enviado" else if [Status] = "Atrasado" then "Não Enviado" else null),
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Condicional Adicionada", "Competência", each Date.AddMonths([Prazo de Envio],-1)),
				    #"Coluna Mesclada Inserida2" = Table.AddColumn(#"Personalização Adicionada", "Chave de Duplicada", each Text.Combine({[Documento], [Id_Contrato],[Funcionário], Text.From([Competência], "pt-BR")}, ""), type text),
				    #"Linhas Classificadas1" = Table.Buffer(Table.Sort(#"Coluna Mesclada Inserida2",{{"Data de Envio", Order.Descending}})),
				    #"Duplicatas Removidas" = Table.Distinct(#"Linhas Classificadas1", {"Chave de Duplicada"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Duplicatas Removidas","NULL","",Replacer.ReplaceValue,{"Data de Envio"}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Valor Substituído1", "Data de Envio", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Data de Envio.1", "Data de Envio.2"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Dividir Coluna por Delimitador",{"Data de Envio.2"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"Data de Envio.1", "Data de Envio"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Competência", type date}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Tipo Alterado1",{{"Número do Pedido", type text}, {"Data de Envio", type date}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado2","---","",Replacer.ReplaceValue,{"Data da Análise"}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Valor Substituído",{{"Data da Análise", type date}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado3", "Chave", each [Razão Social]&[#"Categoria(s)"]&[#"Unidade(s)"]),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Personalização Adicionada3",{{"Id_Contrato", "Id do Contrato"}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Colunas Renomeadas1", "Status de Indicador", each if [Data de Envio] = null then
				        "Não Enviado"
				    else
				        let
				            PrazoMes = Date.Month([Prazo de Envio]),
				            PrazoAno = Date.Year([Prazo de Envio]),
				            MesSeguinte = if PrazoMes = 12 then 1 else PrazoMes + 1,
				            AnoSeguinte = if PrazoMes = 12 then PrazoAno + 1 else PrazoAno, // Ajuste para avançar o ano apenas em dezembro
				            DataLimiteJanela25 = #date(PrazoAno, PrazoMes, 25), // Dia 25 do mês do prazo
				            DataLimiteJanela11 = #date(AnoSeguinte, MesSeguinte, 11) // Dia 11 do próximo mês
				        in
				            if [Data de Envio] <= DataLimiteJanela25 then
				                "Enviado na Janela 25"
				            else if [Data de Envio] <= DataLimiteJanela11 then
				                "Enviado na Janela 11"
				            else
				                "Enviado Atrasado"),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Personalização Adicionada1", "Status de Janela", each if [Status de Indicador] = "Enviado na Janela 25" then "Enviado no Prazo" else if [Status de Indicador] <> "Não Enviado" then "Enviado Atrasado" else "Não Enviado"),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Personalização Adicionada2", each ([Razão Social] <> "Ambiente Teste Fornecedor")),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Linhas Filtradas1",{{"Unidade(s)", "Distribuidora"}}),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Colunas Renomeadas2", "Documento Empresa ou Funcionário", each if [Funcionário] = "---" 
				    then "Empresa"
				    else "Funcionário"),
				    #"Início do Mês Inserido" = Table.AddColumn(#"Personalização Adicionada4", "Início do Mês", each Date.StartOfMonth([Competência]), type date),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Início do Mês Inserido", "Chave_Risco", each Text.Combine({[Id do Contrato], Text.From([Início do Mês], "pt-BR")}, ""), type text),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Coluna Mesclada Inserida",{"Início do Mês"}),
				    #"Personalização Adicionada5" = Table.AddColumn(#"Colunas Removidas1", "Mês/Ano - Compete", each Date.ToText([Competência], "MM/yyyy")),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Personalização Adicionada5", "Chave_Duplicada_Envio", each Text.Combine({[Documento], [Id do Contrato],[Funcionário], [#"Mês/Ano - Compete"]}, ""), type text),
				    #"Linhas Classificadas" = Table.Buffer(Table.Sort(#"Coluna Mesclada Inserida1",{{"Status", Order.Ascending},{"Prazo de Envio", Order.Descending}})),
				    #"Duplicatas Removidas1" = Table.Distinct(#"Linhas Classificadas", {"Chave_Duplicada_Envio"})
				in
				    #"Duplicatas Removidas1"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

