table 'Relatório de Fornecedores'
	lineageTag: bd36dda4-9e1c-48a8-b898-edaeba750b47

	measure '(Total) Documentos' = CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]))
		formatString: #,0
		lineageTag: d80a563c-104c-4f6c-b367-9d0d98c3bc92

	measure '(%) Aderência' = ```
			VAR TotalDocs = [(Total) Documentos]
			VAR DocsSemAtraso = CALCULATE([(Total) Documentos], 'Relatório de Fornecedores'[Status] <> "Atrasado")  
			RETURN  
			IF(TotalDocs > 0 && DocsSemAtraso = 0, 0,  (DocsSemAtraso / TotalDocs))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 274d0687-c363-44d1-8067-2436ad7d3490

	measure '(%) Conformidade' = ```
			
			VAR TotalDocs = [(Total) Documentos]
			VAR DocsAprovados = CALCULATE([(Total) Documentos], 'Relatório de Fornecedores'[Status] = "Aprovado")
			RETURN  
			IF(TotalDocs > 0, (DocsAprovados / TotalDocs+0), IF(TotalDocs > 0 && (DocsAprovados=0 || DocsAprovados=BLANK()),0,BLANK()))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ef85822d-3642-4e4f-9b1c-da2ead9a9033

	measure '(Não Enviados) Documentos' = CALCULATE([(Total) Documentos], 'Relatório de Fornecedores'[Status] = "Atrasado")
		formatString: #,0
		lineageTag: f79432f0-f02f-475e-8b58-6a610766da4e

	measure '(Recusados) Documentos' = CALCULATE([(Total) Documentos], 'Relatório de Fornecedores'[Status] = "Recusado")
		formatString: 0
		lineageTag: 348d3beb-24a8-4d9c-be3d-911a7e88d98b

	measure '(Máximo) Valor' = 1
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 9e2f550c-ec4a-4d3c-8e83-9962f763b3df

	measure '(Aprovados) Documentos' = CALCULATE([(Total) Documentos], 'Relatório de Fornecedores'[Status] = "Aprovado")+0
		formatString: #,0
		lineageTag: 30830e2e-a616-491a-a544-367f102785a7

	measure '(Peso3) Quantidade' = CALCULATE([(Total) Documentos], 'Relatório de Fornecedores'[Peso] = 3)
		formatString: 0
		lineageTag: 09e3b88e-4694-40b2-87eb-ec0245967784

	measure '(Peso1) Quantidade' = CALCULATE([(Total) Documentos], 'Relatório de Fornecedores'[Peso] = 1)
		formatString: 0
		lineageTag: 2d157e27-c6c2-4687-8ee6-f73fa04db76c

	measure '(%)Peso 1' =
			
			VAR PESO1 = CALCULATE([(Peso1) Quantidade],
			      'Relatório de Fornecedores'[Status] <> "Aprovado")
			VAR PESO3 = CALCULATE([(Peso3) Quantidade])
			VAR QUANT1 = [(Peso1) Quantidade]
			
			
			RETURN
			(IF(PESO3<1,
			    (PESO1/QUANT1)+0,
			    (((1/4)*PESO1)/QUANT1)))+ 0
		lineageTag: d718c0be-a7c5-4278-92d0-6afa08c67d2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '(%)Peso 3' =
			
			VAR PESO3 = CALCULATE([(Peso3) Quantidade],
			       'Relatório de Fornecedores'[Status] <> "Aprovado")
			VAR PESO1 = CALCULATE([(Peso1) Quantidade])
			VAR QUANT3 = [(Peso3) Quantidade]
			
			
			RETURN
			(IF(PESO1<1,
			    (PESO3/QUANT3)+0,
			    (((3/4)*PESO3)/QUANT3)))+ 0
		lineageTag: b38052f0-bf94-4da8-9ec1-61860517057d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '(%) Risco Crítico' =
			
			VAR PESO1 = [(%)Peso 1]
			VAR PESO3 = [(%)Peso 3]
			
			RETURN PESO1 + PESO3
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4346657c-8bf1-430e-98e7-2375fdfc4cfd

	measure 'Classificação Risco' = ```
			
			SWITCH(
			    TRUE(), 
			    [(%) Risco Crítico] < 0.25, "RISCO BAIXO",
			    [(%) Risco Crítico] < 0.50, "RISCO MÉDIO",
			    [(%) Risco Crítico] < 0.75, "RISCO ALTO",
			    "RISCO CRÍTICO"
			)
			
			```
		lineageTag: 67eebf14-05a2-4af8-b182-071b62b4e1a2

	measure #Cores = ```
			
			SWITCH(
			    TRUE(), 
			    [(%) Risco Crítico] < 0.25, "#7AB68E",
			    [(%) Risco Crítico] < 0.50, "#E1C233",
			    [(%) Risco Crítico] < 0.75, "#FB9B00",
			    [(%) Risco Crítico] <= 1,"#AB0000"
			)
			
			```
		lineageTag: ce07ef01-c5c8-4461-b40a-3838bf4ec1ed

	measure '(Atrasados) Quantidade' =
			CALCULATE(DISTINCTCOUNT('Relatório de Fornecedores'[DocumentScheduleId]),
			'Relatório de Fornecedores'[Status] <> "Atrasado")
		formatString: 0
		lineageTag: 35185135-922a-4c80-aff0-786db263660f

	column Documento
		dataType: string
		lineageTag: 65a77af9-9e56-40f3-8be3-b3076e3024e2
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: fe049fa9-3e29-4da9-b5e8-53c4dbc10c1b
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: 78ef8008-f98a-4e64-bc3b-34c8876d0365
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 3cb913a7-2252-4a58-8be3-3c3ff1e5cc3e
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: ea3e9fb2-5165-4cad-a782-aa92740f51e1
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 746d961b-a76d-477f-86e0-ab91fcbb19f6
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 2b8800ed-c333-4da9-8753-586492cdb7be
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: a242dbff-1120-4127-9dff-5c75dc2fcf53
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 0a1ea2d6-14c3-40e2-9e25-638be7f584ea
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 19750ebd-a735-4971-80ff-b4a5889ac04c
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: 4407bd7e-daad-4aa7-82ba-42422f153171
			defaultHierarchy: LocalDateTable_47db3005-3824-49b3-b21b-8f9c12f24f93.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Envio'
		dataType: string
		lineageTag: 5cae455b-ea5b-445b-879a-e6079aacdf7c
		summarizeBy: none
		sourceColumn: Data de Envio

		annotation SummarizationSetBy = Automatic

	column 'Data da Análise'
		dataType: string
		lineageTag: 51f0f1fe-eb64-4122-8d9d-27fb1b40ca7b
		summarizeBy: none
		sourceColumn: Data da Análise

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: a28bdc7b-1bdc-4e3b-8daa-3a449cdc976a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: bbc6eb25-ed57-4964-b3bc-358ae622c880
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: Long Date
		lineageTag: 378c993f-69a2-43e7-8a85-868a16b51417
		summarizeBy: none
		sourceColumn: Competência

		variation Variation
			isDefault
			relationship: 618a0209-21db-4f25-9bb8-982851bb7348
			defaultHierarchy: LocalDateTable_5eb8392d-9a6d-4e10-8ac9-ca9d3d28df16.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade(s)
		dataType: string
		lineageTag: 638bca7b-e85c-4af9-af7f-b636a5a0843d
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column 'Staus de Envio'
		dataType: string
		lineageTag: b02cc4b9-c540-4777-be29-55feacb0b161
		summarizeBy: none
		sourceColumn: Staus de Envio

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Documento'
		dataType: string
		lineageTag: 2f477568-e8ab-4389-9bf6-f96e7dff813d
		summarizeBy: none
		sourceColumn: Tipo de Documento

		annotation SummarizationSetBy = Automatic

	column Peso = LOOKUPVALUE(Pesos[Peso],Pesos[Documentos],'Relatório de Fornecedores'[Documento])
		formatString: 0
		lineageTag: 70177145-dfc1-4f30-94a1-4178299e1985
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Relatório de Fornecedores' = m
		mode: import
		source =
				let
				   Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = CAST(EOMONTH(GETDATE(), -1) AS DATETIME) + '23:59:59';#(lf)DECLARE @organizationId uniqueidentifier = '3d9bc20b-b80d-4118-85bf-48bb22b13535';#(lf)DECLARE @initialDate datetime2 = '2024-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = CAST(EOMONTH(GETDATE(), -1) AS DATETIME) + '23:59:59';#(lf)#(lf)#(lf)WITH DocumentScheduleBuildings AS (#(lf)    SELECT#(lf)        [dsb].[DocumentScheduleId],#(lf)        STRING_AGG(CAST([b].[TradeName] as nvarchar(MAX)), ', ') AS [Buildings]#(lf)    FROM#(lf)        [DocumentScheduleBuilding] AS [dsb]#(lf)        INNER JOIN [Building] AS [b] ON [dsb].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [dsb].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsb].[DocumentScheduleId]#(lf)),#(lf)DocumentScheduleCategories AS (#(lf)    SELECT#(lf)        [dsc].[DocumentScheduleId],#(lf)        STRING_AGG(CAST([c].[Name] as nvarchar(MAX)), ', ') AS [Categories]#(lf)    FROM#(lf)        [DocumentScheduleCategory] AS [dsc]#(lf)        INNER JOIN [Category] AS [c] ON [dsc].[CategoryId] = [c].[Id]#(lf)    WHERE#(lf)        [dsc].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsc].[DocumentScheduleId]#(lf))#(lf)SELECT#(lf)    DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)    [ds].Id AS [DocumentScheduleId],#(lf)#(tab) CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)        ELSE 'Desmobilização'#(lf)    END AS 'Tipo do documento',#(lf)    CASE#(lf)        WHEN [c].[OrderNumber] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [c].[OrderNumber]#(lf)    END AS [Número do Pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        CASE#(lf)            WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)            WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)            WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)            WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)            WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)            WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)            WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)            WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)            WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)            ELSE 'Nenhum'#(lf)        END#(lf)    END AS [Tipo de Contrato],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    [bc].[Document] AS [CNPJ],#(lf)    CASE#(lf)        WHEN [er].[Name] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [er].[Name]#(lf)    END AS [Funcionário],#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(tab)FORMAT([ds].[UploadedAt], 'dd/MM/yyyy') AS [Data de Envio],#(lf)    FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)    CASE#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Atrasado'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Próxima Entrega'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Atrasado Recusado'#(lf)        WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Próxima Entrega Recusado'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL#(lf)        THEN#(lf)            'Em Análise'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 0#(lf)        THEN#(lf)            'Aprovado'#(lf)        WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[IsValidated] IS NOT NULL AND [ds].[IsValidated] = 1#(lf)        THEN#(lf)            'Aprovado'#(lf)        ELSE#(lf)            '--'#(lf)    END AS [Status],#(lf)    ISNULL(dsBuildings.[Buildings], '---') AS [Unidade(s)],#(lf)    ISNULL(dsCategories.[Categories], '---') AS [Categoria(s)]#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    LEFT JOIN [DocumentScheduleBuildings] AS dsBuildings ON [ds].[Id] = dsBuildings.[DocumentScheduleId]#(lf)    LEFT JOIN [DocumentScheduleCategories] AS dsCategories ON [ds].[Id] = dsCategories.[DocumentScheduleId]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        (#(lf)            [ds].[UploadedAt] IS NOT NULL#(lf)            OR [c].[Removed] = 0#(lf)        )#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            (#(lf)                ([ds].[ContractId] IS NOT NULL AND [ds].[ContractId] = [c].[Id])#(lf)                OR [ds].[ContractId] IS NULL#(lf)            )#(lf)            OR (#(lf)                (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                        AND EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                        AND NOT EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([ds].[ContractSetId] IS NOT NULL AND [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                    OR [ds].[ContractSetId] IS NULL#(lf)                )#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) #(lf)                    )#(lf)                ) -- unidades#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- categorias#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    (#(lf)                        [d].[DeliveryKind] <> 0#(lf)                        AND [d].[DeliveryKind] <> 1#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0#(lf)                                AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                ) -- deliveykind#(lf)                AND (#(lf)                    -- Agendamento por funcionario#(lf)                    (#(lf)                        [er].[Id] IS NOT NULL#(lf)                        AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                        AND [ds].[Kind] = 5#(lf)                        AND EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                                AND [erc].[ContractId] = [c].[Id]#(lf)                                AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                    -- / Agendamento por funcionario#(lf)                    -- Agendamento comum#(lf)                    OR (#(lf)                        [ds].[EmployeeRegisterId] IS NULL#(lf)                        AND [ds].[ContractId] IS NULL#(lf)                        AND [ds].[Kind] = 1#(lf)                    )#(lf)                    -- / Agendamento comum#(lf)                    -- Agendamento por unidade#(lf)                    OR (#(lf)                        [ds].Kind = 4#(lf)                    )#(lf)                    -- / Agendamento por unidade#(lf)                )#(lf)            )#(lf)        )#(lf)    )#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)-- ORDER BY #(lf)--     [p].[TradeName], [d].[Kind], [d].[Name], [ds].[ExpectedUploadAt], [er].[Name];"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Tipo do documento", type text}, {"Número do Pedido", type text}, {"Id_Contrato", type text}, {"Tipo de Contrato", type text}, {"Fornecedor", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Data de Envio", type any}, {"Data da Análise", type any}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([#"Categoria(s)"] = "Alimentação" or [#"Categoria(s)"] = "Alimentação, Alimentação" or [#"Categoria(s)"] = "Limpeza" or [#"Categoria(s)"] = "Limpeza, Limpeza" or [#"Categoria(s)"] = "Limpeza, Limpeza, Limpeza")),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Prazo de Envio", type date}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado3", "Competência", each if [Documento] = "ASO admissional/Periódico" then [Prazo de Envio]
				
				else Date.AddMonths([Prazo de Envio],-1)),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Competência", type date}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado1", each [Competência] > #date(2023, 12, 31)),
				    #"Valor Substituído" = Table.ReplaceValue(#"Linhas Filtradas1","Atrasado ","",Replacer.ReplaceText,{"Status"}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Valor Substituído", "Unidade(s)", Splitter.SplitTextByDelimiter(", ", QuoteStyle.Csv), {"Unidade(s).1", "Unidade(s).2", "Unidade(s).3", "Unidade(s).4", "Unidade(s).5", "Unidade(s).6", "Unidade(s).7", "Unidade(s).8", "Unidade(s).9", "Unidade(s).10", "Unidade(s).11", "Unidade(s).12", "Unidade(s).13", "Unidade(s).14", "Unidade(s).15", "Unidade(s).16", "Unidade(s).17", "Unidade(s).18", "Unidade(s).19", "Unidade(s).20", "Unidade(s).21", "Unidade(s).22", "Unidade(s).23", "Unidade(s).24", "Unidade(s).25", "Unidade(s).26", "Unidade(s).27", "Unidade(s).28", "Unidade(s).29", "Unidade(s).30", "Unidade(s).31", "Unidade(s).32", "Unidade(s).33", "Unidade(s).34", "Unidade(s).35", "Unidade(s).36", "Unidade(s).37", "Unidade(s).38", "Unidade(s).39", "Unidade(s).40", "Unidade(s).41", "Unidade(s).42", "Unidade(s).43", "Unidade(s).44", "Unidade(s).45", "Unidade(s).46"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Unidade(s).1", type text}, {"Unidade(s).2", type text}, {"Unidade(s).3", type text}, {"Unidade(s).4", type text}, {"Unidade(s).5", type text}, {"Unidade(s).6", type text}, {"Unidade(s).7", type text}, {"Unidade(s).8", type text}, {"Unidade(s).9", type text}, {"Unidade(s).10", type text}, {"Unidade(s).11", type text}, {"Unidade(s).12", type text}, {"Unidade(s).13", type text}, {"Unidade(s).14", type text}, {"Unidade(s).15", type text}, {"Unidade(s).16", type text}, {"Unidade(s).17", type text}, {"Unidade(s).18", type text}, {"Unidade(s).19", type text}, {"Unidade(s).20", type text}, {"Unidade(s).21", type text}, {"Unidade(s).22", type text}, {"Unidade(s).23", type text}, {"Unidade(s).24", type text}, {"Unidade(s).25", type text}, {"Unidade(s).26", type text}, {"Unidade(s).27", type text}, {"Unidade(s).28", type text}, {"Unidade(s).29", type text}, {"Unidade(s).30", type text}, {"Unidade(s).31", type text}, {"Unidade(s).32", type text}, {"Unidade(s).33", type text}, {"Unidade(s).34", type text}, {"Unidade(s).35", type text}, {"Unidade(s).36", type text}, {"Unidade(s).37", type text}, {"Unidade(s).38", type text}, {"Unidade(s).39", type text}, {"Unidade(s).40", type text}, {"Unidade(s).41", type text}, {"Unidade(s).42", type text}, {"Unidade(s).43", type text}, {"Unidade(s).44", type text}, {"Unidade(s).45", type text}, {"Unidade(s).46", type text}}),
				    #"Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Tipo Alterado2", {"Documento", "DocumentScheduleId", "Tipo do documento", "Número do Pedido", "Id_Contrato", "Tipo de Contrato", "Fornecedor", "CNPJ", "Funcionário", "Prazo de Envio", "Data de Envio", "Data da Análise", "Status", "Categoria(s)", "Competência"}, "Atributo", "Valor"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Não Dinâmicas",{{"Valor", "Unidade(s)"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"Atributo"}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Colunas Removidas", "Staus de Envio", each if [Status] = "Atrasado" then "Não Enviado"
				
				else "Enviado"),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Personalização Adicionada1", "Tipo de Documento", each if [Tipo do documento] = "Mobilização" then
				   if  [Funcionário] = "---" then "Mobilização Empresa"
				   else "Mobilização Funcionário"
				
				else if [Tipo do documento] = "Recorrente" then
				   if  [Funcionário] = "---" then "Recorrente Empresa"
				   else "Recorrente Funcionário"
				
				   else [Tipo do documento])
				in
				    #"Personalização Adicionada2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

