table 'Dia a Dia - Status Fornecedor'
	lineageTag: c5888d1f-0052-4aa8-b765-8286df44cd18

	column Nome
		dataType: string
		lineageTag: 2ea0c54d-7250-4581-9cc7-f9dbfd5d00a6
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 8c500f8d-8cb9-4439-83fe-eb004fab6daf
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: e655145a-9515-4018-b9bc-08f8814a84ce
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 3f8d904d-35b4-4ef3-8e2d-94756e54b1fa
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 62b8358a-41b2-4ed9-87dd-1af84b22c318
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: e64651b7-de1d-4315-9b85-bcffc10668c2
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: 1ac3600c-3b0a-4242-83d1-5b93c8cdf1da
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: 9e48fd6d-3e46-4b48-ab69-8f185936874a
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia do Subcontrato'
		dataType: string
		lineageTag: f9190be3-6380-4b5c-a12d-a1dd16c4e9eb
		summarizeBy: none
		sourceColumn: Nome Fantasia do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: 096ed70d-63c8-4e8c-b3f5-19ec8230c613
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: e2aa0f99-c931-4173-913d-b57a1db30724
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência do Contrato.1'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f54a41b1-c29b-4170-90bf-812959e0adcf
		summarizeBy: none
		sourceColumn: Vigência do Contrato.1

		variation Variation
			isDefault
			relationship: c780ade2-bbd0-42f2-8f93-2dc87732f6ed
			defaultHierarchy: LocalDateTable_b150b07a-f102-42fc-ae2a-e1c8f99194e3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência do Contrato.2'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ab5b18fc-93ee-452f-a00f-f17fa2d1914a
		summarizeBy: none
		sourceColumn: Vigência do Contrato.2

		variation Variation
			isDefault
			relationship: c77d61e5-b52a-4d75-a6de-615e92b4d7da
			defaultHierarchy: LocalDateTable_063b7f35-4765-4fee-8f54-6b5ce5cbdc0d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: edcd467d-8d1e-4a42-88a4-47ca293b173a
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 77c22f18-85b8-49ea-80f9-621c5d8633ce
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Total Docs'
		dataType: int64
		formatString: 0
		lineageTag: 378ef8f4-2847-4f67-a54e-a732cc0aa92d
		summarizeBy: sum
		sourceColumn: Total Docs

		annotation SummarizationSetBy = Automatic

	column 'Documentos entregues'
		dataType: int64
		formatString: 0
		lineageTag: 909d8e0d-b193-44dc-a66a-d8e8acb1c0d4
		summarizeBy: sum
		sourceColumn: Documentos entregues

		annotation SummarizationSetBy = Automatic

	column 'Taxa de entrega'
		dataType: double
		lineageTag: ff621320-03b8-4fc5-8478-83f04e186acd
		summarizeBy: sum
		sourceColumn: Taxa de entrega

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Restrições
		dataType: string
		lineageTag: 519caaf9-d097-45ec-a3c8-a46a69ed8fb3
		summarizeBy: none
		sourceColumn: Restrições

		annotation SummarizationSetBy = Automatic

	column 'Docs pendentes com restrição de pgto'
		dataType: string
		lineageTag: 1443af3b-6ae7-4b6a-849b-950aaeec7b87
		summarizeBy: none
		sourceColumn: Docs pendentes com restrição de pgto

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes'
		dataType: string
		lineageTag: f8843ac4-3b2a-4197-be0b-737f7a03c19f
		summarizeBy: none
		sourceColumn: Documentos pendentes

		annotation SummarizationSetBy = Automatic

	column 'Atividades do contrato'
		dataType: string
		lineageTag: 335e4041-6082-46e9-9847-c8361ca24805
		summarizeBy: none
		sourceColumn: Atividades do contrato

		annotation SummarizationSetBy = Automatic

	column diadia
		dataType: string
		lineageTag: bd6442ea-8f72-4236-90f6-7fc60232eb56
		summarizeBy: none
		sourceColumn: diadia

		annotation SummarizationSetBy = Automatic

	column 'Dias de Contrato'
		dataType: double
		lineageTag: 1ad13c99-064c-4f3c-81fb-9d010c81e13f
		summarizeBy: sum
		sourceColumn: Dias de Contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Personalizar.1'
		dataType: string
		lineageTag: 0533a2c5-e70f-420c-a86e-683f20fcbff8
		summarizeBy: none
		sourceColumn: Personalizar.1

		annotation SummarizationSetBy = Automatic

	column Dias
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8284ef13-84e0-4700-8cfc-45cee3ed82e4
		summarizeBy: none
		sourceColumn: Dias

		variation Variation
			isDefault
			relationship: 977ab2cd-d207-46f1-8d55-0a59a087583c
			defaultHierarchy: LocalDateTable_e3538a62-796d-4cbf-86dc-e7b96b0641c4.'Hierarquia de datas'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Qtde pessoas contratadas'
		dataType: string
		lineageTag: 7a68546b-fd94-4150-a7fa-f6c71c4b839b
		summarizeBy: none
		sourceColumn: Qtde pessoas contratadas

		annotation SummarizationSetBy = Automatic

	column 'Quantidade de efetivos'
		dataType: int64
		formatString: 0
		lineageTag: c706297c-44db-45d0-8246-245ab8fc9acb
		summarizeBy: sum
		sourceColumn: Quantidade de efetivos

		annotation SummarizationSetBy = Automatic

	column 'Qtde funcionários mobilizados'
		dataType: string
		lineageTag: 50be264a-5e99-4ebe-89aa-c58a4a34b5b2
		summarizeBy: none
		sourceColumn: Qtde funcionários mobilizados

		annotation SummarizationSetBy = Automatic

	column 'Documentos em análise'
		dataType: string
		lineageTag: 77e7ce57-e4f1-4230-a585-9ffd30caad33
		summarizeBy: none
		sourceColumn: Documentos em análise

		annotation SummarizationSetBy = Automatic

	partition 'Dia a Dia - Status Fornecedor' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\RennanCosta\Diretório Padrão\Atlas Inovações - Documentos\Relatórios\Dados\02. Externo\01. AFM Gestão\CCR\2025\08 - Agosto\28.08\Fornecedores - 2508281029.xlsx")),
				    #"Status de fornecedores_sheet" = Fonte{[Item="Status de fornecedores",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Status de fornecedores_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas", List.Select(Table.ColumnNames(#"Linhas Superiores Removidas"), each try not List.IsEmpty(FilterNullAndWhitespace(Table.Column(#"Linhas Superiores Removidas", _))) otherwise true)),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Outras Colunas Removidas", each not List.IsEmpty(FilterNullAndWhitespace(Record.FieldValues(_)))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Cabeçalhos Promovidos", each ([Categoria] = "CSC")),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Linhas Filtradas1",{{"Qtde funcionários cadastrados", "Quantidade de efetivos"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Nome", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Razão Social do Contrato", type text}, {"CNPJ do Contrato", type text}, {"Tipo de Fornecedor", type text}, {"Nome Fantasia do Subcontrato", type text}, {"Razão Social do Subcontrato", type text}, {"CNPJ do Subcontrato", type text}, {"Vigência do Contrato", type text}, {"Tipo de Contratação", type text}, {"Número do Pedido", type text}, {"Quantidade de efetivos", Int64.Type}, {"Total Docs", Int64.Type}, {"Documentos entregues", Int64.Type}, {"Taxa de entrega", type number}, {"Restrições", type text}, {"Docs pendentes com restrição de pgto", type text}, {"Documentos pendentes", type text}}),
				    #"Linhas em Branco Removidas1" = Table.SelectRows(#"Tipo Alterado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Linhas em Branco Removidas1", "diadia", each Text.Combine({[Nome], [Razão social], [CNPJ], [Categoria], [Unidade], [Razão Social do Contrato], [CNPJ do Contrato], [Tipo de Fornecedor], [Nome Fantasia do Subcontrato], [Razão Social do Subcontrato], [CNPJ do Subcontrato], [Vigência do Contrato], [Tipo de Contratação], [Número do Pedido], Text.From([Quantidade de efetivos], "pt-BR"), Text.From([Total Docs], "pt-BR"), Text.From([Documentos entregues], "pt-BR"), Text.From([Taxa de entrega], "pt-BR"), [Restrições], [Docs pendentes com restrição de pgto], [Documentos pendentes]}, ""), type text),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Coluna Mesclada Inserida", "Vigência do Contrato", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Vigência do Contrato.1", "Vigência do Contrato.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência do Contrato.1", type date}, {"Vigência do Contrato.2", type date}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado1", "Dias de Contrato", each [Vigência do Contrato.2] - [Vigência do Contrato.1]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Dias de Contrato", type number}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado2", "Personalizar.1", each {1..[Dias de Contrato]}),
				    #"Personalizar.1 Expandido" = Table.ExpandListColumn(#"Personalização Adicionada1", "Personalizar.1"),
				    #"Valor Substituído" = Table.ReplaceValue(#"Personalizar.1 Expandido",null,1,Replacer.ReplaceValue,{"Personalizar.1"}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Valor Substituído", "Personalizar", each Date.AddDays([Vigência do Contrato.1],[Personalizar.1]-1)),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada2",{{"Personalizar", "Dias"}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Renomeadas", each ([Tipo de Contratação] <> "Temporário") and ([Categoria] = "GERAL"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

