table 'FGTS Digital Colaboradores'
	lineageTag: cf5112bb-9992-4ded-9706-4d903401abfb

	measure 'Média de Colaboradores FGTS Digital' = AVERAGEX(VALUES('FGTS Digital Colaboradores'[Competência].[Mês]),CALCULATE(DISTINCTCOUNT('FGTS Digital Colaboradores'[Funcionário])))
		formatString: #,0
		lineageTag: 4d162d90-4f3b-4b38-93cb-9bf6f5ad29ee

		annotation PBI_FormatHint = {"isDecimal":true}

	column Cliente
		dataType: string
		lineageTag: 79a9f203-e085-4fcb-b30e-f270f70a1ee0
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 3b8afffd-84fe-4240-803a-a3be8599a9f0
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: cf8514a9-bee1-47bf-9798-c3e159be9d02
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 948853ae-27a5-448e-bb41-b5bfe203b4c4
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: da6cd144-424d-4fb0-94de-28d9d3f3227d
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column PIS
		dataType: int64
		formatString: 0
		lineageTag: 8f35b439-aabc-44bc-b7fa-e2dff47557a1
		summarizeBy: sum
		sourceColumn: PIS

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 5f4a9c84-4127-4294-87bb-fa8cc302e8a5
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: Long Date
		lineageTag: 47327764-c868-414a-92a4-dbe9978cc672
		summarizeBy: none
		sourceColumn: Competência

		variation Variation
			isDefault
			relationship: 7e66bffb-4f46-43cd-9d15-7af29dd58355
			defaultHierarchy: LocalDateTable_6092533a-2750-413a-acb9-75c11ad64869.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 19e00c94-589c-4126-b622-3a342d2e04b0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Observação
		dataType: string
		lineageTag: 59e1395b-d5f9-409b-8867-3fc57f40862e
		summarizeBy: none
		sourceColumn: Observação

		annotation SummarizationSetBy = Automatic

	column 'Valor sefip'
		dataType: int64
		formatString: 0
		lineageTag: 2e27f229-8fc9-46ac-b00c-b23899d1186f
		summarizeBy: sum
		sourceColumn: Valor sefip

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: int64
		formatString: 0
		lineageTag: ff35ede8-bc9e-49dc-a8bf-d1043e7cfcc5
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

	column 'Valor cadastrado'
		dataType: int64
		formatString: 0
		lineageTag: 75948466-0d06-40c2-b393-a417c2d8f687
		summarizeBy: sum
		sourceColumn: Valor cadastrado

		annotation SummarizationSetBy = Automatic

	column Escala
		dataType: string
		lineageTag: 1b0eff89-c76c-4270-90ce-d25db9fe168c
		summarizeBy: none
		sourceColumn: Escala

		annotation SummarizationSetBy = Automatic

	column 'Início da jornada'
		dataType: string
		lineageTag: 3882f8cf-b082-499a-8497-565939fad75e
		summarizeBy: none
		sourceColumn: Início da jornada

		annotation SummarizationSetBy = Automatic

	column 'Término da jornada'
		dataType: string
		lineageTag: f932cf09-a1eb-4127-9cbd-3459daf6e0a4
		summarizeBy: none
		sourceColumn: Término da jornada

		annotation SummarizationSetBy = Automatic

	column 'Intrajornada descansada'
		dataType: string
		lineageTag: 0ece9651-3e79-4ca0-91f2-43baa771b8c1
		summarizeBy: none
		sourceColumn: Intrajornada descansada

		annotation SummarizationSetBy = Automatic

	column 'Intrajornada remunerada'
		dataType: string
		lineageTag: cab4dab8-4f03-46bb-b58b-ed5bd924f60a
		summarizeBy: none
		sourceColumn: Intrajornada remunerada

		annotation SummarizationSetBy = Automatic

	column 'Valor intrajornada remunerada'
		dataType: int64
		formatString: 0
		lineageTag: e207205d-c0ff-4231-a5a6-13fad5b0f5b9
		summarizeBy: sum
		sourceColumn: Valor intrajornada remunerada

		annotation SummarizationSetBy = Automatic

	column 'Adicional noturno'
		dataType: int64
		formatString: 0
		lineageTag: 5c0d196d-e609-4ce5-8831-39535c6ce962
		summarizeBy: sum
		sourceColumn: Adicional noturno

		annotation SummarizationSetBy = Automatic

	column 'Hora noturna reduzida'
		dataType: int64
		formatString: 0
		lineageTag: 21379e1c-3648-4e2c-a13a-5ea3e9cb6f7e
		summarizeBy: sum
		sourceColumn: Hora noturna reduzida

		annotation SummarizationSetBy = Automatic

	column 'Hora extra'
		dataType: string
		lineageTag: c8da46fd-83be-49ed-a63d-24b8315366c1
		summarizeBy: none
		sourceColumn: Hora extra

		annotation SummarizationSetBy = Automatic

	column 'Valor hora extra'
		dataType: int64
		formatString: 0
		lineageTag: c6d7f5b0-d336-47ab-94f3-3796ea92aaa0
		summarizeBy: sum
		sourceColumn: Valor hora extra

		annotation SummarizationSetBy = Automatic

	column 'Trabalha aos feriados'
		dataType: string
		lineageTag: e3fd7b7b-69a6-44dc-80dc-22592c6fc277
		summarizeBy: none
		sourceColumn: Trabalha aos feriados

		annotation SummarizationSetBy = Automatic

	column Insalubridade
		dataType: int64
		formatString: 0
		lineageTag: 146e1844-c359-4c5e-a5a8-c9f620bd3ae3
		summarizeBy: sum
		sourceColumn: Insalubridade

		annotation SummarizationSetBy = Automatic

	column 'Total insalubridade'
		dataType: int64
		formatString: 0
		lineageTag: 0e3c01a3-1ee9-4203-a170-eb9f1f5ae615
		summarizeBy: sum
		sourceColumn: Total insalubridade

		annotation SummarizationSetBy = Automatic

	column Periculosidade
		dataType: int64
		formatString: 0
		lineageTag: bd7ac9c5-7710-4b00-a3e6-416706d7f9c8
		summarizeBy: sum
		sourceColumn: Periculosidade

		annotation SummarizationSetBy = Automatic

	column 'Total periculosidade'
		dataType: int64
		formatString: 0
		lineageTag: 8edf0ea0-bfb0-4147-839d-4f88aae39b03
		summarizeBy: sum
		sourceColumn: Total periculosidade

		annotation SummarizationSetBy = Automatic

	column 'Gratificação/Acúm. funções'
		dataType: int64
		formatString: 0
		lineageTag: 36d134a9-7382-4c3f-ad9b-38c7a853e838
		summarizeBy: sum
		sourceColumn: Gratificação/Acúm. funções

		annotation SummarizationSetBy = Automatic

	column 'Valor gratificação/Acúm. funções'
		dataType: int64
		formatString: 0
		lineageTag: cb96e3d6-e367-4be3-9a53-71116fb597a4
		summarizeBy: sum
		sourceColumn: Valor gratificação/Acúm. funções

		annotation SummarizationSetBy = Automatic

	column 'Gratificação liderança'
		dataType: int64
		formatString: 0
		lineageTag: 1fd7793e-d9db-4756-a1e5-6d7b5062ceb0
		summarizeBy: sum
		sourceColumn: Gratificação liderança

		annotation SummarizationSetBy = Automatic

	column 'Outros adicionais'
		dataType: int64
		formatString: 0
		lineageTag: 87201e6d-8103-4ac2-a5e4-2ee973009ab0
		summarizeBy: sum
		sourceColumn: Outros adicionais

		annotation SummarizationSetBy = Automatic

	column Responsável
		dataType: string
		lineageTag: e75bea99-7b8c-4e64-8a99-5731602b1da3
		summarizeBy: none
		sourceColumn: Responsável

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 65f1f549-a6e0-46fd-b42b-4a3e06fa27f9
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: a8998f9c-f39d-4ff9-b152-9c8ac2fb9058
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: ea5eb5cf-da17-4ee3-8fd8-b42476cf9ccd
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	partition 'FGTS Digital Colaboradores' = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select#(lf)#(tab)o.TradeName as 'Cliente',#(lf)#(tab)b.TradeName as 'Unidade',#(lf)#(tab)p.TradeName as 'Fornecedor',#(lf)#(tab)cat.Name as 'Categoria',#(lf)#(tab)r.Name as 'Regional',#(lf)#(tab)c.OrderNumber AS 'Número do Pedido',#(lf)#(tab)c.Id AS 'Id_Contrato',#(lf)#(tab)e.Name as 'Funcionário',#(lf)#(tab)e.PisNumber as 'PIS',#(lf)#(tab)FORMAT(g.Competency, 'MM/yyyy') as 'Competência',#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN ee.Status = 0#(lf)#(tab)#(tab)THEN 'Irregular'#(lf)#(lf)#(tab)#(tab)WHEN ee.Status = 1#(lf)#(tab)#(tab)THEN 'Regular'#(lf)#(tab)END as 'Status',#(lf)#(tab)ee.StatusObservation as 'Observação',#(lf)#(tab)ee.Remuneration as 'Valor sefip',#(lf)#(tab)ee.SalaryExpected as 'Valor do contrato',#(lf)#(tab)ee.EffectiveSalary as 'Valor cadastrado',#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 0#(lf)#(tab)#(tab)THEN '0x0'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 1#(lf)#(tab)#(tab)THEN '2x1'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 2#(lf)#(tab)#(tab)THEN '4x2'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 3#(lf)#(tab)#(tab)THEN '5x1'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 4#(lf)#(tab)#(tab)THEN '5x2'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 5#(lf)#(tab)#(tab)THEN '6x1'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 6#(lf)#(tab)#(tab)THEN '6x2'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 7#(lf)#(tab)#(tab)THEN '12x36'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 8#(lf)#(tab)#(tab)THEN '12x48'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 9#(lf)#(tab)#(tab)THEN '12x36 (36hrs)'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 10#(lf)#(tab)#(tab)THEN '4x4'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveScale = 11#(lf)#(tab)#(tab)THEN '14x14'#(lf)#(tab)END as 'Escala',#(lf)#(tab)FORMAT(ee.EffectiveStartTime, 'HH:mm') as 'Início da jornada',#(lf)#(tab)FORMAT(ee.EffectiveEndTime, 'HH:mm') as 'Término da jornada',#(lf)#(tab)FORMAT(ee.EffectiveInterval, 'HH:mm') as 'Intrajornada descansada',#(lf)#(tab)FORMAT(ee.EffectiveOvertimeInterval, 'HH:mm') as 'Intrajornada remunerada',#(lf)#(tab)ee.EffectiveTotalMonthlyOvertimeInterval as 'Valor intrajornada remunerada',#(lf)#(tab)ee.EffectiveTotalAdditionalValueNightTime as 'Adicional noturno',#(lf)#(tab)ee.EffectiveTotalAdditionalValueNightTimeReduced as 'Hora noturna reduzida',#(lf)#(tab)FORMAT(ee.EffectiveOverTime, 'HH:mm') as 'Hora extra',#(lf)#(tab)ee.EffectiveTotalMonthlyOvertimeHour as 'Valor hora extra',#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN ee.EffectiveHolidayWorkingKind = 0#(lf)#(tab)#(tab)THEN 'Sim, Trabalha nos feriados'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveHolidayWorkingKind = 1#(lf)#(tab)#(tab)THEN 'Não trabalha nos feriados'#(lf)#(lf)#(tab)#(tab)WHEN ee.EffectiveHolidayWorkingKind = 3#(lf)#(tab)#(tab)THEN 'Folga compensada'#(lf)#(tab)END as 'Trabalha aos feriados',#(lf)#(tab)ee.EffectiveUnhealthiness as 'Insalubridade',#(lf)#(tab)ee.EffectiveTotalUnhealthiness as 'Total insalubridade',#(lf)#(tab)ee.EffectiveDangerousness as 'Periculosidade',#(lf)#(tab)ee.EffectiveTotalDangerousness as 'Total periculosidade',#(lf)#(tab)ee.EffectiveBonus as 'Gratificação/Acúm. funções',#(lf)#(tab)ee.EffectiveTotalBonus as 'Valor gratificação/Acúm. funções',#(lf)#(tab)ee.EffectiveTotalLeadership as 'Gratificação liderança',#(lf)#(tab)ee.EffectiveTotalOthersAdditional as 'Outros adicionais',#(lf)#(tab)u.Name as 'Responsável',#(lf)#(tab)u.Email as 'Email'#(lf)from #(lf)#(tab)EmployeeEntry ee#(lf)#(lf)#(tab)left join Employee e#(lf)#(tab)on e.Id = ee.EmployeeId#(lf)#(lf)#(tab)inner join [User] u #(lf)#(tab)on u.Id = ee.ResponsibleId#(lf)#(lf)#(tab)left join [Function] f#(lf)#(tab)on f.Id = ee.FunctionId#(lf)#(lf)#(tab)inner join Gfip g#(lf)#(tab)on g.Id = ee.GfipId#(lf)#(lf)#(tab)inner join ContractSet cs#(lf)#(tab)on cs.Id = g.ContractSetId#(lf)#(lf)#(tab)inner join Contract c#(lf)#(tab)on c.ContractSetId = g.ContractSetId#(lf)#(lf)#(tab)inner join Building b#(lf)#(tab)on b.Id = cs.BuildingId#(lf)#(lf)#(tab)inner join Region r#(lf)#(tab)on r.Id = b.RegionId #(lf)#(lf)#(tab)inner join Provider p #(lf)#(tab)on p.Id = cs.ProviderId#(lf)#(lf)#(tab)inner join Organization o#(lf)#(tab)on o.Id = b.OrganizationId#(lf)#(lf)#(tab)inner join CategoryContractSet catSet#(lf)#(tab)on g.ContractSetId = catSet.ContractSetId#(lf)#(lf)#(tab)inner join Category cat#(lf)#(tab)on catSet.CategoryId = cat.Id#(lf)where#(lf)o.Id = '23691bb8-3910-436a-9467-0df7b443fb38' and#(lf)g.Competency >= '2022-02-01 00:00:00.0000000'#(lf)and g.Id NOT IN#(lf)(#(lf)'F950FDB2-E041-4A73-8950-A7E80C3D0E69',#(lf)'679BE57D-5145-4DF1-956D-D08E4CA9E54E',#(lf)'CCCBD6D1-EDCC-4373-9ADF-00C0FE5EAA9C',#(lf)'22E7A015-3F18-4E85-8446-6E1BE76AE6CA'#(lf))#(lf)#(lf)order by #(lf)#(tab)o.TradeName,#(lf)#(tab)b.TradeName,#(lf)#(tab)p.TradeName,#(lf)#(tab)e.Name,#(lf)#(tab)g.Competency#(lf)#(lf)#(lf)#(lf)#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Cliente", type text}, {"Unidade", type text}, {"Fornecedor", type text}, {"Categoria", type text}, {"Funcionário", type text}, {"PIS", Int64.Type}, {"Número do Pedido", type text}, {"Competência", type date}, {"Status", type text}, {"Observação", type text}, {"Valor sefip", Int64.Type}, {"Valor do contrato", Int64.Type}, {"Valor cadastrado", Int64.Type}, {"Escala", type text}, {"Início da jornada", type text}, {"Término da jornada", type text}, {"Intrajornada descansada", type text}, {"Intrajornada remunerada", type text}, {"Valor intrajornada remunerada", Int64.Type}, {"Adicional noturno", Int64.Type}, {"Hora noturna reduzida", Int64.Type}, {"Hora extra", type text}, {"Valor hora extra", Int64.Type}, {"Trabalha aos feriados", type text}, {"Insalubridade", Int64.Type}, {"Total insalubridade", Int64.Type}, {"Periculosidade", Int64.Type}, {"Total periculosidade", Int64.Type}, {"Gratificação/Acúm. funções", Int64.Type}, {"Valor gratificação/Acúm. funções", Int64.Type}, {"Gratificação liderança", Int64.Type}, {"Outros adicionais", Int64.Type}, {"Responsável", type text}, {"Email", type text}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas em Branco Removidas", each ([Categoria] <> "GF"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

