table 'Status do Fornecedores'
	lineageTag: 6f05e263-bb70-4969-84d3-7ffde8466f2a

	measure _Quantidade_Fornecedores = CALCULATE(DISTINCTCOUNT('Status do Fornecedores'[Índice]))
		formatString: 0
		lineageTag: 0bf7353f-ed22-4f3b-a3c1-cf45b2256c67

	column Fornecedor
		dataType: string
		lineageTag: 5dd34db0-fb29-463e-9b17-12779528562a
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 9f652e86-f3ac-465e-8c18-801bf4bd6570
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: e842513f-0f4d-486f-bb7e-ca5a15a64d0f
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 410b65d1-7933-4481-a644-0a0db0109ea1
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 333f8c72-8790-48ef-b0ca-e11039845f08
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: 634d6921-9bde-4152-bbc0-dc6559f448cf
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: e7b3f18d-6f84-4d45-8665-3a909f3c7789
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: 71fa4d5d-b4e7-48f2-b277-60970dae2888
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia do Subcontrato'
		dataType: string
		lineageTag: 8f8662f1-5d16-482c-a252-847d1ec9f61e
		summarizeBy: none
		sourceColumn: Nome Fantasia do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: 48c3fe02-4325-4793-95a6-b663c0f3dd0a
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: d329b84a-9b6d-4d19-831f-d9aaf93719fe
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: e295e3bc-65e5-401f-bed1-606c2ae106b2
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 49a29c92-42cd-4591-89ba-673e0b610894
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Total Docs'
		dataType: int64
		formatString: 0
		lineageTag: df8bff08-f30b-472d-ba72-afe2d8b2911f
		summarizeBy: sum
		sourceColumn: Total Docs

		annotation SummarizationSetBy = Automatic

	column 'Documentos entregues'
		dataType: int64
		formatString: 0
		lineageTag: 52f87da4-20d7-4e6f-b8f8-a4c365414bd4
		summarizeBy: sum
		sourceColumn: Documentos entregues

		annotation SummarizationSetBy = Automatic

	column 'Taxa de entrega'
		dataType: double
		lineageTag: 8650093a-5e14-4502-af3d-d98d0d8d2d5c
		summarizeBy: sum
		sourceColumn: Taxa de entrega

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Restrições
		dataType: string
		lineageTag: 62d20db8-bfb4-4f95-9823-20cf99f065ab
		summarizeBy: none
		sourceColumn: Restrições

		annotation SummarizationSetBy = Automatic

	column 'Docs pendentes com restrição de pgto'
		dataType: string
		lineageTag: 39fb96fc-f3fc-4454-855c-054d571a5802
		summarizeBy: none
		sourceColumn: Docs pendentes com restrição de pgto

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes'
		dataType: string
		lineageTag: e8f8215c-d42f-4173-9e0a-cc92c13bf800
		summarizeBy: none
		sourceColumn: Documentos pendentes

		annotation SummarizationSetBy = Automatic

	column 'N de Docs Pendentes'
		dataType: string
		lineageTag: 686d7942-bec7-46e5-9413-4e03863d54a3
		summarizeBy: none
		sourceColumn: N de Docs Pendentes

		annotation SummarizationSetBy = Automatic

	column 'Taxa de Pendência'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8504b944-ea55-4045-b3ca-74433987ce21
		summarizeBy: sum
		sourceColumn: Taxa de Pendência

		annotation SummarizationSetBy = Automatic

	column 'Status do Fornecedor'
		dataType: string
		lineageTag: a7f0046b-d5f7-4c9b-a022-d8ac4a92a4cf
		summarizeBy: none
		sourceColumn: Status do Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Chave Gestores'
		dataType: string
		lineageTag: 66d62c6a-99ba-4895-9da0-36941e5a7be8
		summarizeBy: none
		sourceColumn: Chave Gestores

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 491b78ea-6ab5-443d-8043-a152271c4f4d
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column Mesclado
		dataType: string
		lineageTag: 53994ab5-dd16-41a0-989b-300677775122
		summarizeBy: none
		sourceColumn: Mesclado

		annotation SummarizationSetBy = Automatic

	column 'Atividades do contrato'
		dataType: string
		lineageTag: 98843861-5385-4883-8bee-56944650923b
		summarizeBy: none
		sourceColumn: Atividades do contrato

		annotation SummarizationSetBy = Automatic

	column 'Qtde pessoas contratadas'
		dataType: string
		lineageTag: f081ebb5-a2ec-43ae-916f-28044d8f90cf
		summarizeBy: none
		sourceColumn: Qtde pessoas contratadas

		annotation SummarizationSetBy = Automatic

	column 'Qtde funcionários mobilizados'
		dataType: string
		lineageTag: d8addc02-d1c8-40ef-b716-7a3e9a111a60
		summarizeBy: none
		sourceColumn: Qtde funcionários mobilizados

		annotation SummarizationSetBy = Automatic

	column 'Documentos em análise'
		dataType: string
		lineageTag: 159f1891-8ada-4558-a841-006afd3de55a
		summarizeBy: none
		sourceColumn: Documentos em análise

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 7d1ba847-a6a9-4bc9-897e-824c5354d021
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column 'Quantidade de efetivos'
		dataType: int64
		formatString: 0
		lineageTag: 48f6e7eb-0bee-441b-8674-900026180d4e
		summarizeBy: sum
		sourceColumn: Quantidade de efetivos

		annotation SummarizationSetBy = Automatic

	column 'Contratos.Grau de Risco - Trabalhista'
		dataType: string
		lineageTag: a6cad000-8886-4ad2-9be9-60d19ccb9510
		summarizeBy: none
		sourceColumn: Contratos.Grau de Risco - Trabalhista

		annotation SummarizationSetBy = Automatic

	column 'Status Atlas' =
			
			VAR RIS      = 'Status do Fornecedores'[(_Grau_Risco_M)]
			VAR rawPend  = 'Status do Fornecedores'[Taxa de Pendência]
			VAR DOCS = 'Status do Fornecedores'[Total Docs]
			VAR PEND     = IF(NOT ISBLANK(rawPend), IF(rawPend > 1, rawPend / 100, rawPend))
			VAR faixa =
			    SWITCH(
			        TRUE(),
			        ISBLANK(PEND), BLANK(),
			        PEND <= 0.2,     " 80–100%"
			    )
			VAR DOC_PEND = 'Status do Fornecedores'[Documentos pendentes]
			VAR DOC_ANA = 'Status do Fornecedores'[Documentos em análise]
			RETURN
			SWITCH(
			    TRUE(),
			    RIS = "Não Monitorado", "Habilitado",
			    DOCS = 0, "Habilitado",
			    PEND = 0,               "Habilitado",
			    IF(DOC_PEND = DOC_ANA,"Não Habilitado - Possui documentos em análise",
			        IF(PEND=1,"Não Habilitado - Não entregou nenhum documento",  IF(PEND <= 0.2,"Habilitado com Ressalvas - Conforme" & faixa,"Não Habilitado")
			)))
		lineageTag: 50c281b8-8a69-4348-9707-2a380d966bae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column (_Grau_Risco_M) =
			IF(
			    'Status do Fornecedores'[Contratos.Grau de Risco - Trabalhista] = "Não Monitorado", "Não Monitorado", 'Status do Fornecedores'[Contratos.Grau de Risco - Trabalhista] )
		lineageTag: 8d2f819e-496f-44a9-bc26-8d303266f029
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column (_Status_Contrato) = ```
			
			IF('Status do Fornecedores'[Vigência do Contrato Inicio] > TODAY(), 
			    "Contrato Futuro", 
			    IF('Status do Fornecedores'[Vigência do Contrato Fim] < TODAY(), 
			        "Contrato Inativo", 
			        "Contrato Ativo"
			    )
			)
			
			```
		lineageTag: 93312bc9-6096-4408-88f7-47b645569f3b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Gestor do Contrato'
		dataType: string
		lineageTag: 852cc698-e133-4a60-a58a-1ed0bd8a8e82
		summarizeBy: none
		sourceColumn: Gestor do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência do Contrato Inicio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4b1448e-5307-402b-9d54-3688f99186ab
		summarizeBy: none
		sourceColumn: Vigência do Contrato Inicio

		variation Variation
			isDefault
			relationship: b9a6ebe6-4baf-4548-a902-bdee9fa3e712
			defaultHierarchy: LocalDateTable_13ef217d-1847-4a15-adc9-ba5f561ff520.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência do Contrato Fim'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24de60a9-ae9c-4956-bb3d-4760ec2d7ace
		summarizeBy: none
		sourceColumn: Vigência do Contrato Fim

		variation Variation
			isDefault
			relationship: f65d50ff-26d6-4db3-b7a5-28f8bcaad748
			defaultHierarchy: LocalDateTable_726fd567-6f62-44b2-a92b-ff894d9edc59.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: c27f8bf7-31f4-48fd-89c0-1b4fb2fafe9a
		summarizeBy: sum
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	partition 'Status do Fornecedores' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://adminatlasinovacoescom.sharepoint.com/:x:/r/sites/DiretrioPadro/Documentos%20Compartilhados/Relat%C3%B3rios/Dados/02.%20Externo/01.%20AFM%20Gest%C3%A3o/GSInima/08%20-%20Power%20BI/2026/1%20-%20Janeiro/(Rec)Fornecedores%20-%20260106113239.xlsx")),
				    #"Status de fornecedores_sheet" = Fonte{[Item="Status de fornecedores",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Status de fornecedores_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas", List.Select(Table.ColumnNames(#"Linhas Superiores Removidas"), each try not List.IsEmpty(FilterNullAndWhitespace(Table.Column(#"Linhas Superiores Removidas", _))) otherwise true)),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Outras Colunas Removidas", each not List.IsEmpty(FilterNullAndWhitespace(Record.FieldValues(_)))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"Qtde funcionários cadastrados", "Quantidade de efetivos"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas2",{{"Nome", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Razão Social do Contrato", type text}, {"CNPJ do Contrato", type text}, {"Tipo de Fornecedor", type text}, {"Nome Fantasia do Subcontrato", type text}, {"Razão Social do Subcontrato", type text}, {"CNPJ do Subcontrato", type text}, {"Vigência do Contrato", type text}, {"Tipo de Contratação", type text}, {"Número do Pedido", type text}, {"Quantidade de efetivos", Int64.Type}, {"Total Docs", Int64.Type}, {"Documentos entregues", Int64.Type}, {"Taxa de entrega", type number}, {"Restrições", type text}, {"Docs pendentes com restrição de pgto", type text}, {"Documentos pendentes", type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "N de Docs Pendentes", each [Total Docs] - [Documentos entregues]),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Personalização Adicionada",{"Nome", "Razão social", "CNPJ", "Categoria", "Unidade", "Razão Social do Contrato", "CNPJ do Contrato", "Tipo de Fornecedor", "Nome Fantasia do Subcontrato", "Razão Social do Subcontrato", "CNPJ do Subcontrato", "Vigência do Contrato", "Tipo de Contratação", "Número do Pedido", "Quantidade de efetivos", "Total Docs", "Documentos entregues", "N de Docs Pendentes", "Taxa de entrega", "Restrições", "Docs pendentes com restrição de pgto", "Documentos pendentes"}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Colunas Reordenadas", "Taxa de Pendência", each if [N de Docs Pendentes]= 0 then 0
				else [N de Docs Pendentes]/[Total Docs]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Taxa de Pendência", Percentage.Type}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado1", "Status do Fornecedor", each if [Taxa de Pendência] = 1 then "Não Entregue" else if [Taxa de Pendência] >= 0.8 then "Não Habilitado" else if [Taxa de Pendência] >= 0.5 then "Habilitado com Ressalva" else if [Taxa de Pendência] >= 0 then "Habilitado" else "Sem Classificação"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada2",{{"Nome", "Fornecedor"}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Colunas Renomeadas", "Vigência do Contrato", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Vigência do Contrato Inicio", "Vigência do Contrato Fim"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência do Contrato Inicio", type date}, {"Vigência do Contrato Fim", type date}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado2", "Chave Gestores", each [Fornecedor]&[Categoria]),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Personalização Adicionada3",{{"Razão social", Text.Upper, type text}}),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Texto em Maiúscula", "Chave", each [Fornecedor]&[CNPJ]&[Unidade]&[Categoria]&[Número do Pedido]),
				    #"Texto em Maiúscula1" = Table.TransformColumns(#"Personalização Adicionada4",{{"Fornecedor", Text.Upper, type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Texto em Maiúscula1", {"Chave"}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Duplicatas Removidas", "Índice", 0, 1, Int64.Type),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Índice Adicionado", "Mesclado", each Text.Combine({[Número do Pedido], [Unidade]}, ""), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"Mesclado"}, Contratos, {"Chave-Cadas"}, "Contratos", JoinKind.LeftOuter),
				    #"Contratos Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Contratos", {"Grau de Risco - Trabalhista"}, {"Contratos.Grau de Risco - Trabalhista"}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Contratos Expandido", {"Número do Pedido"}, Contratos, {"N° do Pedido"}, "Contratos", JoinKind.LeftOuter),
				    #"Contratos Expandido1" = Table.ExpandTableColumn(#"Consultas Mescladas1", "Contratos", {"Nome do Gestor do Contrato"}, {"Gestor do Contrato"})
				in
				    #"Contratos Expandido1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

