table 'Documentos em Análise'
	lineageTag: 941748fe-575a-4074-ae85-ff049f2ce062

	measure _Total_Documentos = ```
			
			        CALCULATE(
			            DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId])
			        )
			
			```
		formatString: 0
		lineageTag: 04d5e06f-36b4-43ce-8f4f-22bbd1954c85

	measure 'Documentos em Análise' =
			IF(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Em Análise")=0,0,CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Em Análise"))
		formatString: 0
		lineageTag: 2af97cb3-ff8f-40b7-9231-ac5b3dfb19ba

	measure '(Aprovados) Documentos' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Aprovado")/[_Total_Documentos] + 0
		lineageTag: bf552cbf-8d4e-4736-b064-ac3992b0df9d

		formatStringDefinition =
				VAR APRO =FORMAT([(Aprovados) Documentos],"0.0%")
				
				VAR TOTAL = [_Total_Documentos]
				
				RETURN """" & APRO & " (" & TOTAL & ")"

	measure '1 - Quantidade de Docs Aprovados' =
			if(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Aprovado") = 0,
			"N/A"
			, (CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Aprovado")))
		formatString: #,0
		lineageTag: 11ee845c-1ee6-49f2-8a6f-8c6ee98a4c5d

	measure '3 - %Atrasados' =
			(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado")+ CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado"))/[_Total_Documentos]
		lineageTag: 0053bc5e-4e3b-4f7f-ba80-0fb5015ae793

		formatStringDefinition =
				VAR vAtrasado = FORMAT([3 - %Atrasados],"0.0%")
				VAR vTotal = [_Total_Documentos]
				VAR vResultados = """" & vAtrasado & " (" & vTotal & ")"
				return vResultados

	measure '3 - Atrasados' = ```
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado") +  
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado")
			```
		formatString: #,0
		lineageTag: 1333a4cf-2038-48a7-9d87-23b33dac0f17

	measure '2 - Recusados' = ```
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado") + 
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Próximas Entregaas Recusadas")
			```
		formatString: 0
		lineageTag: 6b7513c8-21ca-431b-8a71-3638f9bc270c

	measure '4 - %Quantidade de Enviados' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] <> "Atrasado")/[_Total_Documentos]  + 0
		lineageTag: dec939ec-684d-443d-b5cc-80e2d74c63ea

		formatStringDefinition =
				VAR PORCEN = FORMAT([4 - %Quantidade de Enviados],"0.0%")
				
				VAR TOTAL = [_Total_Documentos]
				
				RETURN """" & PORCEN & " (" & TOTAL & ")"

	measure _Enviados_Quantidade =
			
			
			CALCULATE([_Total_Documentos],
			'Documentos em Análise'[Status] <> "Atrasado")
		formatString: #,0
		lineageTag: 227b0b6c-139e-4bbc-91f5-5947713a5084

	measure 'Quantidade de Enviados dividido por Documentos Total' =
			
			DIVIDE([_Enviados_Quantidade], [_Total_Documentos])
		lineageTag: 4563817b-edea-4742-a4db-3cf8fddf0535

		formatStringDefinition =
				VAR vEnviados = FORMAT([Quantidade de Enviados dividido por Documentos Total], "0.0%")
				VAR vTotal = [_Total_Documentos]
				VAR vResultado = """" & vEnviados & " (" & vTotal & ")"
				RETURN vResultado

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure _Conformidade_Aprovados = ```
			
			VAR Modo = SELECTEDVALUE('#ControleProximaEntrega'[Opção], "Ignorar Próximas Entregas")
			
			VAR APROVADO = 
			    CALCULATE(
			        DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Status] = "Aprovado"
			    )
			
			VAR TOTAL =
			    SWITCH(
			        Modo,
			        "Ignorar Próximas Entregas",
			            CALCULATE(
			                DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			                'Documentos em Análise'[Status] <> "Próxima Entrega"
			            ),
			        "Incluir Próximas Entregas",
			            CALCULATE(
			                DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId])
			            )
			    )
			
			RETURN 
			IF(
			    APROVADO = BLANK() && TOTAL > 0,
			    0,
			    APROVADO / TOTAL
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c6bd1d2a-cea2-4029-86f1-befe81dc18f2

	measure %Recusados =
			(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado") + CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Próximas Entregas Recusadas"))/[_Enviados_Quantidade]
		formatString: 0%;-0%;0%
		lineageTag: 122791aa-7e05-4c81-8408-54a5fbd781e4

	measure %Atrasados =
			(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado") + CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado"))/[_Total_Documentos]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a4e5238a-8926-4371-8c98-f126e2b84440

	measure 'Quantidade de Analisado' = ```
			CALCULATE(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] <> "Atrasado",
			'Documentos em Análise'[Status] <> "Em Análise"))
			
			```
		formatString: #,0
		lineageTag: b7a2b6b1-ded9-43e3-ba59-23fdc6ab3439

	measure '_Aderência_Envio Documento' = ```
			
			VAR Modo = [Modo_ProximaEntrega]
			
			VAR ENVIADO =
			    SWITCH(
			        Modo,
			        "Ignorar Próximas Entregas",
			            CALCULATE(
			                [_Total_Documentos],
			                'Documentos em Análise'[Status] <> "Atrasado"
			                   
			            ),
			        "Incluir Próximas Entregas",
			            CALCULATE(
			                [_Total_Documentos],
			                'Documentos em Análise'[Status] <> "Atrasado"  && 'Documentos em Análise'[Status] <> "Próxima Entrega"
			            )
			    )
			
			VAR TOTAL = [_Total_Documentos]
			
			RETURN
			    IF(
			        ENVIADO = BLANK() && TOTAL > 0,
			        0,
			        ENVIADO / TOTAL
			    )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 686f7950-5935-4cb6-b511-dbc9223258eb

	measure _%_Peso_3 =
			
			VAR PESO3 = CALCULATE([_Total_Documentos],
			       'Documentos em Análise'[Peso do Documentos]= 3,
			       'Documentos em Análise'[Status] <> "Aprovado")
			VAR PESO1 = CALCULATE([_Total_Documentos],
			       'Documentos em Análise'[Peso do Documentos]= 1)
			VAR QUANT3 = [_Peso3_Quantidade]
			
			
			RETURN
			(IF(PESO1<1,
			    IF(PESO3=0 && QUANT3>0,0,(PESO3/QUANT3)),
			    IF(PESO3=0 && QUANT3>0,0,(((3/4)*PESO3)/QUANT3))))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9a286f2f-04b6-40fb-abbb-81b31291dbd4

	measure _Peso1_Quantidade =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 1)
		formatString: 0
		lineageTag: df2541e8-9a25-4f00-9435-7608e39c3f15

	measure _%_Peso_1 =
			
			
			VAR PESO1 = CALCULATE([_Total_Documentos],
			       'Documentos em Análise'[Peso do Documentos]= 1,
			       'Documentos em Análise'[Status] <> "Aprovado")
			VAR PESO3 = CALCULATE([_Total_Documentos],
			       'Documentos em Análise'[Peso do Documentos]= 3)
			VAR QUANT1 = [_Peso1_Quantidade]
			
			
			RETURN
			(IF(PESO3<1,
			
			    IF(PESO1=0 && QUANT1>0,0,(PESO1/QUANT1)),
			    (IF(PESO1=0 && QUANT1>0,0,(((1/4)*PESO1)/QUANT1)))))
		lineageTag: bd6c8b62-db58-4b25-b8e1-4d014c447849

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Peso3_Quantidade =
			CALCULATE([_Total_Documentos],
			        'Documentos em Análise'[Peso do Documentos] = 3)
		formatString: 0
		lineageTag: 3848ae26-b978-40dd-87fe-a74deb120435

	measure '(Risco) Críticos' = ([_%_Peso_1] + [_%_Peso_3])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08a200f9-cdae-45c7-9e60-790a9c9582c0

	measure 'Quantidade Contratos - Total' = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[Número do Pedido]))
		formatString: 0
		lineageTag: 6360696d-3583-4992-8d06-46131b05c66d

	measure _Média_Tempo_de_Atraso =
			CALCULATE(AVERAGE('Documentos em Análise'[Tempo de Atraso]),
			USERELATIONSHIP(Contratos[Id_Contrato],'Documentos em Análise'[Id_Contrato]))
		lineageTag: 99ac8fda-8c0c-4b32-95fe-076d160b1a4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Hoje = TODAY()
		formatString: Short Date
		lineageTag: 3551ebcf-fc11-41cd-ab38-a041f29c6f7b

	measure _Tempo_de_atraso =
			CALCULATE(VALUES('Documentos em Análise'[Tempo de Atraso]),
			USERELATIONSHIP('Documentos em Análise'[Id_Contrato],Contratos[Id_Contrato]))
		formatString: 0
		lineageTag: c20f5b1d-b6ee-4832-9460-37d0bddf167b

	measure _Unidades_Relacionadas_Contratos =
			CALCULATE(VALUES(Contratos[Id_Contrato]),
			USERELATIONSHIP(Contratos[Id_Contrato],'Documentos em Análise'[Id_Contrato]))
		lineageTag: 521d6e52-25c1-4d03-bbe3-90664e73f1a7

	measure ###ATRASADOS = CALCULATE([_Total_Documentos],'Documentos em Análise'[Status] = "Atrasado")
		formatString: 0
		lineageTag: d47cc9c6-1190-4074-9e34-d3bb1975460e

	measure '###PRÓXIMAS ENTREGAS' = CALCULATE([_Total_Documentos],'Documentos em Análise'[Status] = "Próxima Entrega")
		formatString: 0
		lineageTag: 3f14b095-0f58-4398-93ce-93f00be58ae8

	measure 'Grupo de Auditoria' = ```
			
			CALCULATE (
			    SELECTEDVALUE ( TabelaCronograma[Grupo] ),
			    FILTER (
			        TabelaCronograma,
			        TabelaCronograma[Mês auditoria] = MONTH ( TODAY() )
			    )
			)
			
			```
		lineageTag: eda72a77-2fe0-42f2-a137-2b37f2e6471a

	measure 'Cor documento' =
			
			SWITCH(TRUE(),
			SELECTEDVALUE('Documentos em Análise'[Doc Entra na Auditoria]) = "Dentro da Auditoria", "black",
			SELECTEDVALUE('Documentos em Análise'[Tipo de Doc (Auditável/Mensal)]) = "Auditável", "grey",
			SELECTEDVALUE('Documentos em Análise'[Tipo de Doc (Auditável/Mensal)]) = "Mensal", "black"
			)
		lineageTag: 824931f3-88af-46ed-b6f5-0a0cda8c0102

	measure 'Mês de auditoria' =
			
			
			VAR Ano = YEAR(TODAY())  -- pode ser qualquer ano
			VAR MesNum = SELECTEDVALUE('Documentos em Análise'[Mês Auditoria Documento] ) -- número 1–12
			RETURN
			FORMAT(DATE(Ano, MesNum, 1), "mmmm")
		lineageTag: e90ea8d2-7a9b-4f0c-acad-be63e6281471

	column Documento
		dataType: string
		lineageTag: d5f82226-1c97-4b36-856d-fe9033aa5fe0
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: abd7cc4e-5251-4dd9-bca6-2fdefef44b0f
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: d1db0887-7608-4921-b0d0-55e8d967cfae
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 3643d765-de0a-41b0-baf5-0d6d577e16a1
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 9d70f986-7488-4fc4-b868-ee31c27c0126
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: b3cd0473-d63b-419b-b1dc-d03b258440e2
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 8c86c10a-baf0-4066-9d85-63ccd661bee4
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: d-m-yy
		lineageTag: 88631286-9557-4c4a-99e1-e66718300c15
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: b6118b9f-17b5-4365-b86a-94681a560edc
			defaultHierarchy: LocalDateTable_601600e6-bb4d-43b9-b6d2-852c3b8420b6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Status
		dataType: string
		lineageTag: 3dfe1e27-a33e-4342-9b1e-08c28976946d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: 61d21e61-d1e7-45c6-912e-66113eaf8bcb
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: fe7f7f20-4582-46a3-9b12-cd3d02ff1fa8
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column 'Status (Reclassificado)'
		dataType: string
		lineageTag: aa9f93ea-f496-4430-b672-823e7a1c17ee
		summarizeBy: none
		sourceColumn: Status (Reclassificado)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 5813ea47-6254-43c1-b215-017a8c334e3f
		summarizeBy: none
		sourceColumn: Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Chave Fornecedores'
		dataType: string
		lineageTag: 1bc51141-3225-4207-beb8-7fe0d9d28f80
		summarizeBy: none
		sourceColumn: Chave Fornecedores

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 63f5bf03-e1a4-47cd-ad96-94d47f271c71
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Data da Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: eab0069a-5b47-46f7-b4a3-47c3cfbd278e
		summarizeBy: none
		sourceColumn: Data da Análise

		variation Variation
			isDefault
			relationship: e3235d18-953f-4421-a55e-8ccd744820af
			defaultHierarchy: LocalDateTable_357696e8-dd17-4215-94fe-b3ee76ea8695.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Peso do Documentos' = LOOKUPVALUE('Classificação Docs'[Peso],'Classificação Docs'[Documento],'Documentos em Análise'[Documento])
		formatString: 0
		lineageTag: aaea68fa-a9a8-4ea7-b743-2bd84f46926a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Chave Status Forne'
		dataType: string
		lineageTag: e0270797-9abb-4d60-a5df-f3980818c9ae
		summarizeBy: none
		sourceColumn: Chave Status Forne

		annotation SummarizationSetBy = Automatic

	column 'Início do Mês'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4dc0a292-2d87-4b75-81e0-5fd916acc229
		summarizeBy: none
		sourceColumn: Início do Mês

		variation Variation
			isDefault
			relationship: a9d9fd61-8d69-4f49-a994-a87c6d8f60ae
			defaultHierarchy: LocalDateTable_48db6bef-46cc-436d-b9b3-ecc8ff826528.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo do documento'
		dataType: string
		lineageTag: bd802db9-dadf-43bb-b331-053f4014d200
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Doc'
		dataType: string
		lineageTag: 65c4c2ed-89ba-40af-a3fa-5fea0be6bed7
		summarizeBy: none
		sourceColumn: Tipo de Doc

		annotation SummarizationSetBy = Automatic

	column Recorrência
		dataType: string
		lineageTag: 800d3130-8c7b-485e-9356-978f235f303f
		summarizeBy: none
		sourceColumn: Recorrência

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 2d398353-473a-4eca-9ca1-f47d6a82c0d8
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Data de Envio'
		dataType: dateTime
		formatString: dd-mm-yy
		lineageTag: 7d2418a0-6c00-470a-a123-4dd74d7bbffe
		summarizeBy: none
		sourceColumn: Data de Envio

		variation Variation
			isDefault
			relationship: 819d05d5-a67f-47d5-8931-d9594f5173cd
			defaultHierarchy: LocalDateTable_9a453578-6439-4abb-bfb0-ff14bdd381e3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Id_Contrato
		dataType: string
		lineageTag: 991a457a-51f3-4ef2-befd-d505172d47cc
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tempo de Atraso'
		dataType: int64
		formatString: 0
		lineageTag: c292378c-7826-4b6e-a8e6-fb1a97b281ee
		summarizeBy: sum
		sourceColumn: Tempo de Atraso

		annotation SummarizationSetBy = Automatic

	column 'Status Envio'
		dataType: string
		lineageTag: b19d1d41-3b90-4c32-9f39-0943597477ba
		summarizeBy: none
		sourceColumn: Status Envio

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Doc (Auditável/Mensal)' = ```
			
			SWITCH(
			    TRUE(),
			    'Documentos em Análise'[Documento] = "Cartão de Ponto", "Mensal",
			    'Documentos em Análise'[Documento] = "Comprovante Bancário de Pagamento de Salários", "Mensal", 
			    'Documentos em Análise'[Documento] = "GPS ou DARF Pago + Recibo de Entrega DCTFWeb", "Mensal", 
			    'Documentos em Análise'[Documento] = "GFD Guia do FGTS Digital, Comprovante PIX e Relação de Trabalhadores", "Mensal",
			
			    "Auditável"
			)
			```
		lineageTag: fbe84009-720b-494c-bc30-8d01ad3affeb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Grupo =
			
			LOOKUPVALUE(
			    TabelaUnidades[Grupo], TabelaUnidades[Unidade], 'Documentos em Análise'[Unidade(s)]
			)
		lineageTag: 9a5fa69b-56da-4e84-9585-74c141701d1a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Doc Entra na Auditoria' = ```
			
			VAR MesAtual = MONTH(TODAY())
			VAR AnoAtual = YEAR(TODAY())
			
			-- Primeiro e último dia da janela
			VAR InicioJanela = EDATE(DATE(AnoAtual, MesAtual, 1), -5)  -- 5 meses atrás, primeiro dia
			VAR FimJanela = EOMONTH(DATE(AnoAtual, MesAtual, 1), -2)    -- 2 meses atrás, último dia
			
			-- Grupo que será auditado neste mês
			VAR GrupoAuditoria =
			    FILTER(
			        TabelaCronograma,
			        TabelaCronograma[Mês auditoria] = MesAtual
			    )
			
			VAR GrupoDoc = 'Documentos em Análise'[Grupo]
			VAR TipoDoc = 'Documentos em Análise'[Tipo de Doc (Auditável/Mensal)]
			VAR Competencia = 'Documentos em Análise'[Competência]
			
			RETURN
			IF(
			    TipoDoc = "Auditável"
			        && COUNTROWS(FILTER(GrupoAuditoria, TabelaCronograma[Grupo] = GrupoDoc)) > 0
			        && Competencia >= InicioJanela
			        && Competencia <= FimJanela,
			    "Dentro da Auditoria",
			    "Fora da Auditoria"
			)
			
			
			```
		lineageTag: ded2dad1-c5ca-40af-8ab7-613262a8bdad
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Mês Auditoria Documento' = ```
			
			VAR GrupoDoc = 'Documentos em Análise'[Grupo]
			VAR MesCompetencia = MONTH('Documentos em Análise'[Competência])
			VAR TipoDoc = 'Documentos em Análise'[Tipo de Doc (Auditável/Mensal)]
			
			-- Filtrar todas as auditorias do grupo que abrangem este mês de competência
			VAR AuditoriaCorreta =
			    FILTER(
			        TabelaCronograma,
			        TabelaCronograma[Grupo] = GrupoDoc
			            && MOD(TabelaCronograma[Mês auditoria] - MesCompetencia + 12, 12) >= 2
			            && MOD(TabelaCronograma[Mês auditoria] - MesCompetencia + 12, 12) <= 5
			    )
			
			-- Mês da auditoria
			VAR MesAuditoria =
			    MAXX(AuditoriaCorreta, TabelaCronograma[Mês auditoria])
			
			RETURN
			IF(
			    TipoDoc = "Auditável",
			    MesAuditoria,
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: b8b6e64b-6dda-447d-8cb5-6bf02a01a0e0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Status Envio Docs Auditados' = ```
			
			VAR DocAuditoria = 'Documentos em Análise'[Doc Entra na Auditoria]
			VAR DataEnvio = 'Documentos em Análise'[Data de Envio]
			VAR MesAuditoria = 'Documentos em Análise'[Mês Auditoria Documento]
			VAR MesCompetencia = MONTH('Documentos em Análise'[Competência])
			VAR AnoCompetencia = YEAR('Documentos em Análise'[Competência])
			VAR TipoDoc = 'Documentos em Análise'[Tipo de Doc (Auditável/Mensal)]
			
			-- Ajuste do ano da auditoria
			VAR AnoAuditoria = AnoCompetencia + IF(MesAuditoria < MesCompetencia, 1, 0)
			
			-- Último dia do mês anterior à auditoria
			VAR DataLimite = EOMONTH(DATE(AnoAuditoria, MesAuditoria, 1), -1)
			
			RETURN
			IF(
			    TipoDoc = "Auditável",
			    IF(
			        ISBLANK(DataEnvio),
			        "Não Enviado",
			        IF(DataEnvio <= DataLimite, "Enviado", "Enviado")
			    ),
			    IF(
			    'Documentos em Análise'[Status Envio] = "Atrasado",
			    "Não enviado", 
			        IF('Documentos em Análise'[Status Envio] =  "Enviado Atrasado" || 
			        'Documentos em Análise'[Status Envio] =  "Enviado no Prazo", 
			        "Enviado"
			)
			))
			```
		lineageTag: 79ab8417-8c8d-4892-a3f6-506f749ceebd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Prazo Envio Docs Auditados' = ```
			
			VAR DocAuditoria = 'Documentos em Análise'[Doc Entra na Auditoria]
			VAR MesAuditoria = 'Documentos em Análise'[Mês Auditoria Documento]
			VAR MesCompetencia = MONTH('Documentos em Análise'[Competência])
			VAR AnoCompetencia = YEAR('Documentos em Análise'[Competência])
			
			-- Ajuste do ano da auditoria
			VAR AnoAuditoria = AnoCompetencia + IF(MesAuditoria < MesCompetencia, 1, 0)
			
			-- Último dia do mês anterior à auditoria
			VAR DataLimiteAuditoria = EOMONTH(DATE(AnoAuditoria, MesAuditoria, 1), -1)
			
			-- Prazo original da coluna
			VAR PrazoOriginal = 'Documentos em Análise'[Prazo de Envio]
			
			RETURN
			IF(
			    DocAuditoria = "Dentro da Auditoria",
			    DataLimiteAuditoria,
			    PrazoOriginal
			)
			
			```
		formatString: dd-mm-yy
		lineageTag: e1cf6153-cc9a-4456-9c97-8532993bc0af
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 1135b626-c147-424a-adee-e6ac3008039b
			defaultHierarchy: LocalDateTable_d2b1d3bd-f28c-444f-8cf3-3fd50eb7779d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'mes competencia' = MONTH('Documentos em Análise'[Competência])
		formatString: 0
		lineageTag: d55112be-0b97-4690-a46a-10bc2e1cda29
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ano competencia' = YEAR('Documentos em Análise'[Competência])
		formatString: 0
		lineageTag: 03652ceb-1cd0-4182-82c2-07ad81e3bb11
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Nome mês de auditoria' =
			
			
			
			VAR Ano = YEAR(TODAY())  -- pode ser qualquer ano
			VAR MesNum = 'Documentos em Análise'[Mês Auditoria Documento] -- número 1–12
			RETURN
			IF(
			    'Documentos em Análise'[Mês Auditoria Documento] = BLANK(), BLANK(),
			    FORMAT(DATE(Ano, MesNum, 1), "mmmm")
			)
		lineageTag: 4d6800e1-04a5-4db4-b32c-37b17b27a1d5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Documentos em Análise' = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = GETDATE();#(lf)DECLARE @organizationId uniqueidentifier = 'ff063ad2-100d-4f34-895b-5af6697eec11';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = EOMONTH(GETDATE());#(lf)#(lf)WITH DocumentScheduleBuildings AS (#(lf)    SELECT#(lf)        [dsb].[DocumentScheduleId],#(lf)        STRING_AGG([b].[TradeName], ', ') AS [Buildings]#(lf)    FROM#(lf)        [DocumentScheduleBuilding] AS [dsb]#(lf)        INNER JOIN [Building] AS [b] ON [dsb].[BuildingId] = [b].[Id]#(lf)    WHERE#(lf)        [dsb].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsb].[DocumentScheduleId]#(lf)),#(lf)DocumentScheduleCategories AS (#(lf)    SELECT#(lf)        [dsc].[DocumentScheduleId],#(lf)        STRING_AGG([c].[Name], ', ') AS [Categories]#(lf)    FROM#(lf)        [DocumentScheduleCategory] AS [dsc]#(lf)        INNER JOIN [Category] AS [c] ON [dsc].[CategoryId] = [c].[Id]#(lf)    WHERE#(lf)        [dsc].[Removed] = CAST(0 AS bit)#(lf)    GROUP BY#(lf)        [dsc].[DocumentScheduleId]#(lf))#(lf)SELECT#(lf)    DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)#(tab)#(lf)#(tab)CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)    [ds].Id AS [DocumentScheduleId],#(lf)#(tab)[c].Id AS [Id_Contrato],#(lf)    CASE#(lf)        WHEN [c].[OrderNumber] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [c].[OrderNumber]#(lf)    END AS [Número do Pedido],#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        CASE#(lf)            WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)            WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)            WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)            WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)            WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)            WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)            WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)            WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)            WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)            ELSE 'Nenhum'#(lf)        END#(lf)    END AS [Tipo de Contrato],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)#(tab)[bc].[CompanyName] AS [Razão Social],#(lf)    dbo.FormatCNPJ(bc.Document) as [CNPJ],#(lf)    CASE#(lf)        WHEN [er].[Name] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [er].[Name]#(lf)    END AS [Funcionário],#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(tab)FORMAT([ds].[UploadedAt], 'dd/MM/yyyy') AS [Data de Envio],#(lf)#(tab)FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)    CASE#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Atrasado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Próxima Entrega'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Atrasado Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Próxima Entrega Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL#(lf)        THEN#(lf)            'Em Análise'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 0#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[IsValidated] IS NOT NULL AND [ds].[IsValidated] = 1#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)ELSE#(lf)            '--'#(lf)    END AS [Status],#(lf)    ISNULL(dsBuildings.[Buildings], '---') AS [Unidade(s)],#(lf)    ISNULL(dsCategories.[Categories], '---') AS [Categoria(s)]#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    LEFT JOIN [DocumentScheduleBuildings] AS dsBuildings ON [ds].[Id] = dsBuildings.[DocumentScheduleId]#(lf)    LEFT JOIN [DocumentScheduleCategories] AS dsCategories ON [ds].[Id] = dsCategories.[DocumentScheduleId]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        [c].[Removed] = 0#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            (#(lf)                ([ds].[ContractId] IS NOT NULL AND [ds].[ContractId] = [c].[Id])#(lf)                OR [ds].[ContractId] IS NULL#(lf)            )#(lf)            OR (#(lf)                (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                        AND EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                        AND NOT EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND (#(lf)                    ([ds].[ContractSetId] IS NOT NULL AND [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                    OR [ds].[ContractSetId] IS NULL#(lf)                )#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) #(lf)                    )#(lf)                ) -- unidades#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- categorias#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    (#(lf)                        [d].[DeliveryKind] <> 0#(lf)                        AND [d].[DeliveryKind] <> 1#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0#(lf)                                AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                ) -- deliveykind#(lf)                AND (#(lf)                    -- Agendamento por funcionario#(lf)                    (#(lf)                        [er].[Id] IS NOT NULL#(lf)                        AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                        AND [ds].[Kind] = 5#(lf)                        AND EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                                AND [erc].[ContractId] = [c].[Id]#(lf)                                AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                    -- / Agendamento por funcionario#(lf)                    -- Agendamento comum#(lf)                    OR (#(lf)                        [ds].[EmployeeRegisterId] IS NULL#(lf)                        AND [ds].[ContractId] IS NULL#(lf)                        AND [ds].[Kind] = 1#(lf)                    )#(lf)                    -- / Agendamento comum#(lf)                    -- Agendamento por unidade#(lf)                    OR (#(lf)                        [ds].Kind = 4#(lf)                    )#(lf)                    -- / Agendamento por unidade#(lf)                )#(lf)            )#(lf)        )#(lf)    )#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)-- ORDER BY #(lf)--     [p].[TradeName], [d].[Kind], [d].[Name], [ds].[ExpectedUploadAt], [er].[Name];"]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(Fonte, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Número do Pedido", type any}, {"Tipo de Contrato", type text}, {"Fornecedor", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Status (Reclassificado)", each if Text.Contains([Status], "Recusado") then "Enviado" else if [Status] = "Aprovado" then "Enviado" else if [Status] = "Em Análise" then "Enviado" else if [Status] = "Atrasado" then "Não Enviado" else if [Status] = "Próxima Entrega" then "No Prazo" else null),
				    #"Consultas Mescladas2" = Table.NestedJoin(#"Coluna Condicional Adicionada", {"Documento"}, #"Classificação Docs", {"Documento"}, "Classificação Docs", JoinKind.LeftOuter),
				    #"Classificação Docs Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas2", "Classificação Docs", {"Recorrência"}, {"Classificação Docs.Recorrência"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Classificação Docs Expandido",{{"Classificação Docs.Recorrência", "Recorrência"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas2", "Competência", each if [Tipo do documento]="Recorrente" then Date.AddMonths([Prazo de Envio],-1)
				else [Prazo de Envio]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Competência", type date}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado1", "Chave Fornecedores", each [Fornecedor]&[#"Categoria(s)"]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Número do Pedido", type text}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado2", "Chave", each [Fornecedor]&[CNPJ]&[#"Unidade(s)"]&[#"Categoria(s)"]&[Número do Pedido]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Personalização Adicionada2","---","",Replacer.ReplaceValue,{"Data da Análise"}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Valor Substituído",{{"Data da Análise", type date}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado3", "Chave Status Forne", each [Fornecedor]&[#"Categoria(s)"]&[#"Unidade(s)"]),
				    #"Início do Mês Inserido" = Table.AddColumn(#"Personalização Adicionada3", "Início do Mês", each Date.StartOfMonth([Competência]), type date),
				    #"Linhas Filtradas" = Table.SelectRows(#"Início do Mês Inserido", each ([Fornecedor] = "Fornecedor Orgânico Argo")),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Linhas Filtradas", "Personalizar", each if [Funcionário] = "---" then "Documento de Empresa" else "Documento de Funcionário"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Condicional Adicionada1",{{"Personalizar", "Tipo de Doc"}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Renomeadas1", each  ([Número do Pedido] <> "---") and ([Competência] >= #date(2024, 08, 01))),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Linhas Filtradas1", each true),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Linhas Filtradas2",{{"Data de Envio", type date}}),
				    #"Linhas Filtradas3" = Table.SelectRows(#"Tipo Alterado4", each true),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Linhas Filtradas3", "Tempo de Atraso", each if [Data de Envio] = null then 
				    Duration.Days(Date.From(DateTime.LocalNow()) - [Prazo de Envio]) 
				else 
				    Duration.Days([Data de Envio] - [Prazo de Envio])),
				    Personalizar1 = Table.AddColumn(#"Personalização Adicionada4", "Status Envio", each if [Data de Envio] = null then "Atrasado" else if [Tempo de Atraso] > 0 then "Enviado Atrasado" else "Enviado no Prazo"),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(Personalizar1,{{"Tempo de Atraso", Int64.Type}}),
				    #"Linhas Filtradas4" = Table.SelectRows(#"Tipo Alterado5", each ([#"Unidade(s)"] <> "Aparecida Shopping" and [#"Unidade(s)"] <> "DF Plaza" and [#"Unidade(s)"] <> "Shopping Crystal "))
				in
				    #"Linhas Filtradas4"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

