table 'Status de Funcionários'
	lineageTag: 27f5f462-2fbb-405a-92dc-2ada073c22d9

	column Nome
		dataType: string
		lineageTag: 2a40faa1-2418-4d05-a6cc-8337f8f31895
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Número de matrícula'
		dataType: string
		lineageTag: 3383d1b0-6ef1-42d7-9da1-7304eda41718
		summarizeBy: none
		sourceColumn: Número de matrícula

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 0cf6e6e8-cbc0-4e23-a8dd-cc3a75fa0804
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column PIS
		dataType: string
		lineageTag: 85f4889b-49b2-47fd-829d-fa7dad46b94e
		summarizeBy: none
		sourceColumn: PIS

		annotation SummarizationSetBy = Automatic

	column 'Documento Estrangeiro'
		dataType: string
		lineageTag: b0b06cab-cb9e-4b4f-bd28-3265bb3e6d3d
		summarizeBy: none
		sourceColumn: Documento Estrangeiro

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: be33c2f5-bf85-47bf-a425-4c777f64208a
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 16f48a19-d13e-48dd-84b8-bdc4229863fc
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: 0929b0ee-c45e-4aed-953a-043db675facd
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: d8daa700-ebf0-44f0-8839-e93302ede424
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 3c184942-bf7f-45ba-a780-351bc5b3fae7
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: 2eea26a1-7c3a-47fa-a1c6-6471f51041a0
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: 81578857-0df3-48bf-98b8-1bfb943c8662
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Número de matrícula_1'
		dataType: string
		lineageTag: a15ee36f-6699-45bb-a659-c5aea3937c87
		summarizeBy: none
		sourceColumn: Número de matrícula_1

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: cc397173-2b02-4ad3-8f27-c89e0473d992
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia do Subcontrato'
		dataType: string
		lineageTag: b423dd2a-a0c6-475b-a5fb-7afb1400fde3
		summarizeBy: none
		sourceColumn: Nome Fantasia do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: 4f626d64-6e13-420a-9b8c-07b174224922
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: d2e8b61c-b6be-4a80-8028-20786fe84077
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência do Contrato'
		dataType: string
		lineageTag: 9573aa85-0350-4c8e-ba54-d5d6bd5933c3
		summarizeBy: none
		sourceColumn: Vigência do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Início e Fim das Atividades'
		dataType: string
		lineageTag: 2346c200-b7ac-45fd-9930-67610e027f09
		summarizeBy: none
		sourceColumn: Início e Fim das Atividades

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: 6fd53da9-ab17-4efe-a928-e586f0b0b582
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Modalidade de Contratação'
		dataType: string
		lineageTag: 727018a9-a497-45a9-ac05-6e7d54670e09
		summarizeBy: none
		sourceColumn: Modalidade de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Tipo de moradia'
		dataType: string
		lineageTag: 6ee4d5ff-891d-4377-8457-38bfecf14bf5
		summarizeBy: none
		sourceColumn: Tipo de moradia

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 8c47da63-0efd-4dd6-ae8c-ee7a5014e91d
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: 2a3683a2-e16e-4f65-aa86-d91d611700af
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column Escala
		dataType: string
		lineageTag: 1209672d-4094-424c-93f6-e8c09e7101e5
		summarizeBy: none
		sourceColumn: Escala

		annotation SummarizationSetBy = Automatic

	column 'Início da jornada'
		dataType: dateTime
		formatString: Long Time
		lineageTag: c7191144-efb1-484d-bbd9-22f0c2d2be97
		summarizeBy: none
		sourceColumn: Início da jornada

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Término da jornada'
		dataType: dateTime
		formatString: Long Time
		lineageTag: cb0c901c-1ddd-4a7a-85a4-63a7712125c6
		summarizeBy: none
		sourceColumn: Término da jornada

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Total de Docs'
		dataType: int64
		formatString: 0
		lineageTag: 982e93cf-9882-4bcf-88eb-23bc7c931c22
		summarizeBy: sum
		sourceColumn: Total de Docs

		annotation SummarizationSetBy = Automatic

	column 'Total de válidos'
		dataType: int64
		formatString: 0
		lineageTag: f1ee005c-9cd7-450e-9574-49c961fa2ac5
		summarizeBy: sum
		sourceColumn: Total de válidos

		annotation SummarizationSetBy = Automatic

	column '% docs válidos'
		dataType: double
		lineageTag: 83323d72-158e-4948-8f63-793ac3c3be26
		summarizeBy: sum
		sourceColumn: % docs válidos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total em análise'
		dataType: int64
		formatString: 0
		lineageTag: 717ea546-5db4-4708-92ea-018345cb9c5e
		summarizeBy: sum
		sourceColumn: Total em análise

		annotation SummarizationSetBy = Automatic

	column '% docs em análise'
		dataType: double
		lineageTag: 422eb979-6ef0-4547-89d1-0b1f7b60b053
		summarizeBy: sum
		sourceColumn: % docs em análise

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total pendentes'
		dataType: int64
		formatString: 0
		lineageTag: 9adaab5d-905d-402d-add1-8428e284e094
		summarizeBy: sum
		sourceColumn: Total pendentes

		annotation SummarizationSetBy = Automatic

	column '% docs entregues'
		dataType: double
		lineageTag: 264028eb-e0dc-423c-88d6-470d9735f97e
		summarizeBy: sum
		sourceColumn: % docs entregues

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mobilizado até'
		dataType: string
		lineageTag: 95344e30-b4fa-4ac0-a7c7-1965a9eee3f9
		summarizeBy: none
		sourceColumn: Mobilizado até

		annotation SummarizationSetBy = Automatic

	column 'Próximo documento a vencer'
		dataType: string
		lineageTag: 61694909-7629-4cf3-8dca-9267611c3971
		summarizeBy: none
		sourceColumn: Próximo documento a vencer

		annotation SummarizationSetBy = Automatic

	column 'Status Restrição de acesso'
		dataType: string
		lineageTag: e9ee118d-c33d-4c24-8db2-6d3b8baedb97
		summarizeBy: none
		sourceColumn: Status Restrição de acesso

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes (Não entregues ou Recusados)'
		dataType: string
		lineageTag: 60dc17e4-657f-4947-8440-8257c2df5661
		summarizeBy: none
		sourceColumn: Documentos pendentes (Não entregues ou Recusados)

		annotation SummarizationSetBy = Automatic

	column Chave2
		dataType: string
		lineageTag: 8c1fe65d-1281-4a67-b4ad-b8a3cc0846ab
		summarizeBy: none
		sourceColumn: Chave2

		annotation SummarizationSetBy = Automatic

	column 'Data de Referência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f46cd87a-0fc3-44b9-ab5d-0cd797ba9329
		summarizeBy: none
		sourceColumn: Data de Referência

		variation Variation
			isDefault
			relationship: b1add9f3-6962-400d-9dc8-e47e7f13336b
			defaultHierarchy: LocalDateTable_dcc6a55c-68db-46d9-91b5-5f93c0fcf913.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Chave
		dataType: string
		lineageTag: 4eeccf4b-c40d-4386-ae1a-e7f1683e2883
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	partition 'Status de Funcionários' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://adminatlasinovacoescom.sharepoint.com/:x:/r/sites/DiretrioPadro/Documentos%20Compartilhados/Relat%C3%B3rios/Dados/02.%20Externo/03.%20Consultoria/Argo/Setup/Relat%C3%B3rio%20de%20Funcion%C3%A1rios.xlsx"), null, true),
				    #"Status de Funcionários_Sheet" = Fonte{[Item="Status de Funcionários",Kind="Sheet"]}[Data],
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Status de Funcionários_Sheet", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"Chave", "Chave2"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Nome", type text}, {"Número de matrícula", type text}, {"CPF", type text}, {"PIS", type text}, {"Documento Estrangeiro", type text}, {"Fornecedor", type text}, {"Razão Social", type text}, {"CNPJ", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Razão Social do Contrato", type text}, {"CNPJ do Contrato", type text}, {"Número de matrícula_1", type text}, {"Tipo de Fornecedor", type text}, {"Nome Fantasia do Subcontrato", type text}, {"Razão Social do Subcontrato", type text}, {"CNPJ do Subcontrato", type text}, {"Vigência do Contrato", type text}, {"Tipo de Contratação", type text}, {"Modalidade de Contratação", type text}, {"Tipo de moradia", type text}, {"Número do Pedido", type text}, {"Função", type text}, {"Escala", type text}, {"Início da jornada", type time}, {"Término da jornada", type time}, {"Total de Docs", Int64.Type}, {"Total de válidos", Int64.Type}, {"% docs válidos", type number}, {"Total em análise", Int64.Type}, {"% docs em análise", type number}, {"Total pendentes", Int64.Type}, {"% docs entregues", type number}, {"Mobilizado até", type text}, {"Próximo documento a vencer", type text}, {"Status Restrição de acesso", type text}, {"Documentos pendentes (Não entregues ou Recusados)", type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado1", "Chave", each [Fornecedor]&[Categoria]&[Unidade]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Data de Referência", type date}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [Data de Referência] > #date(2025, 3, 31)),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Linhas Filtradas", {{"Início da jornada", null}}),
				    #"Erros Substituídos1" = Table.ReplaceErrorValues(#"Erros Substituídos", {{"Término da jornada", null}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Erros Substituídos1", each ([Fornecedor] = "Fornecedor Orgânico Argo") and ([Unidade] <> "Aparecida Shopping" and [Unidade] <> "DF Plaza" and [Unidade] <> "Shopping Crystal "))
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

