table Contratos
	lineageTag: 33203019-45b3-4408-9f6f-bbcb107f01e5

	measure _Contratos_ = CALCULATE(DISTINCTCOUNT(Contratos[Id_Contrato]))
		formatString: 0
		lineageTag: 78ae437f-f4ab-4fb9-978e-1becc6851f59

	column 'Razão Social'
		dataType: string
		lineageTag: 123533f8-d77d-4273-a6d4-76cb93d7a29c
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: e7043ae3-a889-4722-a2af-32f88381ee05
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 9a0cfd55-99a8-441b-a8c5-719c02c51f7a
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 83373f62-d1f1-4cc0-bdbb-015915266d55
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6bf48811-0194-4537-83a2-f22a4915c34d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3485691-3867-4ae6-91ba-20c1cc1f0184
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 79fcae21-1c72-499a-af60-6e6cf92a10c8
			defaultHierarchy: LocalDateTable_f2b77408-f670-4ea2-92e4-56df79cc7986.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: d47859b7-10c7-4a3b-9d46-050771f7877e
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: be323ba9-9fed-465e-b8ae-e6432016b5ac
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 802284ed-82f2-40f6-850b-28a1b0425157
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 9108edd6-2f04-4e2c-9ee0-c7f0fd45e23f
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: int64
		formatString: 0
		lineageTag: b2d76fbe-4ee9-471a-8403-e132b5df580d
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: af815e2b-dc87-40cd-bb49-5eed4b200da2
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 523df4ea-f6a1-4db1-a74c-677e2ae17baa
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicial'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d123a2d-7401-4f6b-96f3-a7f57db8180e
		summarizeBy: none
		sourceColumn: Vigência Inicial

		variation Variation
			isDefault
			relationship: 5ca2bc5c-b041-4969-a9fe-58659a49c81e
			defaultHierarchy: LocalDateTable_ee2c871d-52be-4563-9c7a-f78d7bdd35af.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Final'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 049d5a3b-711d-4347-8468-3cd399b14552
		summarizeBy: none
		sourceColumn: Vigência Final

		variation Variation
			isDefault
			relationship: 119c718b-5ed6-4043-b4cd-fe4fdbca8c59
			defaultHierarchy: LocalDateTable_48923555-b9e6-4759-8e19-a775fc7fdb41.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status Contrato'
		dataType: string
		lineageTag: cff701c0-d61f-4032-b933-8eeae91dc623
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column 'Nome do Gestor'
		dataType: string
		lineageTag: da7b6965-6b87-4261-9f6c-6ef033c2ef6a
		summarizeBy: none
		sourceColumn: Nome do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 81dc1407-11ba-435e-b755-57bf84cbc2ed
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Grupo de Risco - Mobilização'
		dataType: string
		lineageTag: afc41e83-48da-42e0-b6e4-5791eaeac562
		summarizeBy: none
		sourceColumn: Grupo de Risco - Mobilização

		annotation SummarizationSetBy = Automatic

	column 'Data Original do Contrato'
		dataType: string
		lineageTag: 52dfa6de-c96e-49e9-8f54-a3ec4c943524
		summarizeBy: none
		sourceColumn: Data Original do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Objeto de Contrato'
		dataType: string
		lineageTag: e082db9f-573c-45a2-846e-ea574e525934
		summarizeBy: none
		sourceColumn: Objeto de Contrato

		annotation SummarizationSetBy = Automatic

	column CNO
		dataType: string
		lineageTag: 54cbeb61-0084-4d52-a982-17e616bc0cb6
		summarizeBy: none
		sourceColumn: CNO

		annotation SummarizationSetBy = Automatic

	column 'Data de Mobilização'
		dataType: string
		lineageTag: 5721aa71-b47a-4823-bec4-6117cd11d0ff
		summarizeBy: none
		sourceColumn: Data de Mobilização

		annotation SummarizationSetBy = Automatic

	column 'Grau de Risco - Trabalhista'
		dataType: string
		lineageTag: 04c7aaca-62b9-4be4-9adf-de8c442531f7
		summarizeBy: none
		sourceColumn: Grau de Risco - Trabalhista

		annotation SummarizationSetBy = Automatic

	column 'Nome do Gestor do Contrato'
		dataType: string
		lineageTag: dd932cdc-a0d4-48fe-9106-e96cba1f5556
		summarizeBy: none
		sourceColumn: Nome do Gestor do Contrato

		annotation SummarizationSetBy = Automatic

	column 'E-mail do Gestor do Contrato'
		dataType: string
		lineageTag: cbce6507-5016-40d9-a410-c2b4a3cbb3e7
		summarizeBy: none
		sourceColumn: E-mail do Gestor do Contrato

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 573b0061-5da5-4f53-9f2e-60e04e9c376b
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column 'Data da Solicitação'
		dataType: string
		lineageTag: fb096c26-bced-4d78-95cb-db6f247ef772
		summarizeBy: none
		sourceColumn: Data da Solicitação

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[Número do Pedido],#(lf)    bc.CompanyName[Razão Social],#(lf)    dbo.FNCNPJMask([bc].[Document]) AS [CNPJ],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],#(lf)#(tab)cm.[Name][Nome do Gestor],#(lf)#(tab)cm.[Email][Email do Gestor],#(lf)#(tab)cm.[Phone][Telefone do Gestor],#(lf)#(tab)[Grupo de Risco].[Name] AS [Grupo de Risco - Mobilização],#(lf)#(tab)cfv2.[Value] AS [Data Original do Contrato],#(lf)#(tab)cfv3.[Value] AS [Objeto de Contrato],#(lf)    cfv4.[Value] AS [CNO],#(lf)    cfv5.[Value] AS [Data de Mobilização],#(lf)#(tab)[Grau de Risco].[Name] AS [Grau de Risco - Trabalhista],#(lf)    cfv6.[Value] AS [Nome do Gestor do Contrato],#(lf)    cfv7.[Value] AS [E-mail do Gestor do Contrato],#(lf)    cfv8.[Value] AS [Solicitante],#(lf)    cfv9.[Value] AS [Data da Solicitação]#(lf)#(tab)#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)ContractManager cm with(nolock) on cm.ContractId = c.Id#(lf)#(tab)INNER JOIN #(lf)#(tab)#(tab)Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)INNER JOIN #(lf)#(tab)#(tab)Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)INNER JOIN #(lf)#(tab)#(tab)BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)INNER JOIN #(lf)#(tab)#(tab)[Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)INNER JOIN #(lf)#(tab)#(tab)[Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv2 WITH(NOLOCK) ON cfv2.EntityId = c.Id AND cfv2.CustomFieldId = '35F4D9D3-A055-4BBA-AC14-168B26BC2A07' -- Data original do início do contrato#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv3 WITH(NOLOCK) ON cfv3.EntityId = c.Id AND cfv3.CustomFieldId = 'B334C1D9-2CA3-4954-A7A4-7056362CC480' -- Objeto de Contrato#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv4 WITH(NOLOCK) ON cfv4.EntityId = c.Id AND cfv4.CustomFieldId = '4D0CB535-C054-4D66-96D5-A4C9A697DDF6' -- CNO#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv5 WITH(NOLOCK) ON cfv5.EntityId = c.Id AND cfv5.CustomFieldId = 'FE71101C-EA3A-4F21-A392-999EE3810D92' -- Data de Mobilização#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv6 WITH(NOLOCK) ON cfv6.EntityId = c.Id AND cfv6.CustomFieldId = 'BEA30E2D-D72D-466B-9DCF-E3963CDD894E' -- Nome do gestor do contrato#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv7 WITH(NOLOCK) ON cfv7.EntityId = c.Id AND cfv7.CustomFieldId = 'D76E189B-AF15-4881-B8EF-13AF376BDF5B' -- E-mail do gestor do contrato#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv8 WITH(NOLOCK) ON cfv8.EntityId = c.Id AND cfv8.CustomFieldId = '810B170B-D585-4EDA-BBD7-299F1E844750' -- Nome do solicitante#(lf)#(tab)LEFT JOIN #(lf)#(tab)#(tab)CustomFieldValue cfv9 WITH(NOLOCK) ON cfv9.EntityId = c.Id AND cfv9.CustomFieldId = '9D457DE9-8142-4098-95E6-312C255C85DE' -- Data da solicitação#(lf)#(tab)OUTER APPLY #(lf)    (#(lf)        SELECT cfi2.[Name]#(lf)        FROM CustomFieldValue cfv10 WITH(NOLOCK)#(lf)        INNER JOIN CustomFieldItem cfi2 WITH(NOLOCK) ON cfv10.CustomFieldItemId = cfi2.Id#(lf)        WHERE cfv10.EntityId = c.Id#(lf)            AND cfv10.Removed = 0#(lf)            AND cfi2.Removed = 0#(lf)            AND cfv10.CustomFieldId = 'fd7e2177-9dc6-4ca0-9b79-a7c88fa6abcb' -- Grupo de Risco - Mobilização#(lf)    ) AS [Grupo de Risco]#(lf)OUTER APPLY #(lf)    (#(lf)        SELECT cfi3.[Name]#(lf)        FROM CustomFieldValue cfv11 WITH(NOLOCK)#(lf)        INNER JOIN CustomFieldItem cfi3 WITH(NOLOCK) ON cfv11.CustomFieldItemId = cfi3.Id#(lf)        WHERE cfv11.EntityId = c.Id#(lf)            AND cfv11.Removed = 0#(lf)            AND cfi3.Removed = 0#(lf)            AND cfv11.CustomFieldId = '2740532e-e70c-434c-99e1-e9930cd607d5' -- Grau de Risco - Trabalhista#(lf)    ) AS [Grau de Risco]#(lf)where b.OrganizationId = '24d80b2f-c0de-4e58-9273-06a8de082474'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber#(lf)#(lf)#(tab) "]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Número do Pedido", type any}, {"Razão Social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"Sla", type text}, {"Status", type text}, {"Cadastro no sistema", type date}, {"Vigência", type text}, {"Unidade", type text}, {"Regional", type text}, {"Categoria", type text}, {"Fornecedor", type text}, {"Valor do contrato", Int64.Type}, {"Nome do Gestor", type text}, {"Email do Gestor", type text}, {"Telefone do Gestor", type any}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","NULL",null,Replacer.ReplaceValue,{"Número do Pedido"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","NULL","SEM GESTOR",Replacer.ReplaceText,{"Nome do Gestor"}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Valor Substituído1", "Vigência", Splitter.SplitTextByDelimiter(" a ", QuoteStyle.Csv), {"Vigência.1", "Vigência.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência.1", type date}, {"Vigência.2", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Vigência.1", "Vigência Inicial"}, {"Vigência.2", "Vigência Final"}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(
				    #"Colunas Renomeadas",
				    "Status Contrato",
				    each 
				        if [Vigência Final] < DateTime.Date(DateTime.LocalNow()) then "Vigência Finalizada"
				        else if [Vigência Inicial] > DateTime.Date(DateTime.LocalNow()) then "Vigência Futura"
				        else "Vigente"
				),
				    #"Dividir Coluna por Delimitador1" = Table.SplitColumn(#"Coluna Condicional Adicionada", "Email do Gestor", Splitter.SplitTextByDelimiter("@", QuoteStyle.Csv), {"E-mail do Gestor.1", "E-mail do Gestor.2"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador1",{{"E-mail do Gestor.1", type text}, {"E-mail do Gestor.2", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado2",{"E-mail do Gestor.2"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Colunas Removidas","."," ",Replacer.ReplaceText,{"E-mail do Gestor.1"}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Valor Substituído2",{{"E-mail do Gestor.1", Text.Proper, type text}}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Colocar Cada Palavra Em Maiúscula","Null","SEM GESTOR",Replacer.ReplaceText,{"E-mail do Gestor.1"}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Valor Substituído3",{"Nome do Gestor"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"E-mail do Gestor.1", "Nome do Gestor"}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Renomeadas1", {"Id_Contrato"})
				in
				    #"Duplicatas Removidas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

