table Contratos
	lineageTag: 1fd70a1f-e20f-49bf-89f4-880cb325b5f9

	column CNPJ
		dataType: string
		lineageTag: 7a3d5058-81e8-48a8-8501-51c7d57bda87
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: d161d663-6e3c-496c-9e02-61057a061737
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3f757940-f19d-45be-86f1-73a9b7a69ba5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 631462a0-35f8-46f0-a32c-dbcf4dcc654f
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 981e8b82-c32f-40ce-8008-2c6ea563dd4a
			defaultHierarchy: LocalDateTable_0b2a5d4c-cb90-4c9f-a030-6dd6d808f000.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: f34ee242-8a86-4fba-8937-ec2c97b22d15
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 9362236c-15de-4969-a4ca-9fe3a14d0195
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 6ab54d3a-1196-498f-ab6b-d4e79ba55f7c
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'N° do pedido'
		dataType: string
		lineageTag: 722a1008-a834-4b2b-8262-0e7e4aeb3246
		summarizeBy: none
		sourceColumn: N° do pedido

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: c013ac1b-711e-4db9-86ff-9ca5699a4cf8
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 1f51fa21-2c33-413a-8204-21893486aa3d
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 45b67d62-28e3-4791-ac67-146dd4eb4a71
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 919c7cfa-ccd6-408b-96ce-58c75f0fbf78
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 6995e896-5022-4b66-ba76-e1c0c91e9b8b
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: 8c44b616-4489-470d-b2f6-25c6bfd12556
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Email do Gestor'
		dataType: string
		lineageTag: 8e8a948c-f59c-4c1e-8bff-109a50a9840c
		summarizeBy: none
		sourceColumn: Email do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: 7ba80480-28fc-452e-9891-58f890a23078
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Status Contrato'
		dataType: string
		lineageTag: d9195dce-13e3-475b-a3cd-ca6d9a394c10
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicial'
		dataType: dateTime
		formatString: General Date
		lineageTag: c7cae3f4-37ea-48b5-8d8f-75415edf2e8c
		summarizeBy: none
		sourceColumn: Vigência Inicial

		variation Variation
			isDefault
			relationship: aaffd829-5ffc-478a-b48e-e5d2c7c55d44
			defaultHierarchy: LocalDateTable_ee7b9fe3-6b04-4e5c-a387-956ea507fc16.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Vigência Final'
		dataType: dateTime
		formatString: General Date
		lineageTag: d0f984e7-939b-4479-87d1-2e277c220df9
		summarizeBy: none
		sourceColumn: Vigência Final

		variation Variation
			isDefault
			relationship: a5cea7d8-ec5b-4ebf-8353-cbce66d9ab93
			defaultHierarchy: LocalDateTable_0c0b74f7-10fa-4a7b-ab75-cbcaba50740e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Gestor
		dataType: string
		lineageTag: d78a8b80-de8a-4d1f-9bd9-0b69be9d1827
		summarizeBy: none
		sourceColumn: Gestor

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)    bc.CompanyName[Razão Social],#(lf)   dbo.FNCNPJMask([bc].[Document]) AS [CNPJ],#(lf)#(tab)c.OrderNumber [Número do Pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    convert(date, c.ValidityInitial)[Vigência Inicial], #(lf)    convert(date, c.ValidityFinal)[Vigência Final],#(lf)#(lf)    CASE#(lf)        WHEN c.ValidityInitial > GETDATE() THEN 'Contrato Futuro'#(lf)        WHEN c.ValidityFinal < GETDATE() THEN 'Contrato Inativo'#(lf)        ELSE 'Contrato Vigente'#(lf)    END AS 'Status Contrato',#(lf)#(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],  #(lf)#(tab)ISNULL(cm.[Name],'SEM GESTOR')[Gestor],#(lf)#(tab)cm.[Email][Email do Gestor],#(lf)#(tab)cm.[Phone][Telefone do Gestor]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(tab)#(tab)left join ContractManager cm with(nolock) on cm.ContractId = c.Id#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)where b.OrganizationId = 'b271f317-ca46-4890-8f51-1d421363313d'#(lf)#(tab)  and c.Removed = 0#(lf)      and p.Id <> '16763E30-7AB1-4B2E-A2B7-5AD89E0068C9' -- 'Algar Demonstração'#(lf)#(lf)#(tab)  order by c.OrderNumber "]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Cadastro no sistema", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

