table 'Documentos em Análise'
	lineageTag: 941748fe-575a-4074-ae85-ff049f2ce062

	measure _Total_Documentos = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]))
		formatString: #,0
		lineageTag: 04d5e06f-36b4-43ce-8f4f-22bbd1954c85

	measure 'Documentos em Análise' =
			IF(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Em Análise")=0,0,CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Em Análise"))
		formatString: 0
		lineageTag: 2af97cb3-ff8f-40b7-9231-ac5b3dfb19ba

	measure '(Atrasados) Quantidade' =
			
			VAR Atrasados = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado")
			
			RETURN IF ( Atrasados = 0, 0 ,Atrasados)
		formatString: #,0
		lineageTag: 1333a4cf-2038-48a7-9d87-23b33dac0f17

	measure _Recusados_Quantidade =
			
			
			VAR Recusados = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado Recusado")
			
			RETURN IF(Recusados =0,0,Recusados)
		formatString: #,0
		lineageTag: 6b7513c8-21ca-431b-8a71-3638f9bc270c

	measure '(Enviados) Quantidade' =
			VAR ENVIADOS = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] <> "Atrasado")
			
			VAR Enviado = FORMAT(ENVIADOS,"#.##%")
			
			RETURN IF(ENVIADOS=BLANK(),0,ENVIADOS)
		formatString: #,0
		lineageTag: 227b0b6c-139e-4bbc-91f5-5947713a5084

	measure 'Quantidade de Enviados dividido por Documentos Total' =
			
			DIVIDE([(Enviados) Quantidade], [_Total_Documentos])
		lineageTag: 4563817b-edea-4742-a4db-3cf8fddf0535

		formatStringDefinition =
				VAR vEnviados = FORMAT([Quantidade de Enviados dividido por Documentos Total], "0.0%")
				VAR vTotal = [_Total_Documentos]
				VAR vResultado = """" & vEnviados & " (" & vTotal & ")"
				RETURN vResultado

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure _%_Recusados =
			
			VAR RECUSADO = CALCULATE([_Total_Documentos],
			'Documentos em Análise'[Status] = "Atrasado Recusado")
			
			VAR TOTAL = [_Total_Documentos]
			
			RETURN IF(RECUSADO = 0 && TOTAL >0,0,DIVIDE(RECUSADO,TOTAL))
		formatString: 0%;-0%;0%
		lineageTag: 122791aa-7e05-4c81-8408-54a5fbd781e4

	measure 'Quantidade de Analisado' = ```
			CALCULATE(CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] <> "Atrasado",
			'Documentos em Análise'[Status] <> "Em Análise"))
			
			```
		formatString: #,0
		lineageTag: b7a2b6b1-ded9-43e3-ba59-23fdc6ab3439

	measure 'Não Analisados' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Atrasado")
		formatString: #,0
		lineageTag: 1f105f0e-1510-473e-9fbd-836474bb154f

	measure 'Em Análise' =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			'Documentos em Análise'[Status] = "Em Análise")
		formatString: #,0
		lineageTag: d5965d6d-a3e3-461d-abef-c1d1da00dfb5

	measure _Peso_2 = ```
			
			VAR Peso1Count = 
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]), 
			        'Documentos em Análise'[Peso do Documentos] = 1)
			
			VAR Peso2CountNaoAprovado = 
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]), 
			        'Documentos em Análise'[Peso do Documentos] = 2, 
			        'Documentos em Análise'[Status] <> "Aprovado")
			
			VAR QuantPeso2 = [_Peso_2_Quantidade_Documentos]
			
			VAR Resultado =
			    IF(
			        QuantPeso2 = 0,
			        BLANK(),
			        IF(
			            Peso2CountNaoAprovado = 0,
			            0,
			            IF(
			                Peso1Count < 1,
			                Peso2CountNaoAprovado / QuantPeso2,
			                ((2/3) * Peso2CountNaoAprovado) / QuantPeso2
			            )
			        )
			    )
			
			RETURN Resultado
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9a286f2f-04b6-40fb-abbb-81b31291dbd4

	measure _Peso_1_Quantidade_Documentos =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 1)
		formatString: 0
		lineageTag: df2541e8-9a25-4f00-9435-7608e39c3f15

	measure _Peso_1 = ```
			
			VAR Peso2Count = 
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]), 
			        'Documentos em Análise'[Peso do Documentos] = 2)
			
			VAR Peso1CountNaoAprovado = 
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]), 
			        'Documentos em Análise'[Peso do Documentos] = 1, 
			        'Documentos em Análise'[Status] <> "Aprovado")
			
			VAR QuantPeso1 = [_Peso_1_Quantidade_Documentos]
			
			VAR Resultado =
			    IF(
			        QuantPeso1 = 0,
			        BLANK(),
			        IF(
			            Peso1CountNaoAprovado = 0,
			            0,
			            IF(
			                Peso2Count < 1,
			                Peso1CountNaoAprovado / QuantPeso1,
			                (1/3) * Peso1CountNaoAprovado / QuantPeso1
			            )
			        )
			    )
			
			RETURN Resultado
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bd6c8b62-db58-4b25-b8e1-4d014c447849

	measure _Peso_2_Quantidade_Documentos =
			CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Peso do Documentos] = 2)
		formatString: 0
		lineageTag: 3848ae26-b978-40dd-87fe-a74deb120435

	measure 'Quantidade Fornecedores - Total' = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[CNPJ]))
		formatString: 0
		lineageTag: a97ca23e-3625-46fe-a07a-ef2a728e4e98

	measure 'Quantidade Contratos - Total' = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[Número do Pedido]))
		formatString: 0
		lineageTag: 6360696d-3583-4992-8d06-46131b05c66d

	measure 'NUMERO DE PEDIDOS' = DISTINCTCOUNT('Documentos em Análise'[Número do Pedido])
		formatString: 0
		lineageTag: ac406a88-917f-4828-88a4-be92007d7ffa

	measure _%_Aderência =
			
			
			VAR Enviados = (CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Status] <> "Atrasado"))
			
			 VAR Agendados = [_Total_Documentos]
			
			 RETURN IF(
			            Enviados = 0 && Agendados>0,
			            0,
			            Enviados/Agendados
			            )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08f66f33-9d66-4549-a7fd-aedc37d60f49

	measure _%_Conformidade =
			
			VAR Aprovados = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]),
			        'Documentos em Análise'[Status] = "Aprovado")
			
			VAR Agendados = [_Total_Documentos]
			
			RETURN IF(
			            Aprovados=0 && Agendados >0,
			            0,
			            Aprovados/Agendados
			            )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eeb72fcd-9935-4986-8772-65ccf8e69fa1

	measure _%_Grupo_Risco = [_Peso_1] + [_Peso_2]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f259783d-acd9-461b-8907-b19e9512daff

	measure (Hoje) = TODAY()
		formatString: Short Date
		lineageTag: 620b5277-0a4c-4203-98cc-47370bb3acf2

	measure '_Média_Dias Atrasados' = CALCULATE(AVERAGE('Documentos em Análise'[Tempo de Atraso]),USERELATIONSHIP(Contratos[Id_Contrato],'Documentos em Análise'[Id_Contrato]))
		lineageTag: f2d77c36-860b-4338-8eb7-d0f65243b98f

		formatStringDefinition =
				VAR ATRAS = FORMAT([_Média_Dias Atrasados],"#")
				
				VAR QUANT = FORMAT([_Total_Documentos],"#,###")
				
				RETURN """" & ATRAS & " (" & QUANT & ")"

	measure '(Enviado) No Prazo' =
			CALCULATE([_Total_Documentos],
			'Documentos em Análise'[Status Envio] = "Enviado no Prazo")/[_Total_Documentos]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6daf8321-6b45-421a-ae1a-8e8c1d00a21c

	measure '(Atrasado) Peso 2' = ```
			
			VAR Peso1Count = 
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]), 
			        'Documentos em Análise'[Peso do Documentos] = 1)
			
			VAR Peso2CountNaoAprovado = 
			    CALCULATE(DISTINCTCOUNT('Documentos em Análise'[DocumentScheduleId]), 
			        'Documentos em Análise'[Peso do Documentos] = 2, 
			        'Documentos em Análise'[Status] = "Atrasado")
			
			VAR Resultado =
			    IF(
			        Peso1Count < 1,
			        Peso2CountNaoAprovado / [_Peso_2_Quantidade_Documentos],
			        ((2/3) * Peso2CountNaoAprovado) / [_Peso_2_Quantidade_Documentos]
			    )
			
			RETURN Resultado
			
			```
		lineageTag: 5366a350-16ba-4458-84c8-188f73bd39f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Pendência_Após o Prazo' =
			
			
			VAR CONTRATOS = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[Número do Pedido]),
			'Documentos em Análise'[Status Envio] = "Atrasado")
			
			
			RETURN IF(CONTRATOS=BLANK(),0,CONTRATOS)
		lineageTag: bc4f4135-7584-4276-a39a-d488081f269c

		formatStringDefinition =
				VAR FUNC = [_Pendência_Após o Prazo]
				
				VAR TOTAL = [(Pedidos) _Quantidade]
				
				RETURN """" & FUNC & " (" & FORMAT(FUNC/TOTAL,"#0.0%" & ")")

	measure '_Pendência_CNPJ Após o Prazo' =
			
			
			VAR CONTRATOS = CALCULATE(DISTINCTCOUNT('Documentos em Análise'[CNPJ]),
			'Documentos em Análise'[Status Envio] = "Atrasado")
			
			
			RETURN IF(CONTRATOS=BLANK(),0,CONTRATOS)
		lineageTag: 3fd803af-5cb6-4d72-8ab7-ff091b48bae6

		formatStringDefinition =
				VAR FUNC = [_Pendência_CNPJ Após o Prazo]
				
				VAR TOTAL = [_CNPJ_Quantidade_Relacao]
				
				RETURN """" & FUNC & " (" & FORMAT(FUNC/TOTAL,"#0.0%" & ")")

	measure _Dias_Atraso_ =
			CALCULATE(SUM('Documentos em Análise'[Tempo de Atraso]),
			USERELATIONSHIP(Contratos[Id_Contrato],'Documentos em Análise'[Id_Contrato]))
		formatString: 0
		lineageTag: efeea2bc-a3d6-41d7-954f-1e1c21d1c6b9

	measure _Pendentes_ =
			CALCULATE(
			    [_Total_Documentos],
			    'Documentos em Análise'[Status] <> "Em Análise" &&'Documentos em Análise'[Status] <> "Aprovado")
		formatString: 0
		lineageTag: 79226e13-7d63-4675-8d68-7d468938149e

	measure '!Status Bloqueio Pagamento' = ```
			
			VAR TotalDocs = [_Total_Documentos]
			VAR QtdBloqueio =
			    CALCULATE (
			        [_Total_Documentos],
			        'Documentos em Análise'[Bloqueio Pagamento] = "Bloqueio de Pagamento"
			    )
			VAR QtdPossivel =
			    CALCULATE (
			        [_Total_Documentos],
			        'Documentos em Análise'[Bloqueio Pagamento] = "Possível Bloqueio"
			    )
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( TotalDocs ), BLANK(),
			    QtdBloqueio > 0, "Bloqueio",
			    QtdPossivel > 0, "Atenção",
			    "S/B"
			)
			
			```
		lineageTag: 6c3bbba5-00c7-4bc1-9f99-c0597f542c79

	measure _Contratos_Quantidade = CALCULATE(DISTINCTCOUNT(Contratos[Número do Pedido]))
		formatString: 0
		lineageTag: a4e1a26e-681f-4782-a076-f8314a919fbf

	column Documento
		dataType: string
		lineageTag: d5f82226-1c97-4b36-856d-fe9033aa5fe0
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: abd7cc4e-5251-4dd9-bca6-2fdefef44b0f
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: d1db0887-7608-4921-b0d0-55e8d967cfae
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contrato'
		dataType: string
		lineageTag: 3643d765-de0a-41b0-baf5-0d6d577e16a1
		summarizeBy: none
		sourceColumn: Tipo de Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 9d70f986-7488-4fc4-b868-ee31c27c0126
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: b3cd0473-d63b-419b-b1dc-d03b258440e2
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 8c86c10a-baf0-4066-9d85-63ccd661bee4
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 88631286-9557-4c4a-99e1-e66718300c15
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: b6118b9f-17b5-4365-b86a-94681a560edc
			defaultHierarchy: LocalDateTable_601600e6-bb4d-43b9-b6d2-852c3b8420b6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 3dfe1e27-a33e-4342-9b1e-08c28976946d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: 61d21e61-d1e7-45c6-912e-66113eaf8bcb
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column 'Status (Reclassificado)'
		dataType: string
		lineageTag: aa9f93ea-f496-4430-b672-823e7a1c17ee
		summarizeBy: none
		sourceColumn: Status (Reclassificado)

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 5813ea47-6254-43c1-b215-017a8c334e3f
		summarizeBy: none
		sourceColumn: Competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Data da Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: eab0069a-5b47-46f7-b4a3-47c3cfbd278e
		summarizeBy: none
		sourceColumn: Data da Análise

		variation Variation
			isDefault
			relationship: e3235d18-953f-4421-a55e-8ccd744820af
			defaultHierarchy: LocalDateTable_357696e8-dd17-4215-94fe-b3ee76ea8695.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Peso do Documentos' = LOOKUPVALUE('Classificação Docs'[Peso],'Classificação Docs'[Documento],'Documentos em Análise'[Documento])
		formatString: 0
		lineageTag: aaea68fa-a9a8-4ea7-b743-2bd84f46926a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: cf086d50-6173-4855-86a4-b408b5f0889d
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column 'Tempo de Atraso'
		dataType: int64
		formatString: 0
		lineageTag: 8b9b749e-fafd-460d-9142-4e4454b6523f
		summarizeBy: sum
		sourceColumn: Tempo de Atraso

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Status (Enviado)'
		dataType: string
		lineageTag: 75d2aefa-8d5e-401b-bd05-6ca3f402dce4
		summarizeBy: none
		sourceColumn: Status (Enviado)

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 9e3d03d2-6495-40b0-a679-576779786b40
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Data de Envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 088e8d1f-b876-40e5-ad0d-9b29762d3982
		summarizeBy: none
		sourceColumn: Data de Envio

		variation Variation
			isDefault
			relationship: 81a1887c-7d3a-4fdf-9b33-f61fd46237cc
			defaultHierarchy: LocalDateTable_1c348a00-dcb9-41aa-a5e5-8798cb7dfb41.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status Envio'
		dataType: string
		lineageTag: d232d7aa-2ba0-4dcb-90c4-b1443f136926
		summarizeBy: none
		sourceColumn: Status Envio

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 8aa98466-f6e0-4bfa-900e-4f68e058cf4d
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Classificação Risco' = LOOKUPVALUE('Documentos Algar'[Classificação Docs.Classificação de Risco],'Documentos Algar'[Documento],'Documentos em Análise'[Documento])
		lineageTag: cfbf5677-b40c-4c5f-906b-b5d88e42149a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Peso do Documento' = LOOKUPVALUE('Documentos Algar'[Classificação Docs.Peso],'Documentos Algar'[Documento],'Documentos em Análise'[Documento])
		formatString: 0
		lineageTag: 243b3e18-74ca-4b47-b8d9-e98d68bab9e0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Bloqueio de Pagamento' = LOOKUPVALUE('Documentos Algar'[Classificação Docs.Prazo Bloqueio Pagamento],'Documentos Algar'[Documento],'Documentos em Análise'[Documento])
		lineageTag: 5f40a123-e651-44e9-a152-8c45127cdeca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Bloqueio Pagamento' = ```
			
			VAR vStatus =
			    'Documentos em Análise'[Status] 
			VAR vPrazoBloq =
			     'Documentos em Análise'[Prazo de Bloqueio de Pagamento]        -- "D+30" | "D+90" | "Indeterminado"
			VAR vPrazoEnvio =
			    'Documentos em Análise'[Prazo de Envio]          -- Data limite de envio
			
			-- Dias de atraso (se ainda não venceu, fica 0)
			VAR vDiasAtraso ='Documentos em Análise'[Tempo de Atraso]
			RETURN
			SWITCH (
			    TRUE (),
			
			    -- 1) Em Análise ou Aprovado => sem bloqueio
			    vStatus IN { "Em Análise", "Aprovado" }, "Sem Bloqueio de Pagamento",
			
			    -- 2) Indeterminado => sem bloqueio
			    vPrazoBloq = "Prazo indeterminado", "Sem Bloqueio de Pagamento",
			
			    -- 3) D+30 => se atraso > 30 bloqueia, senão possível bloqueio
			    vPrazoBloq = "D+30",
			        IF ( vDiasAtraso > 30, "Bloqueio de Pagamento", "Possível Bloqueio" ),
			
			    -- 4) D+90 => se atraso > 90 bloqueia, senão possível bloqueio
			    vPrazoBloq = "D+90",
			        IF ( vDiasAtraso > 90, "Bloqueio de Pagamento", "Possível Bloqueio" ),
			
			    -- fallback
			    "Fora da Condicional"
			)
			
			```
		lineageTag: 07e04f64-12dc-4f9f-975b-0cf285ed8e56
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: f126913d-eff8-44a4-b5a4-46c85a7ca22e
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column 'Status Bloqueio' = ```
			
			
			SWITCH(TRUE(), 
			'Documentos em Análise'[Bloqueio Pagamento] = "Sem Bloqueio de Pagamento","S/B",
			'Documentos em Análise'[Bloqueio Pagamento] = "Bloqueio de Pagamento","Bloqueio",
			'Documentos em Análise'[Bloqueio Pagamento] = "Possível Bloqueio","Atenção","---")
			```
		lineageTag: b6b2433d-d9a0-48f4-985d-abcb6332ebc3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Status Contrato'
		dataType: string
		lineageTag: e81d5d15-2ea2-4e2e-a7e4-1cdf66a3b971
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	partition 'Documentos em Análise' = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = GETDATE();#(lf)DECLARE @organizationId uniqueidentifier = 'b271f317-ca46-4890-8f51-1d421363313d';#(lf)DECLARE @initialDate datetime2 = '2022-01-01 00:00:00';#(lf)DECLARE @finalDate datetime2 = GETDATE() ;#(lf)#(lf)SELECT#(lf)    DISTINCT#(lf)    [ds].[Name] AS [Documento],#(lf)#(tab)CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)    [ds].Id AS [DocumentScheduleId],#(lf)    CASE#(lf)        WHEN [c].[OrderNumber] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [c].[OrderNumber]#(lf)    END AS [Número do Pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    CASE#(lf)        WHEN [c].[Type] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        CASE#(lf)            WHEN [c].[Type] & 1 = 1 THEN 'Contínuo'#(lf)            WHEN [c].[Type] & 2 = 2 THEN 'Grandes Paradas'#(lf)            WHEN [c].[Type] & 4 = 4 THEN 'Eventual'#(lf)            WHEN [c].[Type] & 8 = 8 THEN 'Temporário'#(lf)            WHEN [c].[Type] & 16 = 16 THEN 'Visitante técnico'#(lf)            WHEN [c].[Type] & 32 = 32 THEN 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)            WHEN [c].[Type] & 64 = 64 THEN 'Prestação de serviço eventual fora da área operacional'#(lf)            WHEN [c].[Type] & 128 = 128 THEN 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)            WHEN [c].[Type] & 256 = 256 THEN 'Compra Direta, Regulariza e Delegada'#(lf)            ELSE 'Nenhum'#(lf)        END#(lf)    END AS [Tipo de Contrato],#(lf)#(lf)    Case#(lf)        WHEN [ds].[ExpectedUploadAt] < '2024-09-01' then '09/2024'#(lf)        WHEN d.Frequency = 2 and d.DeliveryKind = 0 THEN FORMAT(DATEADD(MONTH, -1, [ds].[ExpectedUploadAt]), 'MM/yyyy')#(lf)        ELSE FORMAT([ds].[ExpectedUploadAt], 'MM/yyyy')#(lf)    END AS [Competência],#(lf)    #(lf)#(tab)CASE#(lf)        WHEN c.ValidityInitial > GETDATE() THEN 'Contrato Futuro'#(lf)        WHEN c.ValidityFinal < GETDATE() THEN 'Contrato Inativo'#(lf)        ELSE 'Contrato Ativo'#(lf)    END AS 'Status Contrato',#(lf)#(lf)#(tab)[bc].[CompanyName] AS [Razão Social],#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    dbo.FNCNPJMask([bc].[Document]) AS [CNPJ],#(lf)    CASE#(lf)        WHEN [er].[Name] IS NULL THEN#(lf)        '---'#(lf)    ELSE#(lf)        [er].[Name]#(lf)    END AS [Funcionário],#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN [ds].[UploadedAt] IS NULL THEN NULL#(lf)#(tab)#(tab)#(tab)ELSE  FORMAT([ds].[UploadedAt], 'dd/MM/yyyy') END AS [Data de Envio],#(lf)#(tab)FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data da Análise],#(lf)    CASE#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Atrasado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND ([ds].[UploadedAt] IS NULL)#(lf)        THEN#(lf)            'Próxima Entrega'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] < @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Atrasado Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[ExpectedUploadAt] >= @currentDate AND [ds].[RequiresValidation] = 1 AND ([ds].[UploadedAt] IS NOT NULL) AND ([ds].[ValidatedAt] IS NOT NULL) AND ([ds].[IsValidated] IS NOT NULL) AND [ds].[IsValidated] = 0#(lf)        THEN#(lf)            'Próxima Entrega Recusado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 1 AND [ds].[IsValidated] IS NULL#(lf)        THEN#(lf)            'Em Análise'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[RequiresValidation] = 0#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)WHEN#(lf)            [ds].[UploadedAt] IS NOT NULL AND [ds].[IsValidated] IS NOT NULL AND [ds].[IsValidated] = 1#(lf)        THEN#(lf)            'Aprovado'#(lf)#(tab)#(tab)ELSE#(lf)            '--'#(lf)    END AS [Status],#(lf)    b.TradeName AS [Unidade(s)],#(lf)    cat.Name AS [Categoria(s)]#(lf) #(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)    [c].[Removed] = 0#(lf)    AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)    AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)    AND (#(lf)        (#(lf)            ([ds].[ContractId] IS NOT NULL AND [ds].[ContractId] = [c].[Id])#(lf)            OR [ds].[ContractId] IS NULL#(lf)        )#(lf)        OR (#(lf)            (#(lf)                [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                OR (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                    AND EXISTS (#(lf)                        SELECT 1#(lf)                        FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                        WHERE value = [c].[OrderNumber]#(lf)                    )#(lf)                )#(lf)                OR (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                    AND NOT EXISTS (#(lf)                        SELECT 1#(lf)                        FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                        WHERE value = [c].[OrderNumber]#(lf)                    )#(lf)                )#(lf)            )#(lf)            AND (#(lf)                ([ds].[ContractSetId] IS NOT NULL AND [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                OR [ds].[ContractSetId] IS NULL#(lf)            )#(lf)            AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)            AND (#(lf)                (#(lf)                    ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                )#(lf)                OR (#(lf)                    NOT EXISTS (#(lf)                        SELECT#(lf)                            1#(lf)                        FROM#(lf)                            [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                        WHERE#(lf)                            [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                            AND [dsb].[Removed] = 0#(lf)                    ) OR EXISTS (#(lf)                        SELECT#(lf)                            1#(lf)                        FROM#(lf)                            [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                        WHERE#(lf)                            [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                            AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                            AND [dsb].[Removed] = 0#(lf)                    ) #(lf)                )#(lf)            ) -- unidades#(lf)            AND (#(lf)                (#(lf)                    ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                )#(lf)                OR (#(lf)                    NOT EXISTS (#(lf)                        SELECT#(lf)                            1#(lf)                        FROM#(lf)                            [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                        WHERE#(lf)                            [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                            AND [dsc].[Removed] = 0#(lf)                    ) OR EXISTS (#(lf)                        SELECT#(lf)                            1#(lf)                        FROM#(lf)                            [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                        WHERE#(lf)                            [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                            AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                            AND [dsc].[Removed] = 0#(lf)                    )#(lf)                )#(lf)            ) -- categorias#(lf)            AND (#(lf)                ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)            )#(lf)            AND (#(lf)                ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)            )#(lf)            AND (#(lf)                (#(lf)                    [d].[DeliveryKind] <> 0#(lf)                    AND [d].[DeliveryKind] <> 1#(lf)                )#(lf)                OR (#(lf)                    [d].[DeliveryKind] = 1#(lf)                    AND (#(lf)                        [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                        OR (#(lf)                            [d].[DeliveryDay] < 0#(lf)                            AND (#(lf)                                DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                OR (#(lf)                                    DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                    AND (#(lf)                        ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                        OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                    )#(lf)                )#(lf)                OR (#(lf)                    [d].[DeliveryKind] = 0#(lf)                    AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                    AND (#(lf)                        (#(lf)                            [d].[DeliveryDay] > 0#(lf)                            AND (#(lf)                                DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                OR (#(lf)                                    DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        OR (#(lf)                            [d].[DeliveryDay] < 0#(lf)                            AND (#(lf)                                DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                OR (#(lf)                                    DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                )#(lf)            ) -- deliveykind#(lf)            AND (#(lf)                -- Agendamento por funcionario#(lf)                (#(lf)                    [er].[Id] IS NOT NULL#(lf)                    AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                    AND [ds].[Kind] = 5#(lf)                    AND EXISTS (#(lf)                        SELECT#(lf)                            1#(lf)                        FROM#(lf)                            [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                        WHERE#(lf)                            [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                            AND [erc].[ContractId] = [c].[Id]#(lf)                            AND [erc].[Removed] = 0#(lf)                    )#(lf)                )#(lf)                -- / Agendamento por funcionario#(lf)                -- Agendamento comum#(lf)                OR (#(lf)                    [ds].[EmployeeRegisterId] IS NULL#(lf)                    AND [ds].[ContractId] IS NULL#(lf)                    AND [ds].[Kind] = 1#(lf)                )#(lf)                -- / Agendamento comum#(lf)                -- Agendamento por unidade#(lf)                OR (#(lf)                    [ds].Kind = 4#(lf)                )#(lf)                -- / Agendamento por unidade#(lf)            )#(lf)        )#(lf)    )#(lf))    INNER JOIN Building b                 WITH (NOLOCK) ON b.Id = c.BuildingId#(lf)    INNER JOIN Category cat               WITH (NOLOCK) ON cat.Id = c.CategoryId#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)    and p.Id <> '16763E30-7AB1-4B2E-A2B7-5AD89E0068C9' -- 'Algar Demonstração'#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Documento", type text}, {"DocumentScheduleId", type text}, {"Número do Pedido", type text}, {"Tipo de Contrato", type text}, {"Fornecedor", type text}, {"CNPJ", type text}, {"Funcionário", type text}, {"Prazo de Envio", type date}, {"Status", type text}, {"Unidade(s)", type text}, {"Categoria(s)", type text}, {"Data de Envio", type date}, {"Data da Análise", type date}, {"Competência", type date}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Status (Reclassificado)", each if Text.Contains([Status], "Recusado") then "Enviado" else if [Status] = "Aprovado" then "Enviado" else if [Status] = "Em Análise" then "Enviado" else if [Status] = "Atrasado" then "Não Enviado" else null),
				    #"Personalização Adicionada5" = Table.AddColumn(#"Coluna Condicional Adicionada", "Tempo de Atraso", each Duration.Days(Date.From(DateTime.LocalNow())-[Prazo de Envio]
				)),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Personalização Adicionada5", "Status (Enviado)", each if [Status] = "Atrasado Recusado" then "Recusado" else if [Status] = "Atrasado" then "Pendente" else "Enviado"),
				    #"Personalização Adicionada6" = Table.AddColumn(#"Coluna Condicional Adicionada1", "Status Envio", each if [Data de Envio] <> null and [Data de Envio] > [Prazo de Envio] then "Enviado Atrasado" 
				    else if [Data de Envio] <> null and [Data de Envio] <= [Prazo de Envio] then "Enviado no Prazo" 
				    else if [Data de Envio] = null and [Status] = "Atrasado" then "Atrasado" 
				    else null)
				in
				    #"Personalização Adicionada6"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

