table Reprovações
	lineageTag: a9e0228a-c4aa-4fcc-b9f6-5e5e348c68d1

	measure '(Enviados) Quantidade de Documentos' = DISTINCTCOUNT('Reprovações'[DocumentScheduleId])
		formatString: #,0
		lineageTag: a2c9a25d-faa8-4192-b965-0108dd3080a7

	measure '(Recusas) Quantidade de Recusas' =
			CALCULATE(DISTINCTCOUNT('Reprovações'[Id_Reanálise]),
			'Reprovações'[Status_Documentacao] = "Reprovado")
		formatString: #,0
		lineageTag: f209132e-a615-4d55-a867-fd6f7e33e085

	measure (%Reprovações) = [(Recusas) Quantidade de Recusas]/[(Análise) Quantidade de Análises]
		lineageTag: f6dc022a-6b48-46c2-bd6e-9b5e61c3d189

		formatStringDefinition =
				var porc = FORMAT('Reprovações'[(%Reprovações)],"0.0%")
				
				var anali = FORMAT([(Análise) Quantidade de Análises],"#,###")
				
				return """" & porc & " (" & anali & ")"

	measure '(Análise) Quantidade de Análises' = CALCULATE(DISTINCTCOUNT('Reprovações'[Id_Reanálise]))
		formatString: #,0
		lineageTag: d2049031-7e2b-4fce-bc9c-604f0b53f7be

	measure '(Taxa) de Recusas' = [(Recusas) Quantidade de Recusas]/[(Enviados) Quantidade de Documentos]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 58b1bec9-5768-41ba-9b24-f8783e610e35

	measure '(Recusas2) Quantidade de Recusas' =
			CALCULATE(DISTINCTCOUNT('Reprovações'[Id_Reanálise]),
			'Reprovações'[Status_Documentacao] = "Reprovado")
		lineageTag: b11bdb5f-81f1-4baf-8202-7a48ea74c117

		formatStringDefinition =
				VAR RECU = FORMAT([(Recusas) Quantidade de Recusas],"#,###")
				
				VAR ENVI = FORMAT([(Enviados) Quantidade de Documentos],"#,###")
				
				RETURN """" & RECU & " (" & ENVI & ")"

	column Id_Cliente
		dataType: string
		lineageTag: 1b161648-46fa-43ff-856b-02ffbc307b28
		summarizeBy: none
		sourceColumn: Id_Cliente

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 40adcb66-f7c6-450f-8b8b-169800cc2749
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Data_Envio
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0ec7ca2-cc09-4c7e-a923-ac7f726e6490
		summarizeBy: none
		sourceColumn: Data_Envio

		variation Variation
			isDefault
			relationship: 619a4651-f157-449f-8e3a-4aee345631cd
			defaultHierarchy: LocalDateTable_101ff77e-4e17-4516-80c4-f64ea4434338.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Status_Documentacao
		dataType: string
		lineageTag: df947257-1f7b-48ca-bee4-344aab37e7ab
		summarizeBy: none
		sourceColumn: Status_Documentacao

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 71826eb5-7217-4ed9-9724-140a98fe66cf
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 339d5418-b278-4721-a3c4-dff859e941fd
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Status Contrato'
		dataType: string
		lineageTag: f1306533-3d6b-4625-93bb-5a4f37e45fb9
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 01c2801f-495a-4fb4-a2b3-5d1bb760e282
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: c58995bc-ad8a-4bb1-9849-af8ad619f1ed
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentScheduleId
		dataType: string
		lineageTag: e9c4eea2-0aa5-453a-b9c0-5b9ddbce24f0
		summarizeBy: none
		sourceColumn: DocumentScheduleId

		annotation SummarizationSetBy = Automatic

	column 'Nome Cliente'
		dataType: string
		lineageTag: c2998014-9d84-4671-9823-5ee60fc13015
		summarizeBy: none
		sourceColumn: Nome Cliente

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 61cb8937-05c9-4bb8-be6a-0b03551026a7
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: f5b59119-f848-4384-81cc-8752032d072c
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column 'Analisado por'
		dataType: string
		lineageTag: 2baa1874-0cba-4f15-82a2-b5ec7b184af8
		summarizeBy: none
		sourceColumn: Analisado por

		annotation SummarizationSetBy = Automatic

	column Id_Validador
		dataType: string
		lineageTag: 3d1c9957-1fcf-42ff-a8d8-4cfa3c51de87
		summarizeBy: none
		sourceColumn: Id_Validador

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: string
		lineageTag: 129eb26f-c7df-4abf-b6b9-5f293a800bf3
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 84f540bc-d727-4511-bb02-3656c7f37332
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: 8c02efeb-d6b9-43ec-818e-67bc22ad2258
			defaultHierarchy: LocalDateTable_db5d89f7-b1d7-4506-87cb-b29373bb43a3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Data_Análise
		dataType: dateTime
		formatString: General Date
		lineageTag: e1c1e4a8-31f8-4ccf-acd1-53676bcc6efe
		summarizeBy: none
		sourceColumn: Data_Análise

		variation Variation
			isDefault
			relationship: 9899a185-7fc9-4b90-a6c3-ab1981605c54
			defaultHierarchy: LocalDateTable_2a099c2c-da9c-4092-95c5-128d6156f034.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Id_Reanálise
		dataType: string
		lineageTag: 06e8b78b-fac3-4973-b52c-e33cedf79c36
		summarizeBy: none
		sourceColumn: Id_Reanálise

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: b2a21edb-83df-4278-a552-aab6415ecf9a
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	column 'Número de Pedido'
		dataType: string
		lineageTag: 8bcdbbe9-a189-4427-af56-613c0c373460
		summarizeBy: none
		sourceColumn: Número de Pedido

		annotation SummarizationSetBy = Automatic

	partition Reprovações = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2       = CAST(GETDATE() AS DATETIME);#(lf)DECLARE @organizationId uniqueidentifier = 'b271f317-ca46-4890-8f51-1d421363313d';#(lf)DECLARE @initialDate datetime2       = '2025-11-01 00:00:00';#(lf)DECLARE @finalDate datetime2         = '2025-12-01 00:00:00';#(lf)#(lf)SELECT DISTINCT#(lf)       ds.Name AS [Documento],#(lf)#(tab)   ds.Id   AS [DocumentScheduleId],#(lf)#(tab)   o.TradeName as 'Nome Cliente',#(lf)           c.Id as 'Id_Contrato',#(lf)           c.OrderNumber as 'Número de Pedido',#(lf)#(tab)   CASE#(lf)            WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)            WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)            WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)    WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)            ELSE '--'#(lf)       END AS 'Tipo do documento',#(lf)#(lf)    c.Id AS [Id_Cliente],#(lf)    p.TradeName      AS [Fornecedor],#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN (ds.ValidatedBy =  '00000000-0000-0000-0000-000000000000' and dsv.Responsibleid is null) THEN 'Validado Automaticamente'#(lf)        WHEN dsv.Responsibleid =  '00000000-0000-0000-0000-000000000000' THEN 'Validado Automaticamente'#(lf)#(tab)#(tab)WHEN ds.RequiresValidation = 0 THEN 'Não é Necessário Validação'#(lf)        WHEN (ds.ValidatedBy IS NULL and dsv.Responsibleid is null) THEN 'Pendente de Validação'#(lf)        ELSE ISNULL(u.Name, '---') #(lf)    END AS 'Analisado por',#(lf)#(lf)#(tab)ISNULL(ISNULL (dsv.Responsibleid, ds.ValidatedBy), '00000000-0000-0000-0000-000000000000')  as 'Id_Validador',#(lf)#(lf)    CASE#(lf)        WHEN c.ValidityInitial > GETDATE() THEN 'Contrato Futuro'#(lf)        WHEN c.ValidityFinal < GETDATE() THEN 'Contrato Inativo'#(lf)        ELSE 'Contrato Ativo'#(lf)    END AS 'Status Contrato',#(lf)    b.TradeName[Unidade],#(lf)#(tab)bc.CompanyName[Razão Social],#(lf)#(tab)ca.[Name][Categoria],#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN (ds.ValidatedBy = '00000000-0000-0000-0000-000000000000' and dsv.Responsibleid is null) THEN 'Sistema'#(lf)        WHEN dsv.Responsibleid =  '00000000-0000-0000-0000-000000000000' THEN 'Sistema'#(lf)#(tab)#(tab)WHEN u.Email like '%Atlas%'  THEN 'Atlas'#(lf)        WHEN ds.ValidatedBy IS NULL THEN 'Pendente de Validação'#(lf)        ELSE 'Cliente'#(lf)    END AS 'Time',#(lf)#(lf)    FORMAT(ds.ExpectedUploadAt, 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(lf)    ISNULL(#(lf)        ISNULL(FORMAT(df.CreatedAt, 'dd/MM/yyyy HH:mm:ss'),#(lf)               FORMAT(df.UpdatedAt, 'dd/MM/yyyy HH:mm:ss')),#(lf)               FORMAT(ds.UploadedAt, 'dd/MM/yyyy HH:mm:ss')#(lf)    ) AS Data_Envio,#(lf)#(lf)#(tab)ISNULL(#(lf)        FORMAT(dsv.Createdat, 'dd/MM/yyyy HH:mm:ss'),#(lf)        FORMAT(ds.ValidatedAt, 'dd/MM/yyyy HH:mm:ss')#(lf)    ) AS Data_Análise,#(lf)#(tab)#(lf)#(tab)CASE#(lf)        WHEN ISNULL(dsv.IsValid, ds.IsValidated) = 1 THEN 'Aprovado'#(lf)        WHEN ISNULL(dsv.IsValid, ds.IsValidated) = 0 THEN 'Reprovado'#(lf)        WHEN ds.IsValidated IS NULL THEN 'Aguardando Validação'#(lf)        ELSE 'Pendente'#(lf)    END AS Status_Documentacao,#(lf)     #(lf)    ISNULL(dsv.id, ds.id) as 'Id_Reanálise',#(lf)    dsv.message#(lf)#(lf)FROM#(lf)    DocumentSchedule                AS ds    WITH (NOLOCK)#(lf)    INNER JOIN Document             AS d     WITH (NOLOCK) ON ds.DocumentId      = d.Id#(lf)    INNER JOIN Organization         AS o     WITH (NOLOCK) ON ds.OrganizationId  = o.Id#(lf)#(tab)INNER JOIN BranchCompany        AS bc    WITH (NOLOCK) ON ds.BranchCompanyId = bc.Id#(lf)    INNER JOIN Provider             AS p     WITH (NOLOCK) ON bc.ProviderId      = p.Id#(lf)#(lf)    -- volta a usar Contract/Category no FROM principal, só pra pegar Categoria#(lf)    INNER JOIN DocumentScheduleContractBI dscMain WITH (NOLOCK) ON dscMain.DocumentScheduleId = ds.Id#(lf)    INNER JOIN Contract              AS c     WITH (NOLOCK) ON c.Id = dscMain.ContractId#(lf)    INNER JOIN Building              AS b     WITH (NOLOCK) ON b.Id = c.BuildingId#(lf)    INNER JOIN Category              AS ca    WITH (NOLOCK) ON ca.Id = c.CategoryId#(lf)    LEFT  JOIN EmployeeRegister      AS er    WITH (NOLOCK) ON ds.EmployeeRegisterId = er.Id#(lf)    LEFT  JOIN DocumentScheduleValidationLog AS dsv WITH(NOLOCK) ON dsv.DocumentScheduleId = ds.Id#(lf)#(tab)LEFT  JOIN [User]                AS u     WITH(NOLOCK) ON u.Id = COALESCE(dsv.Responsibleid, ds.ValidatedBy)#(lf)#(tab)LEFT  JOIN DocumentFile          AS df    WITH(NOLOCK) ON df.Id = dsv.DocumentFileId#(lf)    #(lf)WHERE#(lf)  ds.OrganizationId = @organizationId#(lf)  AND (ds.Removed = 0 OR (ds.Removed = 1 AND ds.IsValidated = 0))#(lf)  AND (d.Removed  = 0 OR (d.Removed  = 1 AND ds.IsValidated = 0))#(lf)  AND (d.Archived = 0 OR (d.Archived = 1 AND ds.IsValidated = 0))#(lf)  AND ds.UploadedAt IS NOT NULL#(lf)  AND ds.RequiresValidation = 1#(lf)  AND p.Id <> '16763E30-7AB1-4B2E-A2B7-5AD89E0068C9' "]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Prazo de Envio", type date}, {"Data_Envio", type datetime}, {"Data_Análise", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

