table 'Documentos fornecedores'
	lineageTag: 695afe72-eb1e-47c0-aa1f-b817e863f8d2

	measure Contagem = CALCULATE(COUNTROWS())
		formatString: 0
		lineageTag: 73f5166b-bb34-4b00-98f8-1db2a09a0af2

	measure Aprovado =
			CALCULATE(COUNTROWS(),
			'Documentos fornecedores'[Status] = "Aprovado")+0
		formatString: 0
		lineageTag: aaed6534-3cb9-4615-8859-577d192ed81e

	measure Pendente =
			CALCULATE(COUNTROWS(),
			'Documentos fornecedores'[Analise] = "Pendente")+0
		formatString: 0
		lineageTag: fe81474f-a0f9-4a9a-858c-ff79bdb65c02

	measure 'Em Análise' =
			CALCULATE(COUNTROWS(),
			'Documentos fornecedores'[Status] = "Em Análise")+0
		formatString: 0
		lineageTag: 7183f3ae-f226-4867-ab07-76cdc0479b1c

	measure %Atrasados =
			IF(CALCULATE(COUNTROWS(),
			'Documentos fornecedores'[Status]="Atrasado")/
			CALCULATE(COUNTROWS(), ALLSELECTED('Documentos fornecedores'))=0,
			0,CALCULATE(COUNTROWS(),
			'Documentos fornecedores'[Status]="Atrasado")/
			CALCULATE(COUNTROWS(), ALLSELECTED('Documentos fornecedores')))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4eaa2111-fa60-4a0f-8021-802b387a0475

	measure Reprovado =
			CALCULATE(COUNTROWS(),
			'Documentos fornecedores'[Status] = "Reprovado") + 0
		formatString: 0
		lineageTag: 20024b9f-c9eb-4830-9c1e-0e84af5dcc9f

	measure 'Recusados dividido por Contagem' =
			
			DIVIDE([Reprovado], [Contagem])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4aea8851-5129-4c42-ba06-8cd2be25751a

	measure %Pendentes = DIVIDE([Pendente],[Contagem])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a2cfc430-7243-47ed-90d6-42ced4d5ac91

	measure 'Aprovados dividido por Contagem' =
			
			DIVIDE([Aprovado], [Contagem])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 73d37a15-d20a-4868-a7da-e6d2950e455d

	measure 'Em Análise dividido por Contagem' =
			
			DIVIDE([Em Análise], [Contagem])
		formatString: 0%;-0%;0%
		lineageTag: b9eb24c4-eff1-4133-be99-12d91dbc2755

	measure 'Não Enviados' =
			CALCULATE(COUNTROWS(),
			'Documentos fornecedores'[Status] = "Não Enviados")
		formatString: 0
		lineageTag: 86443a7d-4451-4d17-b5bf-64aebd935142

	measure '%Não Enviados dividido por Contagem' =
			
			DIVIDE([Não Enviados], [Contagem])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cfdc0d36-5929-49c0-90bf-251202876c35

	column Fornecedor
		dataType: string
		lineageTag: 7e6a74a4-b4fa-4e18-8008-7fa37bf01556
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 7dc13fc3-8a29-4f89-8d2e-c4c24576f398
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 4a9ae9d2-ddef-46df-aac9-8b4e507e6190
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Unidade(s)
		dataType: string
		lineageTag: 4a5d7f14-9e8f-403a-913f-4826295144ce
		summarizeBy: none
		sourceColumn: Unidade(s)

		annotation SummarizationSetBy = Automatic

	column Categoria(s)
		dataType: string
		lineageTag: b5b520e0-d21f-4b4c-9ae5-7068b77dc2d6
		summarizeBy: none
		sourceColumn: Categoria(s)

		annotation SummarizationSetBy = Automatic

	column Analise
		dataType: string
		lineageTag: e491480d-ead7-4c98-b0fc-5e79111c88c1
		summarizeBy: none
		sourceColumn: Analise

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do fornecedor'
		dataType: string
		lineageTag: 63ab8627-c241-492c-a416-5f6a7b3eca50
		summarizeBy: none
		sourceColumn: CNPJ do fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Prazo de envio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 11d605fc-6f31-4681-9477-bf7e9ebabb5d
		summarizeBy: none
		sourceColumn: Prazo de envio

		variation Variation
			isDefault
			relationship: 02fe3ef0-4645-470d-932a-fe301f4f2ce3
			defaultHierarchy: LocalDateTable_b8beef19-1070-426d-8f00-41a733b04393.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Competência
		dataType: dateTime
		formatString: Long Date
		lineageTag: 725a3f8c-2e3f-4e14-b714-059e7617f2c1
		summarizeBy: none
		sourceColumn: Competência

		variation Variation
			isDefault
			relationship: 02a99aad-eb0a-4517-b698-46bbde8b0a21
			defaultHierarchy: LocalDateTable_9e0ed63e-3eaf-4778-9576-e75a2fffc40d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Documento
		dataType: string
		lineageTag: 38b2781b-a412-40aa-b151-618d462767c3
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	partition 'Documentos fornecedores' = m
		mode: import
		source = ```
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoãoLima\Diretório Padrão\Atlas Inovações - Documentos\Produtos\AFM\Gestão\16. Relatório Interno e Externo - Power BI\02. Externo\04. Produto\EDF\Relatório - Fornecedores.xlsx"), null, true),
				    #"Documentos fornecedores_Sheet" = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Documentos fornecedores_Sheet", [PromoteAllScalars=true]),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Cabeçalhos Promovidos",{"Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253", "Column254", "Column255", "Column256", "Column257", "Column258", "Column259", "Column260", "Column261", "Column262", "Column263", "Column264", "Column265", "Column266", "Column267", "Column268", "Column269", "Column270", "Column271", "Column272", "Column273", "Column274", "Column275", "Column276", "Column277", "Column278", "Column279", "Column280", "Column281", "Column282", "Column283", "Column284", "Column285", "Column286", "Column287", "Column288", "Column289", "Column290", "Column291", "Column292", "Column293", "Column294", "Column295", "Column296", "Column297", "Column298", "Column299", "Column300", "Column301", "Column302", "Column303", "Column304", "Column305", "Column306", "Column307", "Column308", "Column309", "Column310", "Column311", "Column312", "Column313", "Column314", "Column315", "Column316", "Column317", "Column318", "Column319", "Column320", "Column321", "Column322", "Column323", "Column324", "Column325", "Column326", "Column327", "Column328", "Column329", "Column330", "Column331", "Column332", "Column333", "Column334", "Column335", "Column336", "Column337", "Column338", "Column339", "Column340", "Column341", "Column342", "Column343", "Column344", "Column345", "Column346", "Column347", "Column348", "Column349", "Column350", "Column351", "Column352", "Column353", "Column354", "Column355", "Column356", "Column357", "Column358", "Column359", "Column360", "Column361", "Column362", "Column363", "Column364", "Column365", "Column366", "Column367", "Column368", "Column369", "Column370", "Column371", "Column372", "Column373", "Column374", "Column375", "Column376", "Column377", "Column378", "Column379", "Column380", "Column381", "Column382", "Column383", "Column384", "Column385", "Column386", "Column387", "Column388", "Column389", "Column390", "Column391", "Column392", "Column393", "Column394", "Column395", "Column396", "Column397", "Column398", "Column399", "Column400", "Column401", "Column402", "Column403", "Column404", "Column405", "Column406", "Column407", "Column408", "Column409", "Column410", "Column411", "Column412", "Column413", "Column414", "Column415", "Column416", "Column417", "Column418", "Column419", "Column420", "Column421", "Column422", "Column423", "Column424", "Column425", "Column426", "Column427", "Column428", "Column429", "Column430", "Column431", "Column432", "Column433", "Column434", "Column435", "Column436", "Column437", "Column438", "Column439", "Column440", "Column441", "Column442", "Column443", "Column444", "Column445", "Column446", "Column447", "Column448", "Column449", "Column450", "Column451", "Column452", "Column453", "Column454", "Column455", "Column456", "Column457", "Column458", "Column459", "Column460", "Column461", "Column462", "Column463", "Column464", "Column465", "Column466", "Column467", "Column468", "Column469", "Column470", "Column471", "Column472", "Column473", "Column474", "Column475", "Column476", "Column477", "Column478", "Column479", "Column480", "Column481", "Column482", "Column483", "Column484", "Column485", "Column486", "Column487", "Column488", "Column489", "Column490", "Column491", "Column492", "Column493", "Column494", "Column495", "Column496", "Column497", "Column498", "Column499", "Column500", "Column501", "Column502", "Column503", "Column504", "Column505", "Column506", "Column507", "Column508", "Column509", "Column510", "Column511", "Column512", "Column513", "Column514", "Column515", "Column516", "Column517", "Column518", "Column519", "Column520", "Column521", "Column522", "Column523", "Column524", "Column525", "Column526", "Column527", "Column528", "Column529", "Column530", "Column531", "Column532", "Column533", "Column534", "Column535", "Column536", "Column537", "Column538", "Column539", "Column540", "Column541", "Column542", "Column543", "Column544", "Column545", "Column546", "Column547", "Column548", "Column549", "Column550", "Column551", "Column552", "Column553", "Column554", "Column555", "Column556", "Column557", "Column558", "Column559", "Column560", "Column561", "Column562", "Column563", "Column564", "Column565", "Column566", "Column567", "Column568", "Column569", "Column570", "Column571", "Column572", "Column573", "Column574", "Column575", "Column576", "Column577", "Column578", "Column579", "Column580", "Column581", "Column582", "Column583", "Column584", "Column585", "Column586", "Column587", "Column588", "Column589", "Column590", "Column591", "Column592", "Column593", "Column594", "Column595", "Column596", "Column597", "Column598", "Column599", "Column600", "Column601", "Column602", "Column603", "Column604", "Column605", "Column606", "Column607", "Column608", "Column609", "Column610", "Column611", "Column612", "Column613", "Column614", "Column615", "Column616", "Column617", "Column618", "Column619", "Column620", "Column621", "Column622", "Column623", "Column624", "Column625", "Column626", "Column627", "Column628", "Column629", "Column630", "Column631", "Column632", "Column633", "Column634", "Column635", "Column636", "Column637", "Column638", "Column639", "Column640", "Column641", "Column642", "Column643", "Column644", "Column645", "Column646", "Column647", "Column648", "Column649", "Column650", "Column651", "Column652", "Column653", "Column654", "Column655", "Column656", "Column657", "Column658", "Column659", "Column660", "Column661", "Column662", "Column663", "Column664", "Column665", "Column666", "Column667", "Column668", "Column669", "Column670", "Column671", "Column672", "Column673", "Column674", "Column675", "Column676", "Column677", "Column678", "Column679", "Column680", "Column681", "Column682", "Column683", "Column684", "Column685", "Column686", "Column687", "Column688", "Column689", "Column690", "Column691", "Column692", "Column693", "Column694", "Column695", "Column696", "Column697", "Column698", "Column699", "Column700", "Column701", "Column702", "Column703", "Column704", "Column705", "Column706", "Column707", "Column708", "Column709", "Column710", "Column711", "Column712", "Column713", "Column714", "Column715", "Column716", "Column717", "Column718", "Column719", "Column720", "Column721", "Column722", "Column723", "Column724", "Column725", "Column726", "Column727", "Column728", "Column729", "Column730", "Column731", "Column732", "Column733", "Column734", "Column735", "Column736", "Column737", "Column738", "Column739", "Column740", "Column741", "Column742", "Column743", "Column744", "Column745", "Column746", "Column747", "Column748", "Column749", "Column750", "Column751", "Column752", "Column753", "Column754", "Column755", "Column756", "Column757", "Column758", "Column759", "Column760", "Column761", "Column762", "Column763", "Column764", "Column765", "Column766", "Column767", "Column768", "Column769", "Column770", "Column771", "Column772", "Column773", "Column774", "Column775", "Column776", "Column777", "Column778", "Column779", "Column780", "Column781", "Column782", "Column783", "Column784", "Column785", "Column786", "Column787", "Column788", "Column789", "Column790", "Column791", "Column792", "Column793", "Column794", "Column795", "Column796", "Column797", "Column798", "Column799", "Column800", "Column801", "Column802", "Column803", "Column804", "Column805", "Column806", "Column807", "Column808", "Column809", "Column810", "Column811", "Column812", "Column813", "Column814", "Column815", "Column816", "Column817", "Column818", "Column819", "Column820", "Column821", "Column822", "Column823", "Column824", "Column825", "Column826", "Column827", "Column828", "Column829", "Column830", "Column831", "Column832", "Column833", "Column834", "Column835", "Column836", "Column837", "Column838", "Column839", "Column840", "Column841", "Column842", "Column843", "Column844", "Column845", "Column846", "Column847", "Column848", "Column849", "Column850", "Column851", "Column852", "Column853", "Column854", "Column855", "Column856", "Column857", "Column858", "Column859", "Column860", "Column861", "Column862", "Column863", "Column864", "Column865", "Column866", "Column867", "Column868", "Column869", "Column870", "Column871", "Column872", "Column873", "Column874", "Column875", "Column876", "Column877", "Column878", "Column879", "Column880", "Column881", "Column882", "Column883", "Column884", "Column885", "Column886", "Column887", "Column888", "Column889", "Column890", "Column891", "Column892", "Column893", "Column894", "Column895", "Column896", "Column897", "Column898", "Column899", "Column900", "Column901", "Column902", "Column903", "Column904", "Column905", "Column906", "Column907", "Column908", "Column909", "Column910", "Column911", "Column912", "Column913", "Column914", "Column915", "Column916", "Column917", "Column918", "Column919", "Column920", "Column921", "Column922", "Column923", "Column924", "Column925", "Column926", "Column927", "Column928", "Column929", "Column930", "Column931", "Column932", "Column933", "Column934", "Column935", "Column936", "Column937", "Column938", "Column939", "Column940", "Column941", "Column942", "Column943", "Column944", "Column945", "Column946", "Column947", "Column948", "Column949", "Column950", "Column951", "Column952", "Column953", "Column954", "Column955", "Column956", "Column957", "Column958", "Column959", "Column960", "Column961", "Column962", "Column963", "Column964", "Column965", "Column966", "Column967", "Column968", "Column969", "Column970", "Column971", "Column972", "Column973", "Column974", "Column975", "Column976", "Column977", "Column978", "Column979", "Column980", "Column981", "Column982", "Column983", "Column984", "Column985", "Column986", "Column987", "Column988", "Column989", "Column990", "Column991", "Column992", "Column993", "Column994", "Column995", "Column996", "Column997", "Column998", "Column999", "Column1000", "Column1001", "Column1002", "Column1003", "Column1004", "Column1005", "Column1006", "Column1007", "Column1008", "Column1009", "Column1010", "Column1011", "Column1012", "Column1013", "Column1014", "Column1015", "Column1016", "Column1017", "Column1018", "Column1019", "Column1020", "Column1021", "Column1022", "Column1023", "Column1024", "Column1025"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas em Branco Removidas", "Analise", each if [Status] = "Aprovado" then "Aprovado" else if [Status] = "Em Análise" then "Em Análise" else "Pendente"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Prazo de envio", type date}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Competência", each 
				Date.AddMonths([Prazo de envio],-1)),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Competência", type date}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado1", each ([Competência] <> #date(2024, 4, 15) and [Competência] <> #date(2024, 4, 19) and [Competência] <> #date(2024, 5, 27) and [Competência] <> #date(2024, 5, 29)))
				in
				    #"Linhas Filtradas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

