table 'Entrega SEFIP'
	lineageTag: 1f2cc662-8e7b-408c-9d10-89dad4875b2a

	column Unidade
		dataType: string
		lineageTag: 76b78e9b-fe52-4168-9cb1-adc62f8c0f07
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: d6116599-5a93-479b-bccd-d4dc45f0b7ea
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 6f1e0cde-ad7f-4bd8-8515-49b8c9344c85
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Tipo de documento'
		dataType: string
		lineageTag: 3b8ce4d9-ce2d-4152-b936-c8a7ebf4172a
		summarizeBy: none
		sourceColumn: Tipo de documento

		annotation SummarizationSetBy = Automatic

	column Situação
		dataType: string
		lineageTag: 69e9e09f-ea11-4738-a894-c3b2a4dd605b
		summarizeBy: none
		sourceColumn: Situação

		annotation SummarizationSetBy = Automatic

	column 'Mês de competência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 517432db-1a27-4cef-8420-c464bd41893b
		summarizeBy: none
		sourceColumn: Mês de competência

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DataOrder = ```
			RANKX(ALL('Entrega SEFIP'[Mês de competência]), 'Entrega SEFIP'[Mês de competência], , DESC, DENSE)
			
			```
		formatString: 0
		lineageTag: f6e10c6a-3f09-4b58-8587-175085f3aa81
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Fornecedor - Categoria - Unidade'
		dataType: string
		lineageTag: d3018aca-5fce-40ad-ba78-d637aaaa70f5
		summarizeBy: none
		sourceColumn: Fornecedor - Categoria - Unidade

		annotation SummarizationSetBy = Automatic

	column 'Contagem SEFIP Entregues' = ```
			SWITCH(TRUE(), 
			'Entrega SEFIP'[Situação] = "Ok", 1, 
			'Entrega SEFIP'[Situação] = "*", 1, 
			0
			)
			```
		formatString: 0
		lineageTag: bcd27c71-6648-4256-9f5d-c2729b1ef45f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Início Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9b7a0012-e511-436e-b932-9c7b8f8f47c1
		summarizeBy: none
		sourceColumn: Início Vigência

		variation Variation
			isDefault
			relationship: 407b752f-436c-42ad-b37d-286b96e8e38e
			defaultHierarchy: LocalDateTable_5c39ae2d-026d-434f-94c0-5f81e198f7f0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b7d4a394-e6f8-43a5-b0e3-b46d76226d47
		summarizeBy: none
		sourceColumn: Fim Vigência

		variation Variation
			isDefault
			relationship: d9fcd76b-2f59-4659-9fb6-b0385c061848
			defaultHierarchy: LocalDateTable_7b5071ca-deac-4853-a1bc-434e86433c6c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status Contrato'
		dataType: string
		lineageTag: e4fb64a1-adb0-4add-b779-9cfdff7856a4
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	partition 'Entrega SEFIP' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoanaMalheiros\Diretório Padrão\Atlas Inovações - Documentos\Consultoria\1.1. AFM CLIENTES\SYN\3. Apresentações\0. Status SYN\Relatório AFM Gestão\5. Maio\afm_gestao_report_documentos_11_14_15_07_2024.xlsx"), null, true),
				    #"Entrega de documentos_Sheet" = Fonte{[Item="Entrega de documentos",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Entrega de documentos_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Column1", type any}, {"Relatório - Entrega de documentos", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}, {"Column39", type text}, {"Column40", type text}, {"Column41", type text}, {"Column42", type text}, {"Column43", type text}, {"Column44", type text}, {"Column45", type text}, {"Column46", type text}, {"Column47", type text}, {"Column48", type text}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",9),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas",{"Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48"}),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Outras Colunas Removidas", [PromoteAllScalars=true]),
				    #"Cabeçalhos Promovidos2" = Table.PromoteHeaders(#"Cabeçalhos Promovidos1", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos2",{{"Unidade", type text}, {"Fornecedor", type text}, {"Categoria", type text}, {"Nº do Pedido", type text}, {"RE", type text}, {"Boleto", type text}, {"C. Pgto", type text}, {"RE_1", type text}, {"Boleto_2", type text}, {"C. Pgto_3", type text}, {"RE_4", type text}, {"Boleto_5", type text}, {"C. Pgto_6", type text}, {"RE_7", type text}, {"Boleto_8", type text}, {"C. Pgto_9", type text}, {"RE_10", type text}, {"Boleto_11", type text}, {"C. Pgto_12", type text}, {"RE_13", type text}, {"Boleto_14", type text}, {"C. Pgto_15", type text}, {"RE_16", type text}, {"Boleto_17", type text}, {"C. Pgto_18", type text}, {"RE_19", type text}, {"Boleto_20", type text}, {"C. Pgto_21", type text}, {"RE_22", type text}, {"Boleto_23", type text}, {"C. Pgto_24", type text}, {"RE_25", type text}, {"Boleto_26", type text}, {"C. Pgto_27", type text}, {"RE_28", type text}, {"Boleto_29", type text}, {"C. Pgto_30", type text}, {"RE_31", type text}, {"Boleto_32", type text}, {"C. Pgto_33", type text}, {"RE_34", type text}, {"Boleto_35", type text}, {"C. Pgto_36", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"RE", "RE - Abril/23"}, {"Boleto", "Boleto - Abril/23"}, {"C. Pgto", "C. Pgto - Abril/23"}, {"RE_1", "RE - Maio/23"}, {"Boleto_2", "Boleto - Maio/23"}, {"C. Pgto_3", "C. Pgto - Maio/23"}, {"RE_4", "RE - Junho/23"}, {"Boleto_5", "Boleto - Junho/23"}, {"C. Pgto_6", "C. Pgto - Junho/23"}, {"RE_7", "RE - Julho/23"}, {"Boleto_8", "Boleto - Julho/23"}, {"C. Pgto_9", "C. Pgto - Julho/23"}, {"RE_10", "RE - Agosto/23"}, {"Boleto_11", "Boleto - Agosto/23"}, {"C. Pgto_12", "C. Pgto - Agosto/23"}, {"RE_13", "RE - Setembro/23"}, {"Boleto_14", "Boleto - Setembro/23"}, {"C. Pgto_15", "C. Pgto - Setembro/23"}, {"RE_16", "RE - Outubro/23"}, {"Boleto_17", "Boleto - Outubro/23"}, {"C. Pgto_18", "C. Pgto - Outubro/23"}, {"RE_19", "RE - Novembro/23"}, {"Boleto_20", "Boleto - Novembro/23"}, {"C. Pgto_21", "C. Pgto - Novembro/23"}, {"RE_22", "RE - Dezembro/23"}, {"Boleto_23", "Boleto - Dezembro/23"}, {"C. Pgto_24", "C. Pgto - Dezembro/23"}, {"RE_25", "RE - Janeiro/24"}, {"Boleto_26", "Boleto -  Janeiro/24"}, {"C. Pgto_27", "C. Pgto - Janeiro/24"}, {"RE_28", "RE - Fevereiro/24"}, {"Boleto_29", "Boleto - Fevereiro/24"}, {"C. Pgto_30", "C. Pgto - Fevereiro/24"}, {"RE_31", "RE - Março/24"}, {"Boleto_32", "Boleto - Março/24"}, {"C. Pgto_33", "C. Pgto - Março/24"}, {"RE_34", "RE - Abril/24"}, {"Boleto_35", "Boleto - Abril/24"}, {"C. Pgto_36", "C. Pgto - Abril/24"}, {"RE_37", "RE - Maio/24"}, {"Boleto_38", "Boleto - Maio/24"}, {"C. Pgto_39", "C. Pgto - Maio/24"}}),
				    #"Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Colunas Renomeadas", {"Unidade", "Fornecedor", "Categoria", "Nº do Pedido"}, "Tipo de documento", "Situação"),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Colunas Não Dinâmicas", "Tipo de documento", Splitter.SplitTextByDelimiter(" - ", QuoteStyle.Csv), {"Tipo de documento.1", "Mês de competência"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Tipo de documento.1", type text}, {"Mês de competência", type date}}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Tipo Alterado2",{{"Tipo de documento.1", "Tipo de documento"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas1",{"Nº do Pedido"}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Mês de competência", type date}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado3", each ([Situação] <> "---")),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Linhas Filtradas", "Fornecedor - Categoria - Unidade", each Text.Combine({[Fornecedor], [Categoria], [Unidade]}, " - "), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"Fornecedor - Categoria - Unidade"}, Contratos, {"Fornecedor-Categoria-Unidade"}, "Contratos", JoinKind.LeftOuter),
				    #"Contratos Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Contratos", {"Início Vigência", "Fim Vigência", "Status Contrato"}, {"Início Vigência", "Fim Vigência", "Status Contrato"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Contratos Expandido", each ([Status Contrato] = "Vigente"))
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

