table 'Base - Acompanhamento de GPs'
	lineageTag: 8cbbc357-5cf6-4f41-99b3-a1b9dd8ca84b

	measure _Quantidade_ = CALCULATE(COUNTROWS())
		formatString: #,0
		lineageTag: c4ae2673-05e9-45a8-89fc-0527bc494c3e

	column Column1
		dataType: string
		lineageTag: 0aa165bd-6f7b-4d60-9e74-7559fadee4f1
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column UNIDADE
		dataType: string
		lineageTag: 1aa90703-19ac-498d-a5fc-c48df5bd6235
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column REGIONAL
		dataType: string
		lineageTag: 2f4f45c1-b581-4148-9962-320fdfaa919c
		summarizeBy: none
		sourceColumn: REGIONAL

		annotation SummarizationSetBy = Automatic

	column 'EQUIP.'
		dataType: string
		lineageTag: ca1bd37e-a8c7-4c57-9f14-44f9d3543a43
		summarizeBy: none
		sourceColumn: EQUIP.

		annotation SummarizationSetBy = Automatic

	column CENTRO
		dataType: int64
		formatString: 0
		lineageTag: 8707df5a-40b9-4f53-a615-ff43452f4031
		summarizeBy: sum
		sourceColumn: CENTRO

		annotation SummarizationSetBy = Automatic

	column 'CÓD. REV.'
		dataType: string
		lineageTag: 6ea2f259-03dd-4dbf-b34e-95d7114ba992
		summarizeBy: none
		sourceColumn: CÓD. REV.

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: 0c655544-6e02-4c78-b123-cd1e32263518
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column 'STATUS GP'
		dataType: string
		lineageTag: 0ba02943-cb45-4094-8d0b-a7ad1be96fcd
		summarizeBy: none
		sourceColumn: STATUS GP

		annotation SummarizationSetBy = Automatic

	column INICIO
		dataType: dateTime
		formatString: Long Date
		lineageTag: f25191c4-e5ab-436b-8d19-54bc919451e8
		summarizeBy: none
		sourceColumn: INICIO

		variation Variation
			isDefault
			relationship: 4184f80c-b6c6-4be6-a59f-9846e6a61d75
			defaultHierarchy: LocalDateTable_d0a2a6cd-f6c5-41f4-9011-ee94f1c36265.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FIM
		dataType: dateTime
		formatString: Long Date
		lineageTag: 875060fc-0cc4-40e2-bf7f-18dbb6025b1e
		summarizeBy: none
		sourceColumn: FIM

		variation Variation
			isDefault
			relationship: f2e1fd9d-bcf0-4fc3-9068-058e4683f42e
			defaultHierarchy: LocalDateTable_eef9e452-8320-4649-9c47-dbfafc56b6fa.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'DIAS - INICIO GP'
		dataType: int64
		formatString: 0
		lineageTag: a10ede9d-1844-4f1c-a1f5-a3c8c0038697
		summarizeBy: sum
		sourceColumn: DIAS - INICIO GP

		annotation SummarizationSetBy = Automatic

	column MÊS
		dataType: int64
		formatString: 0
		lineageTag: f7085954-f943-4647-bbbd-532384cb588a
		summarizeBy: sum
		sourceColumn: MÊS

		annotation SummarizationSetBy = Automatic

	column TRIMESTRE
		dataType: string
		lineageTag: 2ef39bda-a84b-4073-b761-6282378c272d
		summarizeBy: none
		sourceColumn: TRIMESTRE

		annotation SummarizationSetBy = Automatic

	column 'STATUS GP '
		dataType: string
		lineageTag: f36edeec-1fea-47c2-aa11-6c0d8f71c1c4
		summarizeBy: none
		sourceColumn: "STATUS GP "

		annotation SummarizationSetBy = Automatic

	column SUBCATEGORIA
		dataType: string
		lineageTag: bae77fdc-d960-414d-9a33-e53d00644dfe
		summarizeBy: none
		sourceColumn: SUBCATEGORIA

		annotation SummarizationSetBy = Automatic

	column 'DESCRIÇÃO ESCOPO'
		dataType: string
		lineageTag: 3ddca9e8-198e-42fa-a042-b3dbb20b76ef
		summarizeBy: none
		sourceColumn: DESCRIÇÃO ESCOPO

		annotation SummarizationSetBy = Automatic

	column FORNECEDORES
		dataType: string
		lineageTag: 60149129-5510-4303-9477-7840a5eccf4f
		summarizeBy: none
		sourceColumn: FORNECEDORES

		annotation SummarizationSetBy = Automatic

	column 'STATUS CONTRATAÇÃO'
		dataType: string
		lineageTag: e9464cab-5b77-454c-a1d9-6bfc18e48c22
		summarizeBy: none
		sourceColumn: STATUS CONTRATAÇÃO

		annotation SummarizationSetBy = Automatic

	column RC
		dataType: int64
		formatString: 0
		lineageTag: 47a3a258-8075-4ace-96db-caccc748a991
		summarizeBy: sum
		sourceColumn: RC

		annotation SummarizationSetBy = Automatic

	column 'DATA APROV. RC'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 92a5a0e5-fa2b-4ce9-8316-cbb102b8cbbb
		summarizeBy: none
		sourceColumn: DATA APROV. RC

		variation Variation
			isDefault
			relationship: 1a6a72a8-3b6b-4a8f-bc54-d4c9b62812c7
			defaultHierarchy: LocalDateTable_555b1d7d-ec50-4e65-8e1a-ad504beaeae7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'DIAS APROV.'
		dataType: int64
		formatString: 0
		lineageTag: 4f00baa9-cd58-45d7-ad5d-72a61c6914cf
		summarizeBy: sum
		sourceColumn: DIAS APROV.

		annotation SummarizationSetBy = Automatic

	column 'ADERÊNCIA CRONOLOGIA RC'
		dataType: string
		lineageTag: 44935114-e746-41c5-b7df-058675d55a3e
		summarizeBy: none
		sourceColumn: ADERÊNCIA CRONOLOGIA RC

		annotation SummarizationSetBy = Automatic

	column 'MODELO CONTRATAÇÃO2'
		dataType: string
		lineageTag: 61666690-87e0-40b8-92e2-788d007557cd
		summarizeBy: none
		sourceColumn: MODELO CONTRATAÇÃO2

		annotation SummarizationSetBy = Automatic

	column WS/RFQ
		dataType: string
		lineageTag: 1f1b5c0b-dbc0-4437-bac6-115f1fd67b41
		summarizeBy: none
		sourceColumn: WS/RFQ

		annotation SummarizationSetBy = Automatic

	column PC
		dataType: string
		lineageTag: cc3031ab-4536-41ca-8520-a3e086c58fd7
		summarizeBy: none
		sourceColumn: PC

		annotation SummarizationSetBy = Automatic

	column 'DATA CRIAÇÃO PC '
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5ca3f0f5-f736-4f04-a87c-94ef7ab4ff8e
		summarizeBy: none
		sourceColumn: "DATA CRIAÇÃO PC "

		variation Variation
			isDefault
			relationship: 5b1da08e-d3b7-4e2f-b027-0e71d6dd511e
			defaultHierarchy: LocalDateTable_6d836a53-33f6-4902-b3f1-3ed2a4d87348.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ADERÊNCIA CRONOLOGIA PC (DIAS)'
		dataType: int64
		formatString: 0
		lineageTag: baf38658-9305-4b90-bc1b-9bb1522e8b78
		summarizeBy: sum
		sourceColumn: ADERÊNCIA CRONOLOGIA PC (DIAS)

		annotation SummarizationSetBy = Automatic

	column 'ADERÊNCIA CRONOLOGIA PC'
		dataType: string
		lineageTag: e694c601-627d-4770-9855-4d5aa0000022
		summarizeBy: none
		sourceColumn: ADERÊNCIA CRONOLOGIA PC

		annotation SummarizationSetBy = Automatic

	column OBSERVAÇÕES
		dataType: string
		lineageTag: 4abb88aa-7580-4c5d-809a-7433638c832e
		summarizeBy: none
		sourceColumn: OBSERVAÇÕES

		annotation SummarizationSetBy = Automatic

	column 'ORÇAMENTO GP'
		dataType: double
		lineageTag: 6bebf330-e646-44ed-a5d8-452570880834
		summarizeBy: sum
		sourceColumn: ORÇAMENTO GP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SPEND CONTRATADO'
		dataType: double
		lineageTag: 4dd2618e-1ff4-492f-8237-63e7af095d6a
		summarizeBy: sum
		sourceColumn: SPEND CONTRATADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ORÇ. X REAL.'
		dataType: double
		lineageTag: 9a19013a-6a53-4fdd-b707-d2bbfd5e20f5
		summarizeBy: sum
		sourceColumn: ORÇ. X REAL.

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ORÇ. X REAL.STATUS'
		dataType: string
		lineageTag: 3887bce2-bbbc-4ccf-845a-ce1c04249b7e
		summarizeBy: none
		sourceColumn: ORÇ. X REAL.STATUS

		annotation SummarizationSetBy = Automatic

	column 'QTDE DE PESSOAS PREVISTAS'
		dataType: int64
		formatString: 0
		lineageTag: 1d39cdb9-e5e3-46b9-8941-d43d3fd2be26
		summarizeBy: sum
		sourceColumn: QTDE DE PESSOAS PREVISTAS

		annotation SummarizationSetBy = Automatic

	column 'FOLLOW UP MOBILIZAÇÃO'
		dataType: string
		lineageTag: 201df7c9-5e26-4dc0-8cb0-665eba5e36a5
		summarizeBy: none
		sourceColumn: FOLLOW UP MOBILIZAÇÃO

		annotation SummarizationSetBy = Automatic

	column MOBILIZAÇÃO
		dataType: string
		lineageTag: a76fa65a-eef0-41d7-be5f-e6b2eda3b452
		summarizeBy: none
		sourceColumn: MOBILIZAÇÃO

		annotation SummarizationSetBy = Automatic

	column Column37
		dataType: string
		lineageTag: 59aa9a0b-7fa6-4c23-b8b4-fa01703dbbea
		summarizeBy: none
		sourceColumn: Column37

		annotation SummarizationSetBy = Automatic

	column 'Contratos no Integra' =
			
			VAR Contrato = Contratos[_Contratos_Quantidade]
			
			RETURN IF( Contrato = BLANK(),
			                                "Não Está o Integra VC", "Está no Integra VC")
		lineageTag: 11825d25-ccb3-4658-9439-503fc7a628df
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Base - Acompanhamento de GPs' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoãoLima\Diretório Padrão\Atlas Inovações - Documentos\Relatórios\Dados\02. Externo\01. AFM Gestão\Votorantim Cimentos\02. SLA\Mapa - Planejamento de GPs.xlsx"), null, true),
				    #"Base - Acompanhamento de GPs_Sheet" = Fonte{[Item="Base - Acompanhamento de GPs",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Base - Acompanhamento de GPs_Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type any}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type text}, {"Column29", type text}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type text}, {"Column34", type any}, {"Column35", type text}, {"Column36", type text}, {"Column37", type any}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",2),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Column1", type text}, {"UNIDADE", type text}, {"REGIONAL", type text}, {"EQUIP.", type text}, {"CENTRO", Int64.Type}, {"CÓD. REV.", type text}, {"TIPO", type text}, {"STATUS GP", type text}, {"INICIO", type date}, {"FIM", type any}, {"DIAS - INICIO GP", Int64.Type}, {"MÊS", Int64.Type}, {"TRIMESTRE", type text}, {"STATUS GP ", type text}, {"SUBCATEGORIA", type text}, {"DESCRIÇÃO ESCOPO", type text}, {"FORNECEDORES", type text}, {"STATUS CONTRATAÇÃO", type text}, {"RC", Int64.Type}, {"DATA APROV. RC", type date}, {"DIAS APROV.", Int64.Type}, {"ADERÊNCIA CRONOLOGIA RC", type text}, {"MODELO CONTRATAÇÃO2", type text}, {"WS/RFQ", type text}, {"PC", type text}, {"DATA CRIAÇÃO PC ", type date}, {"ADERÊNCIA CRONOLOGIA PC (DIAS)", Int64.Type}, {"ADERÊNCIA CRONOLOGIA PC", type text}, {"OBSERVAÇÕES", type text}, {"ORÇAMENTO GP", type number}, {"SPEND CONTRATADO", type number}, {"ORÇ. X REAL.", type number}, {"ORÇ. X REAL.#(lf)STATUS", type text}, {"QTDE DE PESSOAS PREVISTAS", Int64.Type}, {"FOLLOW UP MOBILIZAÇÃO", type text}, {"MOBILIZAÇÃO", type text}, {"Column37", type any}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"FIM", type date}}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Tipo Alterado2", {{"ORÇAMENTO GP", null},{"SPEND CONTRATADO", null},{"QTDE DE PESSOAS PREVISTAS", null}}),
				    #"Erros Substituídos1" = Table.ReplaceErrorValues(#"Erros Substituídos", {{"ORÇ. X REAL.#(lf)STATUS", null}}),
				    #"Erros Substituídos2" = Table.ReplaceErrorValues(#"Erros Substituídos1", {{"ORÇ. X REAL.", null}})
				in
				    #"Erros Substituídos2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

