table 'FGTS Digital'
	lineageTag: e4d2e098-9105-4faf-afca-4e6172ce14f2

	measure 'Quantidade 2' = CALCULATE(COUNTROWS())
		formatString: 0
		lineageTag: a5fd555c-b0d9-430d-8e2b-aa7087a66d47

	measure 'Doccumentos Pendentes' =
			
			CALCULATE(
			    CONCATENATEX(
			        FILTER(
			            VALUES('FGTS Digital'[Documentos]),
			            'FGTS Digital'[Documentos] <> "Ok"
			        ),
			       'FGTS Digital'[Documentos],
			        "; "
			    )
			)
		lineageTag: 69e5fd9d-0e09-41eb-99b7-3d7dc024c584

	column Unidade
		dataType: string
		lineageTag: 3a77d258-ff91-4ba1-8a49-c069145c7ca8
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 73c15c19-cbbc-4d1e-aaba-6b496cacd05d
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 33c65aec-c8de-471e-920a-2d9d01e0ec72
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Nº do Pedido'
		dataType: string
		lineageTag: bac1e093-1944-4c25-9747-37b98f5b95ac
		summarizeBy: none
		sourceColumn: Nº do Pedido

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: Long Date
		lineageTag: deb1e429-a5fb-4377-9712-c923ebbcd7ea
		summarizeBy: none
		sourceColumn: Competência

		variation Variation
			isDefault
			relationship: 8f884b65-af89-4250-a686-f8c53f51d113
			defaultHierarchy: LocalDateTable_a237b398-b28a-4219-85d7-96aaae9b82cc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Documentos
		dataType: string
		lineageTag: c53d8e6e-23d9-41c4-96b6-1862f8b1a28e
		summarizeBy: none
		sourceColumn: Documentos

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 87bb4d12-b61d-4699-b108-7c1c54b08cf0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 1ceb6f13-9d0e-4aa4-963f-38b924c9f65f
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	partition 'FGTS Digital' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\JoãoLima\Diretório Padrão\Atlas Inovações - Documentos\Produtos\AFM\Gestão\16. Relatório Interno e Externo - Power BI\02. Externo\04. Produto\Skic\afm_gestao_report_documentos_13_56_02_09_2024.xlsx"), null, true),
				    #"Entrega de documentos_Sheet" = Fonte{[Item="Entrega de documentos",Kind="Sheet"]}[Data],
				    #"Colunas Removidas" = Table.RemoveColumns(#"Entrega de documentos_Sheet",{"Column1"}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Colunas Removidas",10),
				    #"Linhas Inferiores Removidas" = Table.RemoveLastN(#"Linhas Superiores Removidas",2),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Linhas Inferiores Removidas", [PromoteAllScalars=true]),
				    #"Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Cabeçalhos Promovidos1", {"Column1", "Column2", "Column3", "Column4", "Column5"}, "Atributo", "Valor"),
				    #"Linhas Superiores Removidas1" = Table.Skip(#"Colunas Não Dinâmicas",8),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas1", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"AGO/24_6", "Competência"}, {"C. Pgto", "Status"}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Renomeadas", {"Competência"}, Referência, {"Atributo"}, "Referência", JoinKind.LeftOuter),
				    #"Referência Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Referência", {"Valor"}, {"Referência.Valor"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Referência Expandido",{{"Referência.Valor", "Documentos"}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Colunas Renomeadas1", "Competência", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"Competência.1", "Competência.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Competência.1", type date}, {"Competência.2", Int64.Type}}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Tipo Alterado1",{{"Competência.1", "Competência"}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Renomeadas2",{"Competência.2"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas1", each ([Status] <> "---")),
				    #"Valor Substituído" = Table.ReplaceValue(#"Linhas Filtradas","X","Pendente",Replacer.ReplaceText,{"Status"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Valor Substituído",{ "Unidade", "Fornecedor", "Categoria", "Nº do Pedido", "Competência", "Documentos", "Status"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Colunas Reordenadas","Ok","Aprovado",Replacer.ReplaceText,{"Status"})
				in
				    #"Valor Substituído1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

