table Análise-Horas
	lineageTag: 370c08be-9747-4ff2-8f76-fb21a8b119c3

	measure Soma_horas = ```
			CALCULATE(SUM('Análise-Horas'[Horas-Intervalo]),
			'Análise-Horas'[Horas-Intervalo] > 0 ) 
			```
		lineageTag: 5af1c11b-f648-4b39-b276-8332e986f5c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure teste = CALCULATE(LASTNONBLANK('Análise-Horas'[Horas-Intervalo],'Análise-Horas'[Horas-Intervalo]))
		lineageTag: 0779eace-d798-4c8f-9ae1-494a308ec5db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Soma_Horas_Líquidas =
			CALCULATE(SUM('Análise-Horas'[Horas-Intervalo]),
			'Análise-Horas'[Horas-Intervalo] < 0.333333333,
			'Análise-Horas'[Horas-Intervalo] > 0)
		lineageTag: ce1c8bed-a08b-41f4-8000-27d7d1efb1fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dia da Semana'
		lineageTag: 05b55048-d5ef-4426-9833-6c26a6946c9c

	column Data_Analise
		dataType: dateTime
		formatString: Long Date
		lineageTag: 099c1866-02df-48ba-8dca-dd807cc60c29
		summarizeBy: none
		sourceColumn: Data_Analise

		variation Variation
			isDefault
			relationship: 273236f9-8b6f-48bd-a114-4159f68cff61
			defaultHierarchy: LocalDateTable_c79cda78-06e1-424b-8df4-5830015d5424.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hora_Analise
		dataType: dateTime
		formatString: hh:nn:ss
		lineageTag: 5a96bd74-f6ed-4081-8989-160ea44903e7
		summarizeBy: none
		sourceColumn: Hora_Analise

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Índice Adicionado1.Data-Hora'
		dataType: dateTime
		formatString: General Date
		lineageTag: 04be17c1-6beb-4aa4-8607-3fbec0e3b76f
		summarizeBy: none
		sourceColumn: Índice Adicionado1.Data-Hora

		variation Variation
			isDefault
			relationship: 8fbf43bd-a35c-4e89-b1ee-e62f29d375da
			defaultHierarchy: LocalDateTable_32098f9b-7b54-4b7f-9a30-25310108bccf.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Horas-Intervalo
		dataType: double
		lineageTag: 276c05c0-2d39-47d1-8683-a1b5896febc6
		summarizeBy: sum
		sourceColumn: Horas-Intervalo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dFaixa-Horario
		dataType: string
		lineageTag: 5cadbcb4-380a-4795-a51e-448e0e97dead
		summarizeBy: none
		sourceColumn: dFaixa-Horario

		annotation SummarizationSetBy = Automatic

	column dPeriodo
		dataType: string
		lineageTag: 6156e0cd-ccce-431e-ae62-c76057935c0a
		summarizeBy: none
		sourceColumn: dPeriodo

		annotation SummarizationSetBy = Automatic

	column 'Analisado por'
		dataType: string
		lineageTag: 1d936864-6100-466b-a284-f4bc0a4f253e
		summarizeBy: none
		sourceColumn: Analisado por

		annotation SummarizationSetBy = Automatic

	column Data_Hora
		dataType: dateTime
		formatString: General Date
		lineageTag: e38ca40c-99d1-4b8f-b88a-eeec5f7ef7ad
		summarizeBy: none
		sourceColumn: Data_Hora

		variation Variation
			isDefault
			relationship: dd8d7e90-27c2-467c-a33b-d200eb40c4d1
			defaultHierarchy: LocalDateTable_e77ba001-f1e1-4ba1-aba0-0bbd04c90939.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Análise-Horas = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = CAST(GETDATE() AS DATETIME);#(lf)DECLARE @organizationId uniqueidentifier = '23691bb8-3910-436a-9467-0df7b443fb38';#(lf)DECLARE @initialDate datetime2 = '2025-08-01 00:00:00';#(lf)DECLARE @finalDate datetime2 ='2025-09-01 00:00:00';#(lf)#(lf)#(lf)SELECT #(lf)      #(tab) CASE#(lf)#(tab)#(tab)WHEN (ds.ValidatedBy =  '00000000-0000-0000-0000-000000000000' and dsv.Responsibleid is null)   THEN 'Validado Automaticamente'#(lf)        WHEN dsv.Responsibleid =  '00000000-0000-0000-0000-000000000000' THEN 'Validado Automaticamente'#(lf)#(tab)#(tab)WHEN [ds].[RequiresValidation] = 0 THEN 'Não é Necessário Validação'#(lf)        WHEN (ds.ValidatedBy IS NULL and dsv.Responsibleid is null) THEN 'Pendente de Validação'#(lf)        ELSE ISNULL(u.Name, isnull(u2.name,'---'))#(lf)    END AS 'Analisado por',#(lf)#(lf)    ISNULL(FORMAT(dsv.Createdat, 'dd/MM/yyyy HH:mm:ss'), FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy HH:mm:ss')) AS Data_Hora,#(lf)#(tab)ISNULL(FORMAT(dsv.Createdat, 'dd/MM/yyyy'), FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy')) AS Data_Analise,#(lf)    ISNULL(FORMAT(dsv.Createdat, 'HH:mm:ss'), FORMAT([ds].[ValidatedAt], 'HH:mm:ss')) AS Hora_Analise#(lf)#(lf)#(tab)#(tab)#(lf)#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    LEFT JOIN DocumentScheduleValidationLog AS dsv WITH(NOLOCK) ON dsv.DocumentScheduleId = ds.Id#(lf)#(tab)LEFT JOIN [User] AS u WITH(NOLOCK) ON u.Id = dsv.Responsibleid#(lf)#(tab)LEFT JOIN [User] AS u2 WITH(NOLOCK) ON u2.Id = ds.ValidatedBy #(lf)    LEFT JOIN DocumentFile AS df WITH(NOLOCK) ON df.Id = dsv.DocumentFileId#(lf)   #(lf)#(lf)WHERE#(lf)      COALESCE(dsv.CreatedAt, ds.ValidatedAt) is not null#(lf) --COALESCE(dsv.CreatedAt, ds.ValidatedAt) <  @finalDate#(lf)  and ds.OrganizationId = @organizationId#(lf) AND COALESCE(dsv.Responsibleid, ds.ValidatedBy) in (#(lf)        '29A1349B-8E1E-43D3-9160-53669CAEA58A',#(lf)        'E1076560-C1AD-4D8D-BCFA-1BFEE30D266B',#(lf)        'D8370DAB-1B54-42D9-9799-4C4E50C58054',#(lf)        'C5C76937-9602-4BD4-98AD-B2DBFE279412',#(lf)        '800A0EA0-F909-4774-B444-538E05221582',#(lf)        '56908D45-2DF8-4E52-B4FB-2EF825FB3B92',#(lf)        '4B4DFA7D-A74E-4765-9A2A-439C9FFD06A8')#(lf)order by  [ds].Id#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Data_Hora", type datetime}, {"Data_Analise", type date}, {"Hora_Analise", type time}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado",{{"Analisado por", Order.Descending}, {"Data_Hora", Order.Descending}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Linhas Classificadas", "Índice", 1, 1, Int64.Type),
				    #"Índice Adicionado1" = Table.AddIndexColumn(#"Índice Adicionado", "Índice.1", 0, 1, Int64.Type),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Índice Adicionado1", {"Índice.1"}, #"Índice Adicionado1", {"Índice"}, "Índice Adicionado1", JoinKind.LeftOuter),
				    #"Índice Adicionado1 Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Índice Adicionado1", {"Data_Hora"}, {"Índice Adicionado1.Data-Hora"}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Índice Adicionado1 Expandido",{"Índice", "Índice.1"}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Colunas Removidas1", "Personalizar", each [#"Índice Adicionado1.Data-Hora"]-[#"Data_Hora"]),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Personalização Adicionada3",{"Personalizar"}),
				    #"Personalização Adicionada4" = Table.AddColumn(#"Colunas Removidas2", "Personalizar", each [#"Índice Adicionado1.Data-Hora"]-[#"Data_Hora"]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada4",{{"Personalizar", type duration}}),
				    #"Total de Horas Calculadas" = Table.TransformColumns(#"Tipo Alterado2",{{"Personalizar", Duration.TotalHours, type number}}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Total de Horas Calculadas",{{"Personalizar", "Minutos-Intervalo"}}),
				    #"Personalização Adicionada5" = Table.AddColumn(#"Colunas Renomeadas2", "Personalizar", each if [Hora_Analise] > #time(23,0,1) then 24
				else if [Hora_Analise] > #time(22,01,1) then 23
				else if [Hora_Analise] > #time(21,01,1) then 22
				else if [Hora_Analise] > #time(20,01,1) then 21
				else if [Hora_Analise] > #time(19,01,1) then 20
				else if [Hora_Analise] > #time(18,01,1) then 19
				else if [Hora_Analise] > #time(17,01,1) then 18
				else if [Hora_Analise] > #time(16,01,1) then 17
				else if [Hora_Analise] > #time(15,01,1) then 16
				else if [Hora_Analise] > #time(14,01,1) then 15
				else if [Hora_Analise] > #time(13,01,1) then 14
				else if [Hora_Analise] > #time(12,01,1) then 13
				else if [Hora_Analise] > #time(11,01,1) then 12
				else if [Hora_Analise] > #time(10,01,1) then 11
				else if [Hora_Analise] > #time(9,01,1) then 10
				else if [Hora_Analise] > #time(8,01,1) then 9
				else if [Hora_Analise] > #time(7,01,1) then 8
				else if [Hora_Analise] > #time(6,01,1) then 7
				else if [Hora_Analise] > #time(5,01,1) then 6
				else if [Hora_Analise] > #time(4,01,1) then 5
				else if [Hora_Analise] > #time(3,01,1) then 4
				else if [Hora_Analise] > #time(2,01,1) then 3
				else if [Hora_Analise] > #time(1,01,1) then 2
				else 1),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Personalização Adicionada5",{{"Personalizar", "dFaixa-Horario"}}),
				    #"Personalização Adicionada6" = Table.AddColumn(#"Colunas Renomeadas3", "Personalizar", each if [Hora_Analise] > #time(19,0,1) then 3
				else if [Hora_Analise] > #time(12,0,1) then 2
				else if [Hora_Analise] > #time(6,0,1) then 1
				else 4),
				    #"Colunas Renomeadas4" = Table.RenameColumns(#"Personalização Adicionada6",{{"Personalizar", "dPeriodo"}, {"Minutos-Intervalo", "Horas-Intervalo"}})
				in
				    #"Colunas Renomeadas4"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

