table Análises
	lineageTag: 273e3545-2f68-4ab9-bea3-9815ebc53cbf

	measure _Contratos_Anlisados = CALCULATE(DISTINCTCOUNT('Análises'[Id_Contrato]))
		formatString: 0
		lineageTag: cfa154c3-93dd-46ac-9a80-6db8a71c748c

	measure _AN_Documentação_Restrição =
			CALCULATE('Análises'[_AN_Total_Documentos],
			'Análises'[Restrição de Pagamento] = "Restrição de Pagamento")
		formatString: 0
		lineageTag: 03ca474b-c5d1-4637-bebb-301adfd0633f

	measure _AN_Total_Documentos = CALCULATE(DISTINCTCOUNT('Análises'[Id_Reanálise]))
		formatString: 0
		lineageTag: 246ceb2d-92e3-4ef5-a08b-36757611f291

	measure _AN_Reversão_Restricao_ =
			
			VAR REV = CALCULATE([_AN_Documentação_Restrição],
			'Análises'[Analisado por] = "Priscila Barros")
			
			
			RETURN REV
		formatString: 0
		lineageTag: d2a69a37-069b-4634-abb9-6ab14690ab87

	measure _AN_%Reversão_Documentos =
			
			var RES = 'Análises'[_AN_Documentação_Restrição]
			
			var REV = 'Análises'[_AN_Reversão_Restricao_]
			
			RETURN IF(REV = 0 && RES>0,0,REV/RES)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: f8fd2ed7-0fc6-4ab1-814d-22f88e5d4e04

	column Documento
		dataType: string
		lineageTag: 499b2670-0a8c-475c-87d1-d7c4911b82ae
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column DocumentSchedule
		dataType: string
		lineageTag: 3d183101-969f-4e7a-9d81-b22c1276246f
		summarizeBy: none
		sourceColumn: DocumentSchedule

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 5d805d1a-1ef6-46f3-8008-939f9d2b3630
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: a8f5d724-94eb-48d7-b98d-3a50d6870eb5
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 5bdbb043-cfb1-4a24-b99b-9cba55f9bd3a
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 66a36a34-0cc6-404a-8726-2768cc9f38c8
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: ed7abc84-9d28-4880-8ce9-61967e0f7e30
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo do documento'
		dataType: string
		lineageTag: 2941286a-0618-42fb-93bf-2945db3b00fa
		summarizeBy: none
		sourceColumn: Tipo do documento

		annotation SummarizationSetBy = Automatic

	column 'Restrição de Pagamento'
		dataType: string
		lineageTag: a19e8468-2060-4cb7-b9a4-cbc33665444a
		summarizeBy: none
		sourceColumn: Restrição de Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Analisado por'
		dataType: string
		lineageTag: c4c80cf8-7cb6-4ca8-b007-66cc943c8d28
		summarizeBy: none
		sourceColumn: Analisado por

		annotation SummarizationSetBy = Automatic

	column 'Prazo de Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7df263f0-e596-4914-895a-c468b2614cd5
		summarizeBy: none
		sourceColumn: Prazo de Envio

		variation Variation
			isDefault
			relationship: 0dd818a9-b6f3-40b3-b5d2-70cd9b4cff6b
			defaultHierarchy: LocalDateTable_f70c089c-e4bf-4f62-a605-c976fc6fb87d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Último Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 78a38d77-4046-4821-9951-db03b0b77e8c
		summarizeBy: none
		sourceColumn: Data Último Envio

		variation Variation
			isDefault
			relationship: 71df7b46-910a-45c3-b586-296dcd3350f6
			defaultHierarchy: LocalDateTable_7da8dd32-88a4-4e2f-a909-46763af17731.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Última Análise'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bd452460-3840-460b-905d-10d6a5e3b750
		summarizeBy: none
		sourceColumn: Data de Última Análise

		variation Variation
			isDefault
			relationship: 2b487693-4118-4849-8f6a-dd2a4addedde
			defaultHierarchy: LocalDateTable_bc62c781-6693-472d-9dc2-ecc57bf07d92.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Data_Envio
		dataType: dateTime
		formatString: General Date
		lineageTag: 52c47db9-758a-4fa7-8a06-67628a6b7f7a
		summarizeBy: none
		sourceColumn: Data_Envio

		variation Variation
			isDefault
			relationship: dcb6509f-a60b-46d0-8e52-93feab16314c
			defaultHierarchy: LocalDateTable_e5df5836-c3b9-47e1-9097-bb9e8be62df1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data de Renálise'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8606a346-5067-4c11-975c-2d4d5cb57bcc
		summarizeBy: none
		sourceColumn: Data de Renálise

		variation Variation
			isDefault
			relationship: 9d63278c-38ba-42f8-afd0-5a5251874b9c
			defaultHierarchy: LocalDateTable_44293742-83b5-4505-8ed9-0fd03adf61f2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ae5a5a46-2371-45ff-863e-c6dee5690993
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Id_Reanálise
		dataType: string
		lineageTag: 0aa8e11e-7685-4e8c-8161-dcf3eaf690a3
		summarizeBy: none
		sourceColumn: Id_Reanálise

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: e5e5514a-03ef-401c-a6f1-5e25dcf5c1c7
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	column Competência
		dataType: dateTime
		formatString: Long Date
		lineageTag: 60e60b6b-3520-42ac-b11d-84e45779727e
		summarizeBy: none
		sourceColumn: Competência

		variation Variation
			isDefault
			relationship: 8c55c364-52f2-4e09-90db-e56436c21bb1
			defaultHierarchy: LocalDateTable_d4d59c71-649e-4af8-bbf5-b7322eede8fa.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Análises = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="DECLARE @currentDate datetime2 = CAST(GETDATE() AS DATETIME);#(lf)DECLARE @organizationId uniqueidentifier = '23691bb8-3910-436a-9467-0df7b443fb38';#(lf)--DECLARE @initialDate datetime2 = '2025-10-01 00:00:00';#(lf)--DECLARE @finalDate datetime2 = CAST(GETDATE() AS DATETIME);#(lf)#(lf)#(lf)SELECT DISTINCT#(lf)       [ds].[Name] AS [Documento],#(lf)#(tab)   [ds].[Id] as [DocumentSchedule],#(lf)#(tab)    [c].[Id] AS [Id_Contrato],#(lf)#(lf)    CASE WHEN [c].[OrderNumber] IS NULL THEN '---' ELSE [c].[OrderNumber] END AS [Número do Pedido],#(lf)#(tab)#(lf)    [p].[TradeName] AS [Fornecedor],#(lf)    [bc].[CompanyName] AS [Razão Social],#(lf)    dbo.FormatCNPJ(bc.Document) as [CNPJ],#(lf)#(tab)CASE#(lf)        WHEN d.DeliveryKind = 0 THEN 'Recorrente'#(lf)        WHEN d.DeliveryKind = 1 THEN 'Mobilização'#(lf)        WHEN d.DeliveryKind = 2 THEN 'Treinamento'#(lf)#(tab)#(tab)WHEN d.DeliveryKind = 3 THEN 'Desmobilização'#(lf)        ELSE '--'#(lf)    END AS 'Tipo do documento',#(lf)#(tab)#(lf)CASE d.OrganizationRestrictions#(lf)        WHEN 0 THEN 'Nenhuma'#(lf)        WHEN 1 THEN 'Restrição de acesso'#(lf)        WHEN 2 THEN 'Restrição de pagamento'#(lf)        WHEN 3 THEN 'Restrição de acesso e Restrição de pagamento'#(lf)        ELSE '--'#(lf)    END AS [Restrição de Pagamento],#(lf)#(lf)#(tab)   #(tab) CASE#(lf)#(tab)#(tab)WHEN ds.ValidatedBy =  '00000000-0000-0000-0000-000000000000' THEN 'Validado Automaticamente'#(lf)        WHEN ds.ValidatedBy IS NULL THEN 'Pendente de Validação'#(lf)        ELSE ISNULL(u.Name, '---')#(lf)    END AS 'Analisado por',#(lf)#(lf)    FORMAT([ds].[ExpectedUploadAt], 'dd/MM/yyyy') AS [Prazo de Envio],#(lf)#(tab)FORMAT([ds].[UploadedAt], 'dd/MM/yyyy') AS [Data Último Envio],#(lf)    FORMAT([ds].[ValidatedAt], 'dd/MM/yyyy') AS [Data de Última Análise],#(lf)    ISNULL(FORMAT(df.CreatedAt, 'dd/MM/yyyy HH:mm:ss'), FORMAT(df.UpdatedAt,  'dd/MM/yyyy HH:mm:ss')) AS Data_Envio,#(lf)#(tab)FORMAT(dsv.Createdat, 'dd/MM/yyyy HH:mm:ss') AS [Data de Renálise],#(lf)#(tab)CASE #(lf)    WHEN dsv.id IS NOT NULL THEN#(lf)        CASE #(lf)            WHEN dsv.IsValid = 1 THEN 'Aprovado'#(lf)            WHEN dsv.IsValid = 0 THEN 'Reprovado'#(lf)            ELSE '---'#(lf)        END  #(lf)    ELSE #(lf)        CASE#(lf)            WHEN [ds].[ExpectedUploadAt] < @currentDate #(lf)                 AND ([ds].[UploadedAt] IS NULL OR [ds].[UploadedAt] > @currentDate) #(lf)                THEN 'Atrasado'#(lf)#(lf)            WHEN [ds].[ExpectedUploadAt] >= @currentDate #(lf)                 AND [ds].[UploadedAt] IS NULL #(lf)                THEN 'Próxima Entrega'#(lf)#(lf)            WHEN [ds].[ExpectedUploadAt] < @currentDate #(lf)                 AND [ds].[RequiresValidation] = 1 #(lf)                 AND [ds].[UploadedAt] IS NOT NULL #(lf)                 AND [ds].[ValidatedAt] IS NOT NULL #(lf)                 AND [ds].[IsValidated] = 0 #(lf)                THEN 'Atrasado Recusado'#(lf)#(lf)            WHEN [ds].[ExpectedUploadAt] >= @currentDate #(lf)                 AND [ds].[RequiresValidation] = 1 #(lf)                 AND [ds].[UploadedAt] IS NOT NULL #(lf)                 AND [ds].[ValidatedAt] IS NOT NULL #(lf)                 AND [ds].[IsValidated] = 0 #(lf)                THEN 'Próxima Entrega Recusado'#(lf)#(lf)            WHEN [ds].[UploadedAt] IS NOT NULL #(lf)                 AND [ds].[RequiresValidation] = 1 #(lf)                 AND [ds].[IsValidated] IS NULL #(lf)                THEN 'Em Análise'#(lf)#(lf)            WHEN [ds].[UploadedAt] IS NOT NULL #(lf)                 AND ([ds].[RequiresValidation] = 0 OR [ds].[IsValidated] = 1) #(lf)                THEN 'Aprovado'#(lf)#(lf)            ELSE '--'#(lf)        END#(lf)END AS [Status],#(lf)#(tab)dsv.id as 'Id_Reanálise',#(lf)#(tab)dsv.message,#(lf)Case#(lf)        WHEN d.Frequency = 2 and d.DeliveryKind = 0 THEN FORMAT(DATEADD(MONTH, -1, [ds].[ExpectedUploadAt]), 'MM/yyyy')#(lf)        ELSE FORMAT([ds].[ExpectedUploadAt], 'MM/yyyy')#(lf)    END AS [Competência]#(lf)FROM#(lf)    [DocumentSchedule] AS [ds] WITH (NOLOCK)#(lf)    INNER JOIN [Document] AS [d] WITH (NOLOCK) ON [ds].[DocumentId] = [d].[Id]#(lf)    INNER JOIN [Organization] AS [o] WITH (NOLOCK) ON [ds].[OrganizationId] = [o].[Id]#(lf)    INNER JOIN [BranchCompany] AS [bc] WITH (NOLOCK) ON [ds].[BranchCompanyId] = [bc].[Id]#(lf)    INNER JOIN [Provider] AS [p] WITH (NOLOCK) ON [bc].[ProviderId] = [p].[Id]#(lf)    LEFT JOIN [EmployeeRegister] AS [er] WITH (NOLOCK) ON [ds].[EmployeeRegisterId] = [er].[Id]#(lf)#(tab)Inner JOIN DocumentScheduleValidationLog as dsv WITH(NOLOCK) ON dsv.DocumentScheduleId = ds.Id#(lf)#(tab)LEFT JOIN [User] AS u WITH(NOLOCK) ON  u.Id = dsv.Responsibleid#(lf)#(tab)INNER JOIN DocumentFile as df WITH(NOLOCK) ON df.id = dsv.DocumentFileId#(lf)    INNER JOIN [Contract] AS [c] WITH (NOLOCK) ON (#(lf)        (#(lf)            [ds].[UploadedAt] IS NOT NULL#(lf)            OR [c].[Removed] = 0#(lf)        )#(lf)        AND [c].[BranchCompanyId] = [ds].[BranchCompanyId]#(lf)        AND EXISTS (SELECT 1 FROM [Building] AS [b] WITH (NOLOCK) WHERE [b].[Id] = [c].[BuildingId] AND [b].[Removed] = 0 AND [b].[OrganizationId] = @organizationId)#(lf)        AND (#(lf)            ([ds].[ContractId] = [c].[Id])#(lf)            OR (#(lf)                (#(lf)                    [d].[OrderNumberInclusiveOrExclusive] IS NULL#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 1#(lf)                        AND EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[OrderNumberInclusiveOrExclusive] = 0#(lf)                        AND NOT EXISTS (#(lf)                            SELECT 1#(lf)                            FROM STRING_SPLIT([d].[OrderNumber], ';')#(lf)                            WHERE value = [c].[OrderNumber]#(lf)                        )#(lf)                    )#(lf)                )#(lf)                AND ([ds].[ContractSetId] IS NULL OR [ds].[ContractSetId] = [c].[ContractSetId])#(lf)                AND ([d].[TypeContract] IS NULL OR ([d].[TypeContract] & [c].[Type]) = [c].[Type])#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[BuildingId] IS NOT NULL AND [ds].[BuildingId] = [c].[BuildingId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleBuilding] AS [dsb] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsb].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsb].[BuildingId] = [c].[BuildingId]#(lf)                                AND [dsb].[Removed] = 0#(lf)                        ) #(lf)                    )#(lf)                ) -- unidades#(lf)                AND (#(lf)                    (#(lf)                        ([ds].[CategoryId] IS NOT NULL AND [ds].[CategoryId] = [c].[CategoryId])#(lf)                    )#(lf)                    OR (#(lf)                        NOT EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        ) OR EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [DocumentScheduleCategory] AS [dsc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [dsc].[DocumentScheduleId] = [ds].[Id]#(lf)                                AND [dsc].[CategoryId] = [c].[CategoryId]#(lf)                                AND [dsc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- categorias#(lf)                AND (#(lf)                    ([d].[Frequency] = 7 AND [d].[OccurrenceKind] = 15 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Frequency] <> 7 OR [d].[OccurrenceKind] <> 15)#(lf)                )#(lf)                AND (#(lf)                    ([d].[Kind] = 4 AND [d].[DeliveryKind] = 3 AND [c].[ValidityFinal] < GETDATE()) -- se o documento for de desmobilização e o contrato estiver vencido#(lf)                    OR ([d].[Kind] <> 4 OR [d].[DeliveryKind] <> 3)#(lf)                )#(lf)                AND (#(lf)                    (#(lf)                        [d].[DeliveryKind] <> 0#(lf)                        AND [d].[DeliveryKind] <> 1#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 1#(lf)                        AND (#(lf)                            [ds].[ExpectedUploadAt] <= [c].[ValidityFinal]#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                        AND (#(lf)                            ([d].[DeliveryDay] < 0 AND DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) >= [c].[ValidityInitial])#(lf)                            OR ([d].[DeliveryDay] > 0 AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial])#(lf)                        )#(lf)                    )#(lf)                    OR (#(lf)                        [d].[DeliveryKind] = 0#(lf)                        AND [ds].[ExpectedUploadAt] >= [c].[ValidityInitial]#(lf)                        AND (#(lf)                            (#(lf)                                [d].[DeliveryDay] > 0#(lf)                                AND (#(lf)                                    DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, ([d].[DeliveryDay] * -1), [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                            OR (#(lf)                                [d].[DeliveryDay] < 0#(lf)                                AND (#(lf)                                    DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]) <= [c].[ValidityFinal]#(lf)                                    OR (#(lf)                                        DATEDIFF(MONTH, DATEADD(day, [d].[DeliveryDay], [ds].[ExpectedUploadAt]), [c].[ValidityFinal]) <= 1#(lf)                                    )#(lf)                                )#(lf)                            )#(lf)                        )#(lf)                    )#(lf)                ) -- deliveykind#(lf)                AND ( -- Agendamento por funcionario#(lf)                    [ds].[Kind] <> 5#(lf)                    OR (#(lf)                        [er].[Id] IS NOT NULL#(lf)                        AND [c].[BranchCompanyId] = [bc].[Id]#(lf)                        AND EXISTS (#(lf)                            SELECT#(lf)                                1#(lf)                            FROM#(lf)                                [EmployeeRegisterContract] AS [erc] WITH (NOLOCK)#(lf)                            WHERE#(lf)                                [erc].[EmployeeRegisterId] = [er].[Id]#(lf)                                AND [erc].[ContractId] = [c].[Id]#(lf)                                AND [erc].[Removed] = 0#(lf)                        )#(lf)                    )#(lf)                ) -- / Agendamento por funcionario#(lf)                AND ( -- Agendamento comum#(lf)                    [ds].[Kind] <> 1#(lf)                    OR (#(lf)                        [ds].[EmployeeRegisterId] IS NULL#(lf)                        AND [ds].[ContractId] IS NULL#(lf)                    )#(lf)                ) -- / Agendamento comum#(lf)            )#(lf)        )#(lf)    )#(lf)#(lf)WHERE#(lf)    [ds].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Removed] = CAST(0 AS bit)#(lf)    AND [d].[Archived] = CAST(0 AS bit)#(lf)    --AND [ds].[ExpectedUploadAt] >= @initialDate#(lf)    --AND [ds].[ExpectedUploadAt] < @finalDate#(lf)    AND [ds].[OrganizationId] = @organizationId#(lf)#(tab)and u.id = '800A0EA0-F909-4774-B444-538E05221582'#(lf)#(tab)--and ds.id = '4DB8E059-22ED-41A1-8D53-D3C01A26FAF6'#(lf)#(lf)order by ds.id#(lf)#(lf)#(lf)#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Prazo de Envio", type date}, {"Data Último Envio", type date}, {"Data de Última Análise", type date}, {"Data_Envio", type datetime}, {"Data de Renálise", type datetime}, {"Competência", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

