table Contratos
	lineageTag: e0caa39f-fbdf-4943-be91-62a2380a60ce

	measure 'Quantidade de Contratos' = CALCULATE(DISTINCTCOUNT('Contratos'[Nº do pedido]))
		formatString: 0
		lineageTag: 6ab24d3d-fe36-4e19-b9e5-d79400dab92b

	column CNPJ
		dataType: string
		lineageTag: 13c300b5-49a5-4055-88d9-79435326113a
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 45f7fa46-33a4-4074-8a3d-ddae627645c0
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6807157d-1dae-4c92-9dcb-549da11eacec
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: d76dd52f-6c95-4dfb-bef6-fb1c9da1febb
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 7a8df4d4-7c64-479a-b9af-7a4306f45e00
			defaultHierarchy: LocalDateTable_26a421c8-69b2-454c-be1a-4f481453dc9d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Vigência
		dataType: string
		lineageTag: b084cfa5-b092-4154-ba8c-37e31831970a
		summarizeBy: none
		sourceColumn: Vigência

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 78cd1b8d-5e29-4df8-9e3c-419cc3ccf0c2
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 2be4ae40-4107-4952-bf72-f3acd963f86d
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: d487f644-17f8-4fb1-8399-565293cfd376
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: 1a7c65c8-c7af-4974-8cd4-a39e6243a1ac
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Nº do pedido'
		dataType: string
		lineageTag: 4d46e101-adb0-4c13-9cfc-1c289e18d862
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: 2ae88061-679e-4178-b82a-0b3d0b7b84df
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: f015f9b2-f9b0-4a46-9699-89ca03fa9370
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column SLA
		dataType: string
		lineageTag: 08e55afc-8126-4f36-b4af-106f7c2b53a0
		summarizeBy: none
		sourceColumn: SLA

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 51a39857-689e-4032-a1e3-15ae0643f6cd
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: 0edbce29-222f-48de-addf-08877c00e770
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome do gestor do contrato'
		dataType: string
		lineageTag: c39b56ca-9784-404b-9dda-748031a9300f
		summarizeBy: none
		sourceColumn: Nome do gestor do contrato

		annotation SummarizationSetBy = Automatic

	column 'E-mail do gestor do contrato'
		dataType: string
		lineageTag: 72ecb7aa-bd31-4d19-b9de-b2b8349a9d5d
		summarizeBy: none
		sourceColumn: E-mail do gestor do contrato

		annotation SummarizationSetBy = Automatic

	column 'Fim da Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 76d10e50-a210-47e3-ac2a-a15aef97245b
		summarizeBy: none
		sourceColumn: Fim da Vigência

		variation Variation
			isDefault
			relationship: 13fc5a1c-8edf-4280-b629-cc8d4ec15756
			defaultHierarchy: LocalDateTable_d3faafd3-90c5-4d29-b86b-860c366249f2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'inicio da Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d8cf9e5d-e923-4284-afe7-deaf03874a26
		summarizeBy: none
		sourceColumn: inicio da Vigência

		variation Variation
			isDefault
			relationship: ce7b777b-3566-42f2-8ccd-6b86118414d6
			defaultHierarchy: LocalDateTable_603abb1f-23d2-49a8-932f-21ec8e198828.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Personalizar
		dataType: string
		lineageTag: faa4922d-25bb-4023-a9ba-0fbd5af7281b
		summarizeBy: none
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    bc.CompanyName[Razão Social],#(lf)    dbo.FormatCNPJ([bc].[Document]) AS [CNPJ],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],  #(lf)#(tab)cfv1.[Value][Nome do gestor do contrato],#(lf)#(tab)cfv2.[Value][E-mail do gestor do contrato]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)LEFT JOIN CustomFieldValue cfv1 WITH(NOLOCK) ON cfv1.EntityId = c.Id AND cfv1.CustomFieldId = '802C2D49-F3F7-4B3D-A399-6F6BBFFEDD7A'#(lf)#(tab)#(tab)LEFT JOIN CustomFieldValue cfv2 WITH(NOLOCK) ON cfv2.EntityId = c.Id AND cfv2.CustomFieldId = '2FEF3E1B-18B5-427F-9112-946E8589656E'#(lf)where b.OrganizationId = '23691bb8-3910-436a-9467-0df7b443fb38'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(lf)#(tab) #(lf)#(tab)  #(lf)#(tab)"]),
				    #"Linhas em Branco Removidas2" = Table.SelectRows(Fonte, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Linhas em Branco Removidas2",{{"N° do pedido", "Nº do pedido"}, {"Razão Social", "Razão social"}, {"Sla", "SLA"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Nº do pedido", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"SLA", type text}, {"Status", type text}, {"Cadastro no sistema", type datetime}, {"Vigência", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Personalizar", each [Nº do pedido]&[Fornecedor]),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada",{{"Personalizar", "Chave"}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Renomeadas","-GF","",Replacer.ReplaceText,{"Nº do pedido"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Valor Substituído", each ([Categoria] <> "CSC")),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Linhas Filtradas", "Vigência", "Fim da Vigência"),
				    #"Coluna Duplicada1" = Table.DuplicateColumn(#"Coluna Duplicada", "Fim da Vigência", "inicio da Vigência"),
				    #"Últimos caracteres extraídos" = Table.TransformColumns(#"Coluna Duplicada1", {{"Fim da Vigência", each Text.End(_, 10), type text}}),
				    #"Primeiros caracteres extraídos" = Table.TransformColumns(#"Últimos caracteres extraídos", {{"inicio da Vigência", each Text.Start(_, 10), type text}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Primeiros caracteres extraídos",{{"Fim da Vigência", type date}, {"inicio da Vigência", type date}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado1", "Personalizar", each if [Fim da Vigência] < #date(2025, 9, 1) then "N Vigente" else "Vigente")
				in
				    #"Coluna Condicional Adicionada"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

