table 'Dia - Dia - Status de fornecedores'
	lineageTag: 27519e80-2893-488a-98db-2d2f7c036f9c

	column Nome
		dataType: string
		lineageTag: 64c224ca-b2bc-4c0e-8761-db197b1add2a
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: d0ffdc51-ab5c-426f-accb-44fc8ec8c49b
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: e27db3ab-e104-4c2e-8990-a72ad1143879
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 904bbd19-e295-499f-aeef-37ff24f9cfae
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 0f1c3b65-dfd6-450a-82a1-e62a7734f75a
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: 3f04a15f-31fc-4287-a133-e2f8af9be1e1
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: faa3ecbf-1681-4a92-84d8-54ee0cd0f18b
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: bd66aa96-d92c-461e-b7ad-834887cb020b
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia do Subcontrato'
		dataType: string
		lineageTag: 1638f09e-f5dc-4840-aff6-b6182fe4902a
		summarizeBy: none
		sourceColumn: Nome Fantasia do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: 0de943fc-859e-40f5-8c5b-701b62201744
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: 47ded7af-8d08-4209-a45c-be27ae8a7809
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Vigência do Contrato.1'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8579c3b3-341e-4714-9d66-f0304ef0bd26
		summarizeBy: none
		sourceColumn: Vigência do Contrato.1

		variation Variation
			isDefault
			relationship: 63a8033f-614c-4a27-b2e0-d0586cb96322
			defaultHierarchy: LocalDateTable_208d9a00-dfbd-4179-8a77-4896771fc690.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência do Contrato.2'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 78a7571e-6f64-4582-b846-fc69867cff66
		summarizeBy: none
		sourceColumn: Vigência do Contrato.2

		variation Variation
			isDefault
			relationship: 8169aa5e-8810-4f4a-b25f-79312d21db34
			defaultHierarchy: LocalDateTable_064794c9-4e4d-47a0-8ba7-6cc6a03d6876.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: c707ea8d-ade5-48b9-a86a-418416f3a4e7
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 6d6c7f4c-6601-4b72-bd49-28f77a387a95
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Total Docs'
		dataType: int64
		formatString: 0
		lineageTag: 0a1f7460-4f1b-4367-872a-11c23898de0f
		summarizeBy: sum
		sourceColumn: Total Docs

		annotation SummarizationSetBy = Automatic

	column 'Documentos entregues'
		dataType: int64
		formatString: 0
		lineageTag: bf7f7aaa-bb1c-4ef9-b1e4-54d975262006
		summarizeBy: sum
		sourceColumn: Documentos entregues

		annotation SummarizationSetBy = Automatic

	column 'Taxa de entrega'
		dataType: double
		lineageTag: c5219095-38cd-4eb2-a5d5-05f563b80340
		summarizeBy: sum
		sourceColumn: Taxa de entrega

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Restrições
		dataType: string
		lineageTag: 90974d79-e176-49b2-8045-fd229b4bfbc7
		summarizeBy: none
		sourceColumn: Restrições

		annotation SummarizationSetBy = Automatic

	column 'Docs pendentes com restrição de pgto'
		dataType: string
		lineageTag: 2219f7c8-3b0e-4c32-8a26-215eabdd6dcc
		summarizeBy: none
		sourceColumn: Docs pendentes com restrição de pgto

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes'
		dataType: string
		lineageTag: 31943636-1c31-4d8e-b85e-1c45e0876ae3
		summarizeBy: none
		sourceColumn: Documentos pendentes

		annotation SummarizationSetBy = Automatic

	column 'Atividades do contrato'
		dataType: string
		lineageTag: fdd29f0c-aab6-4bcb-943e-4dce2a09b348
		summarizeBy: none
		sourceColumn: Atividades do contrato

		annotation SummarizationSetBy = Automatic

	column Chave
		dataType: string
		lineageTag: bfe574a9-0542-4dae-9d90-f80df2abc441
		summarizeBy: none
		sourceColumn: Chave

		annotation SummarizationSetBy = Automatic

	column 'Dias de Contrato'
		dataType: double
		lineageTag: 9896e66f-6144-4b98-bc0b-a3a37957f9eb
		summarizeBy: sum
		sourceColumn: Dias de Contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Personalizar
		dataType: double
		lineageTag: 12250c84-cee2-4daa-b0d0-99375b7f53cb
		summarizeBy: sum
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dias
		dataType: dateTime
		formatString: Long Date
		lineageTag: e4216fb8-2f08-48f0-9f87-aaa5536cb496
		summarizeBy: none
		sourceColumn: Dias

		variation Variation
			isDefault
			relationship: 5cdf5be2-9cdb-4f54-a0c0-acaa7d75b30e
			defaultHierarchy: LocalDateTable_aadf4b64-b608-4c18-8aa3-15f9d70c4225.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column diadia
		dataType: string
		lineageTag: eae964a5-2350-414d-b38d-6af3d59eb88c
		summarizeBy: none
		sourceColumn: diadia

		annotation SummarizationSetBy = Automatic

	column 'Qtde pessoas contratadas'
		dataType: string
		lineageTag: 73ec0e92-796b-45cc-b36d-f2ef7a34ff77
		summarizeBy: none
		sourceColumn: Qtde pessoas contratadas

		annotation SummarizationSetBy = Automatic

	column 'Quantidade de efetivos'
		dataType: int64
		formatString: 0
		lineageTag: 08bd1b3b-1781-4553-8486-f3fd7ea7851e
		summarizeBy: sum
		sourceColumn: Quantidade de efetivos

		annotation SummarizationSetBy = Automatic

	column 'Qtde funcionários mobilizados'
		dataType: string
		lineageTag: b6297bb1-6e9d-4621-ae23-4734dd959194
		summarizeBy: none
		sourceColumn: Qtde funcionários mobilizados

		annotation SummarizationSetBy = Automatic

	column 'Documentos em análise'
		dataType: string
		lineageTag: 853149f6-c541-449e-8b78-148d2653a4da
		summarizeBy: none
		sourceColumn: Documentos em análise

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: c71987aa-e8c4-4f81-943c-796599c72911
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	partition 'Dia - Dia - Status de fornecedores' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\RennanCosta\Diretório Padrão\Atlas Inovações - Documentos\Relatórios\Dados\02. Externo\01. AFM Gestão\CCR\2025\09  - Setembro\24.09\Fornecedores - 2509251652.xlsx")),
				    #"Status de fornecedores_sheet" = Fonte{[Item="Status de fornecedores",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Status de fornecedores_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas", List.Select(Table.ColumnNames(#"Linhas Superiores Removidas"), each try not List.IsEmpty(FilterNullAndWhitespace(Table.Column(#"Linhas Superiores Removidas", _))) otherwise true)),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Outras Colunas Removidas", each not List.IsEmpty(FilterNullAndWhitespace(Record.FieldValues(_)))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"Qtde funcionários cadastrados", "Quantidade de efetivos"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Nome", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Razão Social do Contrato", type text}, {"CNPJ do Contrato", type text}, {"Tipo de Fornecedor", type text}, {"Nome Fantasia do Subcontrato", type text}, {"Razão Social do Subcontrato", type text}, {"CNPJ do Subcontrato", type text}, {"Vigência do Contrato", type text}, {"Tipo de Contratação", type text}, {"Número do Pedido", type text}, {"Quantidade de efetivos", Int64.Type}, {"Total Docs", Int64.Type}, {"Documentos entregues", Int64.Type}, {"Taxa de entrega", type number}, {"Restrições", type text}, {"Docs pendentes com restrição de pgto", type text}, {"Documentos pendentes", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each true),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Linhas Filtradas", "diadia", each Text.Combine({[Nome], [Razão social], [CNPJ], [Categoria], [Unidade], [Razão Social do Contrato], [CNPJ do Contrato], [Tipo de Fornecedor], [Nome Fantasia do Subcontrato], [Razão Social do Subcontrato], [CNPJ do Subcontrato], [Vigência do Contrato], [Tipo de Contratação], [Número do Pedido], Text.From([Quantidade de efetivos], "pt-BR"), Text.From([Total Docs], "pt-BR"), Text.From([Documentos entregues], "pt-BR"), Text.From([Taxa de entrega], "pt-BR"), [Restrições], [Docs pendentes com restrição de pgto], [Documentos pendentes]}, ""), type text),
				    #"Linhas em Branco Removidas1" = Table.SelectRows(#"Coluna Mesclada Inserida", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas em Branco Removidas1", "Chave", each [Unidade]&[Nome]&[Categoria]),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Personalização Adicionada", "Vigência do Contrato", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Vigência do Contrato.1", "Vigência do Contrato.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência do Contrato.1", type date}, {"Vigência do Contrato.2", type date}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado1", "Dias de Contrato", each [Vigência do Contrato.2]-[Vigência do Contrato.1]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Dias de Contrato", type number}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado2", "Personalizar", each {1..[Dias de Contrato]}),
				    #"Personalizar Expandido" = Table.ExpandListColumn(#"Personalização Adicionada2", "Personalizar"),
				    #"Valor Substituído" = Table.ReplaceValue(#"Personalizar Expandido",null,1,Replacer.ReplaceValue,{"Personalizar"}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Valor Substituído",{{"Personalizar", type number}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado3", "Personalizar.1", each Date.AddDays([Vigência do Contrato.1],[Personalizar]-1)),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada3",{{"Personalizar.1", "Dias"}}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Dias", type date}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado4", each ([Tipo de Contratação] <> "Temporário") and ([Categoria] <> "CSC"))
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

