table Calendário
	lineageTag: 16ccd1cd-ff52-4289-abf4-26d0ad25a1d5

	measure 'Quantidade de Dias Mês a Mês' = CALCULATE(COUNTROWS()*CALCULATE(COUNT('Tabela Chave'[Locação])))
		formatString: 0
		lineageTag: 376902a8-8e5e-4a45-9c59-5959785bc734

	column Date
		formatString: Short Date
		lineageTag: 6a9b6935-ff32-40a7-b7ec-8e9e94931520
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		variation Variation
			isDefault
			relationship: a42133a6-bfd2-4cb1-a5d4-608ca0b658da
			defaultHierarchy: LocalDateTable_32c0a325-e08e-4784-98d8-311afb811eaa.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Calendário = calculated
		mode: import
		source = CALENDAR(DATE(2015,01,01),DATE(2050,12,31))

	annotation PBI_Id = 5d5a4fbad5f74d79b55d302c0a17fc41

