table 'Status de funcionários'
	lineageTag: 306a3cbf-4bcc-4536-b418-70304ae46aac

	measure 'Nº do Pedidos' = CALCULATE(COUNT('Status de funcionários'[Número do Pedido]))
		formatString: 0
		lineageTag: ac9ee50b-a519-46a7-b0eb-baa960d104fb

	measure Colaboradores = CALCULATE(DISTINCTCOUNT('Status de funcionários'[chave]))
		formatString: #,0
		lineageTag: a97f3ef2-ef81-4e5d-ae54-ad388b8c50b6

	column CPF
		dataType: string
		lineageTag: 906e7f44-be2f-4774-a072-a9411f775971
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column PIS
		dataType: string
		lineageTag: d1664ab9-5cf1-4d1b-ba2c-8616749f04e8
		summarizeBy: none
		sourceColumn: PIS

		annotation SummarizationSetBy = Automatic

	column 'Documento Estrangeiro'
		dataType: string
		lineageTag: d54fb551-bc09-4485-aa01-4d400232b4d7
		summarizeBy: none
		sourceColumn: Documento Estrangeiro

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: b5f84dbe-ebd7-4403-8773-cb0f0bede5ee
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 9fad88be-9ec3-4029-840a-c97cf87f9673
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: 816f37a5-84b5-4291-b621-cc4b3476adf5
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: f5ded8a2-5b3a-4a60-b372-bb7ae3f6c534
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 9dd20c75-32c3-4856-b086-efcd944c0abd
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: 381ac428-1f17-45d2-be98-68b469329e82
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: 45df4578-e1b6-40a3-8b3c-76584b1e979d
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: 829a5547-e165-43ea-8856-c06026ee8125
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia do Subcontrato'
		dataType: string
		lineageTag: a0caa420-cb1c-42a4-8742-d0137e9f3059
		summarizeBy: none
		sourceColumn: Nome Fantasia do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: d9f6485b-83ae-4f16-bd83-1c067168146c
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: 89e1c358-6308-494b-8684-a2386173b7bc
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: 73df0f9d-56e3-4d58-ac89-5d99bb2f9c60
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Modalidade de Contratação'
		dataType: string
		lineageTag: 78d82d25-12a0-49e8-b9de-bd27f09a1110
		summarizeBy: none
		sourceColumn: Modalidade de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Tipo de moradia'
		dataType: string
		lineageTag: 42585152-9928-4bdf-9467-cb129f001f15
		summarizeBy: none
		sourceColumn: Tipo de moradia

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 4a4c6e5f-4224-461f-bcd8-307774eb764c
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: 4236efd2-1e55-4446-afa8-e2fca3c25a35
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column Escala
		dataType: string
		lineageTag: a73e0e7b-c052-492b-9a79-bf28fbafe562
		summarizeBy: none
		sourceColumn: Escala

		annotation SummarizationSetBy = Automatic

	column 'Início da jornada'
		dataType: string
		lineageTag: 7ffd9949-d2f9-4763-9a34-86a78a238bb4
		summarizeBy: none
		sourceColumn: Início da jornada

		annotation SummarizationSetBy = Automatic

	column 'Término da jornada'
		dataType: string
		lineageTag: fe1b184a-8be2-4a77-8bbd-de86e0e09bb6
		summarizeBy: none
		sourceColumn: Término da jornada

		annotation SummarizationSetBy = Automatic

	column 'Total de Docs'
		dataType: string
		lineageTag: 331610fc-cbc5-4da8-a42e-111f710a0d03
		summarizeBy: none
		sourceColumn: Total de Docs

		annotation SummarizationSetBy = Automatic

	column 'Total de válidos'
		dataType: string
		lineageTag: 0bc63c18-50bb-4a19-93e3-c0cf02f6d452
		summarizeBy: none
		sourceColumn: Total de válidos

		annotation SummarizationSetBy = Automatic

	column '% docs válidos'
		dataType: string
		lineageTag: 890d91c2-a160-40c2-a956-a5e3a7654280
		summarizeBy: none
		sourceColumn: % docs válidos

		annotation SummarizationSetBy = Automatic

	column 'Total em análise'
		dataType: string
		lineageTag: 719649d7-f6c3-4e98-aa27-d95a291eee8d
		summarizeBy: none
		sourceColumn: Total em análise

		annotation SummarizationSetBy = Automatic

	column '% docs em análise'
		dataType: string
		lineageTag: ec142df2-41d0-4e59-a138-b93d4b5d3209
		summarizeBy: none
		sourceColumn: % docs em análise

		annotation SummarizationSetBy = Automatic

	column 'Total pendentes'
		dataType: string
		lineageTag: d48bab64-64a4-4103-8cca-bfcfca5a8da7
		summarizeBy: none
		sourceColumn: Total pendentes

		annotation SummarizationSetBy = Automatic

	column '% docs entregues'
		dataType: string
		lineageTag: 2124b3ba-400f-4361-bb26-a8539b7407c7
		summarizeBy: none
		sourceColumn: % docs entregues

		annotation SummarizationSetBy = Automatic

	column 'Mobilizado até'
		dataType: string
		lineageTag: 164a8a69-ef26-44f7-a908-98ced150f6db
		summarizeBy: none
		sourceColumn: Mobilizado até

		annotation SummarizationSetBy = Automatic

	column 'Próximo documento a vencer'
		dataType: string
		lineageTag: 4d09f040-9e10-4248-877c-7889c23505df
		summarizeBy: none
		sourceColumn: Próximo documento a vencer

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes (Não entregues ou Recusados)'
		dataType: string
		lineageTag: 150f0bf5-ea0c-4823-975f-df792418d3eb
		summarizeBy: none
		sourceColumn: Documentos pendentes (Não entregues ou Recusados)

		annotation SummarizationSetBy = Automatic

	column Chave2
		dataType: string
		lineageTag: 30675fa0-f9b3-47bc-b8cb-53af61767c22
		summarizeBy: none
		sourceColumn: Chave2

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no Sistema' = LOOKUPVALUE(Contratos[Cadastro no sistema],Contratos[Chave],'Status de funcionários'[Chave2])
		formatString: General Date
		lineageTag: 095a2551-63f8-4014-a6c6-ada60eb5da88
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 5deae9a1-2dbe-498e-a162-ceff7c986397
			defaultHierarchy: LocalDateTable_d8a03ebf-7220-4959-9d3f-1db5beff109d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Mês/Ano - Cadastro' = FORMAT('Status de funcionários'[Cadastro no Sistema],"mm/yyyy")
		lineageTag: a27ad93e-3ae8-478f-8647-8c54682cc367
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 903bf146-b6a8-465b-88c6-c0ff6d731a0d
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column chave
		dataType: string
		lineageTag: 0a31d225-635d-4c9f-9c36-a0908f45ea4b
		summarizeBy: none
		sourceColumn: chave

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20446bfd-2081-4bd5-9309-1718041eeec6
		summarizeBy: none
		sourceColumn: Vigência Inicio

		variation Variation
			isDefault
			relationship: 69ba44d9-0ca7-4c71-b1c6-600362dd1416
			defaultHierarchy: LocalDateTable_8ce819a8-6848-4298-9007-cccbc6fd723f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Fim'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 11023414-b327-4c98-a5e5-58be964fe238
		summarizeBy: none
		sourceColumn: Vigência Fim

		variation Variation
			isDefault
			relationship: 0bbaa3c5-e3cb-4d51-bc1e-2b4b47287f75
			defaultHierarchy: LocalDateTable_9125dfc1-8d84-4c84-83ab-45307836e9e9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Referência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f4c7bca-8087-4018-8264-2359a631d5d4
		summarizeBy: none
		sourceColumn: Data de Referência

		variation Variation
			isDefault
			relationship: c05692ee-5c1f-4260-a66e-68bb2d5d28ab
			defaultHierarchy: LocalDateTable_6bd8983b-cb58-4868-b11c-7dc6cf43bece.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status do Contrato'
		dataType: string
		lineageTag: 579ac12d-ea86-4f6b-933a-5510f84b69a7
		summarizeBy: none
		sourceColumn: Status do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Número de matrícula'
		dataType: string
		lineageTag: 16cef592-39c0-416d-9f09-2698ef446df3
		summarizeBy: none
		sourceColumn: Número de matrícula

		annotation SummarizationSetBy = Automatic

	column 'Número de matrícula_1'
		dataType: string
		lineageTag: 580bb50b-0614-475e-a5cc-aa240f37fd44
		summarizeBy: none
		sourceColumn: Número de matrícula_1

		annotation SummarizationSetBy = Automatic

	column 'Status Restrição de acesso'
		dataType: string
		lineageTag: 54850702-03a4-479d-b9d2-ca7ad2eeac1e
		summarizeBy: none
		sourceColumn: Status Restrição de acesso

		annotation SummarizationSetBy = Automatic

	column 'Data Referência'
		dataType: string
		lineageTag: 06296149-60b1-4f02-9a2b-cfcf296df586
		summarizeBy: none
		sourceColumn: Data Referência

		annotation SummarizationSetBy = Automatic

	column 'Início e Fim das Atividades'
		dataType: string
		lineageTag: 2e2bb17e-9663-40c5-9b34-0798fc4c1073
		summarizeBy: none
		sourceColumn: Início e Fim das Atividades

		annotation SummarizationSetBy = Automatic

	partition 'Status de funcionários' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://adminatlasinovacoescom.sharepoint.com/:x:/r/sites/DiretrioPadro/Documentos%20Compartilhados/Relat%C3%B3rios/Dados/02.%20Externo/01.%20AFM%20Gest%C3%A3o/Pirelli/(Excel)%20Hist%C3%B3rico%20Funcionarios.xlsx"), null, true),
				    #"Status de funcionários_Sheet" = Fonte{[Item="Status de funcionários",Kind="Sheet"]}[Data],
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Status de funcionários_Sheet", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Personalização Adicionada" = Table.AddColumn(#"Cabeçalhos Promovidos1", "Chave2", each [Número do Pedido]&[Fornecedor]&[Categoria]&[Unidade]&[CNPJ]),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "chave", each [Nome]&[CPF]&[PIS]),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Personalização Adicionada1", "Vigência do Contrato", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Vigência do Contrato.1", "Vigência do Contrato.2"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência do Contrato.1", type date}, {"Vigência do Contrato.2", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Vigência do Contrato.1", "Vigência Inicio"}, {"Vigência do Contrato.2", "Vigência Fim"}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Colunas Renomeadas", "Data Referência", each Date.EndOfMonth(Date.AddMonths(DateTime.FixedLocalNow(),-1))),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada2",{{"Data de Referência", type date}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado1", "Status do Contrato", each if [Vigência Inicio] > [Data de Referência] then "Vigência Futura"
				else if [Vigência Fim] <= [Data de Referência] then "Vigência finalizada"
				else "Vigente"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada3", each ([Unidade] <> "PIRELLI PNEUS Goiana"))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

