table Contratos
	lineageTag: 087190bb-78e2-480f-b2b5-a7545f8dad88

	column CNPJ
		dataType: string
		lineageTag: 7df61d5d-9edd-4487-bc47-ed9045090a3f
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: c128ef9c-0b4e-49a0-be5a-f5527458e2b3
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: a13b2a40-3de2-499c-bfb3-dc53c59ecd12
			defaultHierarchy: LocalDateTable_8d94d826-6bf2-466d-89d7-57940de24b60.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Início Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5d3cdf95-8231-46b0-aa97-5cc7aaa7fd0d
		summarizeBy: none
		sourceColumn: Início Vigência

		variation Variation
			isDefault
			relationship: a020eb9c-ae35-4a1a-a48c-577d3dc6ba0e
			defaultHierarchy: LocalDateTable_6f7c3d1a-c4b0-4a62-a5d8-f7a83be4883c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 37a05a3c-fe47-430a-99de-6e33f45fb145
		summarizeBy: none
		sourceColumn: Fim Vigência

		variation Variation
			isDefault
			relationship: c88a2474-018d-4ce5-85d8-df60151de58a
			defaultHierarchy: LocalDateTable_73cbebba-0c00-4a1b-8549-afb0fc619c4f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: 2c5af1c5-99bf-4015-8aec-52dc18378359
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: e7b59119-be1a-42c7-91ee-ed8d145015a1
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 0b5d41c1-2820-495f-a36d-05320b16a151
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Status Contrato'
		dataType: string
		lineageTag: d829377f-3b17-4dbb-ac78-73902c885c92
		summarizeBy: none
		sourceColumn: Status Contrato

		annotation SummarizationSetBy = Automatic

	column Fornecedor-Categoria-Unidade
		dataType: string
		lineageTag: 294920e8-1ad0-4be7-a9b1-2fa77d454b1d
		summarizeBy: none
		sourceColumn: Fornecedor-Categoria-Unidade

		annotation SummarizationSetBy = Automatic

	column 'CNPJ Matriz'
		dataType: string
		lineageTag: 10224e59-bb2e-4aed-93f2-3eee504c8200
		summarizeBy: none
		sourceColumn: CNPJ Matriz

		annotation SummarizationSetBy = Automatic

	column 'CND.Emissão'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a30ed8b4-51e9-4de7-b910-74be9762c8b7
		summarizeBy: none
		sourceColumn: CND.Emissão

		variation Variation
			isDefault
			relationship: 46c1b14d-df94-42ed-9db8-a1ccb5886a08
			defaultHierarchy: LocalDateTable_2081e7be-403c-4351-8cba-b0e97db359b1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CND.Validade'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 93f93bce-7040-45de-ad55-73b933038666
		summarizeBy: none
		sourceColumn: CND.Validade

		variation Variation
			isDefault
			relationship: 32795ec1-5966-4e75-b1a9-dd609caf9d5a
			defaultHierarchy: LocalDateTable_76ad3026-a82e-48ca-b370-94e8d2b8b210.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CND.Status Certidão'
		dataType: string
		lineageTag: c52a7308-a6d4-44e3-8f11-2f7fd77c4e72
		summarizeBy: none
		sourceColumn: CND.Status Certidão

		annotation SummarizationSetBy = Automatic

	column 'CND.Status Validade'
		dataType: string
		lineageTag: bb504a58-e5d5-4586-b5c3-725ff26fe394
		summarizeBy: none
		sourceColumn: CND.Status Validade

		annotation SummarizationSetBy = Automatic

	column 'N° do pedido'
		dataType: string
		lineageTag: 1212eeca-c417-4c27-ae16-aad38caf0b97
		summarizeBy: none
		sourceColumn: N° do pedido

		annotation SummarizationSetBy = Automatic

	column Id_Contrato
		dataType: string
		lineageTag: adce6d3b-1589-4ae7-a9e7-2ee508359922
		summarizeBy: none
		sourceColumn: Id_Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social'
		dataType: string
		lineageTag: 1210bf3b-77ab-4c92-baca-8969bd3351b5
		summarizeBy: none
		sourceColumn: Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 5e1b8212-5f12-432c-b813-5b7913aad643
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: 96d43c25-d84a-4cf0-9ba8-dcac139da1b6
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 45a83893-a4bd-4903-a080-13e2906806b9
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 2da7597d-97fa-4745-b5ae-7485505f17f5
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[N° do pedido],#(lf)#(tab)c.Id [Id_Contrato],#(lf)    bc.CompanyName[Razão Social],#(lf)   dbo.FNCNPJMask(bc.Document) as [CNPJ],#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor]#(lf)from [Contract] c with(nolock)#(lf)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)#(lf)where b.OrganizationId = 'D0E56D74-D3A3-41E5-BC33-34DA6F706B8C'#(lf)"]),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(Fonte, "Vigência", Splitter.SplitTextByDelimiter(" a ", QuoteStyle.Csv), {"Início Vigência", "Fim Vigência"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Início Vigência", type date}, {"Fim Vigência", type date}}),
				    
				    
				    // Calcula o primeiro dia do mês de hoje menos 2 meses
				    ReferenciaData = Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()), -2)),
				
				    // Coluna condicional automática baseada na referência calculada
				    #"Coluna Condicional Adicionada" = Table.AddColumn(
				        #"Tipo Alterado2",
				    "Status Contrato",
				    each if [Início Vigência] <= ReferenciaData and [Fim Vigência] >= ReferenciaData 
				         then "Vigente"
				         else "Não Vigente"
				),
				
				
				
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Coluna Condicional Adicionada", "Fornecedor-Categoria-Unidade", each Text.Combine({[Fornecedor], [Categoria], [Unidade]}, " - "), type text),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Coluna Mesclada Inserida", each ([Status Contrato] = "Vigente")),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas1", each ([Status Contrato] = "Vigente") and ([Fornecedor] <> "TESTE FORNECEDOR 1" and [Fornecedor] <> "TESTE FORNECEDOR 2")),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Linhas Filtradas", {"CNPJ"}, ListaCNPJs, {"CNPJ"}, "ListaCNPJs", JoinKind.LeftOuter),
				    #"ListaCNPJs Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "ListaCNPJs", {"CNPJ Matriz"}, {"CNPJ Matriz"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"ListaCNPJs Expandido", {"Fornecedor-Categoria-Unidade"}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Duplicatas Removidas", {"CNPJ Matriz"}, CND, {"CNPJ"}, "CND", JoinKind.LeftOuter),
				    #"CND Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "CND", {"Emissão", "Validade", "Status Certidão", "Status Validade"}, {"CND.Emissão", "CND.Validade", "CND.Status Certidão", "CND.Status Validade"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"CND Expandido",null,"Certidão não emitida",Replacer.ReplaceValue,{"CND.Status Certidão"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",null,"Certidão não emitida",Replacer.ReplaceValue,{"CND.Status Validade"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído1",{{"CND.Emissão", type date}, {"CND.Validade", type date}, {"CND.Status Certidão", type text}, {"CND.Status Validade", type text}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

