table 'Indicadores de Risco'
	lineageTag: 5ad62308-541f-40eb-b3bb-042caf2e4c3b

	column Risco
		dataType: string
		lineageTag: 3ec9cc78-e059-42ff-8924-b45090d463b0
		summarizeBy: none
		sourceColumn: Risco

		annotation SummarizationSetBy = Automatic

	column Ordem
		dataType: int64
		formatString: 0
		lineageTag: 044a3230-1dda-44a6-a36e-36ff1efd14b3
		summarizeBy: sum
		sourceColumn: Ordem

		annotation SummarizationSetBy = Automatic

	column '% Entrega de Documentos'
		dataType: string
		lineageTag: 335871f1-1e66-4801-bae9-1f45d793f106
		summarizeBy: none
		sourceColumn: % Entrega de Documentos
		sortByColumn: Ordem

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Indicadores de Risco' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcswpyVfSUXJMSsysyFdISVUwNlAF8g2VYnWilXwPr0zJBEm75pUUgaUUUhXMwQqMwAqcQLpA2pMzcxNBuiGSxkqxsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Risco = _t, #"% Entrega de Documentos" = _t, Ordem = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Risco", type text}, {"% Entrega de Documentos", type text}, {"Ordem", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

