table 'Status do Fornecedores'
	lineageTag: 6f05e263-bb70-4969-84d3-7ffde8466f2a

	measure _Quantidade_Contratos = CALCULATE(COUNTROWS())
		formatString: 0
		lineageTag: 0bf7353f-ed22-4f3b-a3c1-cf45b2256c67

	column Fornecedor
		dataType: string
		lineageTag: 5dd34db0-fb29-463e-9b17-12779528562a
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 9f652e86-f3ac-465e-8c18-801bf4bd6570
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: e842513f-0f4d-486f-bb7e-ca5a15a64d0f
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 410b65d1-7933-4481-a644-0a0db0109ea1
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 333f8c72-8790-48ef-b0ca-e11039845f08
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Contrato'
		dataType: string
		lineageTag: 634d6921-9bde-4152-bbc0-dc6559f448cf
		summarizeBy: none
		sourceColumn: Razão Social do Contrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Contrato'
		dataType: string
		lineageTag: e7b3f18d-6f84-4d45-8665-3a909f3c7789
		summarizeBy: none
		sourceColumn: CNPJ do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: 71fa4d5d-b4e7-48f2-b277-60970dae2888
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Nome Fantasia do Subcontrato'
		dataType: string
		lineageTag: 8f8662f1-5d16-482c-a252-847d1ec9f61e
		summarizeBy: none
		sourceColumn: Nome Fantasia do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Razão Social do Subcontrato'
		dataType: string
		lineageTag: 48c3fe02-4325-4793-95a6-b663c0f3dd0a
		summarizeBy: none
		sourceColumn: Razão Social do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'CNPJ do Subcontrato'
		dataType: string
		lineageTag: d329b84a-9b6d-4d19-831f-d9aaf93719fe
		summarizeBy: none
		sourceColumn: CNPJ do Subcontrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contratação'
		dataType: string
		lineageTag: e295e3bc-65e5-401f-bed1-606c2ae106b2
		summarizeBy: none
		sourceColumn: Tipo de Contratação

		annotation SummarizationSetBy = Automatic

	column 'Número do Pedido'
		dataType: string
		lineageTag: 49a29c92-42cd-4591-89ba-673e0b610894
		summarizeBy: none
		sourceColumn: Número do Pedido

		annotation SummarizationSetBy = Automatic

	column 'Total Docs'
		dataType: int64
		formatString: 0
		lineageTag: df8bff08-f30b-472d-ba72-afe2d8b2911f
		summarizeBy: sum
		sourceColumn: Total Docs

		annotation SummarizationSetBy = Automatic

	column 'Documentos entregues'
		dataType: int64
		formatString: 0
		lineageTag: 52f87da4-20d7-4e6f-b8f8-a4c365414bd4
		summarizeBy: sum
		sourceColumn: Documentos entregues

		annotation SummarizationSetBy = Automatic

	column 'Taxa de entrega'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8650093a-5e14-4502-af3d-d98d0d8d2d5c
		summarizeBy: sum
		sourceColumn: Taxa de entrega

		annotation SummarizationSetBy = Automatic

	column Restrições
		dataType: string
		lineageTag: 62d20db8-bfb4-4f95-9823-20cf99f065ab
		summarizeBy: none
		sourceColumn: Restrições

		annotation SummarizationSetBy = Automatic

	column 'Docs pendentes com restrição de pgto'
		dataType: string
		lineageTag: 39fb96fc-f3fc-4454-855c-054d571a5802
		summarizeBy: none
		sourceColumn: Docs pendentes com restrição de pgto

		annotation SummarizationSetBy = Automatic

	column 'Documentos pendentes'
		dataType: string
		lineageTag: e8f8215c-d42f-4173-9e0a-cc92c13bf800
		summarizeBy: none
		sourceColumn: Documentos pendentes

		annotation SummarizationSetBy = Automatic

	column 'N de Docs Pendentes'
		dataType: string
		lineageTag: 686d7942-bec7-46e5-9413-4e03863d54a3
		summarizeBy: none
		sourceColumn: N de Docs Pendentes

		annotation SummarizationSetBy = Automatic

	column 'Taxa de Pendência'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8504b944-ea55-4045-b3ca-74433987ce21
		summarizeBy: sum
		sourceColumn: Taxa de Pendência

		annotation SummarizationSetBy = Automatic

	column 'Status do Fornecedor'
		dataType: string
		lineageTag: a7f0046b-d5f7-4c9b-a022-d8ac4a92a4cf
		summarizeBy: none
		sourceColumn: Status do Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Vigência do Contrato Inicio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b632abc8-7662-4fa2-8729-49682263c406
		summarizeBy: none
		sourceColumn: Vigência do Contrato Inicio

		variation Variation
			isDefault
			relationship: c4e27a1e-b071-4a90-bc4e-7629315aede6
			defaultHierarchy: LocalDateTable_29dc1f1a-8950-49c9-9312-66fbca8aa175.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência do Contrato Fim'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ed278654-cd08-4857-a4f9-f1ebe6e7be91
		summarizeBy: none
		sourceColumn: Vigência do Contrato Fim

		variation Variation
			isDefault
			relationship: f966eb6b-d1e8-4e9a-af09-48f3b4a9e796
			defaultHierarchy: LocalDateTable_38af1735-8ab0-48bf-9a6a-39a0e8bbc129.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Índice
		dataType: string
		lineageTag: 47f2afb1-0c75-49bc-9fd8-239f18bb9c35
		summarizeBy: none
		sourceColumn: Índice

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Atividades do contrato'
		dataType: string
		lineageTag: 2911ccce-2087-4123-b4bb-5f9ac2e1c0d5
		summarizeBy: none
		sourceColumn: Atividades do contrato

		annotation SummarizationSetBy = Automatic

	column 'Qtde pessoas contratadas'
		dataType: string
		lineageTag: a4087403-2ca8-4b5d-81fc-277f8025ef05
		summarizeBy: none
		sourceColumn: Qtde pessoas contratadas

		annotation SummarizationSetBy = Automatic

	column 'Qtde funcionários mobilizados'
		dataType: string
		lineageTag: e78f1143-4fa4-41b1-8def-22708f0e7347
		summarizeBy: none
		sourceColumn: Qtde funcionários mobilizados

		annotation SummarizationSetBy = Automatic

	column 'Documentos em análise'
		dataType: string
		lineageTag: 7962c0fa-73eb-4e9d-a9de-08443f62f01e
		summarizeBy: none
		sourceColumn: Documentos em análise

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: f3bcd9dc-7928-40c9-a62a-633211b44156
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column 'Quantidade de efetivos'
		dataType: int64
		formatString: 0
		lineageTag: d998edc8-0b84-4d35-bdc8-3270a38db1b8
		summarizeBy: sum
		sourceColumn: Quantidade de efetivos

		annotation SummarizationSetBy = Automatic

	partition 'Status do Fornecedores' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\RennanCosta\Diretório Padrão\Atlas Inovações - Documentos\Relatórios\Dados\02. Externo\01. AFM Gestão\RochaLog\2026\01 - Janeiro\Fornecedores - 260106151558.xlsx")),
				    #"Status de fornecedores_sheet" = Fonte{[Item="Status de fornecedores",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Status de fornecedores_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas", List.Select(Table.ColumnNames(#"Linhas Superiores Removidas"), each try not List.IsEmpty(FilterNullAndWhitespace(Table.Column(#"Linhas Superiores Removidas", _))) otherwise true)),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Outras Colunas Removidas", each not List.IsEmpty(FilterNullAndWhitespace(Record.FieldValues(_)))),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas em Branco Removidas", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"Qtde funcionários cadastrados", "Quantidade de efetivos"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas2",{{"Nome", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Categoria", type text}, {"Unidade", type text}, {"Razão Social do Contrato", type text}, {"CNPJ do Contrato", type text}, {"Tipo de Fornecedor", type text}, {"Nome Fantasia do Subcontrato", type text}, {"Razão Social do Subcontrato", type text}, {"CNPJ do Subcontrato", type text}, {"Vigência do Contrato", type text}, {"Tipo de Contratação", type text}, {"Número do Pedido", type text}, {"Quantidade de efetivos", Int64.Type}, {"Total Docs", Int64.Type}, {"Documentos entregues", Int64.Type}, {"Taxa de entrega", type number}, {"Restrições", type text}, {"Docs pendentes com restrição de pgto", type text}, {"Documentos pendentes", type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "N de Docs Pendentes", each [Total Docs] - [Documentos entregues]),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Personalização Adicionada",{"Nome", "Razão social", "CNPJ", "Categoria", "Unidade", "Razão Social do Contrato", "CNPJ do Contrato", "Tipo de Fornecedor", "Nome Fantasia do Subcontrato", "Razão Social do Subcontrato", "CNPJ do Subcontrato", "Vigência do Contrato", "Tipo de Contratação", "Número do Pedido", "Quantidade de efetivos", "Total Docs", "Documentos entregues", "N de Docs Pendentes", "Taxa de entrega", "Restrições", "Docs pendentes com restrição de pgto", "Documentos pendentes"}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Colunas Reordenadas", "Taxa de Pendência", each if [N de Docs Pendentes]= 0 then 0
				else [N de Docs Pendentes]/[Total Docs]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Taxa de Pendência", Percentage.Type}}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado1", "Status do Fornecedor", each if [Taxa de Pendência] = 1 then "Risco Crítico" else if [Taxa de Pendência] >= 0.5 then "Risco Alto" else if [Taxa de Pendência] > 0.2 then "Risco Médio" else if [Taxa de Pendência] >= 0 then "Risco Baixo" else "Sem Classificação"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada2",{{"Nome", "Fornecedor"}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Colunas Renomeadas", "Vigência do Contrato", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Vigência do Contrato.1", "Vigência do Contrato.2"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência do Contrato.1", type date}, {"Vigência do Contrato.2", type date}}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Tipo Alterado2",{{"Vigência do Contrato.1", "Vigência do Contrato Inicio"}, {"Vigência do Contrato.2", "Vigência do Contrato Fim"}}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Colunas Renomeadas1",{{"Razão social", Text.Upper, type text}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Texto em Maiúscula", "Índice", 1, 1, Int64.Type)
				in
				    #"Índice Adicionado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

