table Contratos
	lineageTag: 044b70ef-adf1-4c5a-8e53-c6e64d7fc597

	column 'Nº do pedido'
		dataType: string
		lineageTag: 993bcc94-0162-4f04-a2b6-4b89b0a6d480
		summarizeBy: none
		sourceColumn: Nº do pedido

		annotation SummarizationSetBy = Automatic

	column 'Id do Contrato'
		dataType: string
		lineageTag: bee3e548-8b13-4796-a5bf-b50851ec64e4
		summarizeBy: none
		sourceColumn: Id do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Razão social'
		dataType: string
		lineageTag: 302dd2c2-4e6b-4237-9a67-67dc255bce3f
		summarizeBy: none
		sourceColumn: Razão social

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: 9bd7ee66-9d98-4470-bc75-7d78946a0e7a
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo da contratação'
		dataType: string
		lineageTag: 3c62af82-6a56-4edc-86b6-d6cec42fc40b
		summarizeBy: none
		sourceColumn: Tipo da contratação

		annotation SummarizationSetBy = Automatic

	column Sla
		dataType: string
		lineageTag: addbfe2e-46bf-4f30-8658-181f5a1063eb
		summarizeBy: none
		sourceColumn: Sla

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: e7bbd588-9ead-418d-9066-e1fb3a59a933
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Cadastro no sistema'
		dataType: dateTime
		formatString: General Date
		lineageTag: f8694ef3-b1c9-497d-92cf-2adade4976a9
		summarizeBy: none
		sourceColumn: Cadastro no sistema

		variation Variation
			isDefault
			relationship: 279ddc36-46ef-4fb1-8a97-540a28dae218
			defaultHierarchy: LocalDateTable_1c648297-334e-4a6d-ab92-7dce9f06c8bc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Vigência Inicial'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0f2b385-07f7-44f5-ae01-6cbc428cfa79
		summarizeBy: none
		sourceColumn: Vigência Inicial

		variation Variation
			isDefault
			relationship: bc132850-9e00-4bb1-bb88-f80d23f52e93
			defaultHierarchy: LocalDateTable_64d09ce1-e174-4ad1-9c0b-eb42ae25034c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vigência Final'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4a2fb913-ae9e-4e93-9427-68eda165b2ee
		summarizeBy: none
		sourceColumn: Vigência Final

		variation Variation
			isDefault
			relationship: 8bd1cde4-e1aa-4e32-a740-4f74327464ce
			defaultHierarchy: LocalDateTable_202ec9e1-9ea9-424c-b391-04cda2bd1ead.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: f1d64709-7888-40af-8308-bd78ce603a13
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 6fb0abf8-b34d-4506-b77a-76a9ac2d660a
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 968229f0-df2e-43e7-8376-89e32b0cd42c
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 6c5d76c2-34a8-4853-899e-4fa686e77365
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Valor do contrato'
		dataType: double
		lineageTag: 3d1dde6d-1a29-45cb-b0c0-5d5c5ebd37ea
		summarizeBy: sum
		sourceColumn: Valor do contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome do Gestor'
		dataType: string
		lineageTag: db0f156e-010a-499a-bbe7-dd5077360e09
		summarizeBy: none
		sourceColumn: Nome do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Email do Gestor'
		dataType: string
		lineageTag: 8d7619f8-b685-4024-a726-fbb786ca7033
		summarizeBy: none
		sourceColumn: Email do Gestor

		annotation SummarizationSetBy = Automatic

	column 'Telefone do Gestor'
		dataType: string
		lineageTag: 8e121413-9a50-41a8-9df6-1c089304918f
		summarizeBy: none
		sourceColumn: Telefone do Gestor

		annotation SummarizationSetBy = Automatic

	column Frequência
		dataType: string
		lineageTag: d5c7c627-41ab-41ab-af6d-3adb8b3ab507
		summarizeBy: none
		sourceColumn: Frequência

		annotation SummarizationSetBy = Automatic

	column 'VP de Execução do contrato'
		dataType: string
		lineageTag: 392d0587-6c23-48bf-bba5-c9e0eeb2439c
		summarizeBy: none
		sourceColumn: VP de Execução do contrato

		annotation SummarizationSetBy = Automatic

	column 'VP Requisitante do contrato'
		dataType: string
		lineageTag: b6c786a7-9933-4f0d-be70-af02700bf3c3
		summarizeBy: none
		sourceColumn: VP Requisitante do contrato

		annotation SummarizationSetBy = Automatic

	column 'Nome do gestor técnico'
		dataType: string
		lineageTag: 591d00e9-321a-4ade-84e6-df80677d201a
		summarizeBy: none
		sourceColumn: Nome do gestor técnico

		annotation SummarizationSetBy = Automatic

	column 'E-mail do gestor técnico'
		dataType: string
		lineageTag: 59058f33-6786-4773-8d1d-0f2e7757a951
		summarizeBy: none
		sourceColumn: E-mail do gestor técnico

		annotation SummarizationSetBy = Automatic

	column 'Nome do fiscal técnico'
		dataType: string
		lineageTag: 5124e3fb-b42c-44d1-83ed-7be9ad9a57a2
		summarizeBy: none
		sourceColumn: Nome do fiscal técnico

		annotation SummarizationSetBy = Automatic

	column 'E-mail do fiscal técnico'
		dataType: string
		lineageTag: 3f9c3d5a-808c-495f-87c3-d6c49a3fd09a
		summarizeBy: none
		sourceColumn: E-mail do fiscal técnico

		annotation SummarizationSetBy = Automatic

	column 'Nome do gestor administrativo'
		dataType: string
		lineageTag: c8f0fa2e-8faf-4e39-94eb-89887ea01fcd
		summarizeBy: none
		sourceColumn: Nome do gestor administrativo

		annotation SummarizationSetBy = Automatic

	column 'E-mail do gestor administrativo'
		dataType: string
		lineageTag: 198529f2-7caa-454f-9a5c-b8bb1e36cb4d
		summarizeBy: none
		sourceColumn: E-mail do gestor administrativo

		annotation SummarizationSetBy = Automatic

	column 'Nome do SST responsável'
		dataType: string
		lineageTag: 9ac1e222-52b1-44d3-a0b7-7658524422f4
		summarizeBy: none
		sourceColumn: Nome do SST responsável

		annotation SummarizationSetBy = Automatic

	column 'E-mail do SST responsável'
		dataType: string
		lineageTag: 48b61c6f-0582-49fb-afa7-967fd1898e3c
		summarizeBy: none
		sourceColumn: E-mail do SST responsável

		annotation SummarizationSetBy = Automatic

	column 'Centro de Custo'
		dataType: string
		lineageTag: bb430672-883c-48b8-b453-be3d5e72ae1a
		summarizeBy: none
		sourceColumn: Centro de Custo

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Fornecedor'
		dataType: string
		lineageTag: d1f41261-0f7d-4d19-9694-d50d2a6ec804
		summarizeBy: none
		sourceColumn: Tipo de Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Status Vigência'
		dataType: string
		lineageTag: 7a6418a5-6821-4b18-99d7-a326a2b721d7
		summarizeBy: none
		sourceColumn: Status Vigência

		annotation SummarizationSetBy = Automatic

	column Chave_Contratos
		dataType: string
		lineageTag: 68831393-4989-47f7-8996-4e53e5623a5a
		summarizeBy: none
		sourceColumn: Chave_Contratos

		annotation SummarizationSetBy = Automatic

	partition Contratos = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("atlas-sql-report-production.database.windows.net", "afm-encargos-prod-bi", [Query="select distinct #(lf)#(tab)c.OrderNumber[Nº do pedido],#(lf)#(tab)c.Id[Id do Contrato],#(lf)    bc.CompanyName[Razão social],#(lf)    [bc].[Document] AS [CNPJ],#(lf)#(tab)#(lf)    case#(lf)        when c.[Type] = 1 then 'Contínuo'#(lf)        when c.[Type] = 2 then 'Grandes Paradas'#(lf)        when c.[Type] = 4 then 'Eventual'#(lf)        when c.[Type] = 8 then 'Temporário'#(lf)        when c.[Type] = 16 then 'Visitante técnico'#(lf)        when c.[Type] = 32 then 'Prestação de Serviço de Consultor Proprietário da empresa'#(lf)        when c.[Type] = 64 then 'Prestação de serviço eventual fora da área operacional'#(lf)        when c.[Type] = 128 then 'Prestação de serviço de auditoria, sem acesso as áreas restritas'#(lf)        when c.[Type] = 256 then 'Compra Direta, Regulariza e Delegada'#(lf)    end as 'Tipo da contratação',#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN c.FatherId IS NULL THEN 'Contratado'#(lf)#(tab)#(tab)ELSE 'Subcontratado'#(lf)#(tab) END 'Tipo de Fornecedor',#(lf)    case#(lf)        when c.Sla = 0 then 'Padrão'#(lf)        when c.Sla = 1 then 'Emergencial'#(lf)    end as 'Sla',#(lf)    case#(lf)        when c.[Status] = 0 then 'Regular'#(lf)        when c.[Status] = 1 then 'Aguardando dados de contatos do fornecedor'#(lf)        when c.[Status] = 2 then 'Aguardando fornecedor preencher o contrato'#(lf)        when c.[Status] = 3 then 'Arquivado'#(lf)    end as 'Status',#(lf)    convert(date, c.CreatedAt)[Cadastro no sistema],#(lf)    CONCAT(convert(date, c.ValidityInitial), ' a ',convert(date, c.ValidityFinal))[Vigência], #(lf)    b.TradeName[Unidade],#(lf)#(tab)r.Name AS 'Regional',#(lf)#(tab)ca.[Name][Categoria],#(lf)    p.TradeName[Fornecedor],#(lf)    c.[Value][Valor do contrato],#(lf)#(tab)cm.[Name][Nome do Gestor],#(lf)#(tab)cm.[Email][Email do Gestor],#(lf)#(tab)cm.[Phone][Telefone do Gestor],#(lf)#(tab)cfi3.[Name][Frequência],#(lf)#(tab)cfi5.[Name][VP de Execução do contrato],#(lf)#(tab)cfi7.[Name][VP Requisitante do contrato],#(lf)#(tab)cfv10.[Value][Nome do gestor técnico],#(lf)#(tab)cfv11.[Value][E-mail do gestor técnico],#(lf)#(tab)cfv8.[Value][Nome do fiscal técnico],#(lf)#(tab)cfv9.[Value][E-mail do fiscal técnico],#(tab)#(lf)#(tab)cfv12.[Value][Nome do gestor administrativo],#(lf)#(tab)cfv13.[Value][E-mail do gestor administrativo],#(lf)#(tab)cfv14.[Value][Nome do SST responsável],#(lf)#(tab)cfv15.[Value][E-mail do SST responsável],#(lf)#(tab)cfv16.[Value][Centro de Custo]#(lf)#(lf)from [Contract] c with(nolock)#(lf)#(tab)#(tab)#(lf)#(tab)#(tab)inner join Building b with(nolock) on b.Id = c.BuildingId#(lf)#(tab)#(tab)INNER JOIN Region r WITH(NOLOCK) ON r.Id = b.RegionId#(lf)#(tab)#(tab)inner join BranchCompany bc with(Nolock) on bc.Id = c.BranchCompanyId#(lf)#(tab)#(tab)inner join [Category] ca with(Nolock) on ca.Id = c.CategoryId#(lf)#(tab)#(tab)inner join [Provider] p with(nolock) on c.ProviderId = p.Id#(lf)#(tab)#(tab)left join ContractManager cm with(nolock) on cm.ContractId = c.Id and cm.Removed = 0#(lf)#(tab)#(tab)left join CustomFieldValue cfv8 WITH(NOLOCK) ON cfv8.EntityId = c.Id AND cfv8.CustomFieldId = '46797071-E688-4C4D-9D1E-A43BA98C9648' -- Nome do fiscal técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv9 WITH(NOLOCK) ON cfv9.EntityId = c.Id AND cfv9.CustomFieldId = '2DA18E51-F8A5-4BDC-8553-87A17EB27A7C' -- E-mail do fiscal técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv10 WITH(NOLOCK) ON cfv10.EntityId = c.Id AND cfv10.CustomFieldId = '9C244155-B8D4-4F0B-9413-7ECBCAFCD254' -- Nome do gestor técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv11 WITH(NOLOCK) ON cfv11.EntityId = c.Id AND cfv11.CustomFieldId = '7BF74685-4491-455C-9A27-F582AEE0ECA9' -- E-mail do gestor técnico#(lf)#(tab)#(tab)left join CustomFieldValue cfv12 WITH(NOLOCK) ON cfv12.EntityId = c.Id AND cfv12.CustomFieldId = '9F3F9320-74D8-4A80-A465-21C47B1D3AB1' -- Nome do gestor administrativo#(lf)#(tab)#(tab)left join CustomFieldValue cfv13 WITH(NOLOCK) ON cfv13.EntityId = c.Id AND cfv13.CustomFieldId = '8909197F-A741-48C4-82A9-02090DAD2FAD' -- E-mail do gestor administrativo#(lf)#(tab)#(tab)left join CustomFieldValue cfv14 WITH(NOLOCK) ON cfv14.EntityId = c.Id AND cfv14.CustomFieldId = '853608BB-71D6-407D-8BF1-413B396A4992' -- Nome do SST responsável#(lf)#(tab)#(tab)left join CustomFieldValue cfv15 WITH(NOLOCK) ON cfv15.EntityId = c.Id AND cfv15.CustomFieldId = '73E86956-CFF0-4D88-940B-F0F09E78E677' -- E-mail do SST responsável#(lf)#(tab)#(tab)left join CustomFieldValue cfv16 WITH(NOLOCK) ON cfv16.EntityId = c.Id AND cfv16.CustomFieldId = 'A684A08F-8759-4429-80C0-23BBB16AF57A' -- Centro de Custo#(lf)#(tab)#(tab)outer apply #(lf)#(tab)#(tab)(#(lf)    select cfi2.[Name] from CustomFieldValue cfv2 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi2 with(nolock) on cfv2.CustomFieldItemId = cfi2.Id#(lf)    where cfv2.EntityId = c.Id#(lf)#(tab)#(tab)and cfv2.[Value] is null#(lf)#(tab)#(tab)and cfv2.Removed = 0#(lf)#(tab)#(tab)and cfi2.Removed = 0#(lf)#(tab)#(tab)AND cfv2.CustomFieldId = '1C30677D-3F2F-4396-93DE-1DA0FD90E592' -- Frequência#(lf)#(tab)) as [cfi3]#(lf)#(tab)outer apply #(lf)#(tab)(#(lf)    select cfi4.[Name] from CustomFieldValue cfv4 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi4 with(nolock) on cfv4.CustomFieldItemId = cfi4.Id#(lf)    where cfv4.EntityId = c.Id#(lf)#(tab)#(tab)and cfv4.[Value] is null#(lf)#(tab)#(tab)and cfv4.Removed = 0#(lf)#(tab)#(tab)and cfi4.Removed = 0#(lf)#(tab)#(tab)AND cfv4.CustomFieldId = '586D0602-B8D0-480F-8565-5A1040393B54' -- VP de Execução do contrato#(lf)#(tab)) as [cfi5]#(lf)#(tab)outer apply #(lf)#(tab)(#(lf)    select cfi6.[Name] from CustomFieldValue cfv6 with(nolock)#(lf)#(tab)#(tab)inner join CustomFieldItem cfi6 with(nolock) on cfv6.CustomFieldItemId = cfi6.Id#(lf)    where cfv6.EntityId = c.Id#(lf)#(tab)#(tab)and cfv6.[Value] is null#(lf)#(tab)#(tab)and cfv6.Removed = 0#(lf)#(tab)#(tab)and cfi6.Removed = 0#(lf)#(tab)#(tab)AND cfv6.CustomFieldId = 'A53C1F6C-9334-4AF9-8B78-03CC327FB6D7' -- VP Requisitante do contrato#(lf)#(tab)) as [cfi7]#(lf)where b.OrganizationId = '5e8158ee-be53-42a6-a438-29d67db30280'#(lf)#(tab)  and c.Removed = 0#(lf)#(tab)  order by c.OrderNumber #(lf)#(lf)#(lf)#(tab)#(lf)#(lf)#(tab)"]),
				    #"Colunas Removidas1" = Table.RemoveColumns(Fonte,{"Tipo de Fornecedor"}),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Colunas Removidas1", "Tipo de Fornecedor", each if Text.Contains([Nº do pedido], "S") then "Subcontratado" else "Contratado"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada2",{{"Nº do pedido", type text}, {"Razão social", type text}, {"CNPJ", type text}, {"Tipo da contratação", type text}, {"Status", type text}, {"Vigência", type text}, {"Unidade", type text}, {"Categoria", type text}, {"Fornecedor", type text}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Tipo Alterado", "Vigência", Splitter.SplitTextByDelimiter("a", QuoteStyle.Csv), {"Vigência.1", "Vigência.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Vigência.1", type date}, {"Vigência.2", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Vigência.1", "Vigência Inicial"}, {"Vigência.2", "Vigência Final"}}),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Colunas Renomeadas", "Status Vigência", each if [Vigência Inicial] > DateTime.Date(DateTime.LocalNow()) then "Vigência Futura" else if [Vigência Final] < DateTime.Date(DateTime.LocalNow()) then "Vigência Finalizada" else "Vigente"),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Coluna Condicional Adicionada1", "Chave_Contratos", each Text.Combine({[Nº do pedido], [Razão social], [Unidade], [Categoria]}, ""), type text)
				in
				    #"Coluna Mesclada Inserida"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

